In [5]:
import sys
sys.path.append("../../")
from pathlib import Path
from html import escape
import pandas as pd
from IPython.display import HTML, display

from retrieval.product_retriever import search_product
from evaluation.eval import product_load_tests, evaluate_retrieval, context_relevance
from evaluation.classes import ContextRelevanceWrapper
from evaluation.reporting import (
    build_eval_question_report,
    build_retrieval_doc_rows,
    display_eval_question_report,
    export_retrieval_report_to_markdown,
    get_node_text,
)

In [6]:
def retrieving(test, top_k):
    context = search_product(test.question, top_k=top_k)
    nodes = getattr(context, "nodes", context)
    return nodes

In [7]:
async def evaluate_all_retrieval(limit=None, top_k=5, markdown_path=None):
    
    tests = product_load_tests()
    selected_tests = tests[:limit] if limit is not None else tests
    rows = []
    question_reports = []

    for index, test in enumerate(selected_tests, start=1):
        nodes = retrieving(test, top_k)
        
        metrics = evaluate_retrieval(test, nodes, k=top_k)
        
        result = await context_relevance(ContextRelevanceWrapper(question=test.question, contexts=[get_node_text(item) for item in nodes]))
        metrics["context_relevance"] = result
        rows.append(metrics)
        filtered_metrics = {
            key: value
            for key, value in metrics.items()
            if key.startswith("precision") or key.startswith("recall") or key == "mrr" or key.startswith("ndcg") or key == "context_relevance"
        }
        doc_rows = build_retrieval_doc_rows(nodes, test.relevant_docs)
        display_eval_question_report(
            question=test.question,
            relevant_docs=test.relevant_docs,
            metrics=filtered_metrics,
            text_blocks=[],
            doc_rows=doc_rows,
            index=index,
            total=len(selected_tests),
            metric_columns=4,
        )
        question_report = build_eval_question_report(
            question=test.question,
            relevant_docs=test.relevant_docs,
            retrieved_docs=metrics["retrieved_docs"],
            doc_rows=doc_rows,
            extra_fields={"metrics": filtered_metrics},
            index=index,
            total=len(selected_tests),
        )
        question_reports.append(question_report)

    
    report_df = pd.DataFrame(rows)
    metric_columns = [column for column in report_df.columns if column.startswith(("precision", "recall", "ndcg")) or column in {"mrr", "context_relevance"}]
    summary_df = report_df[metric_columns].mean().to_frame(name="mean").T.round(3)

    display(HTML("<h2 style='margin:32px 0 12px;color:#24292f;'>Final metrics</h2>"))
    display(summary_df)

    if markdown_path is not None:
        saved_path = export_retrieval_report_to_markdown(
            report_df,
            question_reports,
            Path(markdown_path),
            notebook_path="notebooks/product/05_product_retrieval_baseline.ipynb",
        )
        display(HTML(f"<p style='margin:12px 0 0;color:#1a7f37;'>Markdown report saved to: <code>{escape(str(saved_path))}</code></p>"))

    return report_df

In [8]:
await evaluate_all_retrieval(markdown_path="../reports/product_retrieving_evaluation_baseline.md", top_k=30, limit=50)

,rank,hit,section_id,title,score,preview
0,1,no,16279046,-,1.0000,Product: 20Dresses Women Blue Trousers Brand: ...
1,2,no,11421530,-,0.8580,Product: Ginni Arora Label Women Red Slim Fit ...
2,3,no,17393956,-,0.8490,Product: Fabindia Women Beige & Red Striped Co...
3,4,no,17378344,-,0.7719,Product: Saffron Threads Women Black Original ...
4,5,no,17625016,-,0.7647,Product: Fabindia Women Off White Cotton Trous...
5,6,no,17104470,-,0.7405,Product: Fabindia Women Blue Striped Relaxed T...
6,7,no,14220222,-,0.6884,Product: DressBerry Women Green Trousers Brand...
7,8,no,18770054,-,0.6864,Product: Trendyol Women Blue & Yellow Ethnic M...
8,9,no,10440556,-,0.6649,Product: DressBerry Women Olive Green Regular ...
9,10,no,15693320,-,0.6387,Product: Fabindia Women Beige Ethnic Trousers ...
10,11,no,13921450,-,0.6377,Product: Saffron Threads Women Black & Gold Se...
11,12,no,18033910,-,0.6117,Product: Fabindia Women Blue Cotton Trousers B...
12,13,no,17371040,-,0.5894,Product: Saffron Threads Women Pack of 2 Black...
13,14,no,16220618,-,0.5795,Product: 20Dresses Women Olive Green Trousers ...
14,15,no,17511712,-,0.5727,Product: SASSAFRAS Women Stylish Black Solid Y...
15,16,no,19327268,-,0.5327,Product: Lakshita Women Navy Blue Women Blue R...
16,17,no,14099268,-,0.5170,Product: Jaipur Kurti Women Beige Regular Fit ...
17,18,no,18769616,-,0.5166,Product: Trendyol Women Beige & Brown Pure Cot...
18,19,no,17378342,-,0.5124,Product: Saffron Threads Women Off White Solid...
19,20,yes,17817750,-,0.5069,Product: Trendyol Women Green Solid High Rise ...
20,21,no,19011990,-,0.5035,Product: Trendyol Women Blue Pure Cotton Solid...
21,22,no,13499940,-,0.4965,Product: Oxolloxo Women Black & Black Regular ...
22,23,no,19239034,-,0.4946,Product: BROADSTAR Women Navy Blue Relaxed Str...
23,24,no,19327338,-,0.4680,Product: Lakshita Women Beige Relaxed Loose Fi...
24,25,no,14099278,-,0.4593,Product: Jaipur Kurti Women Mustard Regular Fi...
25,26,no,17945078,-,0.4554,Product: Ginni Arora Label Women White Slim Fi...
26,27,no,14220194,-,0.4145,Product: DressBerry Women Burgundy Trousers Br...
27,28,no,17188132,-,0.4074,Product: Rangriti Women Olive Green Solid Slim...
28,29,no,14027022,-,0.4067,Product: Oxolloxo Women Multicoloured Regular ...
29,30,no,9436011,-,0.3608,Product: Jaipur Kurti Women Green Regular Fit ...

,rank,hit,section_id,title,score,preview
0,1,yes,11166548,-,1.0000,Product: Athena Women Burgundy Solid Tailored ...
1,2,no,10758214,-,0.4804,Product: Athena Women Burgundy Solid Pullover ...
2,3,no,12086086,-,0.3919,Product: Athena Women Burgundy Solid Pencil Mi...
3,4,no,11634534,-,0.3760,Product: Athena Women Burgundy Solid Basic Jum...
4,5,no,11634536,-,0.3744,Product: Athena Women Burgundy Solid Basic Jum...
5,6,no,10856152,-,0.3652,Product: SASSAFRAS Women Burgundy Solid Tailor...
6,7,no,11151684,-,0.3112,Product: Athena Women Grey Solid Single Breast...
7,8,no,12402376,-,0.2935,Product: Belle Fille Women Burgundy Solid Asym...
8,9,no,7779375,-,0.2926,Product: Athena Women White Solid Cropped Deni...
9,10,no,13023122,-,0.2605,Product: Athena Women Mustard Yellow Solid Bla...
10,11,no,14320508,-,0.2244,Product: Sztori Plus Size Women Burgundy Hoode...
11,12,no,15300920,-,0.2192,Product: Athena Women Striking Coral Sleek Coa...
12,13,no,16752820,-,0.1944,Product: armure Women Brown & White Checked Su...
13,14,no,7784761,-,0.1922,Product: Athena Women Red Embellished Sweatshi...
14,15,no,16565622,-,0.1825,Product: Latin Quarters Women Maroon Suede Tai...
15,16,no,16552340,-,0.1707,Product: armure Women Maroon Lightweight Tailo...
16,17,no,16429486,-,0.1637,Product: ATHLISIS Women Maroon Lightweight e-D...
17,18,no,18121946,-,0.1617,Product: Athena Women Elegant Lavender Solid N...
18,19,no,18121932,-,0.1512,Product: Athena Women Elegant Lavender Solid F...
19,20,no,11151706,-,0.1508,Product: Athena Women Fuchsia Pink Solid Sweat...
20,21,no,10758220,-,0.1490,Product: Athena Women Green Solid Sweatshirt B...
21,22,no,16491516,-,0.1465,Product: Woods Women Burgundy Camouflage Water...
22,23,no,16002984,-,0.1412,Product: Athena Women Blue Crop Jacket With Fl...
23,24,no,15995804,-,0.1299,Product: FableStreet Women Burgundy Crop Denim...
24,25,no,14356158,-,0.1295,Product: Roadster Women Burgundy Convertible J...
25,26,no,18121952,-,0.1239,Product: Athena Women Black Solid Cut-Out Deta...
26,27,no,6968708,-,0.1238,Product: Alcis Women Burgundy Printed Lightwei...
27,28,no,16706804,-,0.1204,Product: AMERICAN EAGLE OUTFITTERS Women Brown...
28,29,no,15851900,-,0.1168,Product: URBANIC Women Blue Solid Hooded Faux ...
29,30,no,15849954,-,0.1159,Product: URBANIC Women Black & White Houndstoo...

,rank,hit,section_id,title,score,preview
0,1,yes,18921114,-,1.0000,Product: InWeave Women Red Printed A-Line Skir...
1,2,no,17168254,-,0.9132,Product: InWeave Women Red Printed Pure Cotton...
2,3,no,15322490,-,0.6951,Product: InWeave Women Black & Yellow Lahariya...
3,4,no,17168250,-,0.6593,Product: InWeave Women Blue Printed Pure Cotto...
4,5,no,15542594,-,0.6473,Product: InWeave Women Mustard Yellow & White ...
5,6,no,17168268,-,0.5791,Product: InWeave Women Pink & White Printed Pu...
6,7,no,13497800,-,0.5309,Product: InWeave Women Red Striped A-Line Top ...
7,8,no,16524822,-,0.5103,Product: InWeave Women Striking Pink Solid Asy...
8,9,no,15447990,-,0.4652,Product: InWeave Women Bright Orange Printed T...
9,10,no,15760840,-,0.4117,Product: InWeave Red & Gold-Toned Regular Crop...
10,11,no,18922178,-,0.4007,Product: InWeave Women Red Flared Palazzos Bra...
11,12,no,16524698,-,0.3922,Product: InWeave Women Green Printed Co-Ords B...
12,13,no,17355370,-,0.3831,Product: InWeave Women Elegant Charcoal Solid ...
13,14,no,14402632,-,0.3363,Product: InWeave Mustard Yellow & Blue A-Line ...
14,15,no,13610084,-,0.3268,Product: ANVI Be Yourself Women Red & White Pr...
15,16,no,13020628,-,0.2885,Product: InWeave Women Blue & Red Ikkat Printe...
16,17,no,15485484,-,0.2667,Product: InWeave Women Maroon & Blue Printed L...
17,18,no,18922836,-,0.2453,Product: InWeave Navy Blue Empire Solid Kurti ...
18,19,no,18052092,-,0.2452,Product: InWeave Women Green & White Printed D...
19,20,no,18769480,-,0.2338,Product: Trendyol Women Red & White Floral Pri...
20,21,no,18922128,-,0.2323,Product: InWeave Women Black Flared Palazzos B...
21,22,no,12379640,-,0.2222,Product: InWeave Women Maroon & Navy Blue Flar...
22,23,no,17241002,-,0.2143,Product: InWeave Women Pretty Pink Floral Scar...
23,24,no,13857708,-,0.2108,Product: RARE Women White & Red Printed A-Line...
24,25,no,18262776,-,0.2037,Product: InWeave Women Black & Blue Solid Crop...
25,26,no,18052104,-,0.2022,Product: InWeave Maroon & Yellow Printed Organ...
26,27,no,13718888,-,0.1855,Product: InWeave Off White Floral Printed Top ...
27,28,no,18376990,-,0.1734,Product: kriatma Women Red Printed Midi Skirts...
28,29,no,13676002,-,0.1706,Product: InWeave Maroon Printed Dupatta Brand:...
29,30,no,13020642,-,0.1670,Product: InWeave Women Mustard Yellow & Green ...

,rank,hit,section_id,title,score,preview
0,1,no,10451734,-,1.0000,Product: WEAVERS VILLA Women Mustard Yellow & ...
1,2,no,14402632,-,0.7738,Product: InWeave Mustard Yellow & Blue A-Line ...
2,3,no,19218994,-,0.6543,Product: Mitera Mustard & Red Woven Design Zar...
3,4,no,16719554,-,0.6452,Product: Banarasi Style Mustard Woven Design D...
4,5,no,17663018,-,0.6412,Product: Dupatta Bazaar Mustard Yellow Ethnic ...
5,6,no,1319900,-,0.5850,Product: Desi Weavess Mustard Orange & Red Pri...
6,7,no,11117288,-,0.5546,Product: Mitera Mustard & Pink Silk Blend Wove...
7,8,no,15781530,-,0.4734,Product: max Mustard Viscose Rayon Dupatta Bra...
8,9,no,14088428,-,0.4733,Product: SheWill Mustard Brown & Green Cotton ...
9,10,no,16921550,-,0.4659,Product: Safaa Women Mustard Woven Design Wool...
10,11,no,15542594,-,0.4509,Product: InWeave Women Mustard Yellow & White ...
11,12,no,18135092,-,0.4200,Product: Mitera Mustard Yellow Ethnic Motifs Z...
12,13,no,17415222,-,0.4150,Product: The Magic Wand Girls Mustard Yellow &...
13,14,no,14367932,-,0.3841,Product: Safaa Mustard Yellow & White Pure Cot...
14,15,no,13020634,-,0.3819,Product: InWeave Women Mustard Yellow Printed ...
15,16,no,13020642,-,0.3693,Product: InWeave Women Mustard Yellow & Green ...
16,17,no,11524932,-,0.3499,Product: Vishudh Women's Mustard & Pink Stripe...
17,18,no,19240508,-,0.3450,Product: max Women Mustard Yellow Yoke Design ...
18,19,no,19145502,-,0.3445,Product: The Chennai Silks Mustard & Brown Pur...
19,20,no,18122478,-,0.3393,Product: PERFECTBLUE Mustard Yellow & Fuchsia ...
20,21,no,16291090,-,0.3249,Product: BROOWL Women Mustard & Orange Floral ...
21,22,no,17480778,-,0.2942,Product: SALWAR STUDIO Mustard & Brown Printed...
22,23,no,10265397,-,0.2916,Product: Saadgi Mustard Yellow Gotta Patti Dup...
23,24,no,18549594,-,0.2816,Product: Amrutam Fab Mustard & Green Printed S...
24,25,no,17044784,-,0.2785,Product: Studio Shringaar Mustard Yellow Embro...
25,26,no,14987382,-,0.2749,Product: Fabindia Mustard Yellow Pure Cotton R...
26,27,no,13861554,-,0.2718,Product: mf Mustard & Pink Cotton Blend Unstit...
27,28,no,15709312,-,0.2672,Product: Fabindia Mustard Pure Silk Block Prin...
28,29,no,18456682,-,0.2519,Product: Fabindia Women Mustard Yellow Pure Co...
29,30,no,18141434,-,0.2488,Product: MANOHARI Mustard & Gold-Toned Woven D...

,rank,hit,section_id,title,score,preview
0,1,no,16124612,-,1.0000,Product: MANGO Black Self Design Regular Top B...
1,2,no,17607938,-,0.8698,Product: MANGO Women Coral Red Solid Double-Br...
2,3,no,15274016,-,0.7830,Product: MANGO Women Black Pullover Brand: MAN...
3,4,no,17808618,-,0.7669,Product: MANGO Off White Satin Finish Extended...
4,5,no,18319598,-,0.7527,Product: MANGO Women Beige Solid Oversize Fit ...
5,6,no,17270200,-,0.6954,Product: MANGO Coral Pink Solid A-line Midi Sk...
6,7,no,14340718,-,0.6601,Product: MANGO Women Peach-Coloured Solid Regu...
7,8,no,16124404,-,0.6342,Product: MANGO Women Cream-Coloured Solid Pull...
8,9,no,15102906,-,0.6028,Product: MANGO Off White Linen Regular Top Bra...
9,10,no,15102850,-,0.5995,Product: MANGO Blue Regular Top Brand: MANGO C...
10,11,no,15315374,-,0.5968,Product: MANGO Women White Solid Tailored Jack...
11,12,no,11844262,-,0.5935,Product: MANGO Women Yellow Solid Single-Breas...
12,13,no,18319360,-,0.5828,Product: MANGO Women Green Solid Double-Breast...
13,14,no,17608074,-,0.5721,Product: MANGO Women Green Solid Double Breast...
14,15,no,18259392,-,0.5584,Product: MANGO Off White Pure Cotton Solid Ruc...
15,16,no,15963428,-,0.5208,Product: MANGO Women Cream-Coloured Solid Roun...
16,17,no,17269008,-,0.5191,Product: MANGO Women Black Solid Oversized Des...
17,18,no,18783754,-,0.5012,Product: MANGO Women White and Blue Striped Re...
18,19,no,18783498,-,0.4971,Product: MANGO Cream-Coloured Crochet Knit Smo...
19,20,no,15274330,-,0.4970,Product: MANGO Women Off White & Red Striped P...
20,21,no,18783796,-,0.4942,Product: MANGO Women Black Shorts Brand: MANGO...
21,22,no,19101076,-,0.4930,Product: MANGO Women Black Solid Blazer Brand:...
22,23,no,16957104,-,0.4924,Product: MANGO Women Blue Oversized Pure Cotto...
23,24,no,18784288,-,0.4920,Product: MANGO Blue Solid Extended Sleeves Top...
24,25,no,17607846,-,0.4789,Product: MANGO Women Dusty Pink Solid Double B...
25,26,no,15962092,-,0.4775,Product: MANGO Women Olive Green Solid Tailore...
26,27,yes,15265896,-,0.4620,Product: MANGO Women Blue Noa Skinny Fit Mid-R...
27,28,no,15035500,-,0.4563,Product: MANGO Cream-Coloured Solid Basic Jump...
28,29,no,18259304,-,0.4550,Product: MANGO Women Olive Green Regular Trous...
29,30,no,18319628,-,0.4410,Product: MANGO Women Mint Green Solid Single-B...

,rank,hit,section_id,title,score,preview
0,1,yes,11581420,-,1.0000,Product: Sweet Dreams Women Pink & Green Heart...
1,2,no,11581448,-,0.9951,Product: Sweet Dreams Women Pink & Green Heart...
2,3,yes,11581366,-,0.9940,Product: Sweet Dreams Women Pink & Green Heart...
3,4,no,12882594,-,0.5632,Product: Sweet Dreams Women Peach-Coloured & B...
4,5,no,12882732,-,0.4524,Product: Sweet Dreams Women Coral Pink & Black...
5,6,no,12459498,-,0.3578,Product: Sweet Dreams Women Black Solid Regula...
6,7,no,16533336,-,0.3511,Product: Sweet Dreams Women Beige Embroidered ...
7,8,no,16990014,-,0.3159,Product: SASSAFRAS Women Pretty Pink Solid Pla...
8,9,no,16450186,-,0.2980,Product: Berrylush Women Pretty Pink Printed R...
9,10,no,14568680,-,0.2882,Product: Sweet Dreams Women Burgundy Hooded Sw...
10,11,no,15955210,-,0.2882,Product: Missguided Pink Solid Playsuit Brand:...
11,12,no,16006846,-,0.2820,Product: THE SILHOUETTE STORE Women Pink Solid...
12,13,no,10053735,-,0.2557,Product: Cottinfab Women Pink & Black Printed ...
13,14,no,13270464,-,0.2429,Product: Sweet Dreams Women Charcoal Grey Soli...
14,15,no,17919758,-,0.2380,Product: ONLY Women Pink Self Design Round Nec...
15,16,no,14166398,-,0.2298,Product: Sweet Dreams Women Charcoal Grey Skin...
16,17,no,19231232,-,0.2146,Product: Sweet Dreams Women Grey Humor & Comic...
17,18,no,17171608,-,0.1815,Product: QUIERO Women Pretty Pink Self-Design ...
18,19,no,15301014,-,0.1783,Product: Athena Women Pretty Pink Sleek Jumpsu...
19,20,no,13611470,-,0.1752,Product: 20Dresses Women Pretty Pink Printed P...
20,21,no,16466494,-,0.1387,Product: People Pink Basic Jumpsuit Brand: Peo...
21,22,no,18368472,-,0.1360,Product: 20Dresses Pink Basic Jumpsuit Brand: ...
22,23,no,11364296,-,0.1302,Product: SASSAFRAS Women Dusty Pink Solid Basi...
23,24,no,15381904,-,0.1283,Product: Berrylush Women Pink Solid Ruffled Ju...
24,25,no,17605228,-,0.1281,Product: Berrylush Women Red & White Halter Ne...
25,26,no,16642084,-,0.1250,Product: 20Dresses Pink Dancing Through The Ni...
26,27,no,17813700,-,0.1156,Product: Trendyol Women Peach-Coloured & Grey ...
27,28,no,14708574,-,0.1125,Product: IX IMPRESSION Orange & Navy Blue Prin...
28,29,no,16560336,-,0.0990,Product: AND Women Blue & Pink Off-Shoulder Pr...
29,30,no,13558724,-,0.0988,Product: People Women Pink Solid Culotte Jumps...

,rank,hit,section_id,title,score,preview
0,1,no,13799826,-,1.0000,Product: Vishudh Women Grey & Gold-Coloured Ch...
1,2,no,18688392,-,0.9907,Product: Vishudh Women Printed Kurta with Dupa...
2,3,no,17656860,-,0.9535,Product: Vishudh Women Turquoise Blue Floral P...
3,4,yes,18929144,-,0.9491,Product: Vishudh Women Purple Ethnic Straight ...
4,5,no,17132180,-,0.9395,Product: Vishudh Women Black & Teal Blue Check...
5,6,yes,18262138,-,0.9329,Product: Vishudh Women Yellow & Grey Ethnic Mo...
6,7,yes,13536726,-,0.9290,Product: Vishudh Women Yellow & Off-White Prin...
7,8,no,16858486,-,0.9210,Product: Vishudh Women Red Embroidered Pure Co...
8,9,no,13975624,-,0.9070,Product: Vishudh Women Off-White Checked Kurta...
9,10,no,14860664,-,0.9062,Product: Vishudh Women Black Regular Printed K...
10,11,yes,15639890,-,0.8946,Product: Vishudh Women Green & White Floral Pr...
11,12,no,18261878,-,0.8725,Product: Vishudh Women Blue Floral Printed Kur...
12,13,yes,15997054,-,0.8523,Product: Vishudh Women Yellow Floral Embroider...
13,14,yes,15820432,-,0.8509,Product: Vishudh Women Off White Embroidered R...
14,15,no,7572969,-,0.8505,Product: Vishudh Women Red & Orange Self Desig...
15,16,no,16123926,-,0.8461,Product: Vishudh Women Mauve Floral Embroidere...
16,17,no,9673749,-,0.8373,Product: Vishudh Women Turquoise Blue & Gold-T...
17,18,no,9867983,-,0.8309,Product: Vishudh Women Navy Blue Floral Printe...
18,19,yes,18263032,-,0.8293,Product: Vishudh Women Checked Pure Cotton Kur...
19,20,no,18929396,-,0.8256,Product: Vishudh Women Pink Thread Work Kurta ...
20,21,no,17445358,-,0.8068,Product: Vishudh Women Purple Printed Kurta wi...
21,22,no,13433674,-,0.8029,Product: Vishudh Women Sea Green & White Print...
22,23,no,7572958,-,0.7994,Product: Vishudh Women Mauve Regular Kurta wit...
23,24,yes,13119222,-,0.7961,Product: Vishudh Women Black & Off-White Check...
24,25,no,15335772,-,0.7592,Product: Vishudh Women Yellow Striped Regular ...
25,26,no,18929148,-,0.7032,Product: Vishudh Women Turquoise Blue Pleated ...
26,27,no,14482494,-,0.4866,Product: Vishudh Women Brown Ethnic Motifs Kur...
27,28,no,6613532,-,0.4646,Product: Vishudh Women Navy Blue Yoke Design S...
28,29,no,17445574,-,0.4625,Product: Vishudh Women Blue Floral Embroidered...
29,30,no,14194636,-,0.4558,Product: Vishudh Women Grey & Red Floral Print...

,rank,hit,section_id,title,score,preview
0,1,no,14873856,-,1.0000,Product: Ancestry Women Grey & White Striped A...
1,2,yes,15407228,-,0.8489,Product: Ancestry Pink Pure Cotton Self Design...
2,3,yes,14873702,-,0.8392,Product: Ancestry Women Pink Melange Effect Pu...
3,4,yes,19152780,-,0.8205,Product: Ancestry Women Pink Regular Top Brand...
4,5,no,19152792,-,0.8054,Product: Ancestry Women Gold-Toned Longline Ta...
5,6,no,15407188,-,0.7992,Product: Ancestry Women Navy Blue & White Pure...
6,7,no,14873748,-,0.7927,Product: Ancestry Women Taupe Embroidered Long...
7,8,no,17149934,-,0.7700,Product: Ancestry Women Maroon Crop Tailored J...
8,9,no,17326880,-,0.6813,Product: Ancestry Women Pink Regular Fit Pleat...
9,10,no,19152772,-,0.6790,Product: Ancestry Mustard Embroidered Organza ...
10,11,no,15407164,-,0.6710,Product: Ancestry White & Red Pure Cotton Geom...
11,12,no,16588088,-,0.6617,Product: Ancestry Pink & Black Ethnic Motifs P...
12,13,no,17049154,-,0.2759,Product: Anouk Navy Blue Checked Checked Pure ...
13,14,no,12135352,-,0.2678,Product: Anouk Women Black Printed A-Line Top ...
14,15,no,17694118,-,0.2448,Product: Antheaa Women Navy Blue & Black Abstr...
15,16,no,17049100,-,0.2396,Product: Anouk Mustard Yellow & White Checked ...
16,17,no,13424892,-,0.2379,Product: Antheaa Sea Green & Pink Yoke Embroid...
17,18,no,9815193,-,0.2288,Product: anayna Women White & Blue Printed A-L...
18,19,no,18331422,-,0.2168,Product: Anouk Pink & White Ethnic Motifs Prin...
19,20,no,11197978,-,0.2048,Product: Anouk Women Lime Green & Blue Printed...
20,21,no,13424874,-,0.1871,Product: Antheaa Women Rust Brown & Black Embr...
21,22,no,17694106,-,0.1615,Product: Antheaa Women Pink & Blue Floral Prin...
22,23,no,13610084,-,0.1548,Product: ANVI Be Yourself Women Red & White Pr...
23,24,no,16272186,-,0.1537,Product: Anouk X Earthful Women White & Pink F...
24,25,no,13238592,-,0.1488,Product: Anouk Women Coral Orange & White Cott...
25,26,no,17417200,-,0.1480,Product: Anouk Women Red & White Bandhani Prin...
26,27,no,13248456,-,0.1427,Product: anayna Women Red & Golden Printed Fee...
27,28,no,13238030,-,0.1392,Product: Anouk Women Mustard Kurta Brand: Anou...
28,29,no,7763575,-,0.1391,Product: Anouk Women Red Floral Print A-Line K...
29,30,no,18331124,-,0.1328,Product: Anouk Yellow & White Floral Print Pur...

,rank,hit,section_id,title,score,preview
0,1,yes,19140952,-,1.0000,Product: FASHOR Women Blue Geometric Printed G...
1,2,no,18964098,-,0.5397,Product: FASHOR Women Turquoise Blue Geometric...
2,3,no,18116634,-,0.3128,Product: FASHOR Women Pink Ethnic Motifs Embro...
3,4,no,19324632,-,0.3004,Product: FASHOR Women Blue & White Yoke Design...
4,5,no,18964110,-,0.2996,Product: FASHOR Women Pink Printed Thread Work...
5,6,no,15047458,-,0.2618,Product: FASHOR Women Multicoloured Ethnic Mot...
6,7,no,16362760,-,0.2326,Product: House of Pataudi Women Navy Blue Flor...
7,8,no,19198414,-,0.2241,Product: FASHOR Women Navy Blue Floral Embroid...
8,9,no,16486578,-,0.2099,Product: FASHOR Women Maroon Geometric Printed...
9,10,no,19300542,-,0.2094,Product: PARCHHAI Women Blue Geometric Printed...
10,11,no,17624890,-,0.1936,Product: KAAJH Women Blue Ethnic Motifs Printe...
11,12,no,16362738,-,0.1933,Product: House of Pataudi Women Blue & White F...
12,13,no,18787430,-,0.1897,Product: ADEESHA Women Turquoise Blue Printed ...
13,14,no,16884160,-,0.1674,Product: Rajnandini Women Blue Abstract Kurta ...
14,15,no,16931502,-,0.1658,Product: all about you Women Blue & Yellow Eth...
15,16,no,18720202,-,0.1635,Product: FASHOR Women Purple Ethnic Motifs Pri...
16,17,no,18778410,-,0.1583,Product: FASHOR Women Multicoloured & nirvana ...
17,18,no,17447640,-,0.1516,Product: Khushal K Women White Ethnic Motifs P...
18,19,no,16362862,-,0.1499,Product: House of Pataudi Women Sea Green & Pi...
19,20,no,19357994,-,0.1497,Product: FASHOR Women Pink Ethnic Motifs Kurta...
20,21,no,13369436,-,0.1440,Product: YASH GALLERY Women Navy Blue & White ...
21,22,no,11369616,-,0.1300,Product: W Women Blue & Silver Printed Straigh...
22,23,no,11636314,-,0.1221,Product: Shae by SASSAFRAS Women Blue & Off-Wh...
23,24,no,16266664,-,0.1197,Product: House of Pataudi Women Black & White ...
24,25,no,11369528,-,0.1176,Product: W Women Blue & Black Printed Straight...
25,26,no,15889778,-,0.1143,Product: HERE&NOW Women Blue & White Ethnic Mo...
26,27,no,19168608,-,0.1100,Product: RANGMANCH BY PANTALOONS Women Blue Et...
27,28,no,11531500,-,0.1068,Product: Anubhutee Women Navy Blue & Off-White...
28,29,no,16984006,-,0.1028,Product: FASHOR Women Pink Ethnic Motifs Yoke ...
29,30,no,17514330,-,0.0999,Product: Vishudh Women Blue Printed Anarkali K...

,rank,hit,section_id,title,score,preview
0,1,yes,14460680,-,1.0000,Product: Darzi Women Blue Tailored Jacket Bran...
1,2,no,14460654,-,0.7897,Product: Darzi Women Red Tailored Jacket Brand...
2,3,no,14460662,-,0.7302,Product: Darzi Women Maroon Solid Longline Tai...
3,4,no,17666226,-,0.7264,Product: Darzi Women Maroon Tailored Jacket Br...
4,5,no,17666218,-,0.7092,Product: Darzi Women Yellow Tailored Jacket Br...
5,6,no,17665710,-,0.7083,Product: Darzi Women Yellow Striped Fleece Tai...
6,7,no,17513236,-,0.6751,Product: Darzi Women Multicoloured Crop Tailor...
7,8,no,14460688,-,0.5684,Product: Darzi Women Brown Solid Longline Dust...
8,9,no,17665702,-,0.5574,Product: Darzi Women Navy Blue Colourblocked F...
9,10,no,15784540,-,0.3985,Product: Yaadleen Women Turquoise Blue Floral ...
10,11,no,15859778,-,0.2789,Product: Zink London Women Blue Solid Tailored...
11,12,no,13163000,-,0.2566,Product: FableStreet Women Blue Self Design Ta...
12,13,no,11445774,-,0.2219,Product: Darzi Women Charcoal Grey Solid Hoode...
13,14,no,11446072,-,0.2104,Product: Darzi Women Charcoal Grey Solid Hoode...
14,15,no,11789162,-,0.1998,Product: Darzi Women Black & White Sheer Flora...
15,16,no,14364140,-,0.1940,Product: Mast & Harbour Women Blue Colourblock...
16,17,no,13449644,-,0.1800,Product: DODO & MOA Women Navy Blue Checked As...
17,18,no,16005808,-,0.1757,Product: Juelle Women Blue Tailored Jacket Bra...
18,19,no,13645548,-,0.1631,Product: Diwaah Women Multicoloured Embellishe...
19,20,no,13698728,-,0.1629,Product: Diwaah Women Black Embellished Tailor...
20,21,no,12299686,-,0.1568,Product: Darzi Women Maroon Solid Asymmetric F...
21,22,no,15956494,-,0.1565,Product: Missguided Women Blue Striped Pure Co...
22,23,no,15851444,-,0.1556,Product: URBANIC Women Blue & White Dyed Extra...
23,24,no,15811466,-,0.1553,Product: DECHEN Women Navy Blue Textured Tailo...
24,25,no,14500422,-,0.1508,Product: Darzi Women Black Solid A-Line Maxi S...
25,26,no,18787832,-,0.1480,Product: Tokyo Talkies Women Blue Washed Denim...
26,27,no,11445992,-,0.1466,Product: Darzi Women Maroon Solid Hooded Sweat...
27,28,no,15851900,-,0.1456,Product: URBANIC Women Blue Solid Hooded Faux ...
28,29,no,16019732,-,0.1334,Product: RANGMANCH BY PANTALOONS Women Navy Bl...
29,30,no,15962326,-,0.1325,Product: MANGO Women Blue Solid Denim Shacket ...

,rank,hit,section_id,title,score,preview
0,1,yes,13703470,-,1.0000,Product: U.S. Polo Assn. Women Beige Solid Bik...
1,2,no,13690162,-,0.5025,Product: U.S. Polo Assn. Women Black Solid Qui...
2,3,no,15555424,-,0.3652,Product: BEAVER Women Black Solid Biker Jacket...
3,4,no,16220536,-,0.3235,Product: 20Dresses Women Beige Biker Jacket Br...
4,5,no,15555432,-,0.3008,Product: BEAVER Women Black Solid Crop Biker J...
5,6,no,2185647,-,0.2886,Product: U.S.Polo Assn. Women Grey Longline Sh...
6,7,no,15555446,-,0.2772,Product: BEAVER Women Black Crop Biker Jacket ...
7,8,no,14355398,-,0.2545,Product: Roadster Women Chic Brown Solid Biker...
8,9,no,14355452,-,0.2443,Product: Roadster Women Chic Brown Solid Biker...
9,10,no,14017334,-,0.2309,Product: Leather Retail Women Brown Solid Ligh...
10,11,no,17983210,-,0.2274,Product: U S Polo Assn Women White Striped Hoo...
11,12,no,15564338,-,0.2192,Product: Puma Women Beige Bomber Jacket Brand:...
12,13,no,17855178,-,0.1703,Product: H&M Women Beige Detachable Sleeve Win...
13,14,no,15800520,-,0.1680,Product: FabAlley Women Grey Solid Crop Biker ...
14,15,no,14263292,-,0.1647,Product: AMERICAN EAGLE OUTFITTERS Women Black...
15,16,no,14829462,-,0.1541,Product: Campus Sutra Women Tan Suede Windchea...
16,17,no,14355346,-,0.1509,Product: Roadster Women Stylish Black Solid Bi...
17,18,no,15380284,-,0.1397,Product: Fort Collins Women Beige Solid Padded...
18,19,no,15038638,-,0.1299,Product: Campus Sutra Women Brown Suede Windch...
19,20,no,15027768,-,0.1298,Product: Campus Sutra Women Grey Solid Biker J...
20,21,no,15673462,-,0.1273,Product: Missguided Women Beige Solid Longline...
21,22,no,14355478,-,0.1235,Product: Roadster Women Black Solid Coated Bik...
22,23,no,15673166,-,0.1210,Product: Missguided Women Black Solid Biker Ja...
23,24,no,14356188,-,0.1193,Product: Roadster Women Beige Solid Longline S...
24,25,no,10829334,-,0.1189,Product: Tokyo Talkies Women Beige Solid Puffe...
25,26,no,15846080,-,0.1136,Product: H&M Women Beige Quilted Faux Shearlin...
26,27,no,17069364,-,0.1113,Product: Jockey Women Black Solid Hooded Sport...
27,28,no,16103252,-,0.1104,Product: URBANIC Women Beige Buttoned Tailored...
28,29,no,16103226,-,0.1104,Product: URBANIC Women Beige Red Colourblocked...
29,30,no,15673400,-,0.1013,Product: Missguided Women Black Solid Longline...

,rank,hit,section_id,title,score,preview
0,1,yes,15637468,-,1.0000,Product: Mitera Yellow & Multicoloured Floral ...
1,2,no,15442988,-,0.9874,Product: Mitera Blue Embellished Embroidered R...
2,3,no,15519332,-,0.7588,Product: Mitera Purple & Pink Bandhani Saree B...
3,4,no,16331704,-,0.7426,Product: Mitera Yellow & Red Bandhani Saree Br...
4,5,no,17141480,-,0.6719,Product: Mitera Women Olive Green Embroidered ...
5,6,no,17325496,-,0.6379,Product: Mitera Green & Off-White Embroidered ...
6,7,no,16286084,-,0.6331,Product: Mitera Black & Gold-Toned Unstitched ...
7,8,no,15519378,-,0.6317,Product: Mitera Navy Blue Bandhani Printed Sar...
8,9,no,17325492,-,0.6292,Product: Mitera Green & Golden Embroidered Uns...
9,10,no,17325498,-,0.6034,Product: Mitera Maroon & Golden Embroidered Un...
10,11,no,12668552,-,0.5994,Product: Mitera Turquoise Blue & Red Woven Des...
11,12,no,12668502,-,0.5936,Product: Mitera Pink & Blue Woven Design Semi-...
12,13,no,17325490,-,0.5836,Product: Mitera Black & Golden Embroidered Uns...
13,14,no,17206828,-,0.5765,Product: Mitera Black & Beige Embroidered Unst...
14,15,no,16171474,-,0.5707,Product: Mitera Red & Gold-Toned Dupion Silk B...
15,16,no,16286120,-,0.5670,Product: Mitera Red & Green Silk Blend Unstitc...
16,17,no,17141474,-,0.5539,Product: Mitera Women Yellow Embroidered Pure ...
17,18,no,17392504,-,0.5516,Product: Mitera Blue & Gold-Toned Ethnic Motif...
18,19,no,11530694,-,0.5030,Product: Mitera Peach-Coloured & Gold-Toned Em...
19,20,no,16595928,-,0.4715,Product: Mitera Maroon & Golden Ethnic Motifs ...
20,21,no,18302882,-,0.4511,Product: Mitera Teal & Gold-Toned Woven Design...
21,22,no,16311070,-,0.4481,Product: Mitera Maroon & White Bandhani Printe...
22,23,no,15012204,-,0.4244,Product: Mitera Pink & Gold-Toned Woven Design...
23,24,no,16286118,-,0.4155,Product: Mitera Navy Blue & Red Unstitched Dre...
24,25,no,18647316,-,0.4144,Product: Mitera Blue & Black Embellished Sequi...
25,26,no,13515386,-,0.4026,Product: Mitera Mustard Yellow & Red Embroider...
26,27,no,14479084,-,0.3976,Product: Mitera Red & Gold-Toned Zari Silk Ble...
27,28,no,16967650,-,0.3610,Product: Mitera Beige & Red Ethnic Motifs Zari...
28,29,no,16967652,-,0.3609,Product: Mitera Gold-Toned & Pink Woven Design...
29,30,no,18107770,-,0.3546,Product: Mitera Orange & Gold-Toned Embellishe...

,rank,hit,section_id,title,score,preview
0,1,no,14011652,-,1.0000,Product: FableStreet Black Mini Pencil Skirt B...
1,2,no,17739956,-,0.6840,Product: Kotty Women Black Solid Faux Leather ...
2,3,no,18215398,-,0.6731,Product: Popwings Women Camel Brown Pencil Sli...
3,4,no,19072638,-,0.6584,Product: DRAAX Fashions Women Maroon Solid Min...
4,5,no,17403200,-,0.6349,Product: BROADSTAR Women Black Solid Pencil Mi...
5,6,no,13496046,-,0.6317,Product: FableStreet Olive Green Knitted Penci...
6,7,no,19181106,-,0.6068,Product: Bitterlime Women Olive Green & Black ...
7,8,no,17306262,-,0.5979,Product: Purple Feather Women Black Solid Stre...
8,9,no,17899166,-,0.5917,Product: PATRORNA Women Green Solid Pencil Abo...
9,10,no,1294879,-,0.5446,Product: Purple Feather Black Pencil Skirt Wit...
10,11,no,17365546,-,0.5278,Product: BROADSTAR Women Black Solid Pencil Kn...
11,12,no,18173820,-,0.5247,Product: Kotty Women Brown Solid Faux Leather ...
12,13,no,15315920,-,0.5192,Product: MANGO Women Mint Green Solid Pure Cot...
13,14,no,17795314,-,0.5049,Product: Trend Arrest Women Navy Blue Sequence...
14,15,no,18034350,-,0.5000,Product: Missguided Women Olive Green Solid Mi...
15,16,no,18841536,-,0.4856,Product: Styli Women Burgundy Solid Pencil Ski...
16,17,no,17694094,-,0.4800,Product: Antheaa Women Black Embellished Penci...
17,18,no,18215396,-,0.4787,Product: Popwings Women Above Knee-Length Blac...
18,19,no,14024850,-,0.4677,Product: OTORVA Women Denim Blue Solid Pencil ...
19,20,no,17931744,-,0.4629,Product: PATRORNA Women Green & Black Solid Kn...
20,21,no,12086090,-,0.4590,Product: Athena Women Pink Solid Midi Pencil S...
21,22,no,14798956,-,0.4400,Product: Trendyol Women Taupe Solid Pencil Mid...
22,23,no,18676062,-,0.4373,Product: Disrupt Women Mustard-Yellow Solid Sl...
23,24,no,14270952,-,0.4358,Product: NEUDIS Women Pack Of 2 Solid Velvet P...
24,25,no,18629568,-,0.4215,Product: IX IMPRESSION Women Gold Solid Pencil...
25,26,no,17694116,-,0.4112,Product: Antheaa Women Black Solid Pleated Pen...
26,27,no,17927414,-,0.4087,Product: PATRORNA Women Sea Green Solid Above ...
27,28,no,16042324,-,0.4074,Product: STYL CO. Women Green & Orange Graphic...
28,29,no,17899190,-,0.3857,Product: PATRORNA Women Purple Solid Pencil Ab...
29,30,yes,15940138,-,0.3849,Product: SASSAFRAS Burgundy Metallic Twisted P...

,rank,hit,section_id,title,score,preview
0,1,no,14935802,-,1.0000,Product: Roadster Women Deep Mustard Solid Ruc...
1,2,no,14400678,-,0.8016,Product: BLANC9 Women Mustard Yellow Solid Cot...
2,3,no,11184982,-,0.7451,Product: Mast & Harbour Women Off-White & Must...
3,4,no,13018002,-,0.7313,Product: Blissta Mustard Yellow & Gold-Toned S...
4,5,no,19361356,-,0.7056,Product: BoStreet Women Mustard Yellow Solid T...
5,6,yes,13532718,-,0.6649,Product: Harpa Women Mustard Printed Blouson T...
6,7,no,16470574,-,0.6412,Product: armure Women Mustard Striped Lightwei...
7,8,no,14231200,-,0.6218,Product: all about you Women Mustard Brown Sol...
8,9,no,13023122,-,0.6122,Product: Athena Women Mustard Yellow Solid Bla...
9,10,no,13861554,-,0.5745,Product: mf Mustard & Pink Cotton Blend Unstit...
10,11,no,1694433,-,0.5684,Product: SASSAFRAS Mustard Yellow Peplum Jacke...
11,12,no,7942995,-,0.5524,Product: Mustard Yellow Textured Blouse Brand:...
12,13,no,16774898,-,0.5377,Product: Kraus Jeans Women Mustard Puffer Jack...
13,14,no,14906974,-,0.5343,Product: Zink London Women Mustard Shrug Brand...
14,15,no,8441465,-,0.5329,Product: Bossini Mustard Yellow Printed Open F...
15,16,no,14485256,-,0.5154,Product: Mast & Harbour Women Mustard Yellow &...
16,17,no,14364272,-,0.5032,Product: Mast & Harbour Women Mustard Solid Fu...
17,18,no,17157806,-,0.5023,Product: Monte Carlo Women Mustard Lightweight...
18,19,no,17064994,-,0.4904,Product: VEIRDO Woman Mustard Padded Jacket Br...
19,20,no,2248780,-,0.4803,Product: Belle Fille Women Mustard Yellow Soli...
20,21,no,12737836,-,0.4789,Product: SASSAFRAS Women Mustard Yellow Solid ...
21,22,no,10891582,-,0.4616,Product: Alsace Lorraine Paris Women Mustard Y...
22,23,no,13997512,-,0.4585,Product: plusS Women Mustard Brown Pure Cotton...
23,24,no,10597802,-,0.4405,Product: Alsace Lorraine Paris Women Mustard Y...
24,25,no,14862378,-,0.4401,Product: Campus Sutra Women Mustard Windcheate...
25,26,no,16154384,-,0.4221,Product: JC Mode Women Mustard Yellow Solid Pa...
26,27,no,13982600,-,0.4067,Product: VOXATI Women Mustard Printed Tailored...
27,28,no,11364534,-,0.3799,Product: SASSAFRAS Women Mustard Yellow Solid ...
28,29,no,18839638,-,0.3778,Product: Styli Beige Blouson Top Brand: Styli ...
29,30,no,16034762,-,0.3737,Product: Cottinfab Women Mustard Black Checked...

,rank,hit,section_id,title,score,preview
0,1,yes,13071994,-,1.0000,Product: STREET 9 Women Blue Regular Fit Solid...
1,2,yes,13038932,-,0.9411,Product: STREET 9 Women Blue Regular Fit Solid...
2,3,no,13038926,-,0.7212,Product: STREET 9 Women Green & Black Regular ...
3,4,no,13071970,-,0.6576,Product: STREET 9 Women Green Solid Cargo Jogg...
4,5,no,13038960,-,0.6472,Product: STREET 9 Women Black & Yellow Regular...
5,6,no,13038922,-,0.6423,Product: STREET 9 Women Yellow Regular Fit Sol...
6,7,no,13071980,-,0.6368,Product: STREET 9 Women Yellow Regular Fit Pri...
7,8,no,13738666,-,0.6028,Product: STREET 9 Women Olive Green & Black Re...
8,9,no,5389019,-,0.5640,Product: STREET 9 Women Blue Striped Culotte J...
9,10,no,16336020,-,0.5551,Product: STREET 9 Women Bright Orange Typograp...
10,11,no,15803276,-,0.5369,Product: STREET 9 Blue Basic Jumpsuit Brand: S...
11,12,no,13041492,-,0.5125,Product: STREET 9 Women Blue Solid Sweatshirt ...
12,13,no,13038878,-,0.5113,Product: STREET 9 Women Blue Solid Sweatshirt ...
13,14,no,14136072,-,0.5035,Product: STREET 9 Women Blue Flared Faded Para...
14,15,no,19361312,-,0.4849,Product: STREET 9 Women Brown Printed Smart Lo...
15,16,no,12682016,-,0.4745,Product: STREET 9 Women Blue Skinny Fit Mid-Ri...
16,17,no,17904100,-,0.4647,Product: STREET 9 Women Blue Hottie Relaxed Fi...
17,18,no,12682038,-,0.4637,Product: STREET 9 Women Blue Skinny Fit Mid-Ri...
18,19,no,12693476,-,0.4623,Product: STREET 9 Women Blue Straight Fit Mid-...
19,20,no,12693490,-,0.4573,Product: STREET 9 Women Blue Straight Fit Mid-...
20,21,no,14136188,-,0.4307,Product: STREET 9 Women Blue Relaxed Fit Mid-R...
21,22,no,12277584,-,0.4159,Product: STREET 9 Women Navy Blue Regular Fit ...
22,23,no,6608510,-,0.4062,Product: STREET 9 Navy Blue Solid Basic Jumpsu...
23,24,no,9340267,-,0.3346,Product: STREET 9 Black & White Striped Croppe...
24,25,no,13738560,-,0.3291,Product: STREET 9 Women Turquoise Blue Lightwe...
25,26,no,18987460,-,0.3221,Product: BoStreet Women Fluorescent Green Tape...
26,27,no,14136152,-,0.3157,Product: STREET 9 Women Navy Blue Solid Cotton...
27,28,no,18143380,-,0.3004,Product: STREET 9 Women Attractive Lime Green ...
28,29,no,12277606,-,0.2895,Product: STREET 9 Women Olive Green & Brown Ca...
29,30,no,8694599,-,0.2883,Product: STREET 9 Green & Black Colourblocked ...

,rank,hit,section_id,title,score,preview
0,1,no,17685090,-,1.0000,Product: BUY NEW TREND Women Red Black Colourb...
1,2,no,19087856,-,0.6780,Product: ONLY Women Beige & Navy Blue Colourbl...
2,3,no,15137944,-,0.4710,Product: AND Women Black & White Geometric Ope...
3,4,no,17685350,-,0.4517,Product: BUY NEW TREND Women Maroon Lightweigh...
4,5,no,17226172,-,0.4505,Product: SHOWOFF Women Orange Mom Fit High-Ris...
5,6,no,14070682,-,0.4022,Product: Zink London Women Blue Solid Open Fro...
6,7,no,15940140,-,0.4003,Product: SASSAFRAS Women Green Corduroy Crop O...
7,8,no,14093992,-,0.3787,Product: Hangup Women Mustard Yellow Printed L...
8,9,no,18601482,-,0.3772,Product: MONTREZ Women White Black Open Front ...
9,10,no,14094008,-,0.3436,Product: Hangup Women Gold-Toned Printed Light...
10,11,no,16917270,-,0.3363,Product: Cloth Haus India Women Black & Red Fl...
11,12,no,15354744,-,0.3308,Product: FurryFlair Women Red Open Front Jacke...
12,13,no,2223198,-,0.3244,Product: W Women Red Solid Front-Open Longline...
13,14,no,16044812,-,0.3228,Product: Forever New Women Green Solid Comfort...
14,15,no,16971668,-,0.3169,Product: Soch Women Orange Geometric Longline ...
15,16,no,14094028,-,0.3153,Product: Hangup Women Black & Blue Printed Ope...
16,17,no,16917280,-,0.3037,Product: Cloth Haus India Women Black & Orange...
17,18,no,16971666,-,0.2950,Product: Soch Women Blue Geometric Colourblock...
18,19,no,17570446,-,0.2881,Product: SHOWOFF Women Blue Boyfriend Fit High...
19,20,no,14080856,-,0.2756,Product: DressBerry Women Stylish Mustard Soli...
20,21,no,17570328,-,0.2732,Product: SHOWOFF Women Blue Wide Leg High-Rise...
21,22,no,15257760,-,0.2663,Product: Campus Sutra Women Blue White Colourb...
22,23,no,14039732,-,0.2651,Product: Diwaah Women Gold-Toned Embellished O...
23,24,no,14382336,-,0.2533,Product: DressBerry Women Pink Melange Effect ...
24,25,no,15940702,-,0.2518,Product: Label Ritu Kumar Women Black White Fl...
25,26,no,15088844,-,0.2507,Product: Roadster Women Red Open Front Jacket ...
26,27,no,11952000,-,0.2489,Product: DressBerry Women Navy Blue Ribbed Lon...
27,28,no,14199270,-,0.2485,Product: Hangup Women White & Pink Printed Lig...
28,29,no,14094010,-,0.2428,Product: Hangup Women Yellow Printed Lightweig...
29,30,no,7736701,-,0.2339,Product: W Women Teal Blue Solid Front-Open Lo...

,rank,hit,section_id,title,score,preview
0,1,yes,13255768,-,1.0000,Product: FILA Women Red & Grey Colourblocked S...
1,2,no,16705336,-,0.6616,Product: FILA Women Blue Colourblocked Running...
2,3,no,16705334,-,0.6424,Product: FILA Women Blue White Colourblocked R...
3,4,no,16705280,-,0.5555,Product: FILA Women Off White Colourblocked Ru...
4,5,no,16705296,-,0.5437,Product: FILA Women Grey Printed Sweatshirt Br...
5,6,no,19324666,-,0.2772,Product: FASHOR Women Red Ethnic Motifs Thread...
6,7,no,19194932,-,0.2760,Product: Puma Women Red solid Sporty Jacket Br...
7,8,no,16175534,-,0.2313,Product: H&M Women Red Cotton Blend Sweatpants...
8,9,no,16421286,-,0.2264,Product: Kappa Women Red Colourblocked Sporty ...
9,10,no,1010455,-,0.1949,Product: Belle Fille Red Jacket Brand: Belle F...
10,11,no,15730234,-,0.1837,Product: AGIL ATHLETICA Women Red Geometric Li...
11,12,no,1010488,-,0.1800,Product: Belle Fille Red Hooded Jacket Brand: ...
12,13,no,17988988,-,0.1798,Product: FABNEST Women Red Floral Printed Rela...
13,14,no,11421530,-,0.1747,Product: Ginni Arora Label Women Red Slim Fit ...
14,15,no,15354744,-,0.1719,Product: FurryFlair Women Red Open Front Jacke...
15,16,no,14048980,-,0.1717,Product: Leather Retail Women Red Lightweight ...
16,17,no,18875952,-,0.1682,Product: URBANIC Women Red Slim Fit High-Rise ...
17,18,no,17348134,-,0.1660,Product: Fabindia Red & Beige Paisley Printed ...
18,19,no,14447520,-,0.1628,Product: Dupatta Bazaar Red & Silver-Toned Lin...
19,20,no,12309376,-,0.1562,Product: RIVI Women Red Regular Fit Solid Regu...
20,21,no,14348874,-,0.1539,Product: Tokyo Talkies Women Red Solid Regular...
21,22,no,16585584,-,0.1470,Product: Biba Women Red Ethnic Motifs Printed ...
22,23,no,14976268,-,0.1463,Product: FASHOR Women Red Bandhani Printed & Z...
23,24,no,17348528,-,0.1438,Product: Fabindia Women Red & Blue Floral Prin...
24,25,no,12918478,-,0.1399,Product: AGIL ATHLETICA Women Navy Blue & Red ...
25,26,no,596488,-,0.1342,Product: Belle Fille Women Red Hooded Jacket B...
26,27,no,17393956,-,0.1331,Product: Fabindia Women Beige & Red Striped Co...
27,28,no,11102126,-,0.1323,Product: Alcis Women Red Brand Logo Print Runn...
28,29,no,11064260,-,0.1299,Product: SASSAFRAS Women Red Solid Tailored Ja...
29,30,no,16641130,-,0.1294,Product: RIVI Women Red Solid Mid-Rise Cropped...

,rank,hit,section_id,title,score,preview
0,1,no,2117164,-,1.0000,Product: Noi Cream-Coloured & Brown Printed Sh...
1,2,no,16524266,-,0.6559,Product: LOOKNBOOK ART Orange Semi-Stitched Le...
2,3,no,15266700,-,0.4361,Product: max Beige Pure Cotton Dupatta Brand: ...
3,4,no,15312982,-,0.4215,Product: LOOKNBOOK ART Black & Beige Embellish...
4,5,no,16217482,-,0.4095,Product: max Women Orange Palazzos Brand: max ...
5,6,no,14443728,-,0.3752,Product: max Orange Dupatta with Beads and Sto...
6,7,no,18997238,-,0.3450,Product: IRIDAA JAIPUR Beige & Red Mandarin Co...
7,8,no,15748944,-,0.3395,Product: LOOKNBOOK ART Cream-Coloured Embellis...
8,9,no,18838938,-,0.3259,Product: LOOKNBOOK ART Pink Embellished Sequin...
9,10,no,18310306,-,0.3198,Product: LOOKNBOOK ART Black & White Printed S...
10,11,no,17647778,-,0.3194,Product: LOOKNBOOK ART Red Embellished Sequinn...
11,12,no,14497102,-,0.3148,Product: Ishin Women White Ethnic Motifs Embro...
12,13,no,15748940,-,0.3015,Product: LOOKNBOOK ART White & Pink Embellishe...
13,14,no,17060030,-,0.2848,Product: NDS Niharikaa Designer Studio Women O...
14,15,no,11624038,-,0.2842,Product: Ishin White & Gold-Toned Woven Design...
15,16,no,14921732,-,0.2788,Product: Ishin Women Black & Silver-Toned Stri...
16,17,no,12040878,-,0.2748,Product: Indo Era Orange & Pink Striped Dupatt...
17,18,no,14745736,-,0.2718,Product: Baby Lakshmi Girls Orange & Off White...
18,19,no,11149776,-,0.2701,Product: Style Quotient Women Red & Black Chec...
19,20,no,18196776,-,0.2690,Product: LOOKNBOOK ART White Embroidered Semi-...
20,21,no,11256044,-,0.2556,Product: Ethnicity Beige Solid Dupatta Brand: ...
21,22,no,19112000,-,0.2475,Product: INDIAN HERITAGE Brown & Orange Printe...
22,23,no,17748850,-,0.2463,Product: max Black Pure Cotton Dupatta Brand: ...
23,24,no,17060082,-,0.2338,Product: NDS Niharikaa Designer Studio Women C...
24,25,no,17662996,-,0.2325,Product: Dupatta Bazaar Orange Solid Pure Cott...
25,26,no,17647770,-,0.2249,Product: LOOKNBOOK ART Black & Red Embellished...
26,27,no,11081716,-,0.2141,Product: Vastraa Fusion Women Beige Chikankari...
27,28,no,16119706,-,0.2113,Product: SOUNDARYA Orange & White Striped Pure...
28,29,no,16945862,-,0.2083,Product: Anouk Orange Ethnic Motifs Zari Silk ...
29,30,no,14432282,-,0.2051,Product: max White Regular Top Brand: max Colo...

,rank,hit,section_id,title,score,preview
0,1,no,13969870,-,1.0000,Product: Bhama Couture Navy Blue & Red Embroid...
1,2,no,9717189,-,0.9977,Product: Bhama Couture Women Navy Blue Embroid...
2,3,no,9430121,-,0.9767,Product: Bhama Couture Black Embroidered A-Lin...
3,4,no,13969820,-,0.9626,Product: Bhama Couture Maroon & Black Embroide...
4,5,no,9430115,-,0.9624,Product: Bhama Couture Women Navy Blue Embroid...
5,6,yes,12151804,-,0.9557,Product: Bhama Couture Women Blue & Pink Flora...
6,7,no,11672988,-,0.9538,Product: Bhama Couture Women White & Green Flo...
7,8,no,4380660,-,0.9357,Product: Bhama Couture Women Peach-Coloured Pr...
8,9,yes,10355827,-,0.9357,Product: Bhama Couture Women Blue Embroidered ...
9,10,yes,10717820,-,0.9328,Product: Bhama Couture Women Blue Embroidered ...
10,11,no,11625546,-,0.9229,Product: Bhama Couture Women Red & White Strip...
11,12,yes,12151824,-,0.9224,Product: Bhama Couture Women Maroon Printed A-...
12,13,no,4380652,-,0.9016,Product: Bhama Couture Women Off-White Printed...
13,14,no,8339967,-,0.8817,Product: Bhama Couture Women Red Embroidered D...
14,15,yes,10356731,-,0.8754,Product: Bhama Couture Women Blue Embroidered ...
15,16,no,12795840,-,0.8720,Product: Bhama Couture Women Black & Pink Yoke...
16,17,yes,10355839,-,0.8488,Product: Bhama Couture Women Red Solid A-Line ...
17,18,yes,9430103,-,0.8412,Product: Bhama Couture Women Red Solid A-Line ...
18,19,no,13969880,-,0.8344,Product: Bhama Couture Yellow & White Printed ...
19,20,yes,9430109,-,0.8069,Product: Bhama Couture Mustard Yellow A-Line P...
20,21,no,10745490,-,0.7406,Product: Bhama Couture Women Mustard Yellow So...
21,22,no,18288422,-,0.7022,Product: Bhama Couture Women Off White Floral ...
22,23,no,2294119,-,0.6774,Product: Bhama Couture Women Black Solid Top B...
23,24,no,2129862,-,0.6692,Product: Bhama Couture Women Off-White Embroid...
24,25,no,15367618,-,0.6637,Product: Bhama Couture Women Purple & Gold-Ton...
25,26,no,1823751,-,0.6558,Product: Bhama Couture Black Tunic with Embroi...
26,27,no,11607374,-,0.6531,Product: Bhama Couture Women Blue Printed Pepl...
27,28,no,2129857,-,0.6443,Product: Bhama Couture Women Off-White Solid P...
28,29,no,12795854,-,0.6409,Product: Bhama Couture Women Black & Golden Pr...
29,30,no,11607414,-,0.6325,Product: Bhama Couture Women Blue Printed Pepl...

,rank,hit,section_id,title,score,preview
0,1,no,13740956,-,1.0000,Product: Oxolloxo Women Pink Regular Fit Solid...
1,2,yes,15473916,-,0.9746,Product: People Women Pink Tapered Fit High-Ri...
2,3,no,18342112,-,0.4913,Product: Go Colors Women Pink Tapered Fit Trou...
3,4,no,13459738,-,0.4717,Product: Go Colors Women Pink Tapered Fit Soli...
4,5,no,18838276,-,0.4492,Product: Styli Women Pink Skinny Fit High-Rise...
5,6,no,19299208,-,0.4174,Product: Go Colors Women Pink Crepe Trousers B...
6,7,no,15049878,-,0.4057,Product: Marks & Spencer Women Pink Solid Loos...
7,8,no,18838288,-,0.3989,Product: Styli Women Pink Tapered Fit High-Ris...
8,9,no,1986896,-,0.3835,Product: Indibelle Turquoise Blue Peg Leg Slim...
9,10,no,18838374,-,0.3758,Product: Styli Women Pink High-Rise Trousers B...
10,11,no,18342122,-,0.3665,Product: Go Colors Women Blue Tapered Fit Trou...
11,12,no,11040098,-,0.3528,Product: Oxolloxo Women Blue Regular Fit Solid...
12,13,no,18716468,-,0.3512,Product: FableStreet Women Pink Trousers Brand...
13,14,no,17197778,-,0.3131,Product: Mast & Harbour Women Pink Pure Cotton...
14,15,no,15743324,-,0.3056,Product: PINKSKY Women Blue Embroidered Smart ...
15,16,no,13493068,-,0.2898,Product: Tokyo Talkies Women Green Regular Fit...
16,17,no,9686425,-,0.2830,Product: RIVI Women Pink Regular Fit Solid Reg...
17,18,no,16531320,-,0.2823,Product: JC Mode Women Pink Solid Trousers Bra...
18,19,no,8999489,-,0.2743,Product: Bitterlime Women Grey Relaxed Peg Tro...
19,20,no,8999463,-,0.2741,Product: Bitterlime Women Grey Relaxed Regular...
20,21,no,13942772,-,0.2681,Product: akheri Women Pink Solid Cotton Regula...
21,22,no,19186656,-,0.2634,Product: FabAlley Women Pink Pleated Trousers ...
22,23,no,18143380,-,0.2527,Product: STREET 9 Women Attractive Lime Green ...
23,24,no,16350330,-,0.2474,Product: Enchanted Drapes Women Pink Solid Tro...
24,25,no,15743322,-,0.2474,Product: PINKSKY Women Grey Smart Slim Fit Tro...
25,26,no,17278034,-,0.2447,Product: Tommy Hilfiger Women Pink Solid Mid-R...
26,27,no,14075224,-,0.2442,Product: RIVI Women Blue Slim Fit Solid Cotton...
27,28,no,19049088,-,0.2368,Product: H&M Pink Flared Lyocell-Blend Trouser...
28,29,no,13602838,-,0.2362,Product: ROOTED Women Pink Regular Fit Solid P...
29,30,no,18876152,-,0.2254,Product: Annabelle by Pantaloons Women Blue Pl...

,rank,hit,section_id,title,score,preview
0,1,no,14272032,-,1.0000,Product: Oxolloxo Women Orange Solid Regular F...
1,2,no,14027018,-,0.7642,Product: Oxolloxo Women Olive Green Solid Regu...
2,3,no,14272016,-,0.7568,Product: Oxolloxo Women Green Solid Regular Fi...
3,4,no,14388576,-,0.7316,Product: Oxolloxo Women Black & Yellow Polka D...
4,5,no,19235420,-,0.7106,Product: Oxolloxo Women Brown Shorts Brand: Ox...
5,6,no,16836260,-,0.5850,Product: Roadster Women Indigo Shaded Mid Rise...
6,7,no,11012420,-,0.5354,Product: HRX by Hrithik Roshan Women Black & O...
7,8,no,18611674,-,0.5330,Product: Honey by Pantaloons Women Khaki Strip...
8,9,yes,15402090,-,0.5154,Product: Oxolloxo Women Green Regular Shorts B...
9,10,no,17855308,-,0.4969,Product: H&M Women Orange Pointelle-Knit Cotto...
10,11,no,17887492,-,0.4914,Product: Xpose Women Blue Cotton Shorts Brand:...
11,12,no,16247880,-,0.4582,Product: Trend Arrest Women Brown & White Flor...
12,13,no,18297812,-,0.4489,Product: VARUSHKA Women Black Loose Fit Shorts...
13,14,no,18765570,-,0.4483,Product: MOD ECRU Women Yellow Slim Fit Shorts...
14,15,no,13923576,-,0.4229,Product: Oxolloxo Women Multicoloured Checked ...
15,16,no,11772110,-,0.4040,Product: Honey by Pantaloons Women Navy Blue S...
16,17,no,12969482,-,0.3953,Product: Hypernation Women Olive Green Solid S...
17,18,no,14219670,-,0.3927,Product: DressBerry Women Navy Blue Shorts Bra...
18,19,no,18747106,-,0.3915,Product: H&M Women Orange Sweatshirt Shorts Br...
19,20,no,17969870,-,0.3886,Product: MANGO Women Red & Navy Blue Striped P...
20,21,no,12539994,-,0.3759,Product: FableStreet Women Brown Solid Regular...
21,22,no,15883854,-,0.3693,Product: Style Quotient Women Blue Checked Reg...
22,23,no,13069040,-,0.3642,Product: Bene Kleed Women Multicoloured Stripe...
23,24,no,15912162,-,0.3619,Product: Ajile by Pantaloons Women Coral Pink ...
24,25,no,18155594,-,0.3590,Product: Hypernation Women Black Solid Slim Fi...
25,26,yes,16164252,-,0.3494,Product: Honey by Pantaloons Women Green Strip...
26,27,no,16279068,-,0.3338,Product: 20Dresses Women Yellow Cotton Regular...
27,28,no,14954482,-,0.3075,Product: Roadster Women Olive Green Loose Fit ...
28,29,yes,15083714,-,0.2971,Product: DressBerry Women Green Striped Regula...
29,30,no,14375954,-,0.2952,Product: The Dry State Women Pack of 2 Multico...

,rank,hit,section_id,title,score,preview
0,1,yes,17674588,-,1.0000,Product: H&M Women Brown Mesh Top Brand: H&M C...
1,2,no,17965024,-,0.7971,Product: H&M Orange Ankle-Length Trousers Bran...
2,3,no,12383500,-,0.6371,Product: H&M Women Black Solid Long-Sleeved Je...
3,4,no,17842774,-,0.5490,Product: H&M Beige Wide Linen-Blend Trousers B...
4,5,no,17883650,-,0.5315,Product: H&M Beige Pattern-Knit Trousers Brand...
5,6,no,18131688,-,0.5178,Product: H&M Women Black Wide Linen-blend Trou...
6,7,yes,14258606,-,0.4950,Product: H&M Girls White Solid Jersey Top Bran...
7,8,no,17842776,-,0.4458,Product: H&M Women Beige Striped Wide Linen-Bl...
8,9,yes,17964932,-,0.4279,Product: H&M Women Yellow Rapid-Dry Sports Top...
9,10,no,17611544,-,0.4115,Product: H&M Women Yellow Solid Zip-Through Ho...
10,11,no,17883622,-,0.3729,Product: H&M Girls Beige Cotton Jersey Cropped...
11,12,no,17855308,-,0.3681,Product: H&M Women Orange Pointelle-Knit Cotto...
12,13,no,18747130,-,0.3665,Product: H&M Women Beige Sweatshirt Shorts Bra...
13,14,no,17185466,-,0.3602,Product: H&M Women Beige & Grey Solid Sweatshi...
14,15,yes,19074168,-,0.3590,Product: H&M Women Green Ribbed Cropped Top Br...
15,16,no,17575906,-,0.3590,Product: H&M Women Blue Solid Skinny Regular J...
16,17,no,16396394,-,0.3542,Product: H&M Women Green Fine-Knit Joggers Bra...
17,18,no,18747106,-,0.3409,Product: H&M Women Orange Sweatshirt Shorts Br...
18,19,no,16175534,-,0.3392,Product: H&M Women Red Cotton Blend Sweatpants...
19,20,no,17842452,-,0.2985,Product: H&M Women Brown Single-Breasted Jacke...
20,21,no,17759938,-,0.2929,Product: H&M Black Short Twill Skirt Brand: H&...
21,22,no,18747132,-,0.2891,Product: H&M Women Green Terry Shorts Brand: H...
22,23,no,19175092,-,0.2877,Product: H&M Women Beige Solid Pull-On Lyocell...
23,24,no,17155520,-,0.2851,Product: H&M Woman Grey Hoodie Brand: H&M Colo...
24,25,no,17185856,-,0.2827,Product: H&M Women Blue Straight High Jeans Br...
25,26,no,15960258,-,0.2802,Product: H&M Women Beige Long Zip-Through Hood...
26,27,no,16928312,-,0.2793,Product: H&M Women White Rib-knit Cardigan Bra...
27,28,no,19266852,-,0.2773,Product: H&M Women Black Short Skirt Brand: H&...
28,29,no,19071780,-,0.2704,Product: H&M Women Grey Ankle-Length Linen Tro...
29,30,yes,17883620,-,0.2677,Product: H&M Yellow Puff-Sleeved Jersey Top Br...

,rank,hit,section_id,title,score,preview
0,1,yes,16421936,-,1.0000,Product: KALINI Pink & Gold-Toned Paisley Sare...
1,2,yes,15102290,-,0.9565,Product: KALINI Pink & Gold-Toned Woven Design...
2,3,yes,14678908,-,0.9060,Product: KALINI Pink & Yellow Floral Pure Chif...
3,4,yes,17852902,-,0.9046,Product: KALINI Pink & Gold-Toned Zari Saree B...
4,5,no,16914910,-,0.9001,Product: KALINI Pink Poly Georgette Casual Sar...
5,6,yes,15858094,-,0.8343,Product: KALINI Pack of 2 Pink & Blue Floral S...
6,7,no,16948530,-,0.8338,Product: KALINI Pink & Grey Paisley Printed Ch...
7,8,no,14798392,-,0.8185,Product: KALINI Pink & Green Ethnic Motifs Kot...
8,9,no,12961094,-,0.8008,Product: KALINI Pink & Navy Blue Half & Half P...
9,10,no,17414120,-,0.7986,Product: KALINI Pink & White Batik Zari Block ...
10,11,no,16915002,-,0.7293,Product: KALINI Women Green & Pink Ethnic Moti...
11,12,no,16989798,-,0.6934,Product: KALINI Sea Green & Pink Ethnic Motifs...
12,13,no,15102284,-,0.6797,Product: KALINI Green & Pink Ethnic Motifs Art...
13,14,no,14986192,-,0.5822,Product: KALINI Blue & Yellow Floral Saree Bra...
14,15,no,16505402,-,0.5599,Product: KALINI Women Pink Bandhani Printed An...
15,16,no,17118876,-,0.5363,Product: KALINI Blue & Pink Checked Ikat Saree...
16,17,no,12792140,-,0.5350,Product: KALINI Cream-Coloured & Pink Pure Geo...
17,18,no,14541316,-,0.4915,Product: KALINI Orange & Gold-Toned Ethnic Mot...
18,19,no,18503778,-,0.4868,Product: KALINI Women Pink Floral Embroidered ...
19,20,no,18952254,-,0.4697,Product: KALINI Women Pink Ethnic Motifs Embro...
20,21,no,14490860,-,0.4649,Product: KALINI Orange & Gold-Toned Pure Chiff...
21,22,no,15258754,-,0.4568,Product: KALINI Purple & Grey Ethnic Motifs Ar...
22,23,no,16915122,-,0.4435,Product: KALINI Green & White Bandhani Art Sil...
23,24,no,18435860,-,0.4245,Product: KALINI Red & Gold-Toned Embellished S...
24,25,no,16848432,-,0.4209,Product: KALINI Maroon & Gold-Toned Ethnic Mot...
25,26,no,18495710,-,0.4172,Product: KALINI Teal & Pink Checked Zari Silk ...
26,27,no,14679542,-,0.4159,Product: KALINI Off White & Purple Art Silk Ik...
27,28,no,18878880,-,0.4067,Product: KALINI Sea Green & Blue Bandhani Pure...
28,29,no,17407676,-,0.3908,Product: KALINI Black & Beige Silk Blend Bandh...
29,30,no,18907070,-,0.3736,Product: KALINI Women Red & Green Floral Embro...

,rank,hit,section_id,title,score,preview
0,1,no,17226172,-,1.0000,Product: SHOWOFF Women Orange Mom Fit High-Ris...
1,2,no,17570458,-,0.9442,Product: SHOWOFF Women Brown Jogger High-Rise ...
2,3,no,18142596,-,0.8626,Product: SHOWOFF Women Blue Jogger High-Rise L...
3,4,no,17790642,-,0.8019,Product: SHOWOFF Orange & White Printed Culott...
4,5,no,17685090,-,0.8006,Product: BUY NEW TREND Women Red Black Colourb...
5,6,no,17250550,-,0.7821,Product: SHOWOFF Women Black Embellished Top w...
6,7,no,18388758,-,0.7816,Product: SHOWOFF Burgundy Solid Culotte Jumpsu...
7,8,no,18189378,-,0.6909,Product: SHOWOFF Blue Strapless Capri Jumpsuit...
8,9,no,17672184,-,0.6501,Product: SHOWOFF Women Blue High-Rise Heavy Fa...
9,10,no,18338282,-,0.5503,Product: SHOWOFF Women Blue Slim Fit High-Rise...
10,11,no,17570450,-,0.5418,Product: SHOWOFF Women Black Slim Fit Stretcha...
11,12,no,18263720,-,0.5324,Product: SHOWOFF Women Grey & Maroon Floral Pr...
12,13,no,18067038,-,0.5256,Product: BUY NEW TREND Blue Flared Knitted Pal...
13,14,no,17570446,-,0.5066,Product: SHOWOFF Women Blue Boyfriend Fit High...
14,15,no,18142614,-,0.4883,Product: SHOWOFF Women Lavender Jogger High-Ri...
15,16,no,17570328,-,0.4835,Product: SHOWOFF Women Blue Wide Leg High-Rise...
16,17,no,17570364,-,0.4792,Product: SHOWOFF Women Blue Straight Fit High-...
17,18,no,18067072,-,0.4493,Product: BUY NEW TREND Brown Open-Front Shrug ...
18,19,no,18011278,-,0.4341,Product: Inddus Orange & Gold-Toned Unstitched...
19,20,no,18388752,-,0.4336,Product: SHOWOFF Orange & White Printed Jumpsu...
20,21,no,18324286,-,0.4191,Product: Fashion Basket Red & Black Embroidere...
21,22,no,17685350,-,0.4187,Product: BUY NEW TREND Women Maroon Lightweigh...
22,23,no,16524266,-,0.4073,Product: LOOKNBOOK ART Orange Semi-Stitched Le...
23,24,no,17570416,-,0.3637,Product: SHOWOFF Women Black Straight Fit Stre...
24,25,no,17716122,-,0.3492,Product: Ahalyaa Geometric Crepe Top to Toe Fu...
25,26,no,18247990,-,0.3478,Product: SHOWOFF Women Blue Washed Denim Jacke...
26,27,no,18247980,-,0.3380,Product: SHOWOFF Women Blue Washed Denim Jacke...
27,28,no,18309022,-,0.3227,Product: PURVAJA Olive Green & Red Semi-Stitch...
28,29,no,18067068,-,0.3218,Product: BUY NEW TREND Beige Open-Front Shrug ...
29,30,no,17226246,-,0.3158,Product: SHOWOFF Women Charcoal Grey Wide Leg ...

,rank,hit,section_id,title,score,preview
0,1,yes,16379914,-,1.0000,Product: Safaa Women Red Woven Design Acrylic ...
1,2,yes,15768366,-,0.9983,Product: VERO AMORE Women Red & Beige Woven-De...
2,3,no,19366710,-,0.9464,Product: RIVAMA Red & Green Ethnic Motifs Wove...
3,4,no,13616810,-,0.9440,Product: Dupatta Bazaar Red & Orange Woven Des...
4,5,no,13497800,-,0.9393,Product: InWeave Women Red Striped A-Line Top ...
5,6,no,17662882,-,0.8695,Product: Dupatta Bazaar Red Woven Design Dupat...
6,7,yes,16379852,-,0.8630,Product: Safaa Women Red & Black Woven Design ...
7,8,no,2138931,-,0.8181,Product: WEAVERS VILLA Coral Red & Beige Woven...
8,9,no,11379820,-,0.6978,Product: SHINGORA Women Red & Blue Woven Desig...
9,10,no,15121622,-,0.6948,Product: Cayman Women Red & Beige Woollen Wove...
10,11,no,18205188,-,0.6798,Product: Inddus Red & Gold-Toned Woven Design ...
11,12,no,18806012,-,0.6359,Product: awesome Red & Gold-Toned Woven Design...
12,13,no,15874790,-,0.5696,Product: Pashmoda Women Red Woven Design Jamaw...
13,14,no,8278529,-,0.5666,Product: Faserz Red Woven Design Banarasi Dupa...
14,15,no,13104106,-,0.5656,Product: Pashmoda Women Red Woven Design Shawl...
15,16,no,15393074,-,0.5547,Product: Desi Weavess Red Art Silk Dupatta Bra...
16,17,no,4444074,-,0.5492,Product: Dupatta Bazaar Red & Orange Woven Des...
17,18,no,17764814,-,0.5176,Product: Silk Land Red & Gold-Toned Ethnic Mot...
18,19,no,16874574,-,0.4884,Product: Mitera Red Woven Design Zari Silk Ble...
19,20,no,10358133,-,0.4823,Product: Dupatta Bazaar Red & Gold-Coloured Wo...
20,21,no,13552260,-,0.4623,Product: Dupatta Bazaar Red & Yellow Woven Des...
21,22,no,15760840,-,0.4386,Product: InWeave Red & Gold-Toned Regular Crop...
22,23,no,6581979,-,0.4285,Product: Dupatta Bazaar Red & Gold-Toned Woven...
23,24,no,16197692,-,0.4181,Product: Pashmoda Womens Red Kaani Woven Desig...
24,25,no,13448688,-,0.4177,Product: Honey by Pantaloons Women Red Self De...
25,26,no,17764826,-,0.3913,Product: Silk Land Women Red Jacquared Banaras...
26,27,no,19029736,-,0.3694,Product: Mitera Red & Gold-Toned Woven Design ...
27,28,no,17735542,-,0.3601,Product: Iris Red Floral Net Saree Brand: Iris...
28,29,no,17693086,-,0.3390,Product: Silk Land Red & Gold-Toned Woven Desi...
29,30,no,10814044,-,0.3201,Product: WEAVERS VILLA Red & Yellow Phulkari E...

,rank,hit,section_id,title,score,preview
0,1,yes,15917640,-,1.0000,Product: SERONA FABRICS White & Pink Floral Em...
1,2,no,18845142,-,0.7208,Product: SERONA FABRICS Peach-Coloured & White...
2,3,no,18845144,-,0.7127,Product: SERONA FABRICS Grey & Off White Tunic...
3,4,no,15907476,-,0.5333,Product: SERONA FABRICS Red & White Printed Un...
4,5,no,15907474,-,0.4567,Product: SERONA FABRICS Women Peach Floral Pri...
5,6,no,16258082,-,0.4511,Product: SERONA FABRICS Yellow Floral Embroide...
6,7,no,15907480,-,0.4281,Product: SERONA FABRICS Blue & Gold-Toned Embr...
7,8,no,14238538,-,0.4109,Product: Sera Women White & Black Printed Basi...
8,9,no,14375990,-,0.3963,Product: Sera Women Off White & Grey Printed S...
9,10,no,17784302,-,0.3743,Product: Sera Women White Floral Print Georget...
10,11,no,15907478,-,0.3688,Product: SERONA FABRICS Red Embroidered Unstit...
11,12,no,18360202,-,0.3648,Product: Sera Women Off-White Printed Co-Ord S...
12,13,no,15907488,-,0.3644,Product: SERONA FABRICS Pink Embroidered Chand...
13,14,no,996729,-,0.2615,Product: Dupatta Bazaar White Silk Dupatta Bra...
14,15,no,10035883,-,0.2276,Product: Sera Women Black Solid Loose Fit Regu...
15,16,no,19005622,-,0.2206,Product: ORUS White Solid Dupatta Brand: ORUS ...
16,17,no,14008468,-,0.2056,Product: Sera Women Brown & White Printed Flar...
17,18,no,17231652,-,0.1855,Product: Clora Creation White & Beige Striped ...
18,19,no,11275704,-,0.1842,Product: ADA White Solid Mukaish Work Sustaina...
19,20,no,19338482,-,0.1747,Product: Satrani White Embroidered Dupatta Bra...
20,21,no,17831112,-,0.1740,Product: Senyora White Floral Embroidered Shir...
21,22,no,10783332,-,0.1710,Product: Sera Women Off-White & Pink Printed B...
22,23,no,10496030,-,0.1703,Product: Sera Women Black Solid Loose Fit Regu...
23,24,no,10711448,-,0.1701,Product: Dupatta Bazaar Women White Solid Dupa...
24,25,no,19260118,-,0.1682,Product: SALWAR STUDIO White & Blue Printed Un...
25,26,no,2594438,-,0.1585,Product: Sera Blue & White Striped Cinched Wai...
26,27,no,12718796,-,0.1267,Product: Sera Women Black & White Polka Dot Pr...
27,28,no,14056588,-,0.1264,Product: SOUNDARYA Yellow & Pink Striped Dupat...
28,29,no,10358153,-,0.1263,Product: Dupatta Bazaar White Solid Dupatta Br...
29,30,no,16119706,-,0.1254,Product: SOUNDARYA Orange & White Striped Pure...

,rank,hit,section_id,title,score,preview
0,1,no,17447636,-,1.0000,Product: Khushal K Women Green Ethnic Motifs P...
1,2,no,15508896,-,0.8923,Product: Indo Era Women Green Ethnic Motifs Yo...
2,3,no,15258422,-,0.8399,Product: Indo Era Floral Cotton Blend Calf Len...
3,4,yes,16707970,-,0.7710,Product: mokshi Ethnic Motifs Viscose Rayon Ku...
4,5,no,12989804,-,0.7610,Product: mokshi Women Green & Maroon Foil Prin...
5,6,no,15654150,-,0.6986,Product: Indo Era Women Green Ethnic Motifs Yo...
6,7,no,15054430,-,0.6782,Product: Biba Women Green Ethnic Motifs Printe...
7,8,yes,17140156,-,0.6662,Product: Myshka Women Green Kurta with Palazzo...
8,9,no,13392426,-,0.6339,Product: Khushal K Women Lime Green Printed Ku...
9,10,yes,16825614,-,0.5950,Product: Stylum Women Green Embroidered Pure C...
10,11,no,15026486,-,0.5869,Product: W Women Green & Golden Regular Sequin...
11,12,no,17624906,-,0.5781,Product: KAAJH Women Green Embroidered Chikank...
12,13,no,18551726,-,0.5410,Product: POONAM DESIGNER Women Lime Green Gott...
13,14,yes,14920000,-,0.5359,Product: Indo Era Women Green Floral Embroider...
14,15,no,15258010,-,0.5336,Product: Libas Women Green & White Floral Embr...
15,16,no,17048604,-,0.4969,Product: Khushal K Women Green & Pink Printed ...
16,17,yes,16505434,-,0.4792,Product: KALINI Women Green Floral Printed Pur...
17,18,no,18810192,-,0.4766,Product: GUNVANTI FAB Women Green Yoke Design ...
18,19,no,16931552,-,0.4636,Product: all about you Women Green Embroidered...
19,20,no,19040558,-,0.4634,Product: KARAJ JAIPUR Women Green Floral Anark...
20,21,no,18002690,-,0.4435,Product: SINGNI Women Green Embroidered Printe...
21,22,yes,15677426,-,0.4390,Product: SWAGG INDIA Women Green Floral Embroi...
22,23,no,13810898,-,0.4378,Product: Indo Era Women Blue & Green Printed K...
23,24,no,13940072,-,0.4279,Product: W Women Green Geometric Printed Kurta...
24,25,no,14967448,-,0.4193,Product: Indo Era Women Green Ethnic Motifs Pr...
25,26,no,15714504,-,0.4161,Product: Varanga Women Green Ethnic Motifs Emb...
26,27,yes,17232410,-,0.4154,Product: InWeave Green Pure Cotton Print Parad...
27,28,no,13771272,-,0.3985,Product: Nayo Women Green Printed Kurta with T...
28,29,no,15471926,-,0.3802,Product: Kvsfab Women Green Embellished Bell S...
29,30,no,19181470,-,0.3715,Product: Baisacrafts Women Green Striped Pure ...

,rank,hit,section_id,title,score,preview
0,1,no,18328804,-,1.0000,Product: URBANIC Women Black Jeans Brand: URBA...
1,2,no,18542924,-,0.8078,Product: URBANIC Women Black Solid Mid-Rise Wi...
2,3,no,19072596,-,0.7600,Product: URBANIC Women Black Relaxed Fit Mildl...
3,4,no,18867438,-,0.7289,Product: URBANIC Women Black Trousers Brand: U...
4,5,no,18644820,-,0.7148,Product: URBANIC Women Black Solid Blazers Bra...
5,6,no,15845464,-,0.6942,Product: URBANIC Women Black Solid Cotton Swea...
6,7,no,15851566,-,0.6922,Product: URBANIC Women Black Padded Jacket Bra...
7,8,yes,18929182,-,0.6541,Product: URBANIC Black Embroidered Halter Neck...
8,9,no,15852292,-,0.6481,Product: URBANIC Women Black Cotton Solid Crop...
9,10,no,15844202,-,0.6407,Product: URBANIC Women Black & Off White Solid...
10,11,no,15633286,-,0.6283,Product: URBANIC Women Black Solid Skinny Fit ...
11,12,no,18875978,-,0.6044,Product: URBANIC Women Black Denim Shorts Bran...
12,13,no,18905328,-,0.6015,Product: URBANIC Black Basic Jumpsuit Brand: U...
13,14,no,18905308,-,0.5938,Product: URBANIC Black Basic Jumpsuit Brand: U...
14,15,yes,15634138,-,0.5885,Product: URBANIC Women Black Tailored Jacket B...
15,16,no,18907806,-,0.5560,Product: URBANIC Women Black Solid Double-Brea...
16,17,yes,18605954,-,0.5546,Product: URBANIC Women Black Solid Pure Cotton...
17,18,no,15633046,-,0.5477,Product: URBANIC Women Black Pure Cotton Slim ...
18,19,no,16102760,-,0.5404,Product: URBANIC Black Solid Basic Jumpsuit wi...
19,20,yes,15086606,-,0.5322,Product: URBANIC Women Black Printed Sweatshir...
20,21,no,15082220,-,0.5298,Product: URBANIC Black Ribbed Slim Fit Basic J...
21,22,no,15851868,-,0.5154,Product: URBANIC Black & White Printed Basic J...
22,23,yes,15633414,-,0.5012,Product: URBANIC Women Black Solid Cropped Bas...
23,24,yes,18866648,-,0.4953,Product: URBANIC Black Semi Sheer Crop Top Bra...
24,25,no,15851740,-,0.4926,Product: URBANIC Women Plus Size Black Solid W...
25,26,no,15851802,-,0.4704,Product: URBANIC Women Black Solid Two-Piece G...
26,27,no,19093160,-,0.4701,Product: URBANIC Women Black Checked Trousers ...
27,28,no,15098700,-,0.4533,Product: URBANIC Black Solid Mini Co-ordinate ...
28,29,no,15632460,-,0.4417,Product: URBANIC Women Black Solid High-Rise D...
29,30,no,18643006,-,0.4402,Product: URBANIC Women Black Solid Co-Ords Bra...

,rank,hit,section_id,title,score,preview
0,1,no,19270830,-,1.0000,Product: Blamblack Women Black Solid Shirt & P...
1,2,no,19187496,-,0.8607,Product: Blamblack Women Black & Grey Solid Co...
2,3,no,17570416,-,0.7899,Product: SHOWOFF Women Black Straight Fit Stre...
3,4,no,12383500,-,0.6829,Product: H&M Women Black Solid Long-Sleeved Je...
4,5,no,13552234,-,0.6469,Product: Dupatta Bazaar Black Solid Dupatta Br...
5,6,no,17570450,-,0.5882,Product: SHOWOFF Women Black Slim Fit Stretcha...
6,7,no,18207362,-,0.5793,Product: Dupatta Bazaar Black Linen Dupatta Br...
7,8,no,14263292,-,0.5565,Product: AMERICAN EAGLE OUTFITTERS Women Black...
8,9,no,16220586,-,0.5538,Product: 20Dresses Women Black Biker Jacket Br...
9,10,no,16379842,-,0.5448,Product: Safaa Women Black & Beige Woven Desig...
10,11,no,16379878,-,0.5304,Product: Safaa Women Black & Blue Woven Design...
11,12,no,16860084,-,0.5284,Product: DressBerry Women Black Solid Stretcha...
12,13,no,14080898,-,0.5196,Product: DressBerry Women Black Print Detail S...
13,14,no,18328804,-,0.4696,Product: URBANIC Women Black Jeans Brand: URBA...
14,15,no,16379928,-,0.4285,Product: Safaa Women Black & Beige Woven Desig...
15,16,no,14225458,-,0.4179,Product: The Dry State Women Black Solid Regul...
16,17,no,18875978,-,0.4128,Product: URBANIC Women Black Denim Shorts Bran...
17,18,no,18128680,-,0.3803,Product: People Women Black Solid Denim Jacket...
18,19,no,19269372,-,0.3690,Product: BoStreet Women Black Colourblocked Lo...
19,20,no,15341678,-,0.3686,Product: Go Colors Women Black Cotton Tapered ...
20,21,no,13642436,-,0.3597,Product: Alsace Lorraine Paris Women Black Sol...
21,22,no,14547528,-,0.3576,Product: ZOLA Women Black Skinny Fit Light Fad...
22,23,no,16827106,-,0.3552,Product: Ginger by Lifestyle Women Black High-...
23,24,no,14080668,-,0.3460,Product: DressBerry Women Black Solid Sweatshi...
24,25,no,18542924,-,0.3398,Product: URBANIC Women Black Solid Mid-Rise Wi...
25,26,no,16736530,-,0.3329,Product: SHINGORA Women Black & Brown Woven-De...
26,27,no,2082103,-,0.3116,Product: Saree mall Black Unstitched Dress Mat...
27,28,no,19214734,-,0.2919,Product: BoStreet Black Roll-Up Sleeves Shirt ...
28,29,no,16583226,-,0.2913,Product: 20Dresses Women Black Plus Size Cotto...
29,30,no,18967478,-,0.2869,Product: BoStreet Women Black Wide Leg Slits J...

,rank,hit,section_id,title,score,preview
0,1,yes,18819296,-,1.0000,Product: Swasti Women Blue Ethnic Motifs Print...
1,2,no,19260152,-,0.4306,Product: SALWAR STUDIO Blue & Purple Printed U...
2,3,no,19260114,-,0.4306,Product: SALWAR STUDIO Blue & Grey Printed Uns...
3,4,no,15228886,-,0.4146,Product: Blissta Blue Unstitched Dress Materia...
4,5,no,15635874,-,0.4087,Product: SWAGG INDIA Blue Ethnic Motifs Embroi...
5,6,no,11536158,-,0.3917,Product: INDYA Blue Solid Dupatta Brand: INDYA...
6,7,no,18651648,-,0.3819,Product: Swtantra Blue & Gold-Toned Satin Sare...
7,8,no,13869240,-,0.3704,Product: Stylee LIFESTYLE Blue Cotton Blend Un...
8,9,no,18211888,-,0.3563,Product: Iris Women Sky Blue & Light Blue Prin...
9,10,no,16821580,-,0.3556,Product: BharatSthali Blue & Silver Woven Desi...
10,11,no,18323552,-,0.2972,Product: Swtantra Sea Green & Blue Ombre Pure ...
11,12,no,18859092,-,0.2625,Product: Unnati Silks Blue & Orange Dyed Pure ...
12,13,no,18887908,-,0.2570,Product: swatika Green Woven Design Bhagalpuri...
13,14,no,15071832,-,0.2433,Product: all about you Blue & Violet Floral Or...
14,15,no,15243952,-,0.2274,Product: Suta Blue Green Colourblocked Cotton ...
15,16,no,18283286,-,0.2222,Product: Swtantra Mustard & Blue Ombre Satin S...
16,17,no,13956726,-,0.2188,Product: Anubhutee Blue & White Geometric Prin...
17,18,no,17445574,-,0.2161,Product: Vishudh Women Blue Floral Embroidered...
18,19,no,17514330,-,0.2124,Product: Vishudh Women Blue Printed Anarkali K...
19,20,no,15326556,-,0.2058,Product: swatika White Striped Organza Bhagalp...
20,21,no,16198966,-,0.2033,Product: Arhi Blue Raga Saree Brand: Arhi Colo...
21,22,no,16336066,-,0.1986,Product: all about you Blue Woven Design Silk ...
22,23,no,15437594,-,0.1956,Product: Stylum Women Turquoise Blue Geometric...
23,24,no,17215592,-,0.1842,Product: Safaa Blue & White Unstitched Dress M...
24,25,no,17751840,-,0.1736,Product: SALWAR STUDIO Navy Blue Printed Unsti...
25,26,no,7241429,-,0.1712,Product: Dupatta Bazaar Blue Embroidered Dupat...
26,27,no,17788054,-,0.1657,Product: Stylee LIFESTYLE Turquoise Blue & Pin...
27,28,no,18753060,-,0.1646,Product: Globus Women Blue & aquifer Thread Wo...
28,29,no,19100460,-,0.1593,Product: La Vastraa Blue & Yellow Paisley Dyed...
29,30,no,10328759,-,0.1540,Product: Ishin Women Blue & White Printed Unst...

,rank,hit,section_id,title,score,preview
0,1,yes,13244594,-,1.0000,Product: Mayra Women Pink Printed Shirt Style ...
1,2,no,19201936,-,0.8566,Product: H&M Women Pink Pure Cotton Frill-Coll...
2,3,no,15841446,-,0.7875,Product: URBANIC Pink & Beige Floral Print Shi...
3,4,no,19195222,-,0.7799,Product: PRASTHAN Women Pink Floral Print Crep...
4,5,no,18605378,-,0.6845,Product: Vishal Prints Pink & Grey Abstract Pr...
5,6,no,19325284,-,0.5588,Product: POONAM DESIGNER Women Pink Ethnic Mot...
6,7,no,19032532,-,0.5108,Product: BUY NEW TREND Women Pink & Yellow Pri...
7,8,no,9301311,-,0.4829,Product: Tissu Women Pink & Off-White Floral P...
8,9,no,11762378,-,0.4755,Product: AKKRITI BY PANTALOONS Women Pink Prin...
9,10,no,19280832,-,0.4726,Product: VividArtsy Women Pink Tie & Dye Print...
10,11,no,15632410,-,0.4541,Product: URBANIC Women Pink Solid T-shirt with...
11,12,no,19188354,-,0.4312,Product: Colour Me by Melange Women Pink Manda...
12,13,no,16887876,-,0.4210,Product: TANKHI Women Pink Floral Printed Tuni...
13,14,no,15737958,-,0.4165,Product: Fabindia Woman Pink & Beige Silk Orga...
14,15,no,16071640,-,0.3763,Product: Fabindia Women Pink Printed Front Ope...
15,16,no,18839688,-,0.3740,Product: Styli Pink Print Top Brand: Styli Col...
16,17,no,16012516,-,0.3719,Product: Fabindia Women Pink Striped Straight ...
17,18,no,10720170,-,0.3677,Product: Style Quotient Women Pink Self Design...
18,19,no,15720246,-,0.3597,Product: HIGHLIGHT FASHION EXPORT Pink Embroid...
19,20,no,6582659,-,0.3426,Product: W Women Pink Printed A-Line Layered C...
20,21,no,17777226,-,0.3247,Product: Prakrti Pink & White Ethnic Motifs Pr...
21,22,no,17820020,-,0.3223,Product: Mast & Harbour Pink Floral Print Mand...
22,23,no,18076132,-,0.3165,Product: Saree mall Pink & Black Printed Saree...
23,24,no,12151836,-,0.3066,Product: Bhama Couture Women Pink & Golden Pri...
24,25,no,15816496,-,0.2995,Product: Fabindia Pink Yoke Design V-Neck Kurt...
25,26,no,16071622,-,0.2981,Product: Fabindia Women Pink & Cream-Coloured ...
26,27,no,19134302,-,0.2976,Product: INDYA Women Pink Geometric Print Geor...
27,28,no,18244498,-,0.2957,Product: W Women Pink Geometric Striped Keyhol...
28,29,no,14138684,-,0.2926,Product: One of a Kind Women Pink Solid Kurtas...
29,30,no,15980892,-,0.2769,Product: Shae by SASSAFRAS Pink Printed Regula...

,rank,hit,section_id,title,score,preview
0,1,yes,17754230,-,1.0000,Product: Atsevam Cream-Coloured & Red Semi-Sti...
1,2,yes,19217170,-,0.9556,Product: Atsevam Red & Gold-Toned Embroidered ...
2,3,yes,17754248,-,0.9202,Product: Atsevam Red Embroidered Thread Work S...
3,4,yes,17584576,-,0.9056,Product: Atsevam Orange & Red Printed Tie and ...
4,5,yes,19217168,-,0.8924,Product: Atsevam Green & Gold-Toned Embroidere...
5,6,no,19217186,-,0.8827,Product: Atsevam Women Green & Pink Printed Ti...
6,7,yes,19217176,-,0.8490,Product: Atsevam White & Pink Tie and Dye Semi...
7,8,no,17834516,-,0.8386,Product: Atsevam Blue & Pink Ready to Wear Leh...
8,9,no,19217196,-,0.8250,Product: Atsevam Pink Embroidered Thread Work ...
9,10,yes,17754250,-,0.7913,Product: Atsevam Women Pink Embroidered Semi-S...
10,11,no,19162224,-,0.3501,Product: aturabi Peach-Coloured & White Halter...
11,12,no,15107864,-,0.2596,Product: Ives Sea Green Foil Printed A-Line To...
12,13,no,16504020,-,0.2303,Product: ANVI Be Yourself Women Attractive Pea...
13,14,no,14440146,-,0.2185,Product: AASI - HOUSE OF NAYO Navy Blue Stripe...
14,15,no,19232812,-,0.1966,Product: aturabi Green Georgette Top Brand: at...
15,16,no,19160198,-,0.1858,Product: aturabi Women Grey Solid Knee Length ...
16,17,no,14440118,-,0.1811,Product: AASI - HOUSE OF NAYO Navy Blue Crepe ...
17,18,no,17757300,-,0.1646,Product: itse Maroon & Golden Printed A-Line T...
18,19,no,14440122,-,0.1602,Product: AASI - HOUSE OF NAYO Pink Floral Bell...
19,20,no,18512872,-,0.1470,Product: Amrutam Fab Cream-Coloured & Navy Blu...
20,21,no,19160174,-,0.1466,Product: aturabi Women Black Checked Asymmetri...
21,22,no,17394300,-,0.1466,Product: ANVI Be Yourself Women Beige & Brown ...
22,23,no,17359094,-,0.1459,Product: Amrutam Fab Peach-Coloured & Purple E...
23,24,no,12135374,-,0.1255,Product: Anouk Beige & Red Antiviral Finish Et...
24,25,no,15509516,-,0.1237,Product: VASTRANAND Peach-Coloured Floral Mirr...
25,26,no,17150536,-,0.1231,Product: VASTRANAND Peach-Coloured & Multicolo...
26,27,no,19184810,-,0.1195,Product: VASTRAMAY Girls Cream-Coloured Embroi...
27,28,no,15107870,-,0.1173,Product: Ives Blue Printed Crepe A-Line Top Br...
28,29,no,10414130,-,0.1147,Product: AASI - HOUSE OF NAYO Women Off-White ...
29,30,no,19160178,-,0.1088,Product: aturabi Women's Green Solid Knee Leng...

,rank,hit,section_id,title,score,preview
0,1,no,18070000,-,1.0000,Product: panchhi Pink Embroidered Sequinned Un...
1,2,yes,12003682,-,0.9315,Product: panchhi Pink & Beige Embellished Semi...
2,3,yes,19046346,-,0.9200,Product: panchhi Pink & Sea Green Embellished ...
3,4,no,18175384,-,0.9155,Product: panchhi Pink Net Embroidered Sequinne...
4,5,no,13872486,-,0.7946,Product: panchhi Mustard & Pink Embroidered Se...
5,6,no,18175352,-,0.7838,Product: panchhi Lavender & Red Embroidered Se...
6,7,no,13421470,-,0.7831,Product: panchhi Mustard & Pink Embroidered Se...
7,8,no,19046338,-,0.7512,Product: panchhi Blue & Pink Embellished Semi-...
8,9,no,13421500,-,0.7504,Product: panchhi Lime Green & Lime Green Embro...
9,10,no,19046370,-,0.7445,Product: panchhi Lime Green & Embroidered Sequ...
10,11,no,18730470,-,0.7396,Product: panchhi Peach-Coloured & Blue Embroid...
11,12,no,13872488,-,0.7361,Product: panchhi Cream-Coloured & Yellow Embro...
12,13,no,17848104,-,0.7295,Product: panchhi Nude-Coloured Embellished Seq...
13,14,no,15393564,-,0.7259,Product: panchhi Beige & Peach-Coloured Embroi...
14,15,no,12668254,-,0.7121,Product: panchhi Red Codding Embroidered Semi-...
15,16,no,12003688,-,0.7068,Product: panchhi Green & Yellow Embellished Se...
16,17,no,12668248,-,0.6974,Product: panchhi Peach-Coloured & Green Semi-S...
17,18,no,18624652,-,0.6931,Product: panchhi Green & Gold Sequinned Semi-S...
18,19,no,16676710,-,0.6894,Product: panchhi Maroon & Silver-Toned Embroid...
19,20,no,16676694,-,0.6819,Product: panchhi Sea Green & Gold-Toned Embroi...
20,21,no,12003618,-,0.6748,Product: panchhi Green & Green Embroidered Sem...
21,22,no,19046354,-,0.6637,Product: panchhi Maroon Embellished Sequinned ...
22,23,no,18069992,-,0.6570,Product: panchhi Maroon Embroidered Sequinned ...
23,24,no,19046358,-,0.6509,Product: panchhi Sea Green & Red Embroidered S...
24,25,no,19046340,-,0.6491,Product: panchhi Yellow & Teal Embellished Sem...
25,26,no,18624644,-,0.6425,Product: panchhi Olive Green Embroidered Sequi...
26,27,no,18069988,-,0.6362,Product: panchhi Coral & Embroidered Sequinned...
27,28,no,14764064,-,0.6233,Product: panchhi Mustard & Orange Embroidered ...
28,29,no,13515246,-,0.6227,Product: panchhi Blue Embroidered Semi-Stitche...
29,30,no,19046324,-,0.6209,Product: panchhi Navy Blue & Mustard Embellish...

,rank,hit,section_id,title,score,preview
0,1,no,17612960,-,1.0000,Product: 250 DESIGNS Women Navy Blue Floral Co...
1,2,no,2507000,-,0.5666,Product: Roadster Pink Knitted Lace Top Brand:...
2,3,no,18290992,-,0.5014,Product: Superminis Girls Brown & Embroidered ...
3,4,no,17209256,-,0.4513,Product: Unnati Silks Cream-Coloured & Black E...
4,5,no,16372904,-,0.4465,Product: Netram Beige Embroidered Semi-Stitche...
5,6,no,18512872,-,0.4360,Product: Amrutam Fab Cream-Coloured & Navy Blu...
6,7,no,18290988,-,0.4182,Product: Superminis Girls Lime Green & Beige E...
7,8,no,15589086,-,0.3956,Product: Netram Lavender & Silver-Toned Semi-S...
8,9,no,17725246,-,0.3929,Product: DIVASTRI Red & Mustard Banarasi Silk ...
9,10,no,18258322,-,0.3824,Product: Netram Red & Gold-Toned Embroidered S...
10,11,no,18309022,-,0.3719,Product: PURVAJA Olive Green & Red Semi-Stitch...
11,12,no,19104000,-,0.3537,Product: Granthva Fab Blue & White Embroidered...
12,13,no,17638538,-,0.3534,Product: V SALES Grey & Orange Embellished Sem...
13,14,no,18549594,-,0.3223,Product: Amrutam Fab Mustard & Green Printed S...
14,15,no,18309012,-,0.3104,Product: PURVAJA Navy Blue & Red Semi-Stitched...
15,16,no,19104050,-,0.3013,Product: Granthva Fab Green & Black Embroidere...
16,17,no,18258324,-,0.2918,Product: Netram Peach-Coloured & Copper-Toned ...
17,18,no,18258316,-,0.2898,Product: Netram Red Embroidered Semi-Stitched ...
18,19,no,18008128,-,0.2856,Product: Superminis Girls Maroon & Beige Embro...
19,20,no,14501272,-,0.2820,Product: PURVAJA Navy Blue & Silver-Toned Semi...
20,21,no,15543206,-,0.2810,Product: V SALES Turquoise Blue & Grey Embroid...
21,22,no,19103994,-,0.2756,Product: Granthva Fab Peach-Coloured & Gold-To...
22,23,no,19104006,-,0.2725,Product: Granthva Fab Blue & Silver-Toned Embr...
23,24,no,13617704,-,0.2705,Product: Satrani Red & Silver-Toned Embroidere...
24,25,no,19104074,-,0.2681,Product: Granthva Fab White & Maroon Embroider...
25,26,no,17359094,-,0.2651,Product: Amrutam Fab Peach-Coloured & Purple E...
26,27,no,19083864,-,0.2361,Product: Amrutam Fab Blue & White Embroidered ...
27,28,no,18095156,-,0.2358,Product: Warthy Ent Cream-Coloured Sequinned S...
28,29,no,15451514,-,0.2193,Product: V SALES Red Embroidered Thread Work S...
29,30,no,18309016,-,0.2075,Product: PURVAJA Teal & Mustard Semi-Stitched ...

,rank,hit,section_id,title,score,preview
0,1,no,14869156,-,1.0000,Product: Indo Era Deep Black Solid Lehenga wit...
1,2,no,17553556,-,0.9859,Product: Indo Era Green & Gold-Toned Woven Des...
2,3,no,17473346,-,0.9230,Product: Indo Era Green & Gold-Toned Ethnic Mo...
3,4,no,13810898,-,0.9095,Product: Indo Era Women Blue & Green Printed K...
4,5,no,16188740,-,0.8976,Product: Indo Era Women Green Solid Cotton Pal...
5,6,yes,12122360,-,0.8965,Product: Indo Era Brown & Golden Woven Design ...
6,7,no,16950290,-,0.8926,Product: Indo Era Sea Green Floral Print Tie-U...
7,8,yes,13250074,-,0.8889,Product: Indo Era Maroon & Beige Woven Design ...
8,9,no,16713198,-,0.8884,Product: Indo Era Grey Silk Blend Scalloped Ed...
9,10,no,14197506,-,0.8860,Product: Indo Era Orange & Turquoise Blue Wove...
10,11,no,16682770,-,0.8853,Product: Indo Era Women Orange & Gold Striped ...
11,12,no,17069054,-,0.8796,Product: Indo Era Women Black Ethnic Motifs Yo...
12,13,no,12122358,-,0.8736,Product: Indo Era Women Black & Teal Blue Yoke...
13,14,no,15258422,-,0.8726,Product: Indo Era Floral Cotton Blend Calf Len...
14,15,no,16310880,-,0.8699,Product: Indo Era Women Black Ethnic Motifs Yo...
15,16,no,14197518,-,0.8693,Product: Indo Era Red & Golden Woven Design Du...
16,17,no,15798284,-,0.8535,Product: Indo Era Women Beige Floral Embroider...
17,18,no,15508896,-,0.8526,Product: Indo Era Women Green Ethnic Motifs Yo...
18,19,no,16950218,-,0.8508,Product: Indo Era Blue Ethnic Motif Printed Pe...
19,20,no,14235030,-,0.8416,Product: Indo Era Women Black Floral Printed P...
20,21,no,14323728,-,0.8398,Product: Indo Era Women Black & Golden Ethnic ...
21,22,no,11675882,-,0.8397,Product: Indo Era Grey & White Printed Ready t...
22,23,no,15654150,-,0.8375,Product: Indo Era Women Green Ethnic Motifs Yo...
23,24,no,12418804,-,0.8361,Product: Indo Era Women Maroon & Orange Yoke D...
24,25,no,17911130,-,0.8326,Product: Indo Era Women Burgundy Sequined Kurt...
25,26,no,14967448,-,0.8304,Product: Indo Era Women Green Ethnic Motifs Pr...
26,27,no,14239768,-,0.8299,Product: Indo Era Women Brown Solid Straight P...
27,28,no,17577456,-,0.8286,Product: Indo Era Women Classic Off-White Ethn...
28,29,no,15390174,-,0.8281,Product: Indo Era Women Blue Floral Printed Re...
29,30,no,11459658,-,0.8260,Product: Indo Era Folksy Floral Screen Print C...

,rank,hit,section_id,title,score,preview
0,1,yes,18626222,-,1.0000,Product: ONLY Women Blue Straight Fit High-Ris...
1,2,no,16372376,-,0.9860,Product: ONLY Women Blue Slim Fit High-Rise Mi...
2,3,no,19089666,-,0.9669,Product: ONLY Women Blue Slim Fit High-Rise Lo...
3,4,no,18620390,-,0.9567,Product: ONLY Women Blue Skinny Fit High-Rise ...
4,5,no,19089668,-,0.9372,Product: ONLY Women Blue Straight Fit High-Ris...
5,6,no,18626210,-,0.9366,Product: ONLY Women Blue Skinny Fit High-Rise ...
6,7,no,19089706,-,0.9295,Product: ONLY Women Blue Slim Fit High-Rise Mi...
7,8,no,17914728,-,0.9222,Product: ONLY Women Blue Straight Fit High-Ris...
8,9,no,19089694,-,0.8966,Product: ONLY Women Blue Straight Fit High-Ris...
9,10,no,16699772,-,0.8827,Product: ONLY Women Blue High-Rise Mildly Dist...
10,11,no,19143972,-,0.8442,Product: ONLY Women Blue Straight Fit High-Ris...
11,12,no,18620400,-,0.8274,Product: ONLY Women Blue Skinny Fit High-Rise ...
12,13,no,18626254,-,0.8111,Product: ONLY Women Blue Bootcut High-Rise Low...
13,14,no,16916588,-,0.7207,Product: ONLY Women Blue Mom-Fit High-Rise Lig...
14,15,no,18626232,-,0.7084,Product: ONLY Women Blue Skinny Fit High-Rise ...
15,16,no,18620404,-,0.7041,Product: ONLY Women Blue Skinny Fit High-Rise ...
16,17,no,19089710,-,0.6953,Product: ONLY Women Blue Flared Mildly Distres...
17,18,no,18626248,-,0.6822,Product: ONLY Women Blue Skinny Fit High-Rise ...
18,19,no,17914732,-,0.6821,Product: ONLY Women Blue Skinny Fit High-Rise ...
19,20,no,18626226,-,0.6768,Product: ONLY Women Blue Straight Fit High-Ris...
20,21,no,19089662,-,0.5435,Product: ONLY Women Blue Skinny Fit High-Rise ...
21,22,no,18809310,-,0.5012,Product: ONLY Women Blue Skinny Fit Light Fade...
22,23,no,18809318,-,0.4943,Product: ONLY Women Blue Skinny Fit Light Fade...
23,24,no,17570364,-,0.4693,Product: SHOWOFF Women Blue Straight Fit High-...
24,25,no,18822974,-,0.4286,Product: RAREISM Women Blue High-Rise Mildly D...
25,26,no,18338282,-,0.4262,Product: SHOWOFF Women Blue Slim Fit High-Rise...
26,27,no,17541860,-,0.4221,Product: RAREISM Women Blue High-Rise Mildly D...
27,28,no,19089682,-,0.3749,Product: ONLY Women Black Straight Fit Low-Ris...
28,29,no,16653658,-,0.3524,Product: Levis Women Blue 311 Shaping Skinny F...
29,30,no,16653786,-,0.3330,Product: Levis Women Blue 714 Straight Fit Hig...

,rank,hit,section_id,title,score,preview
0,1,yes,11425704,-,1.0000,Product: Uptownie Lite Brown Satin Pleated Fla...
1,2,no,11425706,-,0.9842,Product: Uptownie Lite Black Satin Pleated Fla...
2,3,yes,13467524,-,0.9362,Product: Uptownie Lite Women Red Solid Pleated...
3,4,yes,17944738,-,0.9160,Product: Uptownie Lite Grey Solid Pleated Form...
4,5,yes,11511460,-,0.8928,Product: Uptownie Lite Women Maroon Solid Plea...
5,6,no,15355338,-,0.8263,Product: Uptownie Lite Girls Black Crepe Print...
6,7,yes,16608122,-,0.8205,Product: Uptownie Lite Girls Black & Pink Prin...
7,8,no,11335786,-,0.8025,Product: Uptownie Lite Women Gold-Coloured Sol...
8,9,no,19169942,-,0.6396,Product: Uptownie Lite Women Yellow Crepe Smoc...
9,10,no,17267836,-,0.6323,Product: Uptownie Lite Red & Yellow Striped Ba...
10,11,no,11322090,-,0.6262,Product: Uptownie Lite Women Black Solid Basic...
11,12,no,13501842,-,0.5532,Product: Uptownie Lite Women Black Solid Dhoti...
12,13,no,11234642,-,0.5462,Product: Uptownie Lite Women Black Solid Basic...
13,14,no,10418102,-,0.5283,Product: Uptownie Lite Women Maroon Solid Ruff...
14,15,no,11234652,-,0.4580,Product: Uptownie Lite Women Burgundy Solid Ba...
15,16,no,15852580,-,0.2347,Product: URBANIC Black & White Printed Ruffle ...
16,17,no,13792342,-,0.2110,Product: U&F Purple Flared Maxi Skirt Brand: U...
17,18,no,15633536,-,0.1937,Product: URBANIC Women White & Coffee Brown Ab...
18,19,no,18542846,-,0.1936,Product: URBANIC Women Navy Blue Simplicity Fl...
19,20,no,15227004,-,0.1921,Product: U&F Womens Green Flared Skirt Brand: ...
20,21,no,13792352,-,0.1913,Product: U&F Peach-Coloured Flared Maxi Skirt ...
21,22,no,13792332,-,0.1907,Product: U&F Purple Flared Pleated Maxi Skirt ...
22,23,no,13792392,-,0.1794,Product: U&F Women Mustard Yellow Solid Accord...
23,24,no,13792344,-,0.1728,Product: U&F Woman's Purple Solid Skirt Brand:...
24,25,no,15850624,-,0.1711,Product: URBANIC Dusty Pink Cut-Out Styled Bac...
25,26,no,16542580,-,0.1619,Product: U&F Women Charming Lavender Solid Tie...
26,27,no,18872440,-,0.1556,Product: URBANIC Women Blue Heavy Fade Jeans B...
27,28,no,15852504,-,0.1545,Product: URBANIC Women Blue Cotton Mildly Dist...
28,29,no,15957650,-,0.1519,Product: U&F Women Maroon Solid Accordion Plea...
29,30,no,13792346,-,0.1447,Product: U&F Woman's Maroon Solid Skirt Brand:...

,rank,hit,section_id,title,score,preview
0,1,yes,16950080,-,1.0000,Product: Mitera Grey Embellished Sequinned Sem...
1,2,no,16950082,-,0.7499,Product: Mitera Green & Grey Embroidered Sequi...
2,3,no,18787332,-,0.7140,Product: Mitera Mauve & Silver-Toned Embroider...
3,4,no,16950094,-,0.6918,Product: Mitera Red & Silver-Toned Embellished...
4,5,no,18813862,-,0.6664,Product: Mitera White & Green Embroidered Sequ...
5,6,no,18813860,-,0.6643,Product: Mitera White & Green Embroidered Sequ...
6,7,no,18759692,-,0.6413,Product: Mitera Blue Embroidered Sequinned Sem...
7,8,no,18726440,-,0.6101,Product: Mitera Green & White Embroidered Sequ...
8,9,no,16950086,-,0.6053,Product: Mitera Pink Embellished Sequinned Sem...
9,10,no,18813850,-,0.6036,Product: Mitera White & Maroon Embroidered Seq...
10,11,no,17414454,-,0.5806,Product: Mitera Women Black & Golden Embroider...
11,12,no,18759676,-,0.5593,Product: Mitera Green & Gold-Toned Embroidered...
12,13,no,18813864,-,0.5515,Product: Mitera Peach-Coloured & Silver-Toned ...
13,14,no,16950084,-,0.5440,Product: Mitera Magenta Embroidered Sequinned ...
14,15,no,18726438,-,0.5396,Product: Mitera Rust & White Embroidered Sequi...
15,16,no,16291316,-,0.5377,Product: Mitera Green & Golden Embroidered Sem...
16,17,no,13515390,-,0.5202,Product: Mitera Blue & Gold-Toned Embroidered ...
17,18,no,16316606,-,0.5173,Product: Mitera Black Velvet Sequinned Semi-St...
18,19,no,16877304,-,0.5041,Product: Mitera Women Black & Silver Embroider...
19,20,no,16219572,-,0.4983,Product: Mitera Beige Semi-Stitched Lehenga & ...
20,21,no,11753804,-,0.4910,Product: Mitera Mustard Green & Pink Mirror Se...
21,22,no,12622760,-,0.4883,Product: Mitera Blue & Gold-Toned Embroidered ...
22,23,no,16877280,-,0.4792,Product: Mitera Women Maroon & Silver Embroide...
23,24,no,16950076,-,0.4774,Product: Mitera Yellow Embroidered Sequinned S...
24,25,no,11530674,-,0.4732,Product: Mitera Green & Pink Woven Design Semi...
25,26,no,16291342,-,0.4574,Product: Mitera Red & Golden Embroidered Semi-...
26,27,no,12622736,-,0.4557,Product: Mitera Navy Blue Embroidered Semi-Sti...
27,28,no,16219596,-,0.4433,Product: Mitera Maroon Semi-Stitched Lehenga &...
28,29,no,16291330,-,0.4388,Product: Mitera Red & Golden Embroidered Semi-...
29,30,no,12668574,-,0.4287,Product: Mitera Blue & Gold-Toned Woven Design...

,rank,hit,section_id,title,score,preview
0,1,yes,15243956,-,1.0000,Product: Suta Beige & White Pure Linen Zari Sa...
1,2,no,14988280,-,0.5059,Product: Suta Beige & Black Pure Cotton solid ...
2,3,no,16909300,-,0.4843,Product: Suta Off White & Black Zari Silk Cott...
3,4,no,14988194,-,0.4795,Product: Suta Gold-Toned Solid Zari Pure Linen...
4,5,no,15244224,-,0.4747,Product: Suta Beige & White Floral Embroidered...
5,6,no,15244002,-,0.4453,Product: Suta Pink & Gold-Toned Zari Pure Line...
6,7,no,17638770,-,0.4309,Product: Silk Land Beige & Red Ethnic Motifs Z...
7,8,no,15244024,-,0.3966,Product: Suta Beige Pink Floral Motifs PolyCot...
8,9,no,17781762,-,0.3864,Product: Silk Land Beige & Pink Woven Design Z...
9,10,no,15244106,-,0.3380,Product: Suta White & Pink Polka Dot Printed P...
10,11,no,15244118,-,0.3344,Product: Suta White & Black Ethnic Motifs Jamd...
11,12,no,18262236,-,0.3323,Product: Silk Land Beige & Navy Blue Kalamkari...
12,13,no,16909578,-,0.3156,Product: Suta Violet & Green Embellished Zari ...
13,14,no,17638792,-,0.3105,Product: Silk Land White & Blue Zari Pure Silk...
14,15,no,15511808,-,0.3063,Product: Suta Grey & Maroon Colourblocked Pure...
15,16,no,14988276,-,0.2960,Product: Suta Peach Blue Warli Printed Pure Co...
16,17,no,16909636,-,0.2863,Product: Suta Maroon & Pink Colourblocked Zari...
17,18,no,16909486,-,0.2851,Product: Suta Blue & Yellow Colourblocked Zari...
18,19,no,15243974,-,0.2701,Product: Suta Maroon White Hand Blocked Pure C...
19,20,no,17876884,-,0.2644,Product: Silk Land Navy Blue Ethnic Motifs Zar...
20,21,no,15244104,-,0.2634,Product: Suta Lavender Solid Pure Cotton Ruffl...
21,22,no,18390702,-,0.2614,Product: Suta Off White & Golden Striped Saree...
22,23,no,15243916,-,0.2312,Product: Suta Olive Green & Black Solid Pure C...
23,24,no,15435724,-,0.2242,Product: Suta Navy Blue & Pink Colourblocked M...
24,25,no,17902892,-,0.2222,Product: Silk Land Navy Blue & Golden Ethnic M...
25,26,no,15244114,-,0.2185,Product: Suta Mustard Yellow & Pink Solid Cott...
26,27,no,18166926,-,0.2112,Product: Suta Women White Embroidered Cotton S...
27,28,no,15243876,-,0.2012,Product: Suta Brown & Black Polka Dots Printed...
28,29,no,18676682,-,0.2002,Product: Ethnic Yard Beige & Grey Semi-Stitche...
29,30,no,17638756,-,0.1998,Product: Silk Land Green & Red Floral Zari Pur...

,rank,hit,section_id,title,score,preview
0,1,no,18069150,-,1.0000,Product: Levis Women Blue Skinny Fit Light Fad...
1,2,yes,16653786,-,0.9911,Product: Levis Women Blue 714 Straight Fit Hig...
2,3,no,18069276,-,0.9872,Product: Levis Women Blue Skinny Fit Light Fad...
3,4,no,18903336,-,0.9846,Product: Levis Women Blue 725 Bootcut Light Fa...
4,5,no,16653698,-,0.9680,Product: Levis Women Blue Straight Fit High-Ri...
5,6,no,18903198,-,0.9667,Product: Levis Women Blue Skinny Fit Light Fad...
6,7,no,18903182,-,0.9590,Product: Levis Women Blue Straight Fit High-Ri...
7,8,yes,16653608,-,0.9560,Product: Levis Women Blue Skinny Fit Light Fad...
8,9,no,16653772,-,0.9534,Product: Levis Women Blue Skinny Fit Light Fad...
9,10,yes,18069298,-,0.9465,Product: Levis Women Blue 710 Super Skinny Fit...
10,11,no,16653658,-,0.9463,Product: Levis Women Blue 311 Shaping Skinny F...
11,12,yes,18069260,-,0.9437,Product: Levis Women Blue 710 Super Skinny Fit...
12,13,yes,18069226,-,0.9396,Product: Levis Women Blue 710 Super Skinny Fit...
13,14,no,18069202,-,0.9372,Product: Levis Women Blue 710 Super Skinny Fit...
14,15,no,13326354,-,0.9307,Product: Levis Women Blue Super Skinny Fit Hig...
15,16,no,16794836,-,0.9261,Product: Levis Women Blue 721 Skinny Fit High-...
16,17,no,12259048,-,0.9211,Product: Levis Women Blue 710 Super Skinny Fit...
17,18,no,18903152,-,0.9210,Product: Levis Women Blue Skinny Fit High-Rise...
18,19,yes,16653750,-,0.9073,Product: Levis Women Blue 711 Skinny Fit Mid R...
19,20,no,16653760,-,0.9029,Product: Levis Women Blue 711 Skinny Fit Mid R...
20,21,yes,16532142,-,0.8983,Product: Levis Women Blue 711 Skinny Fit Light...
21,22,no,18903286,-,0.8920,Product: Levis Women Blue 711 Skinny Fit Light...
22,23,yes,16653678,-,0.8801,Product: Levis Women Blue 711 Skinny Fit Heavy...
23,24,no,16865718,-,0.8352,Product: Levis X Deepika Padukone Women Blue 7...
24,25,no,16794818,-,0.8348,Product: Levis Women Blue 501 Straight Fit Hig...
25,26,no,15022668,-,0.6644,Product: Levis Women Navy Blue Super Skinny Fi...
26,27,no,15506368,-,0.6061,Product: Levi's x Deepika Padukone Women Navy ...
27,28,no,18069146,-,0.5573,Product: Levis Women Blue Printed Drop-Shoulde...
28,29,no,16781554,-,0.5037,Product: Levis X Deepika Padukone Blue Ribbed ...
29,30,no,14860462,-,0.4814,Product: Levis Women Blue Round Neck Printed S...

,rank,hit,section_id,title,score,preview
0,1,no,19266888,-,1.0000,Product: H&M Women Black Solid Collared Sweats...
1,2,no,14080898,-,0.9124,Product: DressBerry Women Black Print Detail S...
2,3,no,15845464,-,0.9055,Product: URBANIC Women Black Solid Cotton Swea...
3,4,no,18004440,-,0.8588,Product: Aeropostale Women Black Printed Hoode...
4,5,no,15642616,-,0.8506,Product: Aesthetic Bodies Women Black Cotton S...
5,6,no,15630060,-,0.8447,Product: H&M Women Black Solid Hoodie Brand: H...
6,7,no,14512956,-,0.8289,Product: Powerpuff Girls by Kook N Keech Women...
7,8,no,19269372,-,0.7950,Product: BoStreet Women Black Colourblocked Lo...
8,9,yes,15198584,-,0.7613,Product: H&M Women Black Sweatshirt Brand: H&M...
9,10,no,10611428,-,0.7607,Product: Alsace Lorraine Paris Women Black Sol...
10,11,no,18962138,-,0.7574,Product: Nike Women Black CLUB FLC GX STD CREW...
11,12,no,15870014,-,0.7484,Product: New Balance Women Black Sweatshirt Br...
12,13,no,14080668,-,0.7463,Product: DressBerry Women Black Solid Sweatshi...
13,14,no,12048466,-,0.7347,Product: INVICTUS Women Black Solid Pullover B...
14,15,no,10714640,-,0.7328,Product: Taanz Women Black Solid Sweatshirt Br...
15,16,no,15086606,-,0.7181,Product: URBANIC Women Black Printed Sweatshir...
16,17,no,6726577,-,0.7076,Product: Mast & Harbour Women Black Solid Pull...
17,18,no,13615048,-,0.6810,Product: Flying Machine Women Black Solid Swea...
18,19,no,10683730,-,0.6669,Product: STREET 9 Women Black Solid Sweater Br...
19,20,no,9478497,-,0.6070,Product: The Roadster Lifestyle Co Women Black...
20,21,no,15869386,-,0.5913,Product: New Balance Women Black Solid Hooded ...
21,22,no,16533910,-,0.5864,Product: RAREISM Women Black Hooded Sweatshirt...
22,23,no,18144562,-,0.5698,Product: Marks & Spencer Women Black Sherpa Sw...
23,24,no,10575458,-,0.5560,Product: The Roadster Lifestyle Co Women Black...
24,25,no,10791506,-,0.5537,Product: The Vanca Women Black & Navy Blue Sol...
25,26,no,15778944,-,0.5440,Product: ONLY Women Black & Pink Striped Pullo...
26,27,yes,15963804,-,0.5381,Product: MANGO Women Black Solid Pullover Swea...
27,28,no,16583226,-,0.5376,Product: 20Dresses Women Black Plus Size Cotto...
28,29,no,13593756,-,0.5375,Product: BEVERLY BLUES Women Black Solid Sweat...
29,30,no,14518558,-,0.5306,Product: Powerpuff Girls by Kook N Keech Women...

,rank,hit,section_id,title,score,preview
0,1,no,13843640,-,1.0000,Product: Stylee LIFESTYLE Navy Blue & Gold-Ton...
1,2,no,18750730,-,0.8254,Product: Stylee LIFESTYLE Olive Green & Red Un...
2,3,no,19392350,-,0.8006,Product: Ethnic Yard Green & Grey Embroidered ...
3,4,no,17287376,-,0.7833,Product: Stylee LIFESTYLE Yellow & Gold-Toned ...
4,5,no,18766164,-,0.7406,Product: Stylee LIFESTYLE Black & Gold-Toned P...
5,6,no,19396408,-,0.6967,Product: Stylee LIFESTYLE Womens Beige Embroid...
6,7,no,16533888,-,0.6701,Product: Ethnic Junction Navy Blue & Gold-Tone...
7,8,no,17287346,-,0.6606,Product: Stylee LIFESTYLE Blue & Silver-Toned ...
8,9,no,14482774,-,0.6602,Product: Stylee LIFESTYLE Yellow Embroidered S...
9,10,no,16275034,-,0.6595,Product: Stylee LIFESTYLE Navy Blue & Coral Pr...
10,11,no,15224706,-,0.6572,Product: Stylee LIFESTYLE Green Embellished Se...
11,12,no,13185960,-,0.6528,Product: Stylee LIFESTYLE Women Navy Blue Embr...
12,13,no,18750736,-,0.5891,Product: Stylee LIFESTYLE Beige & Red Unstitch...
13,14,no,18190664,-,0.5677,Product: Stylee LIFESTYLE Maroon & Gold-Toned ...
14,15,no,19239046,-,0.5545,Product: Stylee LIFESTYLE Women Off White Embr...
15,16,no,15144126,-,0.5522,Product: Stylee LIFESTYLE Maroon & Gold-Toned ...
16,17,no,19342368,-,0.5444,Product: MORLY Beige & Gold-Toned Woven Design...
17,18,no,17149844,-,0.5041,Product: Stylee LIFESTYLE Women Teal & Red Uns...
18,19,no,12024994,-,0.4797,Product: Ethnic Junction Green Cotton Blend Un...
19,20,no,13843642,-,0.4718,Product: Stylee LIFESTYLE Navy Blue & White Sa...
20,21,no,17149842,-,0.4634,Product: Stylee LIFESTYLE Navy Blue & Yellow P...
21,22,no,13185952,-,0.4615,Product: Stylee LIFESTYLE Women Green & Brown ...
22,23,no,13996506,-,0.4562,Product: Stylee LIFESTYLE Blue & Gold-Toned Ne...
23,24,no,13869240,-,0.4511,Product: Stylee LIFESTYLE Blue Cotton Blend Un...
24,25,no,14990142,-,0.4387,Product: Stylee LIFESTYLE Turquoise Blue Embro...
25,26,no,18967572,-,0.4308,Product: Lilots Maroon & Gold-Toned Unstitched...
26,27,no,13856418,-,0.4224,Product: Safaa Off-White & Gold-Toned Cotton B...
27,28,no,11253802,-,0.4063,Product: Ishin Navy Blue & White Embroidered U...
28,29,no,17287372,-,0.3941,Product: Stylee LIFESTYLE Grey & Silver-Toned ...
29,30,no,14358624,-,0.3853,Product: Ethnic Junction Green & Gold-Toned Si...

,rank,hit,section_id,title,score,preview
0,1,no,13886174,-,1.0000,Product: Mitera Pink & White Pure Cotton Woven...
1,2,no,18287324,-,0.9565,Product: Mitera Floral Saree Brand: Mitera Col...
2,3,no,12668502,-,0.9472,Product: Mitera Pink & Blue Woven Design Semi-...
3,4,no,17552342,-,0.9199,Product: Mitera Floral Saree with Embroidered ...
4,5,yes,11244988,-,0.9192,Product: Mitera Pink & Gold-Toned Silk Blend W...
5,6,no,11218670,-,0.9063,Product: Mitera Pink & Gold-Toned Silk Blend W...
6,7,yes,18302880,-,0.8819,Product: Mitera Pink & Gold-Toned Woven Design...
7,8,no,18802314,-,0.8798,Product: Mitera Pink & Green Ethnic Motifs Wov...
8,9,no,16125582,-,0.8755,Product: Mitera Pink Embellished Mirror Work H...
9,10,no,12679536,-,0.8586,Product: Mitera Pink & White Pure Georgette Em...
10,11,no,17044538,-,0.8181,Product: Mitera Tie and Dye Pleated Saree Bran...
11,12,no,16950086,-,0.8143,Product: Mitera Pink Embellished Sequinned Sem...
12,13,yes,15012182,-,0.7550,Product: Mitera Pink & Silver-Toned Paisley Za...
13,14,no,16219622,-,0.7523,Product: Mitera Pink Thread Work Semi-Stitched...
14,15,no,14850332,-,0.7486,Product: Mitera Pink & Gold-Toned Woven Design...
15,16,no,11530714,-,0.7368,Product: Mitera Pink & Gold-Toned Woven Design...
16,17,no,15012204,-,0.7270,Product: Mitera Pink & Gold-Toned Woven Design...
17,18,no,16291288,-,0.7145,Product: Mitera Pink & Green Printed Block Pri...
18,19,yes,11454958,-,0.6788,Product: Mitera Pink & Golden Woven Design Ban...
19,20,no,16877306,-,0.6748,Product: Mitera Women Pink & Purple Embroidere...
20,21,no,15098912,-,0.6593,Product: Mitera Pink & Maroon Khari Print Semi...
21,22,no,16576222,-,0.6294,Product: Mitera Pink & Golden Ethnic Motifs Ba...
22,23,no,17669470,-,0.5282,Product: Mitera Colourblocked Satin Saree Bran...
23,24,no,16286086,-,0.5007,Product: Mitera Green & Pink Unstitched Dress ...
24,25,no,18585472,-,0.4430,Product: Mitera Black & Pink Floral Pure Linen...
25,26,no,11096590,-,0.4160,Product: Mitera Orange & Pink Silk Blend Woven...
26,27,no,17898990,-,0.3793,Product: Mitera Fuchsia Striped Sequinned Sare...
27,28,no,15519332,-,0.3702,Product: Mitera Purple & Pink Bandhani Saree B...
28,29,no,16286120,-,0.3477,Product: Mitera Red & Green Silk Blend Unstitc...
29,30,no,17325496,-,0.3443,Product: Mitera Green & Off-White Embroidered ...

,rank,hit,section_id,title,score,preview
0,1,no,18782606,-,1.0000,Product: max Women Black Printed Sweatshirt Br...
1,2,no,15878938,-,0.9750,Product: max Women Grey Printed Round Neck Swe...
2,3,no,18995122,-,0.9550,Product: max Women Black Printed Sweatshirt Br...
3,4,no,15878978,-,0.9170,Product: max Women Green Solid Round Neck Swea...
4,5,yes,15878996,-,0.8613,Product: max Women Olive Green Printed Round n...
5,6,no,15673658,-,0.8230,Product: max Women Peach-Coloured Printed Swea...
6,7,no,15670702,-,0.8183,Product: max Women Rust Pullover with Embellis...
7,8,yes,19204850,-,0.8027,Product: max Women Peach-Coloured Printed Slip...
8,9,yes,16156132,-,0.7187,Product: max Women Olive Green Printed Sweatsh...
9,10,no,19204868,-,0.6358,Product: max Women Lime Green Printed Sweatshi...
10,11,no,17748850,-,0.3602,Product: max Black Pure Cotton Dupatta Brand: ...
11,12,no,15630060,-,0.3275,Product: H&M Women Black Solid Hoodie Brand: H...
12,13,no,17155520,-,0.3263,Product: H&M Woman Grey Hoodie Brand: H&M Colo...
13,14,no,18992236,-,0.3134,Product: max Women Black Monochrome Shrug Bran...
14,15,no,15869842,-,0.2964,Product: New Balance Women Charcoal Grey Drop-...
15,16,no,13185846,-,0.2868,Product: OFF LIMITS Women Grey Melange Solid H...
16,17,no,16499970,-,0.2726,Product: Puma Women Blue Hooded Sweatshirt Bra...
17,18,no,15633514,-,0.2636,Product: URBANIC Women Khaki Cold-Shoulder Lon...
18,19,no,6726577,-,0.2398,Product: Mast & Harbour Women Black Solid Pull...
19,20,no,15007890,-,0.2295,Product: Hubberholme Women Navy Blue Solid Cro...
20,21,no,15844902,-,0.2262,Product: URBANIC Women Grey Ripped Longline Pu...
21,22,no,17155514,-,0.2255,Product: H&M Women Grey Solid Long Sweatshirt ...
22,23,no,16596744,-,0.2243,Product: max Women Black Sporty Jacket Brand: ...
23,24,no,14432282,-,0.2224,Product: max White Regular Top Brand: max Colo...
24,25,no,18743524,-,0.2200,Product: max Off-White Self Design Ruffles Puf...
25,26,no,19195576,-,0.2178,Product: max Black Lace Top Brand: max Color: ...
26,27,no,15596280,-,0.2157,Product: PUMA Women Black & Yellow Colourblock...
27,28,no,17686848,-,0.2141,Product: FOREVER 21 Women Brown Solid Cold Sho...
28,29,no,17570152,-,0.2048,Product: max Purple Solid Regular Top Brand: m...
29,30,no,19176852,-,0.2044,Product: H&M Men Grey Crew-Neck Sweatshirt Bra...

,rank,hit,section_id,title,score,preview
0,1,yes,15897498,-,1.0000,Product: The Roadster Lifestyle Co Women Navy ...
1,2,no,14331672,-,0.9454,Product: Roadster Women Navy Blue & Pink Strip...
2,3,yes,16187090,-,0.9451,Product: The Roadster Lifestyle Co Women Navy ...
3,4,yes,14094106,-,0.9434,Product: Roadster Women Deep Navy Blue High-Ri...
4,5,no,13334168,-,0.8949,Product: The Roadster Lifestyle Co Blue Solid ...
5,6,no,17074032,-,0.8383,Product: Roadster Women Navy Blue & White Stri...
6,7,no,5447351,-,0.8136,Product: Roadster Women Navy Blue Striped Card...
7,8,yes,12278652,-,0.8005,Product: Roadster Women Navy Blue Bootcut Mid-...
8,9,no,11296068,-,0.7805,Product: Roadster Women Navy Blue Solid Bell S...
9,10,no,14356168,-,0.7719,Product: Roadster Women Navy Blue & Maroon Col...
10,11,yes,12278640,-,0.7440,Product: Roadster Women Navy Blue Flared Fit H...
11,12,no,14356146,-,0.7269,Product: Roadster Women Navy Blue Convertible ...
12,13,no,14535784,-,0.7012,Product: Roadster Women Deep Navy Blue Solid D...
13,14,no,13700180,-,0.6637,Product: Roadster Women Navy Blue Solid Straig...
14,15,no,11542060,-,0.6175,Product: Roadster Women Blue Regular Fit Mid-R...
15,16,no,14925764,-,0.6001,Product: Roadster Women Navy Blue Pure Cotton ...
16,17,no,14954422,-,0.5741,Product: Roadster Women Blue Solid Light Fade ...
17,18,no,14356150,-,0.5704,Product: Roadster Women Navy Blue Grey Striped...
18,19,no,16835136,-,0.5599,Product: Roadster Women Indigo Wide Leg Light ...
19,20,yes,8963467,-,0.5542,Product: The Roadster Lifestyle Co Women Navy ...
20,21,no,15773298,-,0.5346,Product: Roadster Women Blue Flared Mildly Dis...
21,22,no,13756834,-,0.5336,Product: Roadster Women Blue Dropped Yoke Slim...
22,23,no,16835218,-,0.4921,Product: Roadster Women Blue Straight Fit High...
23,24,no,14094050,-,0.4756,Product: Roadster Women Deep Navy Blue High-Ri...
24,25,no,11688534,-,0.4748,Product: Roadster Women Blue Skinny Fit Mid-Ri...
25,26,yes,8803831,-,0.4705,Product: Roadster Women Navy Blue Skinny Fit M...
26,27,no,13756932,-,0.4681,Product: Roadster Women Blue Dropped Yoke Slim...
27,28,no,15773232,-,0.4651,Product: Roadster Women Blue Flared Jeans Bran...
28,29,no,14535816,-,0.4472,Product: Roadster Women Pure Cotton Navy Blue ...
29,30,no,14925804,-,0.4455,Product: Roadster Women Blue Slim Fit Light Fa...

,rank,hit,section_id,title,score,preview
0,1,no,14541316,-,1.0000,Product: KALINI Orange & Gold-Toned Ethnic Mot...
1,2,yes,14490860,-,0.8277,Product: KALINI Orange & Gold-Toned Pure Chiff...
2,3,no,18390376,-,0.5030,Product: KALINI Women Orange Printed Pure Cott...
3,4,no,14986192,-,0.4709,Product: KALINI Blue & Yellow Floral Saree Bra...
4,5,no,16915002,-,0.4512,Product: KALINI Women Green & Pink Ethnic Moti...
5,6,no,16848432,-,0.4458,Product: KALINI Maroon & Gold-Toned Ethnic Mot...
6,7,no,17066888,-,0.4456,Product: KALINI Brown & Orange Abstract Printe...
7,8,no,16421936,-,0.4396,Product: KALINI Pink & Gold-Toned Paisley Sare...
8,9,no,18435860,-,0.4222,Product: KALINI Red & Gold-Toned Embellished S...
9,10,no,17035752,-,0.4107,Product: KALINI Coral & Golden Woven Design Sa...
10,11,no,19167336,-,0.4076,Product: KALINI womens Yellow & Orange Dyed Co...
11,12,no,15102284,-,0.3959,Product: KALINI Green & Pink Ethnic Motifs Art...
12,13,no,16989798,-,0.3859,Product: KALINI Sea Green & Pink Ethnic Motifs...
13,14,no,17810904,-,0.3847,Product: KALINI Cream-Coloured & Gold-Toned St...
14,15,no,15102290,-,0.3715,Product: KALINI Pink & Gold-Toned Woven Design...
15,16,no,17852902,-,0.3626,Product: KALINI Pink & Gold-Toned Zari Saree B...
16,17,no,17584716,-,0.3611,Product: KALINI Purple & Orange Floral Bagh Sa...
17,18,no,14679542,-,0.3608,Product: KALINI Off White & Purple Art Silk Ik...
18,19,no,16915122,-,0.3576,Product: KALINI Green & White Bandhani Art Sil...
19,20,no,14798392,-,0.3557,Product: KALINI Pink & Green Ethnic Motifs Kot...
20,21,no,16697004,-,0.3459,Product: KALINI Green & Gold-Toned Woven Desig...
21,22,no,14678908,-,0.3341,Product: KALINI Pink & Yellow Floral Pure Chif...
22,23,no,16697006,-,0.3282,Product: KALINI Maroon & Gold Ethnic Motifs Za...
23,24,no,17035744,-,0.3138,Product: KALINI Black & Golden Woven Design Sa...
24,25,no,17118876,-,0.3118,Product: KALINI Blue & Pink Checked Ikat Saree...
25,26,no,15530056,-,0.3081,Product: KALINI Green & White Leheriya Saree B...
26,27,no,18907070,-,0.3070,Product: KALINI Women Red & Green Floral Embro...
27,28,no,15258754,-,0.3067,Product: KALINI Purple & Grey Ethnic Motifs Ar...
28,29,no,18265998,-,0.2972,Product: KALINI Teal Green & Gold-Toned Stripe...
29,30,no,12754022,-,0.2895,Product: KALINI Black & Red Jute Silk Embroide...

,rank,hit,section_id,title,score,preview
0,1,yes,14646546,-,1.0000,Product: HRX By Hrithik Roshan Outdoor Women W...
1,2,no,15789142,-,0.9416,Product: Slazenger Women Black Running Sporty ...
2,3,no,17069364,-,0.9290,Product: Jockey Women Black Solid Hooded Sport...
3,4,no,15789256,-,0.8764,Product: Slazenger Women Grey Brand Logo Runni...
4,5,no,18522690,-,0.7728,Product: H&M Women Black & White Baseball-Styl...
5,6,no,14957090,-,0.7171,Product: Zastraa Women Black Lightweight Tailo...
6,7,no,15634138,-,0.7154,Product: URBANIC Women Black Tailored Jacket B...
7,8,no,13609880,-,0.7086,Product: HRX by Hrithik Roshan Men Jet Black S...
8,9,no,18282028,-,0.7054,Product: CL SPORT Women Black Reversible Longl...
9,10,no,16191476,-,0.6878,Product: H&M Woman Black Faux-fur-trimmed jack...
10,11,no,15743742,-,0.6799,Product: ADIDAS Women Black Solid Essential In...
11,12,no,11383846,-,0.6760,Product: Alcis Nari Women Black Solid Lightwei...
12,13,no,17069368,-,0.6653,Product: Jockey Women Navy Blue Longline Tailo...
13,14,no,15389978,-,0.6357,Product: PERFKT-U Women Black & Mustard Yellow...
14,15,no,18144568,-,0.6090,Product: Marks & Spencer Women Black Padded Ja...
15,16,no,17069340,-,0.6087,Product: Jockey Women Purple Tailored Jacket B...
16,17,no,12918452,-,0.5684,Product: AGIL ATHLETICA Women Black Solid Spor...
17,18,no,17491608,-,0.5596,Product: Silvertraq Women Black Camouflage Pri...
18,19,no,15684018,-,0.5573,Product: Puma x FIRST MILE Women Purple & Whit...
19,20,no,15730230,-,0.5445,Product: AGIL ATHLETICA Women Navy Blue & Red ...
20,21,no,16100814,-,0.5321,Product: Reich Color Women Black Fleece Lightw...
21,22,no,15869352,-,0.5274,Product: New Balance Women Black Brand Logo Pr...
22,23,no,19267030,-,0.5248,Product: H&M Women Black Short Jacket Brand: H...
23,24,no,15849954,-,0.5167,Product: URBANIC Women Black & White Houndstoo...
24,25,no,15953824,-,0.5037,Product: Columbia Women Black Joy Peak Mid Hoo...
25,26,no,17391422,-,0.4974,Product: Fabindia Women Black Woolen Tailored ...
26,27,no,15836646,-,0.4934,Product: Puma Women Black White Brand Logo Spo...
27,28,no,1052282,-,0.4722,Product: SASSAFRAS Black Embellished Slim Fit ...
28,29,no,16596744,-,0.4568,Product: max Women Black Sporty Jacket Brand: ...
29,30,no,11862698,-,0.4423,Product: Jockey Women Charcoal Grey Melange Ef...

,rank,hit,section_id,title,score,preview
0,1,yes,16835166,-,1.0000,Product: The Roadster Lifestyle Co Women Grey ...
1,2,yes,16835204,-,0.9720,Product: Roadster Women Grey Slim Flared High-...
2,3,yes,16835178,-,0.9379,Product: Roadster Women Grey Slim Flared High-...
3,4,no,14536020,-,0.9170,Product: Roadster Woman Beautiful Grey Solid D...
4,5,yes,13339544,-,0.8984,Product: The Roadster Lifestyle Co Women Grey ...
5,6,no,14954602,-,0.8627,Product: Roadster Women Alluring Grey High-Ris...
6,7,no,14535994,-,0.8579,Product: Roadster Women Grey Solid Denim Truck...
7,8,no,15441284,-,0.7501,Product: The Roadster Lifestyle Co Women Grey ...
8,9,yes,13756948,-,0.7224,Product: Roadster Women Alluring Grey Mid-Rise...
9,10,yes,14954872,-,0.7152,Product: Roadster Women Grey Slouchy Fit Mid-R...
10,11,no,14535748,-,0.6782,Product: Roadster Women Alluring Grey Washed D...
11,12,no,11672562,-,0.6257,Product: Roadster Women Grey Regular Fit Solid...
12,13,yes,8319213,-,0.6089,Product: Roadster Women Grey Skinny Fit Mid-Ri...
13,14,yes,10388213,-,0.5865,Product: Roadster Women Grey Skinny Fit Mid-Ri...
14,15,no,11990670,-,0.4770,Product: Roadster Women Grey & Green Colourblo...
15,16,no,14535802,-,0.4631,Product: Roadster Women Beautiful Grey Self-De...
16,17,no,11697384,-,0.4292,Product: Roadster Black Round Neck Pure Cotton...
17,18,no,14356152,-,0.4209,Product: Roadster Women Grey & White Faux Fur ...
18,19,no,15773476,-,0.3838,Product: The Roadster Lifestyle Co. Women Blac...
19,20,no,14954702,-,0.3557,Product: Roadster Women Black Boyfriend Fit Li...
20,21,no,14536056,-,0.3234,Product: Roadster Women Charcoal Grey Pure Cot...
21,22,no,14954642,-,0.2927,Product: Roadster Women Black Boyfriend Fit Mi...
22,23,no,14356304,-,0.2906,Product: Roadster Women Charcoal Grey Solid Co...
23,24,no,14954422,-,0.2759,Product: Roadster Women Blue Solid Light Fade ...
24,25,no,13334168,-,0.2652,Product: The Roadster Lifestyle Co Blue Solid ...
25,26,no,13346740,-,0.2596,Product: The Roadster Lifestyle Co Women Black...
26,27,no,14954878,-,0.2584,Product: Roadster Women Charcoal Mid-Rise Stra...
27,28,no,14535904,-,0.2549,Product: Roadster Women Stylish Black Solid De...
28,29,no,17005816,-,0.2502,Product: Roadster Women Charcoal Grey Pure Cot...
29,30,no,4451422,-,0.2464,Product: Roadster Women Black Regular Fit Mid-...

,rank,hit,section_id,title,score,preview
0,1,no,16931960,-,1.0000,Product: all about you Teal Blue Self Design K...
1,2,no,18514120,-,0.9758,Product: Paralians Turquoise Blue Peplum Top B...
2,3,no,14641744,-,0.9617,Product: FabAlley Blue Puff Sleeve Chambray Pe...
3,4,no,11607414,-,0.9172,Product: Bhama Couture Women Blue Printed Pepl...
4,5,no,11607374,-,0.8630,Product: Bhama Couture Women Blue Printed Pepl...
5,6,no,18805426,-,0.7277,Product: BoStreet Blue Checked Peplum Top Bran...
6,7,no,17627582,-,0.6804,Product: kipek Women Deep Navy Blue Solid Top ...
7,8,no,15766290,-,0.6682,Product: Pepe Jeans Women Blue Pure Cotton Tro...
8,9,yes,16504028,-,0.6649,Product: ANVI Be Yourself Women Stunning Blue ...
9,10,no,4374524,-,0.6604,Product: RARE Women Green Self Design Peplum T...
10,11,no,5617740,-,0.6401,Product: plusS Sea Green Self Design Peplum To...
11,12,no,17445656,-,0.5994,Product: Vishudh Blue Floral Print Peplum Top ...
12,13,no,10783322,-,0.5815,Product: Sera Women Navy Blue Printed Peplum P...
13,14,no,8715089,-,0.5015,Product: plusS Women Blue Printed Peplum Top B...
14,15,no,16935640,-,0.4950,Product: flaher Women Blue Solid Art Silk Padd...
15,16,no,14658916,-,0.4723,Product: Pepe Jeans Women Blue Washed Mid-Rise...
16,17,no,13013166,-,0.4298,Product: SALWAR STUDIO Women Orange Solid Pepl...
17,18,no,17872080,-,0.4187,Product: Taavi Women Indigo & White Indigo Pri...
18,19,no,14867398,-,0.4158,Product: Janasya Women Blue & White Floral Ruf...
19,20,no,17557370,-,0.4061,Product: Pepe Jeans Women Navy Blue Printed Sh...
20,21,no,13382002,-,0.3860,Product: plusS Women Black Self-Design Smocked...
21,22,no,14424654,-,0.3448,Product: ROOTED Navy Blue Printed Peplum Top B...
22,23,no,18604646,-,0.3402,Product: Zink London Women Blue Floral Lace De...
23,24,no,12504862,-,0.3266,Product: Pepe Jeans Women Teal & White Striped...
24,25,no,14602502,-,0.3241,Product: Vishudh Black Geometric Mandarin Coll...
25,26,no,17566228,-,0.3049,Product: Inddus Women Blue Woven Design Top & ...
26,27,no,17132282,-,0.3004,Product: Athena Women Pretty Pink Self-Design ...
27,28,no,10717820,-,0.2912,Product: Bhama Couture Women Blue Embroidered ...
28,29,no,10627950,-,0.2771,Product: Magnetic Designs Women Blue Solid Bas...
29,30,no,14231406,-,0.2761,Product: all about you Women Blue Self-Design ...

,rank,hit,section_id,title,score,preview
0,1,yes,16533076,-,1.0000,Product: Madame Women Peach-Coloured Self Desi...
1,2,no,18948340,-,0.7722,Product: Madame Peach-Coloured Cuffed Sleeves ...
2,3,no,14556346,-,0.6073,Product: Madame Women White Solid Fuzzy Pullov...
3,4,no,15756110,-,0.5903,Product: Madame Women Pink Pullover Woolen Swe...
4,5,no,16566862,-,0.5359,Product: Madame Women Mauve Lightweight Puffer...
5,6,no,16512732,-,0.5266,Product: Madame Women Beige Self Design Pullov...
6,7,no,15964118,-,0.5018,Product: Madame Women Charcoal Front-Open Swea...
7,8,no,15997770,-,0.4677,Product: Madame Women Yellow & White Checked P...
8,9,no,16512720,-,0.3938,Product: Madame Women Grey Solid Cardigan Swea...
9,10,no,10611424,-,0.3923,Product: Alsace Lorraine Paris Women Peach-Col...
10,11,no,10611410,-,0.3741,Product: Alsace Lorraine Paris Women Peach-Col...
11,12,no,18846880,-,0.3661,Product: Madame Rust Orange Mandarin Collar To...
12,13,no,10891532,-,0.3518,Product: Alsace Lorraine Paris Women Peach-Col...
13,14,no,15616452,-,0.3466,Product: The Dry State Women Peach-Coloured Ho...
14,15,no,18948328,-,0.3382,Product: Madame Pink Solid Crop Top Brand: Mad...
15,16,no,11991442,-,0.3278,Product: Roadster Women Peach-Coloured Solid O...
16,17,no,19269812,-,0.3239,Product: Madame Women Green Tie-Up Shrug Brand...
17,18,no,15158394,-,0.3234,Product: Roadster Women Peach-Coloured Drop-Sh...
18,19,no,13534832,-,0.3007,Product: MANGO Women Peach-Coloured Self-Desig...
19,20,no,14231418,-,0.2938,Product: all about you Women Peach-Coloured Op...
20,21,no,18846868,-,0.2800,Product: Madame Black Studded Top Brand: Madam...
21,22,no,15963876,-,0.2678,Product: MANGO Women Peach-Coloured Cable Knit...
22,23,no,14516092,-,0.2530,Product: Kook N Keech Marvel Women Peach-Colou...
23,24,no,14312170,-,0.2502,Product: Sztori Women Plus Size Peach-Coloured...
24,25,no,15673658,-,0.2255,Product: max Women Peach-Coloured Printed Swea...
25,26,no,16351896,-,0.1899,Product: Missguided Women Peach-Coloured Solid...
26,27,no,8027069,-,0.1857,Product: Peppermint Girls Peach-Coloured Strai...
27,28,no,16472932,-,0.1752,Product: Juelle Women Peach-Coloured Corduroy ...
28,29,no,14824280,-,0.1737,Product: LilPicks Girls Peach-Coloured & Green...
29,30,no,19204850,-,0.1728,Product: max Women Peach-Coloured Printed Slip...

      precision  recall   mrr   ndcg  context_relevance
mean      0.081   0.748  0.57  0.609               0.85

,question,relevant_docs,retrieved_docs,precision,recall,mrr,ndcg,context_relevance
0,Show me Regular trousers within a budget of 2000.,"[17817750, 18770002, 18769968, 18769944, 18769...","[16279046, 11421530, 17393956, 17378344, 17625...",0.033333,0.125,0.050000,0.057588,0.50
1,"Can you find something similar to ""Athena Wome...",[11166548],"[11166548, 10758214, 12086086, 11634534, 11634...",0.033333,1.000,1.000000,1.000000,1.00
2,"Show me products like ""InWeave Women Red Print...",[18921114],"[18921114, 17168254, 15322490, 17168250, 15542...",0.033333,1.000,1.000000,1.000000,1.00
3,I need product with a Woven design pattern in ...,"[12824928, 18262088]","[10451734, 14402632, 19218994, 16719554, 17663...",0.000000,0.000,0.000000,0.000000,1.00
4,I'm looking for products from MANGO for everyd...,"[15315768, 15265896, 15265898, 16892568, 15977...","[16124612, 17607938, 15274016, 17808618, 18319...",0.033333,0.125,0.037037,0.052616,0.50
5,What do you have from Sweet Dreams in Playsuit...,"[11581420, 11581366]","[11581420, 11581448, 11581366, 12882594, 12882...",0.066667,1.000,1.000000,0.919721,1.00
6,I'm looking for Kurta set by Vishudh.,"[13536726, 15997054, 18262138, 13119222, 18263...","[13799826, 18688392, 17656860, 18929144, 17132...",0.266667,1.000,0.250000,0.598079,1.00
7,I'm looking for A-line by Ancestry.,"[15407228, 19152780, 14873702]","[14873856, 15407228, 14873702, 19152780, 19152...",0.100000,1.000,0.500000,0.732829,1.00
8,"Can you find something similar to ""FASHOR Wome...",[19140952],"[19140952, 18964098, 18116634, 19324632, 18964...",0.033333,1.000,1.000000,1.000000,1.00
9,Show me Blue Tailored jacket from Darzi.,[14460680],"[14460680, 14460654, 14460662, 17666226, 17666...",0.033333,1.000,1.000000,1.000000,0.75
10,"Can you find something similar to ""U.S. Polo A...",[13703470],"[13703470, 13690162, 15555424, 16220536, 15555...",0.033333,1.000,1.000000,1.000000,1.00
11,Does Mitera have any Bandhani for a festive oc...,[15637468],"[15637468, 15442988, 15519332, 16331704, 17141...",0.033333,1.000,1.000000,1.000000,0.50
12,Show me Pencil within a budget of 1500.,"[15940138, 9552849, 15301318, 12086086, 188349...","[14011652, 17739956, 18215398, 19072638, 17403...",0.033333,0.125,0.033333,0.051056,0.50
13,Do you have any Mustard Blouson for everyday w...,[13532718],"[14935802, 14400678, 11184982, 13018002, 19361...",0.033333,1.000,0.166667,0.356207,1.00
14,I need Blue Joggers by STREET 9.,"[13038932, 13071994]","[13071994, 13038932, 13038926, 13071970, 13038...",0.066667,1.000,1.000000,1.000000,1.00
15,Show me Front-open within a budget of 2800.,"[16382036, 16382150, 5829334, 5829327, 1199121...","[17685090, 19087856, 15137944, 17685350, 17226...",0.000000,0.000,0.000000,0.000000,0.50
16,Do you have anything from FILA in Red for ever...,[13255768],"[13255768, 16705336, 16705334, 16705280, 16705...",0.033333,1.000,1.000000,1.000000,0.50
17,I'm looking for products that cost no more tha...,"[13135238, 15241584, 13181706, 17739302, 15218...","[2117164, 16524266, 15266700, 15312982, 162174...",0.000000,0.000,0.000000,0.000000,0.50
18,Do you have anything from Bhama Couture in A-l...,"[12151804, 10355827, 10356731, 12151824, 10717...","[13969870, 9717189, 9430121, 13969820, 9430115...",0.266667,1.000,0.166667,0.548742,1.00
19,Do you have any Pink Peg trousers for everyday...,[15473916],"[13740956, 15473916, 18342112, 13459738, 18838...",0.033333,1.000,0.500000,0.630930,1.00
20,Show me Regular shorts within a budget of 1800.,"[15402090, 14170730, 18283554, 18747132, 16164...","[14272032, 14027018, 14272016, 14388576, 19235...",0.100000,0.375,0.111111,0.180888,0.50
21,I'm looking for Regular by H&M.,"[17964932, 17883620, 18652012, 14258606, 18084...","[17674588, 17965024, 12383500, 17842774, 17883...",0.166667,0.625,1.000000,0.527692,1.00
22,I need Pink Saree by KALINI.,"[15858094, 17852902, 15102290, 14678908, 16421...","[16421936, 15102290, 14678908, 17852902, 16914...",0.166667,1.000,1.000000,0.989606,1.00
23,Show me products within a budget of 1800.,"[17094636, 13905652, 13905672, 13905666, 23229...","[17226172, 17570458, 18142596, 17790642, 17685...",0.000000,0.000,0.000000,0.000000,0.50
24,I need product with a Other woven design patte...,"[16379852, 16379914, 15768366]","[16379914, 15768366, 19366710, 13616810, 13497...",0.100000,1.000,1.000000,0.921787,1.00
25,Do you have anything from SERONA FABRICS in Wh...,[15917640],"[15917640, 18845142, 18845144, 15907476, 15907...",0.033333,1.000,1.000000,1.000000,1.00
26,Do you have any Green Kurta set for a festive ...,"[17140156, 16505434, 14121912, 16825614, 16707...","[17447636, 15508896, 15258422, 16707970, 12989...",0.233333,0.875,0.250000,0.495782,1.00
27,I'm looking for something Black from URBANIC f...,"[15849954, 15634138, 18929182, 15086606, 15633...","[18328804, 18542924, 19072596, 18867438, 18644...",0.200000,0.750,0.125000,0.370913,1.00
28,Show me Black products for everyday wear.,"[9440729, 18207452, 18992236, 16612058, 907371...","[19270830, 19187496, 17570416, 12383500, 13552...",0.000000,0.000,0.000000,0.000000,1.00
29,I'm looking for something Blue from Swasti for...,[18819296],"[18819296, 19260152, 19260114, 15228886, 15635...",0.033333,1.000,1.000000,1.000000,1.00
30,I need Shirt style with a Abstract printed pat...,[13244594],"[13244594, 19201936, 15841446, 19195222, 18605...",0.033333,1.000,1.000000,1.000000,0.50
31,I'm looking for products by Atsevam.,"[17754230, 17754250, 17754248, 19217168, 19217...","[17754230, 19217170, 17754248, 17584576, 19217...",0.233333,1.000,1.000000,0.981544,1.00
32,What do you have from panchhi in products and ...,"[19046346, 12003682]","[18070000, 12003682, 19046346, 18175384, 13872...",0.066667,1.000,0.500000,0.693426,1.00
33,What do you have in products under 2500?,"[11765970, 17662818, 15514544, 18068482, 16989...","[17612960, 2507000, 18290992, 17209256, 163729...",0.000000,0.000,0.000000,0.000000,0.50
34,Show me products from Indo Era.,"[14239788, 11459668, 12040868, 15520698, 12040...","[14869156, 17553556, 17473346, 13810898, 16188...",0.066667,0.250,0.166667,0.169895,1.00
35,"Show me products like ""ONLY Women Blue Straigh...",[18626222],"[18626222, 16372376, 19089666, 18620390, 19089...",0.033333,1.000,1.000000,1.000000,1.00
36,Do you have anything from Uptownie Lite in Fla...,"[17944738, 16608122, 11511460, 11425704, 13467...","[11425704, 11425706, 13467524, 17944738, 11511...",0.166667,1.000,1.000000,0.899067,1.00
37,"Can you find something similar to ""Mitera Grey...",[16950080],"[16950080, 16950082, 18787332, 16950094, 18813...",0.033333,1.000,1.000000,1.000000,1.00
38,"Do you have anything similar to ""Suta Beige & ...",[15243956],"[15243956, 14988280, 16909300, 14988194, 15244...",0.033333,1.000,1.000000,1.000000,1.00
39,"Show me options from Levis for everyday wear, ...","[18069226, 16532142, 18069298, 18069260, 16653...","[18069150, 16653786, 18069276, 18903336, 16653...",0.266667,1.000,0.500000,0.617705,1.00
40,Show me Pullover that are Black and have Solid...,"[16707678, 16124454, 13534776, 15964092, 15274...","[19266888, 14080898, 15845464, 18004440, 15642...",0.066667,0.250,0.111111,0.128759,1.00
41,I'm looking for Dress that cost no more than 5...,"[13878542, 17705690, 18365368, 16921564, 16921...","[13843640, 18750730, 19392350, 17287376, 18766...",0.000000,0.000,0.000000,0.000000,0.50
42,I'm looking for something Pink from Mitera for...,"[15012182, 11454958, 11244988, 18302880]","[13886174, 18287324, 12668502, 17552342, 11244...",0.133333,1.000,0.200000,0.474005,1.00
43,I'm looking for Pullover from max for everyday...,"[19204850, 15878996, 16156132]","[18782606, 15878938, 18995122, 15878978, 15878...",0.100000,1.000,0.200000,0.470850,0.50
44,What do you have from Roadster in products and...,"[12278640, 11987092, 8803831, 8963467, 1227865...","[15897498, 14331672, 16187090, 14094106, 13334...",0.233333,0.875,1.000000,0.749486,1.00
45,Show me Orange Saree from KALINI.,[14490860],"[14541316, 14490860, 18390376, 14986192, 16915...",0.033333,1.000,0.500000,0.630930,1.00
46,Do you have any Black Tailored jacket for sports?,[14646546],"[14646546, 15789142, 17069364, 15789256, 18522...",0.033333,1.000,1.000000,1.000000,0.75
47,Do you have anything from Roadster in Grey for...,"[13756948, 8319213, 13339544, 14954872, 103882...","[16835166, 16835204, 16835178, 14536020, 13339...",0.266667,1.000,1.000000,0.917293,1.00
48,I need Peplum with a Self design solid pattern...,[16504028],"[16931960, 18514120, 14641744, 11607414, 11607...",0.033333,1.000,0.111111,0.301030,0.50
49,I need Peach Pullover by Madame.,[16533076],"[16533076, 18948340, 14556346, 15756110, 16566...",0.033333,1.000,1.000000,1.000000,1.00