In [5]:
import sys
sys.path.append("../../")
from pathlib import Path
from html import escape
import pandas as pd
from IPython.display import HTML, display

from retrieval.product_retriever import search_product_hybrid
from evaluation.eval import product_load_tests, evaluate_retrieval, context_relevance
from evaluation.classes import ContextRelevanceWrapper
from evaluation.reporting import (
    build_eval_question_report,
    build_retrieval_doc_rows,
    display_eval_question_report,
    export_retrieval_report_to_markdown,
    get_node_text,
)

In [6]:
def retrieving(test, top_k):
    context = search_product_hybrid(test.question, top_k=top_k)
    nodes = getattr(context, "nodes", context)
    return nodes

In [7]:
async def evaluate_all_retrieval(limit=None, top_k=5, markdown_path=None):
    
    tests = product_load_tests()
    selected_tests = tests[:limit] if limit is not None else tests
    rows = []
    question_reports = []

    for index, test in enumerate(selected_tests, start=1):
        nodes = retrieving(test, top_k)
        
        metrics = evaluate_retrieval(test, nodes, k=top_k)
        
        result = await context_relevance(ContextRelevanceWrapper(question=test.question, contexts=[get_node_text(item) for item in nodes]))
        metrics["context_relevance"] = result
        rows.append(metrics)
        filtered_metrics = {
            key: value
            for key, value in metrics.items()
            if key.startswith("precision") or key.startswith("recall") or key == "mrr" or key.startswith("ndcg") or key == "context_relevance"
        }
        doc_rows = build_retrieval_doc_rows(nodes, test.relevant_docs)
        display_eval_question_report(
            question=test.question,
            relevant_docs=test.relevant_docs,
            metrics=filtered_metrics,
            text_blocks=[],
            doc_rows=doc_rows,
            index=index,
            total=len(selected_tests),
            metric_columns=4,
        )
        question_report = build_eval_question_report(
            question=test.question,
            relevant_docs=test.relevant_docs,
            retrieved_docs=metrics["retrieved_docs"],
            doc_rows=doc_rows,
            extra_fields={"metrics": filtered_metrics},
            index=index,
            total=len(selected_tests),
        )
        question_reports.append(question_report)

    
    report_df = pd.DataFrame(rows)
    metric_columns = [column for column in report_df.columns if column.startswith(("precision", "recall", "ndcg")) or column in {"mrr", "context_relevance"}]
    summary_df = report_df[metric_columns].mean().to_frame(name="mean").T.round(3)

    display(HTML("<h2 style='margin:32px 0 12px;color:#24292f;'>Final metrics</h2>"))
    display(summary_df)

    if markdown_path is not None:
        saved_path = export_retrieval_report_to_markdown(
            report_df,
            question_reports,
            Path(markdown_path),
            notebook_path="notebooks/product/06_product_hybrid_retrieval.ipynb",
        )
        display(HTML(f"<p style='margin:12px 0 0;color:#1a7f37;'>Markdown report saved to: <code>{escape(str(saved_path))}</code></p>"))

    return report_df

In [8]:
await evaluate_all_retrieval(markdown_path="../../reports/product_hybrid_retrieving_evaluation.md", top_k=30, limit=50)

,rank,hit,section_id,title,score,preview
0,1,no,16279046,-,0.7403,Product: 20Dresses Women Blue Trousers Brand: ...
1,2,no,14220194,-,0.6205,Product: DressBerry Women Burgundy Trousers Br...
2,3,no,13523706,-,0.5000,Product: Varanga Women Black & White Geometric...
3,4,no,13647622,-,0.4860,Product: Varanga Women Pink & White Leheriya P...
4,5,no,13769372,-,0.4852,Product: Varanga Classic Black and White Bandh...
5,6,no,11421530,-,0.4290,Product: Ginni Arora Label Women Red Slim Fit ...
6,7,no,17393956,-,0.4245,Product: Fabindia Women Beige & Red Striped Co...
7,8,no,16044098,-,0.4189,Product: SASSAFRAS Women Blue Ribbed Trousers ...
8,9,no,18770032,-,0.3983,Product: Trendyol Women Black High-Rise Trouse...
9,10,no,17378344,-,0.3859,Product: Saffron Threads Women Black Original ...
10,11,no,17625016,-,0.3823,Product: Fabindia Women Off White Cotton Trous...
11,12,no,17104470,-,0.3703,Product: Fabindia Women Blue Striped Relaxed T...
12,13,no,18838354,-,0.3589,Product: Styli Women Multicoloured Printed Hig...
13,14,no,19011990,-,0.3550,Product: Trendyol Women Blue Pure Cotton Solid...
14,15,no,18769616,-,0.3466,Product: Trendyol Women Beige & Brown Pure Cot...
15,16,no,17608014,-,0.3465,Product: MANGO Women Green Chain Printed Trous...
16,17,no,10440556,-,0.3452,Product: DressBerry Women Olive Green Regular ...
17,18,no,14220222,-,0.3442,Product: DressBerry Women Green Trousers Brand...
18,19,no,18770054,-,0.3432,Product: Trendyol Women Blue & Yellow Ethnic M...
19,20,no,17046802,-,0.3431,Product: Chemistry Women Black Pleated Trouser...
20,21,no,14514992,-,0.3420,Product: RIVI Women Blue Regular Trousers Bran...
21,22,no,17197754,-,0.3383,Product: Mast & Harbour Women Blue Pure Cotton...
22,23,no,18867438,-,0.3378,Product: URBANIC Women Black Trousers Brand: U...
23,24,no,18811270,-,0.3357,Product: BoStreet Women White Loose Fit Trouse...
24,25,no,18838276,-,0.3296,Product: Styli Women Pink Skinny Fit High-Rise...
25,26,no,18838318,-,0.3292,Product: Styli Women White Tapered Fit High-Ri...
26,27,no,18838300,-,0.3284,Product: Styli Women Black Straight Fit High-R...
27,28,no,17830914,-,0.3252,Product: KALINI Women Grey Pleated Trousers Br...
28,29,no,17864146,-,0.3216,Product: plusS Women Olive Green Trousers Bran...
29,30,no,15693320,-,0.3194,Product: Fabindia Women Beige Ethnic Trousers ...

,rank,hit,section_id,title,score,preview
0,1,yes,11166548,-,1.0000,Product: Athena Women Burgundy Solid Tailored ...
1,2,no,16752820,-,0.3588,Product: armure Women Brown & White Checked Su...
2,3,no,16154596,-,0.3553,Product: SHAYE Women Black Solid Suede Kamala ...
3,4,no,16565622,-,0.3483,Product: Latin Quarters Women Maroon Suede Tai...
4,5,no,10856152,-,0.3282,Product: SASSAFRAS Women Burgundy Solid Tailor...
5,6,no,16420446,-,0.3167,Product: Harpa Women Red Suede Tailored Jacket...
6,7,no,10758214,-,0.3161,Product: Athena Women Burgundy Solid Pullover ...
7,8,no,12086086,-,0.3049,Product: Athena Women Burgundy Solid Pencil Mi...
8,9,no,12402376,-,0.3043,Product: Belle Fille Women Burgundy Solid Asym...
9,10,no,11634534,-,0.2999,Product: Athena Women Burgundy Solid Basic Jum...
10,11,no,11634536,-,0.2986,Product: Athena Women Burgundy Solid Basic Jum...
11,12,no,16420466,-,0.2824,Product: Harpa Women Black Solid Tailored Jack...
12,13,no,7779375,-,0.2563,Product: Athena Women White Solid Cropped Deni...
13,14,no,14231172,-,0.2176,Product: all about you Women Tan Brown Solid A...
14,15,no,14829462,-,0.1814,Product: Campus Sutra Women Tan Suede Windchea...
15,16,no,15038638,-,0.1794,Product: Campus Sutra Women Brown Suede Windch...
16,17,no,14320508,-,0.1788,Product: Sztori Plus Size Women Burgundy Hoode...
17,18,no,15907458,-,0.1776,Product: aarke Ritu Kumar Women Brown Suede Lo...
18,19,no,10321465,-,0.1753,Product: Belle Fille Women Green Solid Longlin...
19,20,no,10321483,-,0.1729,Product: Belle Fille Women Pink Solid Tailored...
20,21,no,14462796,-,0.1713,Product: HERE&NOW Women Olive Green Solid Tail...
21,22,no,10321487,-,0.1709,Product: Belle Fille Women Green Solid Tailore...
22,23,no,10321499,-,0.1704,Product: Belle Fille Women Navy Blue Solid Tai...
23,24,no,10321401,-,0.1684,Product: Belle Fille Women Sea Green Solid Tai...
24,25,no,14274176,-,0.1663,Product: HERE&NOW Women Pink Solid Tailored Ja...
25,26,no,10321367,-,0.1656,Product: Belle Fille Women Yellow Solid Tailor...
26,27,no,14462864,-,0.1601,Product: HERE&NOW Women Black Solid Tailored J...
27,28,no,11151684,-,0.1556,Product: Athena Women Grey Solid Single Breast...
28,29,no,11064260,-,0.1532,Product: SASSAFRAS Women Red Solid Tailored Ja...
29,30,no,14356158,-,0.1342,Product: Roadster Women Burgundy Convertible J...

,rank,hit,section_id,title,score,preview
0,1,yes,18921114,-,1.0000,Product: InWeave Women Red Printed A-Line Skir...
1,2,no,17168254,-,0.9423,Product: InWeave Women Red Printed Pure Cotton...
2,3,no,15322490,-,0.7090,Product: InWeave Women Black & Yellow Lahariya...
3,4,no,15447990,-,0.6932,Product: InWeave Women Bright Orange Printed T...
4,5,no,17168250,-,0.6841,Product: InWeave Women Blue Printed Pure Cotto...
5,6,no,15760840,-,0.6791,Product: InWeave Red & Gold-Toned Regular Crop...
6,7,no,15542594,-,0.6788,Product: InWeave Women Mustard Yellow & White ...
7,8,no,16524698,-,0.6162,Product: InWeave Women Green Printed Co-Ords B...
8,9,no,17355370,-,0.5421,Product: InWeave Women Elegant Charcoal Solid ...
9,10,no,18922178,-,0.4905,Product: InWeave Women Red Flared Palazzos Bra...
10,11,no,14402632,-,0.4304,Product: InWeave Mustard Yellow & Blue A-Line ...
11,12,no,15760922,-,0.3979,Product: InWeave Women Beautiful Off White Pri...
12,13,no,13497800,-,0.3867,Product: InWeave Women Red Striped A-Line Top ...
13,14,no,17168268,-,0.3858,Product: InWeave Women Pink & White Printed Pu...
14,15,no,13020628,-,0.3804,Product: InWeave Women Blue & Red Ikkat Printe...
15,16,no,16674956,-,0.3714,Product: SHAYE Women Red & White Printed A-Lin...
16,17,no,10833328,-,0.3701,Product: SASSAFRAS Pink & Rust Red Printed A-L...
17,18,no,18594576,-,0.3678,Product: Berrylush Gorgeous Red Floral Peekabo...
18,19,no,18922836,-,0.3456,Product: InWeave Navy Blue Empire Solid Kurti ...
19,20,no,18686138,-,0.3427,Product: KARAJ JAIPUR Women Red Embroidered An...
20,21,no,18686206,-,0.3427,Product: KARAJ JAIPUR Women Red Embroidered An...
21,22,no,18052092,-,0.3307,Product: InWeave Women Green & White Printed D...
22,23,no,16524822,-,0.3300,Product: InWeave Women Striking Pink Solid Asy...
23,24,no,7763575,-,0.3234,Product: Anouk Women Red Floral Print A-Line K...
24,25,no,15485484,-,0.3176,Product: InWeave Women Maroon & Blue Printed L...
25,26,no,18416280,-,0.3012,Product: Berrylush Deep Red Floral Peekaboo Bo...
26,27,no,13248456,-,0.2947,Product: anayna Women Red & Golden Printed Fee...
27,28,no,16972516,-,0.2785,Product: ANVI Be Yourself Women Gorgeous Red P...
28,29,no,18769480,-,0.2733,Product: Trendyol Women Red & White Floral Pri...
29,30,no,13020642,-,0.2639,Product: InWeave Women Mustard Yellow & Green ...

,rank,hit,section_id,title,score,preview
0,1,no,10451734,-,0.7541,Product: WEAVERS VILLA Women Mustard Yellow & ...
1,2,no,18122478,-,0.6697,Product: PERFECTBLUE Mustard Yellow & Fuchsia ...
2,3,no,19218994,-,0.5824,Product: Mitera Mustard & Red Woven Design Zar...
3,4,no,17663018,-,0.5580,Product: Dupatta Bazaar Mustard Yellow Ethnic ...
4,5,no,16719554,-,0.5474,Product: Banarasi Style Mustard Woven Design D...
5,6,no,11117288,-,0.5231,Product: Mitera Mustard & Pink Silk Blend Wove...
6,7,no,18135092,-,0.5223,Product: Mitera Mustard Yellow Ethnic Motifs Z...
7,8,no,17365722,-,0.4817,Product: I Saw It First Women Beige Striped Hi...
8,9,no,18141434,-,0.4767,Product: MANOHARI Mustard & Gold-Toned Woven D...
9,10,no,14159320,-,0.4766,Product: I AM FOR YOU Women Yellow & White Emb...
10,11,no,13452734,-,0.4728,Product: I AM FOR YOU Women Green & Grey Print...
11,12,no,17365728,-,0.4679,Product: I Saw It First Women Dusty Pink & Whi...
12,13,no,17365720,-,0.4439,Product: I Saw It First Women Green Solid Plea...
13,14,no,17403640,-,0.4361,Product: I Saw It First Women Khaki Crinkled T...
14,15,no,17403434,-,0.4172,Product: I Saw It First Women White & Blue Flo...
15,16,no,16921550,-,0.4121,Product: Safaa Women Mustard Woven Design Wool...
16,17,no,14071540,-,0.4075,Product: DressBerry Women Stylish Mustard Self...
17,18,no,17403254,-,0.3999,Product: I Saw It First Women Blue Skinny Fit ...
18,19,no,17403428,-,0.3886,Product: I Saw It First Women Blue Skinny Fit ...
19,20,no,14402632,-,0.3869,Product: InWeave Mustard Yellow & Blue A-Line ...
20,21,no,17403380,-,0.3835,Product: I Saw It First Women Blue Slash Knee ...
21,22,no,17403300,-,0.3806,Product: I Saw It First Women Blue Light Fade ...
22,23,no,12130790,-,0.3598,Product: Inddus Women Mustard Yellow & Red Wov...
23,24,no,19240508,-,0.3477,Product: max Women Mustard Yellow Yoke Design ...
24,25,no,18509068,-,0.3340,Product: SANGAM PRINTS Mustard & Golden Ethnic...
25,26,no,18696924,-,0.3258,Product: RANGMANCH BY PANTALOONS Women Mustard...
26,27,no,5567866,-,0.3204,Product: DressBerry Women Mustard Yellow Self ...
27,28,no,13676084,-,0.3179,Product: Vishudh Women Mustard Yellow Solid He...
28,29,no,15379610,-,0.3138,Product: Chhabra 555 Mustard Yellow & Red Semi...
29,30,no,18196770,-,0.3044,Product: LOOKNBOOK ART Mustard Yellow & Red Se...

,rank,hit,section_id,title,score,preview
0,1,no,14006764,-,0.5000,Product: Saree mall Floral Silk Blend Saree wi...
1,2,no,16124612,-,0.5000,Product: MANGO Black Self Design Regular Top B...
2,3,no,17607938,-,0.4349,Product: MANGO Women Coral Red Solid Double-Br...
3,4,no,18321088,-,0.4144,Product: HRITIKA Grey & Red Saree Brand: HRITI...
4,5,no,18877470,-,0.4058,Product: HRITIKA Red Satin Saree Brand: HRITIK...
5,6,no,15274016,-,0.3915,Product: MANGO Women Black Pullover Brand: MAN...
6,7,no,19165458,-,0.3908,Product: HRITIKA Women Pink Georgette Floral C...
7,8,no,17336142,-,0.3896,Product: UNDER ARMOUR Women Pink Loose Fit Tra...
8,9,no,18224860,-,0.3876,Product: HRITIKA Black Sequinned Saree Brand: ...
9,10,no,17808618,-,0.3834,Product: MANGO Off White Satin Finish Extended...
10,11,no,18319598,-,0.3764,Product: MANGO Women Beige Solid Oversize Fit ...
11,12,no,18468196,-,0.3626,Product: KAMI KUBI Women Blue schiffli-Embroid...
12,13,no,17270200,-,0.3477,Product: MANGO Coral Pink Solid A-line Midi Sk...
13,14,no,19324656,-,0.3442,Product: FASHOR Women Pink Floral Embroidered ...
14,15,no,18964098,-,0.3436,Product: FASHOR Women Turquoise Blue Geometric...
15,16,no,17872080,-,0.3433,Product: Taavi Women Indigo & White Indigo Pri...
16,17,no,18778410,-,0.3392,Product: FASHOR Women Multicoloured & nirvana ...
17,18,no,19198378,-,0.3370,Product: FASHOR Women Green Yoke Design Thread...
18,19,no,19324666,-,0.3370,Product: FASHOR Women Red Ethnic Motifs Thread...
19,20,no,14976268,-,0.3347,Product: FASHOR Women Red Bandhani Printed & Z...
20,21,no,19140952,-,0.3321,Product: FASHOR Women Blue Geometric Printed G...
21,22,no,13523706,-,0.3320,Product: Varanga Women Black & White Geometric...
22,23,no,15047458,-,0.3320,Product: FASHOR Women Multicoloured Ethnic Mot...
23,24,no,14340718,-,0.3301,Product: MANGO Women Peach-Coloured Solid Regu...
24,25,no,16486578,-,0.3282,Product: FASHOR Women Maroon Geometric Printed...
25,26,no,16072014,-,0.3261,Product: FASHOR Women Lavender Striped Keyhole...
26,27,no,16984006,-,0.3250,Product: FASHOR Women Pink Ethnic Motifs Yoke ...
27,28,no,17403640,-,0.3206,Product: I Saw It First Women Khaki Crinkled T...
28,29,no,13647622,-,0.3187,Product: Varanga Women Pink & White Leheriya P...
29,30,no,16124404,-,0.3171,Product: MANGO Women Cream-Coloured Solid Pull...

,rank,hit,section_id,title,score,preview
0,1,yes,11581420,-,1.0000,Product: Sweet Dreams Women Pink & Green Heart...
1,2,no,11581448,-,0.9842,Product: Sweet Dreams Women Pink & Green Heart...
2,3,yes,11581366,-,0.9836,Product: Sweet Dreams Women Pink & Green Heart...
3,4,no,12882594,-,0.5057,Product: Sweet Dreams Women Peach-Coloured & B...
4,5,no,13270464,-,0.4400,Product: Sweet Dreams Women Charcoal Grey Soli...
5,6,no,12882732,-,0.4342,Product: Sweet Dreams Women Coral Pink & Black...
6,7,no,14166398,-,0.4252,Product: Sweet Dreams Women Charcoal Grey Skin...
7,8,no,12459498,-,0.3765,Product: Sweet Dreams Women Black Solid Regula...
8,9,no,16533336,-,0.3681,Product: Sweet Dreams Women Beige Embroidered ...
9,10,no,14568680,-,0.3351,Product: Sweet Dreams Women Burgundy Hooded Sw...
10,11,no,19231232,-,0.2927,Product: Sweet Dreams Women Grey Humor & Comic...
11,12,no,13611470,-,0.2282,Product: 20Dresses Women Pretty Pink Printed P...
12,13,no,16006846,-,0.2260,Product: THE SILHOUETTE STORE Women Pink Solid...
13,14,no,16990014,-,0.2162,Product: SASSAFRAS Women Pretty Pink Solid Pla...
14,15,no,16450186,-,0.2132,Product: Berrylush Women Pretty Pink Printed R...
15,16,no,15955210,-,0.2122,Product: Missguided Pink Solid Playsuit Brand:...
16,17,no,16034502,-,0.1663,Product: Berrylush Women Bright Yellow Printed...
17,18,no,17919758,-,0.1650,Product: ONLY Women Pink Self Design Round Nec...
18,19,no,10053735,-,0.1533,Product: Cottinfab Women Pink & Black Printed ...
19,20,no,16172382,-,0.1514,Product: NEUDIS Red Cowl Neck Satin Regular To...
20,21,no,18489222,-,0.1498,Product: NEUDIS Red Cowl Neck Satin Top Brand:...
21,22,no,17255464,-,0.1481,Product: NEUDIS Women Satin Red Embillished So...
22,23,no,17171608,-,0.1472,Product: QUIERO Women Pretty Pink Self-Design ...
23,24,no,18057644,-,0.1454,Product: NEUDIS Women Black Solid Playsuit wit...
24,25,no,18057660,-,0.1428,Product: NEUDIS Women White Self-Design A-Line...
25,26,no,15301014,-,0.1417,Product: Athena Women Pretty Pink Sleek Jumpsu...
26,27,no,16858560,-,0.1334,Product: NEUDIS Women Black Comfort Flared Tro...
27,28,no,15381904,-,0.1291,Product: Berrylush Women Pink Solid Ruffled Ju...
28,29,no,3452046,-,0.1276,Product: Sera Blue & Peach-Coloured Printed Pl...
29,30,no,17238348,-,0.1189,Product: NEUDIS Beige Cowl Neck Sheen Satin Fi...

,rank,hit,section_id,title,score,preview
0,1,no,9867983,-,0.9155,Product: Vishudh Women Navy Blue Floral Printe...
1,2,no,13799826,-,0.8573,Product: Vishudh Women Grey & Gold-Coloured Ch...
2,3,no,14860664,-,0.8275,Product: Vishudh Women Black Regular Printed K...
3,4,yes,18929144,-,0.8201,Product: Vishudh Women Purple Ethnic Straight ...
4,5,yes,13536726,-,0.8195,Product: Vishudh Women Yellow & Off-White Prin...
5,6,no,7572969,-,0.8085,Product: Vishudh Women Red & Orange Self Desig...
6,7,yes,15997054,-,0.8030,Product: Vishudh Women Yellow Floral Embroider...
7,8,no,7572958,-,0.7704,Product: Vishudh Women Mauve Regular Kurta wit...
8,9,yes,13119222,-,0.7671,Product: Vishudh Women Black & Off-White Check...
9,10,no,13433674,-,0.7544,Product: Vishudh Women Sea Green & White Print...
10,11,no,15335772,-,0.7335,Product: Vishudh Women Yellow Striped Regular ...
11,12,no,17132180,-,0.7219,Product: Vishudh Women Black & Teal Blue Check...
12,13,no,16858486,-,0.6841,Product: Vishudh Women Red Embroidered Pure Co...
13,14,no,17656860,-,0.6835,Product: Vishudh Women Turquoise Blue Floral P...
14,15,yes,18262138,-,0.6815,Product: Vishudh Women Yellow & Grey Ethnic Mo...
15,16,no,18688392,-,0.6641,Product: Vishudh Women Printed Kurta with Dupa...
16,17,no,13975624,-,0.6611,Product: Vishudh Women Off-White Checked Kurta...
17,18,yes,15639890,-,0.6522,Product: Vishudh Women Green & White Floral Pr...
18,19,yes,15820432,-,0.6439,Product: Vishudh Women Off White Embroidered R...
19,20,no,18929396,-,0.6399,Product: Vishudh Women Pink Thread Work Kurta ...
20,21,no,18261878,-,0.6359,Product: Vishudh Women Blue Floral Printed Kur...
21,22,yes,18263032,-,0.6316,Product: Vishudh Women Checked Pure Cotton Kur...
22,23,no,16123926,-,0.6296,Product: Vishudh Women Mauve Floral Embroidere...
23,24,no,9673749,-,0.6271,Product: Vishudh Women Turquoise Blue & Gold-T...
24,25,no,17445358,-,0.6116,Product: Vishudh Women Purple Printed Kurta wi...
25,26,no,836967,-,0.4570,Product: Vishudh White & Green Shirt with Skir...
26,27,no,2467322,-,0.4420,Product: Vishudh Women Navy Blue & Mustard Pri...
27,28,no,7334039,-,0.4072,Product: Vishudh Women White & Pink Printed A-...
28,29,no,2076112,-,0.3811,Product: Vishudh Women Mustard Yellow Floral P...
29,30,no,18929148,-,0.3516,Product: Vishudh Women Turquoise Blue Pleated ...

,rank,hit,section_id,title,score,preview
0,1,no,14873856,-,0.9659,Product: Ancestry Women Grey & White Striped A...
1,2,yes,15407228,-,0.9245,Product: Ancestry Pink Pure Cotton Self Design...
2,3,yes,14873702,-,0.8918,Product: Ancestry Women Pink Melange Effect Pu...
3,4,yes,19152780,-,0.7807,Product: Ancestry Women Pink Regular Top Brand...
4,5,no,14873748,-,0.7679,Product: Ancestry Women Taupe Embroidered Long...
5,6,no,16588088,-,0.6814,Product: Ancestry Pink & Black Ethnic Motifs P...
6,7,no,15407188,-,0.6239,Product: Ancestry Women Navy Blue & White Pure...
7,8,no,19152792,-,0.6170,Product: Ancestry Women Gold-Toned Longline Ta...
8,9,no,17149934,-,0.6046,Product: Ancestry Women Maroon Crop Tailored J...
9,10,no,19152772,-,0.5881,Product: Ancestry Mustard Embroidered Organza ...
10,11,no,17326880,-,0.5619,Product: Ancestry Women Pink Regular Fit Pleat...
11,12,no,15407164,-,0.5438,Product: Ancestry White & Red Pure Cotton Geom...
12,13,no,14159320,-,0.3495,Product: I AM FOR YOU Women Yellow & White Emb...
13,14,no,19148248,-,0.2241,Product: H&M Women Brown Checked Pleated Skirt...
14,15,no,19147756,-,0.2140,Product: H&M Women Green Short Linen-Blend Ski...
15,16,no,17403640,-,0.2125,Product: I Saw It First Women Khaki Crinkled T...
16,17,no,17403254,-,0.2065,Product: I Saw It First Women Blue Skinny Fit ...
17,18,no,18834992,-,0.2063,Product: H&M Women Multi-Color Floral Patterne...
18,19,no,13452734,-,0.2055,Product: I AM FOR YOU Women Green & Grey Print...
19,20,no,18652038,-,0.2047,Product: H&M Women Beige Knitted Vest Top Bran...
20,21,no,17403434,-,0.2031,Product: I Saw It First Women White & Blue Flo...
21,22,no,17365722,-,0.2017,Product: I Saw It First Women Beige Striped Hi...
22,23,no,17403428,-,0.2010,Product: I Saw It First Women Blue Skinny Fit ...
23,24,no,17403380,-,0.1984,Product: I Saw It First Women Blue Slash Knee ...
24,25,no,17403300,-,0.1970,Product: I Saw It First Women Blue Light Fade ...
25,26,no,17365728,-,0.1956,Product: I Saw It First Women Dusty Pink & Whi...
26,27,no,17365646,-,0.1956,Product: I Saw It First Women Black & Yellow F...
27,28,no,17365720,-,0.1929,Product: I Saw It First Women Green Solid Plea...
28,29,no,19147754,-,0.1904,Product: H&M Women White Solid A-Line Mini Ski...
29,30,no,19097390,-,0.1523,Product: I Love She Women White Relaxed High-R...

,rank,hit,section_id,title,score,preview
0,1,yes,19140952,-,1.0000,Product: FASHOR Women Blue Geometric Printed G...
1,2,no,18964098,-,0.4348,Product: FASHOR Women Turquoise Blue Geometric...
2,3,no,11561972,-,0.3137,Product: Satrani Navy Blue Pure Cotton Printed...
3,4,no,17487138,-,0.3062,Product: Libas Women Green & Gold-Toned Geomet...
4,5,no,18964110,-,0.2648,Product: FASHOR Women Pink Printed Thread Work...
5,6,no,18116634,-,0.2590,Product: FASHOR Women Pink Ethnic Motifs Embro...
6,7,no,10935118,-,0.2462,Product: ANAISA Criss-Cross Screen Print Gotta...
7,8,no,16486578,-,0.2368,Product: FASHOR Women Maroon Geometric Printed...
8,9,no,14951330,-,0.1811,Product: Ahalyaa Women Beige Floral Printed Re...
9,10,no,17251886,-,0.1743,Product: SIRIL Blue & Beige Silk Cotton Khadi ...
10,11,no,16773346,-,0.1632,Product: KALINI Women Sea Green Printed Gotta ...
11,12,no,18127962,-,0.1610,Product: AURELIA Women Pink Geometric Printed ...
12,13,no,18787430,-,0.1602,Product: ADEESHA Women Turquoise Blue Printed ...
13,14,no,15241466,-,0.1597,Product: Clora Creation Navy Blue & Gold-Toned...
14,15,no,19324632,-,0.1502,Product: FASHOR Women Blue & White Yoke Design...
15,16,no,11369528,-,0.1482,Product: W Women Blue & Black Printed Straight...
16,17,no,17251884,-,0.1389,Product: SIRIL Green Silk Cotton Khadi Saree B...
17,18,no,17253466,-,0.1381,Product: SIRIL Green Floral Art Silk Khadi Sar...
18,19,no,15047458,-,0.1309,Product: FASHOR Women Multicoloured Ethnic Mot...
19,20,no,17132304,-,0.1284,Product: flaher Women Peach-Coloured Gotta Pat...
20,21,no,17739240,-,0.1266,Product: Clora Creation Green Dupatta with Got...
21,22,no,17739302,-,0.1266,Product: Clora Creation Magenta Dupatta with G...
22,23,no,15241494,-,0.1257,Product: Clora Creation Cream-Coloured & Gold-...
23,24,no,17662850,-,0.1251,Product: Dupatta Bazaar Gold-Toned Embroidered...
24,25,no,17739322,-,0.1232,Product: Clora Creation Cream-Coloured Embroid...
25,26,no,16362760,-,0.1163,Product: House of Pataudi Women Navy Blue Flor...
26,27,no,17739124,-,0.1150,Product: Clora Creation Blue & White Printed D...
27,28,no,13737562,-,0.1144,Product: Tikhi Imli Pink & Golden Embellished ...
28,29,no,19198414,-,0.1121,Product: FASHOR Women Navy Blue Floral Embroid...
29,30,no,16907804,-,0.1082,Product: Libas Women Blue Paisley Yoke Design ...

,rank,hit,section_id,title,score,preview
0,1,yes,14460680,-,0.8864,Product: Darzi Women Blue Tailored Jacket Bran...
1,2,no,17513236,-,0.8375,Product: Darzi Women Multicoloured Crop Tailor...
2,3,no,14460654,-,0.7938,Product: Darzi Women Red Tailored Jacket Brand...
3,4,no,14460662,-,0.7577,Product: Darzi Women Maroon Solid Longline Tai...
4,5,no,17666218,-,0.7522,Product: Darzi Women Yellow Tailored Jacket Br...
5,6,no,17665710,-,0.7423,Product: Darzi Women Yellow Striped Fleece Tai...
6,7,no,17666226,-,0.6702,Product: Darzi Women Maroon Tailored Jacket Br...
7,8,no,14460688,-,0.4139,Product: Darzi Women Brown Solid Longline Dust...
8,9,no,10321499,-,0.3981,Product: Belle Fille Women Navy Blue Solid Tai...
9,10,no,1017828,-,0.3776,Product: Campus Sutra Blue Jacket Brand: Campu...
10,11,no,15859778,-,0.3717,Product: Zink London Women Blue Solid Tailored...
11,12,no,13163000,-,0.3667,Product: FableStreet Women Blue Self Design Ta...
12,13,no,15784540,-,0.3448,Product: Yaadleen Women Turquoise Blue Floral ...
13,14,no,15851900,-,0.3435,Product: URBANIC Women Blue Solid Hooded Faux ...
14,15,no,13449644,-,0.3274,Product: DODO & MOA Women Navy Blue Checked As...
15,16,no,1010438,-,0.3063,Product: Belle Fille Red Tailored Jacket Brand...
16,17,no,10321465,-,0.2858,Product: Belle Fille Women Green Solid Longlin...
17,18,no,17665702,-,0.2787,Product: Darzi Women Navy Blue Colourblocked F...
18,19,no,15194458,-,0.2537,Product: Shae by SASSAFRAS Women Navy Blue & G...
19,20,no,16045698,-,0.2465,Product: KASSUALLY Women Blue Tailored Jacket ...
20,21,no,15811466,-,0.2263,Product: DECHEN Women Navy Blue Textured Tailo...
21,22,no,10319651,-,0.2116,Product: Belle Fille Women Blue Solid Hooded J...
22,23,no,11155510,-,0.2107,Product: Marie Claire Women Navy Blue Solid Ta...
23,24,no,16019732,-,0.2058,Product: RANGMANCH BY PANTALOONS Women Navy Bl...
24,25,no,11064260,-,0.2037,Product: SASSAFRAS Women Red Solid Tailored Ja...
25,26,no,16833328,-,0.1927,Product: Vero Moda Women Blue Floral Lightweig...
26,27,no,16154348,-,0.1826,Product: JC Mode Women Navy Blue Pink Floral P...
27,28,no,18835026,-,0.1824,Product: Lakshita Women Blue Fleece Longline T...
28,29,no,10321385,-,0.1805,Product: Belle Fille Women Blue Solid Double-B...
29,30,no,18787832,-,0.1771,Product: Tokyo Talkies Women Blue Washed Denim...

,rank,hit,section_id,title,score,preview
0,1,yes,13703470,-,1.0000,Product: U.S. Polo Assn. Women Beige Solid Bik...
1,2,no,13690162,-,0.5693,Product: U.S. Polo Assn. Women Black Solid Qui...
2,3,no,2185647,-,0.5500,Product: U.S.Polo Assn. Women Grey Longline Sh...
3,4,no,17983210,-,0.3834,Product: U S Polo Assn Women White Striped Hoo...
4,5,no,15555424,-,0.3281,Product: BEAVER Women Black Solid Biker Jacket...
5,6,no,17038718,-,0.3202,Product: U.S. Polo Assn. Kids Girls Yellow Pri...
6,7,no,16220536,-,0.3135,Product: 20Dresses Women Beige Biker Jacket Br...
7,8,no,15555432,-,0.2963,Product: BEAVER Women Black Solid Crop Biker J...
8,9,no,15555446,-,0.2808,Product: BEAVER Women Black Crop Biker Jacket ...
9,10,no,14355452,-,0.2786,Product: Roadster Women Chic Brown Solid Biker...
10,11,no,11933088,-,0.2710,Product: U.S. Polo Assn. Women Women Blue & Wh...
11,12,no,14355346,-,0.2369,Product: Roadster Women Stylish Black Solid Bi...
12,13,no,14017334,-,0.2278,Product: Leather Retail Women Brown Solid Ligh...
13,14,no,14355398,-,0.2240,Product: Roadster Women Chic Brown Solid Biker...
14,15,no,15800520,-,0.1896,Product: FabAlley Women Grey Solid Crop Biker ...
15,16,no,14829462,-,0.1792,Product: Campus Sutra Women Tan Suede Windchea...
16,17,no,14355478,-,0.1713,Product: Roadster Women Black Solid Coated Bik...
17,18,no,15027768,-,0.1712,Product: Campus Sutra Women Grey Solid Biker J...
18,19,no,15673166,-,0.1685,Product: Missguided Women Black Solid Biker Ja...
19,20,no,16258564,-,0.1665,Product: COVER STORY Women Stunning Blue Solid...
20,21,no,15038638,-,0.1662,Product: Campus Sutra Women Brown Suede Windch...
21,22,no,15982544,-,0.1639,Product: Tokyo Talkies Women Burgundy Leather ...
22,23,no,15673400,-,0.1562,Product: Missguided Women Black Solid Longline...
23,24,no,16091198,-,0.1548,Product: Tokyo Talkies Women Mustard Yellow Cr...
24,25,no,15880878,-,0.1438,Product: Justanned Women Black Striped Leather...
25,26,no,16258552,-,0.1408,Product: COVER STORY Women Deep Burgundy Solid...
26,27,no,16220586,-,0.1353,Product: 20Dresses Women Black Biker Jacket Br...
27,28,no,17981980,-,0.1330,Product: Justanned Women Black Leather Lightwe...
28,29,no,14862444,-,0.1306,Product: Campus Sutra Women Black & Grey Colou...
29,30,no,16091212,-,0.1247,Product: Tokyo Talkies Women Burgundy Solid Cr...

,rank,hit,section_id,title,score,preview
0,1,yes,15637468,-,0.8745,Product: Mitera Yellow & Multicoloured Floral ...
1,2,no,17141480,-,0.8345,Product: Mitera Women Olive Green Embroidered ...
2,3,no,17141474,-,0.7769,Product: Mitera Women Yellow Embroidered Pure ...
3,4,no,15519332,-,0.7624,Product: Mitera Purple & Pink Bandhani Saree B...
4,5,no,15519378,-,0.6332,Product: Mitera Navy Blue Bandhani Printed Sar...
5,6,no,15442988,-,0.6219,Product: Mitera Blue Embellished Embroidered R...
6,7,no,16311070,-,0.6179,Product: Mitera Maroon & White Bandhani Printe...
7,8,no,16331704,-,0.5711,Product: Mitera Yellow & Red Bandhani Saree Br...
8,9,no,17392504,-,0.3650,Product: Mitera Blue & Gold-Toned Ethnic Motif...
9,10,no,17325496,-,0.3431,Product: Mitera Green & Off-White Embroidered ...
10,11,no,17325492,-,0.3403,Product: Mitera Green & Golden Embroidered Uns...
11,12,no,16595928,-,0.3333,Product: Mitera Maroon & Golden Ethnic Motifs ...
12,13,no,17325498,-,0.3285,Product: Mitera Maroon & Golden Embroidered Un...
13,14,no,17325490,-,0.3190,Product: Mitera Black & Golden Embroidered Uns...
14,15,no,16286084,-,0.3166,Product: Mitera Black & Gold-Toned Unstitched ...
15,16,no,12668552,-,0.2997,Product: Mitera Turquoise Blue & Red Woven Des...
16,17,no,12668502,-,0.2968,Product: Mitera Pink & Blue Woven Design Semi-...
17,18,no,17206828,-,0.2882,Product: Mitera Black & Beige Embroidered Unst...
18,19,no,11662456,-,0.2876,Product: Geroo Jaipur Hand Dyed Bandhani Print...
19,20,no,16171474,-,0.2854,Product: Mitera Red & Gold-Toned Dupion Silk B...
20,21,no,16286120,-,0.2835,Product: Mitera Red & Green Silk Blend Unstitc...
21,22,no,11530694,-,0.2686,Product: Mitera Peach-Coloured & Gold-Toned Em...
22,23,no,16588146,-,0.2629,Product: Mitera Blue & Purple Ethnic Motifs Si...
23,24,no,18302882,-,0.2572,Product: Mitera Teal & Gold-Toned Woven Design...
24,25,no,12766966,-,0.2450,Product: Ishin Women Red & Orange Bandhani Pri...
25,26,no,14994700,-,0.2395,Product: Anouk Purple & Pink Bandhani Print Sa...
26,27,no,14994712,-,0.2395,Product: Anouk Orange & Red Bandhani Printed S...
27,28,no,15012204,-,0.2388,Product: Mitera Pink & Gold-Toned Woven Design...
28,29,no,16915122,-,0.2376,Product: KALINI Green & White Bandhani Art Sil...
29,30,no,13348352,-,0.2347,Product: VASTRANAND Orange Poly Georgette Prin...

,rank,hit,section_id,title,score,preview
0,1,no,14011652,-,0.7973,Product: FableStreet Black Mini Pencil Skirt B...
1,2,no,1294879,-,0.7723,Product: Purple Feather Black Pencil Skirt Wit...
2,3,no,18215398,-,0.6984,Product: Popwings Women Camel Brown Pencil Sli...
3,4,no,14798956,-,0.6931,Product: Trendyol Women Taupe Solid Pencil Mid...
4,5,no,17899166,-,0.6753,Product: PATRORNA Women Green Solid Pencil Abo...
5,6,no,14372466,-,0.6714,Product: Chemistry Black Pure Cotton Ribbed Mi...
6,7,no,17739956,-,0.6387,Product: Kotty Women Black Solid Faux Leather ...
7,8,no,13496046,-,0.6238,Product: FableStreet Olive Green Knitted Penci...
8,9,no,17931744,-,0.6187,Product: PATRORNA Women Green & Black Solid Kn...
9,10,no,19072638,-,0.6118,Product: DRAAX Fashions Women Maroon Solid Min...
10,11,no,17403200,-,0.6087,Product: BROADSTAR Women Black Solid Pencil Mi...
11,12,no,19181106,-,0.5978,Product: Bitterlime Women Olive Green & Black ...
12,13,no,18215396,-,0.5949,Product: Popwings Women Above Knee-Length Blac...
13,14,no,17306262,-,0.5882,Product: Purple Feather Women Black Solid Stre...
14,15,no,17927414,-,0.5779,Product: PATRORNA Women Sea Green Solid Above ...
15,16,no,17899190,-,0.5708,Product: PATRORNA Women Purple Solid Pencil Ab...
16,17,no,17898168,-,0.5640,Product: PATRORNA Women Black Solid Knee Lengt...
17,18,no,17365546,-,0.5494,Product: BROADSTAR Women Black Solid Pencil Kn...
18,19,no,17795314,-,0.5443,Product: Trend Arrest Women Navy Blue Sequence...
19,20,no,18034350,-,0.5433,Product: Missguided Women Olive Green Solid Mi...
20,21,no,14024850,-,0.5353,Product: OTORVA Women Denim Blue Solid Pencil ...
21,22,no,18841536,-,0.5344,Product: Styli Women Burgundy Solid Pencil Ski...
22,23,no,15315920,-,0.5276,Product: MANGO Women Mint Green Solid Pure Cot...
23,24,no,18977850,-,0.5237,Product: Popwings Women Black Solid Pencil Ski...
24,25,no,12086090,-,0.5202,Product: Athena Women Pink Solid Midi Pencil S...
25,26,no,17694094,-,0.5182,Product: Antheaa Women Black Embellished Penci...
26,27,no,18629568,-,0.5020,Product: IX IMPRESSION Women Gold Solid Pencil...
27,28,no,18173820,-,0.4884,Product: Kotty Women Brown Solid Faux Leather ...
28,29,no,14270952,-,0.4829,Product: NEUDIS Women Pack Of 2 Solid Velvet P...
29,30,no,16042324,-,0.4815,Product: STYL CO. Women Green & Orange Graphic...

,rank,hit,section_id,title,score,preview
0,1,no,14935802,-,0.9683,Product: Roadster Women Deep Mustard Solid Ruc...
1,2,yes,13532718,-,0.8325,Product: Harpa Women Mustard Printed Blouson T...
2,3,no,11184982,-,0.7684,Product: Mast & Harbour Women Off-White & Must...
3,4,no,7942995,-,0.6599,Product: Mustard Yellow Textured Blouse Brand:...
4,5,no,19207552,-,0.4952,Product: UNITED LIBERTY Women Purple & Gold-To...
5,6,no,11364440,-,0.4891,Product: SASSAFRAS Women Blue & Off-White Prin...
6,7,no,18229566,-,0.4784,Product: FOREVER 21 Women Red Typography Print...
7,8,no,14231200,-,0.4762,Product: all about you Women Mustard Brown Sol...
8,9,no,13845674,-,0.4722,Product: Shae by SASSAFRAS Women Black Ikat Pr...
9,10,no,16931650,-,0.4483,Product: all about you Mustard Yellow Self-Des...
10,11,no,16172382,-,0.4229,Product: NEUDIS Red Cowl Neck Satin Regular To...
11,12,no,18489222,-,0.4178,Product: NEUDIS Red Cowl Neck Satin Top Brand:...
12,13,no,17255464,-,0.4121,Product: NEUDIS Women Satin Red Embillished So...
13,14,no,14400678,-,0.4008,Product: BLANC9 Women Mustard Yellow Solid Cot...
14,15,no,16084334,-,0.3869,Product: Orchid Blues Grey & Pink Floral Print...
15,16,no,18057660,-,0.3757,Product: NEUDIS Women White Self-Design A-Line...
16,17,no,13018002,-,0.3657,Product: Blissta Mustard Yellow & Gold-Toned S...
17,18,no,18839638,-,0.3619,Product: Styli Beige Blouson Top Brand: Styli ...
18,19,no,19361356,-,0.3528,Product: BoStreet Women Mustard Yellow Solid T...
19,20,no,8474043,-,0.3419,Product: Berrylush Women Green Solid Blouson T...
20,21,no,12419366,-,0.3402,Product: Revolution Black & White Checked Plus...
21,22,no,18806012,-,0.3271,Product: awesome Red & Gold-Toned Woven Design...
22,23,no,13581118,-,0.3262,Product: SASSAFRAS Pink & Orange Floral Printe...
23,24,no,16858560,-,0.3238,Product: NEUDIS Women Black Comfort Flared Tro...
24,25,no,17143504,-,0.3224,Product: Tokyo Talkies White Embroidered Blous...
25,26,no,16470574,-,0.3206,Product: armure Women Mustard Striped Lightwei...
26,27,no,13463808,-,0.3146,Product: Global Desi Red Sustainable Printed C...
27,28,no,13023122,-,0.3061,Product: Athena Women Mustard Yellow Solid Bla...
28,29,no,13861554,-,0.2872,Product: mf Mustard & Pink Cotton Blend Unstit...
29,30,no,17238348,-,0.2850,Product: NEUDIS Beige Cowl Neck Sheen Satin Fi...

,rank,hit,section_id,title,score,preview
0,1,yes,13071994,-,1.0000,Product: STREET 9 Women Blue Regular Fit Solid...
1,2,yes,13038932,-,0.9706,Product: STREET 9 Women Blue Regular Fit Solid...
2,3,no,13038926,-,0.7768,Product: STREET 9 Women Green & Black Regular ...
3,4,no,13071970,-,0.7563,Product: STREET 9 Women Green Solid Cargo Jogg...
4,5,no,13038922,-,0.7468,Product: STREET 9 Women Yellow Regular Fit Sol...
5,6,no,13071980,-,0.7401,Product: STREET 9 Women Yellow Regular Fit Pri...
6,7,no,13038960,-,0.7397,Product: STREET 9 Women Black & Yellow Regular...
7,8,no,16336020,-,0.7243,Product: STREET 9 Women Bright Orange Typograp...
8,9,no,13738666,-,0.7187,Product: STREET 9 Women Olive Green & Black Re...
9,10,no,5389019,-,0.6351,Product: STREET 9 Women Blue Striped Culotte J...
10,11,no,19361312,-,0.6291,Product: STREET 9 Women Brown Printed Smart Lo...
11,12,no,15803276,-,0.5670,Product: STREET 9 Blue Basic Jumpsuit Brand: S...
12,13,no,6608510,-,0.5359,Product: STREET 9 Navy Blue Solid Basic Jumpsu...
13,14,no,12277584,-,0.5253,Product: STREET 9 Women Navy Blue Regular Fit ...
14,15,no,9781829,-,0.4109,Product: STREET 9 Blue Denim Pleated Mini A-Li...
15,16,no,12693476,-,0.3981,Product: STREET 9 Women Blue Straight Fit Mid-...
16,17,no,13041492,-,0.3958,Product: STREET 9 Women Blue Solid Sweatshirt ...
17,18,no,13038878,-,0.3953,Product: STREET 9 Women Blue Solid Sweatshirt ...
18,19,no,12693490,-,0.3942,Product: STREET 9 Women Blue Straight Fit Mid-...
19,20,no,14136072,-,0.3938,Product: STREET 9 Women Blue Flared Faded Para...
20,21,no,12682016,-,0.3881,Product: STREET 9 Women Blue Skinny Fit Mid-Ri...
21,22,no,9340267,-,0.3871,Product: STREET 9 Black & White Striped Croppe...
22,23,no,12682038,-,0.3792,Product: STREET 9 Women Blue Skinny Fit Mid-Ri...
23,24,no,17904100,-,0.3776,Product: STREET 9 Women Blue Hottie Relaxed Fi...
24,25,no,14136188,-,0.3649,Product: STREET 9 Women Blue Relaxed Fit Mid-R...
25,26,no,8694599,-,0.3601,Product: STREET 9 Green & Black Colourblocked ...
26,27,no,12277606,-,0.3576,Product: STREET 9 Women Olive Green & Brown Ca...
27,28,no,15884810,-,0.3529,Product: STREET 9 Navy Blue Satin Midi Dress B...
28,29,no,5389041,-,0.3348,Product: STREET 9 Women White & Black Checked ...
29,30,no,11234422,-,0.3109,Product: STREET 9 Women White & Grey Printed B...

,rank,hit,section_id,title,score,preview
0,1,no,14382336,-,0.5515,Product: DressBerry Women Pink Melange Effect ...
1,2,no,16082246,-,0.5000,Product: plusS Women Grey Hooded Sweatshirt Br...
2,3,no,17685090,-,0.5000,Product: BUY NEW TREND Women Red Black Colourb...
3,4,no,19087856,-,0.4904,Product: ONLY Women Beige & Navy Blue Colourbl...
4,5,no,2223198,-,0.4369,Product: W Women Red Solid Front-Open Longline...
5,6,no,11952000,-,0.4316,Product: DressBerry Women Navy Blue Ribbed Lon...
6,7,no,7736701,-,0.4279,Product: W Women Teal Blue Solid Front-Open Lo...
7,8,no,14071540,-,0.4068,Product: DressBerry Women Stylish Mustard Self...
8,9,no,15844140,-,0.4037,Product: URBANIC Women Grey & Black Colourbloc...
9,10,no,15137944,-,0.3870,Product: AND Women Black & White Geometric Ope...
10,11,no,13523706,-,0.3229,Product: Varanga Women Black & White Geometric...
11,12,no,15353040,-,0.3213,Product: ether Women Maroon Solid Front Open S...
12,13,no,14210706,-,0.3203,Product: MANGO Women Peach-Coloured Solid Open...
13,14,no,15413660,-,0.3165,Product: Cayman Women Black & Beige Longline F...
14,15,no,12524642,-,0.3159,Product: MANGO Women Olive Green Solid Longlin...
15,16,no,11973294,-,0.3123,Product: Mast & Harbour Women Dusty Pink Shimm...
16,17,no,13647622,-,0.3092,Product: Varanga Women Pink & White Leheriya P...
17,18,no,13769372,-,0.3085,Product: Varanga Classic Black and White Bandh...
18,19,no,15415146,-,0.3061,Product: Flying Machine Women Charcoal Typogra...
19,20,no,18210214,-,0.2905,Product: FABRIC FITOOR Black Pure Cotton Print...
20,21,no,2322431,-,0.2839,Product: Hypernation Navy Blue Solid Open Fron...
21,22,no,7811561,-,0.2820,Product: Hypernation Orange Solid Open Front S...
22,23,no,15415116,-,0.2804,Product: Flying Machine Women Blue Solid Mock-...
23,24,no,8928317,-,0.2745,Product: Hypernation Rust Brown Solid Open Fro...
24,25,no,11102094,-,0.2651,Product: Alcis Women Charcoal Grey Solid Hoode...
25,26,no,16154282,-,0.2637,Product: JC Mode Women Brown Open Front Jacket...
26,27,yes,16382036,-,0.2398,Product: Vero Moda Women Cream-Coloured Longli...
27,28,no,16044812,-,0.2323,Product: Forever New Women Green Solid Comfort...
28,29,no,17685350,-,0.2259,Product: BUY NEW TREND Women Maroon Lightweigh...
29,30,no,17226172,-,0.2252,Product: SHOWOFF Women Orange Mom Fit High-Ris...

,rank,hit,section_id,title,score,preview
0,1,yes,13255768,-,0.7928,Product: FILA Women Red & Grey Colourblocked S...
1,2,no,16705336,-,0.5050,Product: FILA Women Blue Colourblocked Running...
2,3,no,16172382,-,0.5000,Product: NEUDIS Red Cowl Neck Satin Regular To...
3,4,no,18489222,-,0.4961,Product: NEUDIS Red Cowl Neck Satin Top Brand:...
4,5,no,16705334,-,0.4922,Product: FILA Women Blue White Colourblocked R...
5,6,no,17255464,-,0.4917,Product: NEUDIS Women Satin Red Embillished So...
6,7,no,16705280,-,0.4480,Product: FILA Women Off White Colourblocked Ru...
7,8,no,16705296,-,0.4463,Product: FILA Women Grey Printed Sweatshirt Br...
8,9,no,18057660,-,0.3998,Product: NEUDIS Women White Self-Design A-Line...
9,10,no,19324666,-,0.3757,Product: FASHOR Women Red Ethnic Motifs Thread...
10,11,no,18877470,-,0.3546,Product: HRITIKA Red Satin Saree Brand: HRITIK...
11,12,no,17238348,-,0.3467,Product: NEUDIS Beige Cowl Neck Sheen Satin Fi...
12,13,no,18321088,-,0.3163,Product: HRITIKA Grey & Red Saree Brand: HRITI...
13,14,no,14976268,-,0.3084,Product: FASHOR Women Red Bandhani Printed & Z...
14,15,no,18057656,-,0.3046,Product: NEUDIS Women Navy Blue Mirror Work Du...
15,16,no,19165458,-,0.2971,Product: HRITIKA Women Pink Georgette Floral C...
16,17,no,18224860,-,0.2944,Product: HRITIKA Black Sequinned Saree Brand: ...
17,18,no,19207552,-,0.2603,Product: UNITED LIBERTY Women Purple & Gold-To...
18,19,no,18806012,-,0.2583,Product: awesome Red & Gold-Toned Woven Design...
19,20,no,14381208,-,0.2583,Product: all about you Red & Green Printed Bas...
20,21,no,18699156,-,0.2270,Product: Sidhidata Green & Gold-Toned Checked ...
21,22,no,18699148,-,0.2266,Product: Sidhidata Navy Blue & Silver-Toned Ch...
22,23,no,16858560,-,0.2101,Product: NEUDIS Women Black Comfort Flared Tro...
23,24,no,18057644,-,0.2035,Product: NEUDIS Women Black Solid Playsuit wit...
24,25,no,18993104,-,0.1917,Product: Popwings Women Black & White Floral P...
25,26,no,18993102,-,0.1893,Product: Popwings Women Yellow & Blue Floral P...
26,27,no,18996592,-,0.1686,Product: Popwings Women Black Rayon Regular Fi...
27,28,no,18627744,-,0.1562,Product: UNITED LIBERTY Green & Gold-Toned Wov...
28,29,no,19324656,-,0.1505,Product: FASHOR Women Pink Floral Embroidered ...
29,30,no,18964098,-,0.1502,Product: FASHOR Women Turquoise Blue Geometric...

,rank,hit,section_id,title,score,preview
0,1,no,17403640,-,0.5000,Product: I Saw It First Women Khaki Crinkled T...
1,2,no,2117164,-,0.5000,Product: Noi Cream-Coloured & Brown Printed Sh...
2,3,no,17403254,-,0.4854,Product: I Saw It First Women Blue Skinny Fit ...
3,4,no,13452734,-,0.4829,Product: I AM FOR YOU Women Green & Grey Print...
4,5,no,17403434,-,0.4770,Product: I Saw It First Women White & Blue Flo...
5,6,no,17365722,-,0.4736,Product: I Saw It First Women Beige Striped Hi...
6,7,no,17403428,-,0.4720,Product: I Saw It First Women Blue Skinny Fit ...
7,8,no,14159320,-,0.4667,Product: I AM FOR YOU Women Yellow & White Emb...
8,9,no,17403380,-,0.4655,Product: I Saw It First Women Blue Slash Knee ...
9,10,no,17403300,-,0.4620,Product: I Saw It First Women Blue Light Fade ...
10,11,no,17365728,-,0.4588,Product: I Saw It First Women Dusty Pink & Whi...
11,12,no,17365720,-,0.4521,Product: I Saw It First Women Green Solid Plea...
12,13,no,17570416,-,0.3625,Product: SHOWOFF Women Black Straight Fit Stre...
13,14,no,19097390,-,0.3529,Product: I Love She Women White Relaxed High-R...
14,15,no,18245104,-,0.3498,Product: Miss Chase Women Blue Jogger High-Ris...
15,16,no,18142614,-,0.3495,Product: SHOWOFF Women Lavender Jogger High-Ri...
16,17,no,14925780,-,0.3480,Product: Roadster Women Blue Wide Leg Stretcha...
17,18,no,12629360,-,0.3412,Product: Roadster Women Rust Red Regular Fit M...
18,19,no,18245110,-,0.3411,Product: Miss Chase Women Blue High-Rise Mildl...
19,20,no,19097392,-,0.3364,Product: I Love She Women Maroon Relaxed Skinn...
20,21,no,14954878,-,0.3358,Product: Roadster Women Charcoal Mid-Rise Stra...
21,22,no,11284776,-,0.3319,Product: Mast & Harbour Women Blue Mid-Rise Cl...
22,23,no,17570328,-,0.3312,Product: SHOWOFF Women Blue Wide Leg High-Rise...
23,24,no,16524266,-,0.3280,Product: LOOKNBOOK ART Orange Semi-Stitched Le...
24,25,no,17570364,-,0.3267,Product: SHOWOFF Women Blue Straight Fit High-...
25,26,no,13878270,-,0.3141,Product: High Star Women Blue Straight Fit Hig...
26,27,no,15559842,-,0.3080,Product: High Star Women Grey Jogger High-Rise...
27,28,no,15474590,-,0.3058,Product: High Star Women Rust Jogger High-Rise...
28,29,no,15266700,-,0.2180,Product: max Beige Pure Cotton Dupatta Brand: ...
29,30,no,15312982,-,0.2107,Product: LOOKNBOOK ART Black & Beige Embellish...

,rank,hit,section_id,title,score,preview
0,1,yes,12151824,-,0.9612,Product: Bhama Couture Women Maroon Printed A-...
1,2,no,9430121,-,0.9602,Product: Bhama Couture Black Embroidered A-Lin...
2,3,no,9430115,-,0.9511,Product: Bhama Couture Women Navy Blue Embroid...
3,4,no,13969870,-,0.9506,Product: Bhama Couture Navy Blue & Red Embroid...
4,5,no,11672988,-,0.9482,Product: Bhama Couture Women White & Green Flo...
5,6,no,9717189,-,0.9411,Product: Bhama Couture Women Navy Blue Embroid...
6,7,yes,10355827,-,0.9379,Product: Bhama Couture Women Blue Embroidered ...
7,8,no,13969820,-,0.9268,Product: Bhama Couture Maroon & Black Embroide...
8,9,no,8339967,-,0.9162,Product: Bhama Couture Women Red Embroidered D...
9,10,yes,12151804,-,0.9139,Product: Bhama Couture Women Blue & Pink Flora...
10,11,yes,10356731,-,0.9075,Product: Bhama Couture Women Blue Embroidered ...
11,12,no,11625546,-,0.9029,Product: Bhama Couture Women Red & White Strip...
12,13,yes,10355839,-,0.8971,Product: Bhama Couture Women Red Solid A-Line ...
13,14,yes,10717820,-,0.8950,Product: Bhama Couture Women Blue Embroidered ...
14,15,yes,9430103,-,0.8945,Product: Bhama Couture Women Red Solid A-Line ...
15,16,no,13969880,-,0.8844,Product: Bhama Couture Yellow & White Printed ...
16,17,yes,9430109,-,0.8784,Product: Bhama Couture Mustard Yellow A-Line P...
17,18,no,12795840,-,0.8524,Product: Bhama Couture Women Black & Pink Yoke...
18,19,no,10745490,-,0.8071,Product: Bhama Couture Women Mustard Yellow So...
19,20,no,4380660,-,0.7619,Product: Bhama Couture Women Peach-Coloured Pr...
20,21,no,4380652,-,0.7497,Product: Bhama Couture Women Off-White Printed...
21,22,no,1823751,-,0.7075,Product: Bhama Couture Black Tunic with Embroi...
22,23,no,2129862,-,0.7026,Product: Bhama Couture Women Off-White Embroid...
23,24,no,18288422,-,0.6955,Product: Bhama Couture Women Off White Floral ...
24,25,no,13969840,-,0.6883,Product: Bhama Couture Women White & Red Embro...
25,26,no,10343559,-,0.6849,Product: Bhama Couture Women Blue & White Band...
26,27,no,15367618,-,0.6802,Product: Bhama Couture Women Purple & Gold-Ton...
27,28,no,9816649,-,0.6786,Product: Bhama Couture Women Red Solid Kurta w...
28,29,no,2129857,-,0.6773,Product: Bhama Couture Women Off-White Solid P...
29,30,no,12795854,-,0.6751,Product: Bhama Couture Women Black & Golden Pr...

,rank,hit,section_id,title,score,preview
0,1,no,13740956,-,0.9978,Product: Oxolloxo Women Pink Regular Fit Solid...
1,2,yes,15473916,-,0.9873,Product: People Women Pink Tapered Fit High-Ri...
2,3,no,1986896,-,0.6460,Product: Indibelle Turquoise Blue Peg Leg Slim...
3,4,no,11040098,-,0.5558,Product: Oxolloxo Women Blue Regular Fit Solid...
4,5,no,8999489,-,0.5241,Product: Bitterlime Women Grey Relaxed Peg Tro...
5,6,no,13493068,-,0.5239,Product: Tokyo Talkies Women Green Regular Fit...
6,7,no,8999463,-,0.5047,Product: Bitterlime Women Grey Relaxed Regular...
7,8,no,14075224,-,0.5019,Product: RIVI Women Blue Slim Fit Solid Cotton...
8,9,no,13204932,-,0.4994,Product: all about you Women Pink Solid Croppe...
9,10,no,19085128,-,0.4988,Product: ADBUCKS Women Green Slim Fit High-Ris...
10,11,no,18143380,-,0.4693,Product: STREET 9 Women Attractive Lime Green ...
11,12,no,12072478,-,0.4659,Product: Tokyo Talkies Women Taupe & White Str...
12,13,no,8100649,-,0.4549,Product: Zastraa Women Grey Straight Fit Peg T...
13,14,no,13661764,-,0.4109,Product: Vishudh Women Black & Grey Regular Fi...
14,15,no,16774866,-,0.4052,Product: Kraus Jeans Women Grey Textured Comfo...
15,16,no,11368722,-,0.4051,Product: RANGMANCH BY PANTALOONS Women Red Reg...
16,17,no,11412238,-,0.3973,Product: Melange by Lifestyle Women Gold-Toned...
17,18,no,12917528,-,0.3886,Product: Kazo Women Black Loose Fit Striped Cr...
18,19,no,15000506,-,0.3830,Product: YASH GALLERY Women Mustard Yellow & B...
19,20,no,13110494,-,0.3780,Product: Van Heusen Woman Maroon Checked Pleat...
20,21,no,11011432,-,0.3702,Product: Mayra Women Navy Blue Regular Fit Sol...
21,22,no,18342122,-,0.3693,Product: Go Colors Women Blue Tapered Fit Trou...
22,23,no,15000502,-,0.3640,Product: YASH GALLERY Women Black & Biege Prin...
23,24,no,15000504,-,0.3623,Product: YASH GALLERY Women Coffee Brown & Red...
24,25,no,18416334,-,0.3349,Product: Berrylush Women Blue Floral Vacay Att...
25,26,no,19207552,-,0.3279,Product: UNITED LIBERTY Women Purple & Gold-To...
26,27,no,15441242,-,0.3271,Product: The Roadster Lifestyle Co Women Red S...
27,28,no,18876152,-,0.2977,Product: Annabelle by Pantaloons Women Blue Pl...
28,29,no,16858560,-,0.2837,Product: NEUDIS Women Black Comfort Flared Tro...
29,30,no,15900674,-,0.2793,Product: RANGMANCH BY PANTALOONS Women Red Peg...

,rank,hit,section_id,title,score,preview
0,1,no,13523706,-,0.5000,Product: Varanga Women Black & White Geometric...
1,2,no,14272032,-,0.5000,Product: Oxolloxo Women Orange Solid Regular F...
2,3,no,13647622,-,0.4861,Product: Varanga Women Pink & White Leheriya P...
3,4,no,13769372,-,0.4853,Product: Varanga Classic Black and White Bandh...
4,5,no,9621439,-,0.4696,Product: WISSTLER Women Blue Printed Regular F...
5,6,no,11101312,-,0.4676,Product: WISSTLER Women Blue Printed Regular F...
6,7,no,17251600,-,0.4584,Product: Athena Women Black Shorts Brand: Athe...
7,8,yes,15083714,-,0.4429,Product: DressBerry Women Green Striped Regula...
8,9,no,16836260,-,0.4075,Product: Roadster Women Indigo Shaded Mid Rise...
9,10,no,14027018,-,0.3821,Product: Oxolloxo Women Olive Green Solid Regu...
10,11,no,14272016,-,0.3784,Product: Oxolloxo Women Green Solid Regular Fi...
11,12,no,14340718,-,0.3676,Product: MANGO Women Peach-Coloured Solid Regu...
12,13,no,14388576,-,0.3658,Product: Oxolloxo Women Black & Yellow Polka D...
13,14,no,19235420,-,0.3553,Product: Oxolloxo Women Brown Shorts Brand: Ox...
14,15,no,13529198,-,0.3522,Product: Harvard Women White & Navy Striped Re...
15,16,no,12969482,-,0.3389,Product: Hypernation Women Olive Green Solid S...
16,17,no,13060194,-,0.3343,Product: QUARANTINE Women Off-White Printed Re...
17,18,no,13985432,-,0.3335,Product: Belle Fille Women Blue Solid Regular ...
18,19,no,14672892,-,0.3329,Product: Colour Me by Melange Women Navy Blue ...
19,20,no,19047410,-,0.3317,Product: Roadster Women Black Solid Shorts Bra...
20,21,no,17256464,-,0.3172,Product: Athena Women Blue Shorts Brand: Athen...
21,22,no,14219670,-,0.3061,Product: DressBerry Women Navy Blue Shorts Bra...
22,23,no,15103054,-,0.2973,Product: MANGO Women Yellow Floral Printed Hig...
23,24,no,15083698,-,0.2943,Product: DressBerry Women Pink Striped Regular...
24,25,no,13391802,-,0.2871,Product: Mast & Harbour Women Grey Melange Sol...
25,26,no,12929508,-,0.2856,Product: Mast & Harbour Women Navy Blue Solid ...
26,27,no,11012420,-,0.2677,Product: HRX by Hrithik Roshan Women Black & O...
27,28,no,18611674,-,0.2665,Product: Honey by Pantaloons Women Khaki Strip...
28,29,no,14954482,-,0.2651,Product: Roadster Women Olive Green Loose Fit ...
29,30,no,16885654,-,0.2603,Product: Alsace Lorraine Paris Women Pink Shor...

,rank,hit,section_id,title,score,preview
0,1,yes,17674588,-,1.0000,Product: H&M Women Brown Mesh Top Brand: H&M C...
1,2,no,17965024,-,0.7943,Product: H&M Orange Ankle-Length Trousers Bran...
2,3,no,12383500,-,0.7439,Product: H&M Women Black Solid Long-Sleeved Je...
3,4,no,17883650,-,0.6671,Product: H&M Beige Pattern-Knit Trousers Brand...
4,5,no,17883622,-,0.6621,Product: H&M Girls Beige Cotton Jersey Cropped...
5,6,no,17842774,-,0.6553,Product: H&M Beige Wide Linen-Blend Trousers B...
6,7,no,18131688,-,0.6469,Product: H&M Women Black Wide Linen-blend Trou...
7,8,yes,14258606,-,0.6277,Product: H&M Girls White Solid Jersey Top Bran...
8,9,yes,17964932,-,0.6248,Product: H&M Women Yellow Rapid-Dry Sports Top...
9,10,no,17842776,-,0.6034,Product: H&M Women Beige Striped Wide Linen-Bl...
10,11,no,17575906,-,0.6001,Product: H&M Women Blue Solid Skinny Regular J...
11,12,no,16396394,-,0.5836,Product: H&M Women Green Fine-Knit Joggers Bra...
12,13,yes,17883620,-,0.5764,Product: H&M Yellow Puff-Sleeved Jersey Top Br...
13,14,no,18747130,-,0.5757,Product: H&M Women Beige Sweatshirt Shorts Bra...
14,15,no,17855308,-,0.5733,Product: H&M Women Orange Pointelle-Knit Cotto...
15,16,no,18747106,-,0.5710,Product: H&M Women Orange Sweatshirt Shorts Br...
16,17,no,17185856,-,0.5631,Product: H&M Women Blue Straight High Jeans Br...
17,18,no,17185466,-,0.5592,Product: H&M Women Beige & Grey Solid Sweatshi...
18,19,yes,19074168,-,0.5568,Product: H&M Women Green Ribbed Cropped Top Br...
19,20,no,16175534,-,0.5546,Product: H&M Women Red Cotton Blend Sweatpants...
20,21,no,19071830,-,0.5512,Product: H&M Women Blue Wide High Jeans Brand:...
21,22,no,19074138,-,0.5508,Product: H&M Women Pink Ribbed Cut-Out Top Bra...
22,23,no,18747132,-,0.5410,Product: H&M Women Green Terry Shorts Brand: H...
23,24,yes,18170658,-,0.5338,Product: H&M White Cotton Vest Top Brand: H&M ...
24,25,no,19175092,-,0.5241,Product: H&M Women Beige Solid Pull-On Lyocell...
25,26,no,19071780,-,0.5143,Product: H&M Women Grey Ankle-Length Linen Tro...
26,27,no,17759938,-,0.5005,Product: H&M Black Short Twill Skirt Brand: H&...
27,28,no,19266944,-,0.4981,Product: H&M Women Blue Stand-up Collar Satin ...
28,29,no,18834764,-,0.4945,Product: H&M Women Black Corduroy trousers Bra...
29,30,no,19174870,-,0.4912,Product: H&M Women Black Low-Waisted Bermuda S...

,rank,hit,section_id,title,score,preview
0,1,no,16914910,-,0.9500,Product: KALINI Pink Poly Georgette Casual Sar...
1,2,yes,16421936,-,0.8820,Product: KALINI Pink & Gold-Toned Paisley Sare...
2,3,yes,15102290,-,0.8172,Product: KALINI Pink & Gold-Toned Woven Design...
3,4,no,16915002,-,0.8082,Product: KALINI Women Green & Pink Ethnic Moti...
4,5,no,16948530,-,0.7686,Product: KALINI Pink & Grey Paisley Printed Ch...
5,6,yes,14678908,-,0.7478,Product: KALINI Pink & Yellow Floral Pure Chif...
6,7,no,16989798,-,0.7102,Product: KALINI Sea Green & Pink Ethnic Motifs...
7,8,yes,17852902,-,0.6673,Product: KALINI Pink & Gold-Toned Zari Saree B...
8,9,no,14798392,-,0.6620,Product: KALINI Pink & Green Ethnic Motifs Kot...
9,10,no,12961094,-,0.6538,Product: KALINI Pink & Navy Blue Half & Half P...
10,11,no,17414120,-,0.6491,Product: KALINI Pink & White Batik Zari Block ...
11,12,yes,15858094,-,0.6050,Product: KALINI Pack of 2 Pink & Blue Floral S...
12,13,no,15102284,-,0.5637,Product: KALINI Green & Pink Ethnic Motifs Art...
13,14,no,16625250,-,0.5235,Product: KALINI Maroon & Yellow Floral Saree B...
14,15,no,16915122,-,0.5133,Product: KALINI Green & White Bandhani Art Sil...
15,16,no,18482974,-,0.4967,Product: KALINI Women Red Solid Saree Brand: K...
16,17,no,12754022,-,0.4875,Product: KALINI Black & Red Jute Silk Embroide...
17,18,no,17066888,-,0.4870,Product: KALINI Brown & Orange Abstract Printe...
18,19,no,14986192,-,0.4714,Product: KALINI Blue & Yellow Floral Saree Bra...
19,20,no,17118876,-,0.4658,Product: KALINI Blue & Pink Checked Ikat Saree...
20,21,no,14905990,-,0.4634,Product: KALINI Taupe & Red Floral Printed Zar...
21,22,no,16915192,-,0.4625,Product: KALINI Navy Blue & Beige Ethnic Motif...
22,23,no,16848432,-,0.4314,Product: KALINI Maroon & Gold-Toned Ethnic Mot...
23,24,no,18579630,-,0.4292,Product: KALINI Green & White Printed Leheriya...
24,25,no,17035744,-,0.4269,Product: KALINI Black & Golden Woven Design Sa...
25,26,no,17035752,-,0.4221,Product: KALINI Coral & Golden Woven Design Sa...
26,27,no,16186362,-,0.4176,Product: KALINI White & Red Ethnic Motifs Sare...
27,28,no,14541316,-,0.4119,Product: KALINI Orange & Gold-Toned Ethnic Mot...
28,29,no,14490860,-,0.4111,Product: KALINI Orange & Gold-Toned Pure Chiff...
29,30,no,12792140,-,0.4052,Product: KALINI Cream-Coloured & Pink Pure Geo...

,rank,hit,section_id,title,score,preview
0,1,no,13523706,-,0.5000,Product: Varanga Women Black & White Geometric...
1,2,no,17226172,-,0.5000,Product: SHOWOFF Women Orange Mom Fit High-Ris...
2,3,no,13647622,-,0.4858,Product: Varanga Women Pink & White Leheriya P...
3,4,no,13769372,-,0.4850,Product: Varanga Classic Black and White Bandh...
4,5,no,17570458,-,0.4721,Product: SHOWOFF Women Brown Jogger High-Rise ...
5,6,no,18142596,-,0.4313,Product: SHOWOFF Women Blue Jogger High-Rise L...
6,7,no,17790642,-,0.4009,Product: SHOWOFF Orange & White Printed Culott...
7,8,no,17685090,-,0.4003,Product: BUY NEW TREND Women Red Black Colourb...
8,9,no,17250550,-,0.3911,Product: SHOWOFF Women Black Embellished Top w...
9,10,no,18388758,-,0.3908,Product: SHOWOFF Burgundy Solid Culotte Jumpsu...
10,11,no,18189378,-,0.3455,Product: SHOWOFF Blue Strapless Capri Jumpsuit...
11,12,no,17672184,-,0.3251,Product: SHOWOFF Women Blue High-Rise Heavy Fa...
12,13,no,18210214,-,0.2896,Product: FABRIC FITOOR Black Pure Cotton Print...
13,14,no,19276886,-,0.2882,Product: Mitera Grey Floral Embroidered Net Fu...
14,15,no,18468196,-,0.2811,Product: KAMI KUBI Women Blue schiffli-Embroid...
15,16,no,18338282,-,0.2751,Product: SHOWOFF Women Blue Slim Fit High-Rise...
16,17,no,18425088,-,0.2715,Product: SHOWOFF Women Navy Blue Striped Hoode...
17,18,no,17570450,-,0.2709,Product: SHOWOFF Women Black Slim Fit Stretcha...
18,19,no,14006764,-,0.2694,Product: Saree mall Floral Silk Blend Saree wi...
19,20,no,18056594,-,0.2689,Product: Martini Women Black Pleated Flared Mi...
20,21,no,18263720,-,0.2662,Product: SHOWOFF Women Grey & Maroon Floral Pr...
21,22,no,17872080,-,0.2645,Product: Taavi Women Indigo & White Indigo Pri...
22,23,no,18067038,-,0.2628,Product: BUY NEW TREND Blue Flared Knitted Pal...
23,24,no,16309970,-,0.2572,Product: aarke Ritu Kumar Women Olive Green So...
24,25,no,17570446,-,0.2533,Product: SHOWOFF Women Blue Boyfriend Fit High...
25,26,no,18142614,-,0.2441,Product: SHOWOFF Women Lavender Jogger High-Ri...
26,27,no,17570328,-,0.2417,Product: SHOWOFF Women Blue Wide Leg High-Rise...
27,28,no,17093664,-,0.2400,Product: The Roadster Lifestyle Co Women Black...
28,29,no,17570364,-,0.2396,Product: SHOWOFF Women Blue Straight Fit High-...
29,30,no,17093660,-,0.2384,Product: The Roadster Lifestyle Co Women Charc...

,rank,hit,section_id,title,score,preview
0,1,yes,16379914,-,1.0000,Product: Safaa Women Red Woven Design Acrylic ...
1,2,yes,15768366,-,0.9924,Product: VERO AMORE Women Red & Beige Woven-De...
2,3,yes,16379852,-,0.9305,Product: Safaa Women Red & Black Woven Design ...
3,4,no,2138931,-,0.8599,Product: WEAVERS VILLA Coral Red & Beige Woven...
4,5,no,11379820,-,0.7118,Product: SHINGORA Women Red & Blue Woven Desig...
5,6,no,16608192,-,0.6001,Product: VERO AMORE Women Navy Blue & Red Wove...
6,7,no,13104106,-,0.5939,Product: Pashmoda Women Red Woven Design Shawl...
7,8,no,16608222,-,0.5838,Product: VERO AMORE Women Black & Red Woven De...
8,9,no,15874790,-,0.5656,Product: Pashmoda Women Red Woven Design Jamaw...
9,10,no,15768324,-,0.5294,Product: VERO AMORE Women Black & Red Woven Ku...
10,11,no,15121622,-,0.4876,Product: Cayman Women Red & Beige Woollen Wove...
11,12,no,13616810,-,0.4871,Product: Dupatta Bazaar Red & Orange Woven Des...
12,13,no,19366710,-,0.4793,Product: RIVAMA Red & Green Ethnic Motifs Wove...
13,14,no,13497800,-,0.4697,Product: InWeave Women Red Striped A-Line Top ...
14,15,no,17662882,-,0.4486,Product: Dupatta Bazaar Red Woven Design Dupat...
15,16,no,11149776,-,0.4310,Product: Style Quotient Women Red & Black Chec...
16,17,no,4444074,-,0.4214,Product: Dupatta Bazaar Red & Orange Woven Des...
17,18,no,16608218,-,0.4020,Product: VERO AMORE Women Green & Beige Floral...
18,19,no,16608172,-,0.4015,Product: VERO AMORE Women Maroon & Beige Woven...
19,20,no,16608196,-,0.3975,Product: VERO AMORE Women Blue & Beige Woven D...
20,21,no,16874574,-,0.3829,Product: Mitera Red Woven Design Zari Silk Ble...
21,22,no,15546696,-,0.3757,Product: Sangria Women Maroon Kaani Woollen Wo...
22,23,no,16379900,-,0.3743,Product: Safaa Women Brown & Blue Woven-Design...
23,24,no,16379890,-,0.3656,Product: Safaa Women Beige & Blue Woven Design...
24,25,no,16379928,-,0.3612,Product: Safaa Women Black & Beige Woven Desig...
25,26,no,16379878,-,0.3612,Product: Safaa Women Black & Blue Woven Design...
26,27,no,16379830,-,0.3608,Product: Safaa Women Navy Blue & Maroon Woven ...
27,28,no,15768432,-,0.3608,Product: VERO AMORE Women Burgundy Woven Desig...
28,29,no,16379842,-,0.3584,Product: Safaa Women Black & Beige Woven Desig...
29,30,no,15768344,-,0.3583,Product: VERO AMORE Women Maroon & Beige Woven...

,rank,hit,section_id,title,score,preview
0,1,yes,15917640,-,0.8414,Product: SERONA FABRICS White & Pink Floral Em...
1,2,no,16258082,-,0.7256,Product: SERONA FABRICS Yellow Floral Embroide...
2,3,no,18845142,-,0.7111,Product: SERONA FABRICS Peach-Coloured & White...
3,4,no,18845144,-,0.7064,Product: SERONA FABRICS Grey & Off White Tunic...
4,5,no,15907476,-,0.6121,Product: SERONA FABRICS Red & White Printed Un...
5,6,no,15907474,-,0.5463,Product: SERONA FABRICS Women Peach Floral Pri...
6,7,no,15907480,-,0.5296,Product: SERONA FABRICS Blue & Gold-Toned Embr...
7,8,no,15907478,-,0.5056,Product: SERONA FABRICS Red Embroidered Unstit...
8,9,no,15907488,-,0.4980,Product: SERONA FABRICS Pink Embroidered Chand...
9,10,no,18057660,-,0.2757,Product: NEUDIS Women White Self-Design A-Line...
10,11,no,16172382,-,0.2645,Product: NEUDIS Red Cowl Neck Satin Regular To...
11,12,no,18489222,-,0.2621,Product: NEUDIS Red Cowl Neck Satin Top Brand:...
12,13,no,17255464,-,0.2594,Product: NEUDIS Women Satin Red Embillished So...
13,14,no,17238348,-,0.2209,Product: NEUDIS Beige Cowl Neck Sheen Satin Fi...
14,15,no,14238538,-,0.2054,Product: Sera Women White & Black Printed Basi...
15,16,no,18321088,-,0.2013,Product: HRITIKA Grey & Red Saree Brand: HRITI...
16,17,no,14375990,-,0.1982,Product: Sera Women Off White & Grey Printed S...
17,18,no,18877470,-,0.1968,Product: HRITIKA Red Satin Saree Brand: HRITIK...
18,19,no,18057656,-,0.1937,Product: NEUDIS Women Navy Blue Mirror Work Du...
19,20,no,19165458,-,0.1889,Product: HRITIKA Women Pink Georgette Floral C...
20,21,no,18224860,-,0.1872,Product: HRITIKA Black Sequinned Saree Brand: ...
21,22,no,17784302,-,0.1872,Product: Sera Women White Floral Print Georget...
22,23,no,18360202,-,0.1824,Product: Sera Women Off-White Printed Co-Ord S...
23,24,no,14495856,-,0.1667,Product: DEEBACO Women Grey Parallel Trousers ...
24,25,no,19207552,-,0.1652,Product: UNITED LIBERTY Women Purple & Gold-To...
25,26,no,18699156,-,0.1438,Product: Sidhidata Green & Gold-Toned Checked ...
26,27,no,18699148,-,0.1435,Product: Sidhidata Navy Blue & Silver-Toned Ch...
27,28,no,18806012,-,0.1341,Product: awesome Red & Gold-Toned Woven Design...
28,29,no,16858560,-,0.1329,Product: NEUDIS Women Black Comfort Flared Tro...
29,30,no,996729,-,0.1308,Product: Dupatta Bazaar White Silk Dupatta Bra...

,rank,hit,section_id,title,score,preview
0,1,no,17447636,-,0.9656,Product: Khushal K Women Green Ethnic Motifs P...
1,2,no,15508896,-,0.9089,Product: Indo Era Women Green Ethnic Motifs Yo...
2,3,yes,16707970,-,0.8855,Product: mokshi Ethnic Motifs Viscose Rayon Ku...
3,4,no,15258422,-,0.8347,Product: Indo Era Floral Cotton Blend Calf Len...
4,5,no,15054430,-,0.8081,Product: Biba Women Green Ethnic Motifs Printe...
5,6,no,13810898,-,0.7172,Product: Indo Era Women Blue & Green Printed K...
6,7,no,15654150,-,0.6955,Product: Indo Era Women Green Ethnic Motifs Yo...
7,8,yes,17232410,-,0.6936,Product: InWeave Green Pure Cotton Print Parad...
8,9,no,16931552,-,0.6712,Product: all about you Women Green Embroidered...
9,10,yes,17140156,-,0.6433,Product: Myshka Women Green Kurta with Palazzo...
10,11,no,12989804,-,0.6361,Product: mokshi Women Green & Maroon Foil Prin...
11,12,yes,15677426,-,0.5821,Product: SWAGG INDIA Women Green Floral Embroi...
12,13,yes,16825614,-,0.5282,Product: Stylum Women Green Embroidered Pure C...
13,14,no,15258010,-,0.5045,Product: Libas Women Green & White Floral Embr...
14,15,yes,14920000,-,0.4998,Product: Indo Era Women Green Floral Embroider...
15,16,no,18551726,-,0.4975,Product: POONAM DESIGNER Women Lime Green Gott...
16,17,no,13392426,-,0.4889,Product: Khushal K Women Lime Green Printed Ku...
17,18,no,15026486,-,0.4870,Product: W Women Green & Golden Regular Sequin...
18,19,yes,16505434,-,0.4868,Product: KALINI Women Green Floral Printed Pur...
19,20,no,16172382,-,0.4778,Product: NEUDIS Red Cowl Neck Satin Regular To...
20,21,no,18489222,-,0.4730,Product: NEUDIS Red Cowl Neck Satin Top Brand:...
21,22,no,17255464,-,0.4676,Product: NEUDIS Women Satin Red Embillished So...
22,23,no,18002690,-,0.4599,Product: SINGNI Women Green Embroidered Printe...
23,24,no,18765612,-,0.4339,Product: mirari Women Green Floral Printed Pur...
24,25,yes,14121912,-,0.4134,Product: Anouk Women Dark Green Embroidered Pl...
25,26,no,13452734,-,0.4046,Product: I AM FOR YOU Women Green & Grey Print...
26,27,no,18870794,-,0.3635,Product: FASHION YOU Orange & Blue Unstitched ...
27,28,no,18870804,-,0.3635,Product: FASHION YOU Blue & Pink Unstitched Dr...
28,29,no,17238348,-,0.3573,Product: NEUDIS Beige Cowl Neck Sheen Satin Fi...
29,30,no,16773346,-,0.3514,Product: KALINI Women Sea Green Printed Gotta ...

,rank,hit,section_id,title,score,preview
0,1,no,15852292,-,0.8241,Product: URBANIC Women Black Cotton Solid Crop...
1,2,no,15632460,-,0.6963,Product: URBANIC Women Black Solid High-Rise D...
2,3,no,16102760,-,0.6545,Product: URBANIC Black Solid Basic Jumpsuit wi...
3,4,no,18542924,-,0.5907,Product: URBANIC Women Black Solid Mid-Rise Wi...
4,5,no,15844202,-,0.5849,Product: URBANIC Women Black & Off White Solid...
5,6,yes,15086606,-,0.5519,Product: URBANIC Women Black Printed Sweatshir...
6,7,no,15845464,-,0.5330,Product: URBANIC Women Black Solid Cotton Swea...
7,8,no,15851566,-,0.5304,Product: URBANIC Women Black Padded Jacket Bra...
8,9,no,18328804,-,0.5000,Product: URBANIC Women Black Jeans Brand: URBA...
9,10,no,15633286,-,0.4948,Product: URBANIC Women Black Solid Skinny Fit ...
10,11,no,18905308,-,0.4921,Product: URBANIC Black Basic Jumpsuit Brand: U...
11,12,no,18224860,-,0.4898,Product: HRITIKA Black Sequinned Saree Brand: ...
12,13,no,15852580,-,0.4871,Product: URBANIC Black & White Printed Ruffle ...
13,14,yes,15849954,-,0.4552,Product: URBANIC Women Black & White Houndstoo...
14,15,no,18321088,-,0.4518,Product: HRITIKA Grey & Red Saree Brand: HRITI...
15,16,no,18877470,-,0.4383,Product: HRITIKA Red Satin Saree Brand: HRITIK...
16,17,no,19165458,-,0.4146,Product: HRITIKA Women Pink Georgette Floral C...
17,18,no,18905302,-,0.3984,Product: URBANIC Black & Gold-Toned Jumpsuit B...
18,19,no,19072596,-,0.3800,Product: URBANIC Women Black Relaxed Fit Mildl...
19,20,no,18867438,-,0.3645,Product: URBANIC Women Black Trousers Brand: U...
20,21,no,18644820,-,0.3626,Product: URBANIC Women Black Solid Blazers Bra...
21,22,no,19324656,-,0.3411,Product: FASHOR Women Pink Floral Embroidered ...
22,23,no,18964098,-,0.3402,Product: FASHOR Women Turquoise Blue Geometric...
23,24,no,18778410,-,0.3332,Product: FASHOR Women Multicoloured & nirvana ...
24,25,no,19198378,-,0.3297,Product: FASHOR Women Green Yoke Design Thread...
25,26,no,19324666,-,0.3297,Product: FASHOR Women Red Ethnic Motifs Thread...
26,27,yes,18929182,-,0.3270,Product: URBANIC Black Embroidered Halter Neck...
27,28,no,14976268,-,0.3261,Product: FASHOR Women Red Bandhani Printed & Z...
28,29,no,19140952,-,0.3220,Product: FASHOR Women Blue Geometric Printed G...
29,30,no,15047458,-,0.3218,Product: FASHOR Women Multicoloured Ethnic Mot...

,rank,hit,section_id,title,score,preview
0,1,no,14006764,-,0.5000,Product: Saree mall Floral Silk Blend Saree wi...
1,2,no,19270830,-,0.5000,Product: Blamblack Women Black Solid Shirt & P...
2,3,no,18224860,-,0.4981,Product: HRITIKA Black Sequinned Saree Brand: ...
3,4,no,17351596,-,0.4369,Product: anayna Women Black & White Ethnic Mot...
4,5,no,19187496,-,0.4304,Product: Blamblack Women Black & Grey Solid Co...
5,6,no,14912536,-,0.4213,Product: Libas Green Sleek Pure Georgette Pala...
6,7,no,19276886,-,0.4165,Product: Mitera Grey Floral Embroidered Net Fu...
7,8,no,17570416,-,0.3950,Product: SHOWOFF Women Black Straight Fit Stre...
8,9,no,18321088,-,0.3444,Product: HRITIKA Grey & Red Saree Brand: HRITI...
9,10,no,12383500,-,0.3415,Product: H&M Women Black Solid Long-Sleeved Je...
10,11,no,18877470,-,0.3376,Product: HRITIKA Red Satin Saree Brand: HRITIK...
11,12,no,19140936,-,0.3316,Product: FASHOR Women Maroon Embroidered Keyho...
12,13,no,19357994,-,0.3299,Product: FASHOR Women Pink Ethnic Motifs Kurta...
13,14,no,18720202,-,0.3279,Product: FASHOR Women Purple Ethnic Motifs Pri...
14,15,no,19165458,-,0.3256,Product: HRITIKA Women Pink Georgette Floral C...
15,16,no,18210214,-,0.3252,Product: FABRIC FITOOR Black Pure Cotton Print...
16,17,no,19198414,-,0.3250,Product: FASHOR Women Navy Blue Floral Embroid...
17,18,no,13552234,-,0.3234,Product: Dupatta Bazaar Black Solid Dupatta Br...
18,19,no,19198408,-,0.3224,Product: FASHOR Women Multicoloured Striped Th...
19,20,no,16379558,-,0.3207,Product: FASHOR Women Burgundy Ethnic Motifs Y...
20,21,no,16379878,-,0.3108,Product: Safaa Women Black & Blue Woven Design...
21,22,no,17093664,-,0.3042,Product: The Roadster Lifestyle Co Women Black...
22,23,no,17570450,-,0.2941,Product: SHOWOFF Women Black Slim Fit Stretcha...
23,24,no,18207362,-,0.2897,Product: Dupatta Bazaar Black Linen Dupatta Br...
24,25,no,19324656,-,0.2883,Product: FASHOR Women Pink Floral Embroidered ...
25,26,no,18964098,-,0.2878,Product: FASHOR Women Turquoise Blue Geometric...
26,27,no,18778410,-,0.2843,Product: FASHOR Women Multicoloured & nirvana ...
27,28,no,19198378,-,0.2825,Product: FASHOR Women Green Yoke Design Thread...
28,29,no,19324666,-,0.2825,Product: FASHOR Women Red Ethnic Motifs Thread...
29,30,no,14976268,-,0.2807,Product: FASHOR Women Red Bandhani Printed & Z...

,rank,hit,section_id,title,score,preview
0,1,yes,18819296,-,1.0000,Product: Swasti Women Blue Ethnic Motifs Print...
1,2,no,17403254,-,0.3439,Product: I Saw It First Women Blue Skinny Fit ...
2,3,no,17403428,-,0.3347,Product: I Saw It First Women Blue Skinny Fit ...
3,4,no,17403380,-,0.3302,Product: I Saw It First Women Blue Slash Knee ...
4,5,no,17403300,-,0.3279,Product: I Saw It First Women Blue Light Fade ...
5,6,no,17403434,-,0.3072,Product: I Saw It First Women White & Blue Flo...
6,7,no,19140952,-,0.2892,Product: FASHOR Women Blue Geometric Printed G...
7,8,no,18321088,-,0.2774,Product: HRITIKA Grey & Red Saree Brand: HRITI...
8,9,no,18877470,-,0.2705,Product: HRITIKA Red Satin Saree Brand: HRITIK...
9,10,no,19165458,-,0.2584,Product: HRITIKA Women Pink Georgette Floral C...
10,11,no,18964098,-,0.2560,Product: FASHOR Women Turquoise Blue Geometric...
11,12,no,18224860,-,0.2558,Product: HRITIKA Black Sequinned Saree Brand: ...
12,13,no,19324656,-,0.2208,Product: FASHOR Women Pink Floral Embroidered ...
13,14,no,18778410,-,0.2168,Product: FASHOR Women Multicoloured & nirvana ...
14,15,no,19260152,-,0.2153,Product: SALWAR STUDIO Blue & Purple Printed U...
15,16,no,19260114,-,0.2153,Product: SALWAR STUDIO Blue & Grey Printed Uns...
16,17,no,19198378,-,0.2150,Product: FASHOR Women Green Yoke Design Thread...
17,18,no,19324666,-,0.2150,Product: FASHOR Women Red Ethnic Motifs Thread...
18,19,no,14976268,-,0.2132,Product: FASHOR Women Red Bandhani Printed & Z...
19,20,no,15047458,-,0.2110,Product: FASHOR Women Multicoloured Ethnic Mot...
20,21,no,16486578,-,0.2079,Product: FASHOR Women Maroon Geometric Printed...
21,22,no,15228886,-,0.2071,Product: Blissta Blue Unstitched Dress Materia...
22,23,no,16072014,-,0.2062,Product: FASHOR Women Lavender Striped Keyhole...
23,24,no,16984006,-,0.2054,Product: FASHOR Women Pink Ethnic Motifs Yoke ...
24,25,no,15635874,-,0.2043,Product: SWAGG INDIA Blue Ethnic Motifs Embroi...
25,26,no,17403640,-,0.2018,Product: I Saw It First Women Khaki Crinkled T...
26,27,no,11536158,-,0.1960,Product: INDYA Blue Solid Dupatta Brand: INDYA...
27,28,no,13452734,-,0.1930,Product: I AM FOR YOU Women Green & Grey Print...
28,29,no,18651648,-,0.1910,Product: Swtantra Blue & Gold-Toned Satin Sare...
29,30,no,17365722,-,0.1882,Product: I Saw It First Women Beige Striped Hi...

,rank,hit,section_id,title,score,preview
0,1,yes,13244594,-,0.9397,Product: Mayra Women Pink Printed Shirt Style ...
1,2,no,15841446,-,0.7370,Product: URBANIC Pink & Beige Floral Print Shi...
2,3,no,19195222,-,0.6626,Product: PRASTHAN Women Pink Floral Print Crep...
3,4,no,12641134,-,0.5000,Product: Global Desi Women White Printed Shirt...
4,5,no,19201936,-,0.4947,Product: H&M Women Pink Pure Cotton Frill-Coll...
5,6,no,10080283,-,0.4359,Product: AKKRITI BY PANTALOONS Women Grey Prin...
6,7,no,17547800,-,0.3809,Product: KALINI Maroon Print Shirt Style Pure ...
7,8,no,18605378,-,0.3446,Product: Vishal Prints Pink & Grey Abstract Pr...
8,9,no,17268136,-,0.3170,Product: Fabindia Pink Off White & Pink Mandar...
9,10,no,13614956,-,0.3154,Product: The Dry State Women Black & Pink Flor...
10,11,no,18647784,-,0.3122,Product: SHAYE Multicoloured Print Shirt Style...
11,12,no,19325284,-,0.2794,Product: POONAM DESIGNER Women Pink Ethnic Mot...
12,13,no,17820020,-,0.2793,Product: Mast & Harbour Pink Floral Print Mand...
13,14,no,19188354,-,0.2673,Product: Colour Me by Melange Women Pink Manda...
14,15,no,17348862,-,0.2666,Product: JC Collection Women Pink & Green Prin...
15,16,no,12964214,-,0.2586,Product: Sangria Girls Blue & Pink Tie & Dye H...
16,17,no,19032532,-,0.2554,Product: BUY NEW TREND Women Pink & Yellow Pri...
17,18,no,13452734,-,0.2460,Product: I AM FOR YOU Women Green & Grey Print...
18,19,no,9301311,-,0.2415,Product: Tissu Women Pink & Off-White Floral P...
19,20,no,15841450,-,0.2384,Product: URBANIC Beige & Yellow Floral Print S...
20,21,no,11762378,-,0.2377,Product: AKKRITI BY PANTALOONS Women Pink Prin...
21,22,no,14673176,-,0.2366,Product: Stylo Bug Blue & White Floral Printed...
22,23,no,19280832,-,0.2363,Product: VividArtsy Women Pink Tie & Dye Print...
23,24,no,18473086,-,0.2343,Product: Stylo Bug Blue Floral Print Shirt Sty...
24,25,no,19292568,-,0.2289,Product: The Label Bar Blue Geometric Print Sh...
25,26,no,16844862,-,0.2279,Product: RAREISM Off White & Blue Tie and Dye ...
26,27,no,17622578,-,0.2273,Product: Van Heusen Navy Blue Floral Print Shi...
27,28,no,15632410,-,0.2271,Product: URBANIC Women Pink Solid T-shirt with...
28,29,no,14704116,-,0.2250,Product: Janasya Green Georgette Shirt Style T...
29,30,no,19266960,-,0.2127,Product: H&M Women Black & White Oversized Blo...

,rank,hit,section_id,title,score,preview
0,1,yes,17754230,-,0.9951,Product: Atsevam Cream-Coloured & Red Semi-Sti...
1,2,yes,17754248,-,0.9601,Product: Atsevam Red Embroidered Thread Work S...
2,3,yes,19217170,-,0.9585,Product: Atsevam Red & Gold-Toned Embroidered ...
3,4,yes,17584576,-,0.9377,Product: Atsevam Orange & Red Printed Tie and ...
4,5,yes,19217168,-,0.9343,Product: Atsevam Green & Gold-Toned Embroidere...
5,6,no,19217186,-,0.9284,Product: Atsevam Women Green & Pink Printed Ti...
6,7,no,17834516,-,0.9106,Product: Atsevam Blue & Pink Ready to Wear Leh...
7,8,yes,19217176,-,0.9104,Product: Atsevam White & Pink Tie and Dye Semi...
8,9,no,19217196,-,0.9059,Product: Atsevam Pink Embroidered Thread Work ...
9,10,yes,17754250,-,0.8925,Product: Atsevam Women Pink Embroidered Semi-S...
10,11,no,17403640,-,0.4839,Product: I Saw It First Women Khaki Crinkled T...
11,12,no,17403254,-,0.4703,Product: I Saw It First Women Blue Skinny Fit ...
12,13,no,13452734,-,0.4679,Product: I AM FOR YOU Women Green & Grey Print...
13,14,no,17403434,-,0.4624,Product: I Saw It First Women White & Blue Flo...
14,15,no,17365722,-,0.4593,Product: I Saw It First Women Beige Striped Hi...
15,16,no,17403428,-,0.4578,Product: I Saw It First Women Blue Skinny Fit ...
16,17,no,14159320,-,0.4528,Product: I AM FOR YOU Women Yellow & White Emb...
17,18,no,17403380,-,0.4518,Product: I Saw It First Women Blue Slash Knee ...
18,19,no,17403300,-,0.4485,Product: I Saw It First Women Blue Light Fade ...
19,20,no,17365728,-,0.4455,Product: I Saw It First Women Dusty Pink & Whi...
20,21,no,17365720,-,0.4392,Product: I Saw It First Women Green Solid Plea...
21,22,no,19097390,-,0.3469,Product: I Love She Women White Relaxed High-R...
22,23,no,19097392,-,0.3315,Product: I Love She Women Maroon Relaxed Skinn...
23,24,no,17403510,-,0.2038,Product: I Saw It First Women Blue Highly Dist...
24,25,no,19162224,-,0.1751,Product: aturabi Peach-Coloured & White Halter...
25,26,no,17365646,-,0.1718,Product: I Saw It First Women Black & Yellow F...
26,27,no,19071830,-,0.1711,Product: H&M Women Blue Wide High Jeans Brand:...
27,28,no,17185856,-,0.1666,Product: H&M Women Blue Straight High Jeans Br...
28,29,no,17784446,-,0.1664,Product: H&M Women Blue Flared High Ankle Jean...
29,30,no,17403370,-,0.1664,Product: I Saw It First Women Pink & White Che...

,rank,hit,section_id,title,score,preview
0,1,no,18070000,-,1.0000,Product: panchhi Pink Embroidered Sequinned Un...
1,2,yes,19046346,-,0.8979,Product: panchhi Pink & Sea Green Embellished ...
2,3,no,18175384,-,0.8012,Product: panchhi Pink Net Embroidered Sequinne...
3,4,no,19046338,-,0.7622,Product: panchhi Blue & Pink Embellished Semi-...
4,5,yes,12003682,-,0.7510,Product: panchhi Pink & Beige Embellished Semi...
5,6,no,18175352,-,0.7315,Product: panchhi Lavender & Red Embroidered Se...
6,7,no,19046370,-,0.7055,Product: panchhi Lime Green & Embroidered Sequ...
7,8,no,18730470,-,0.7022,Product: panchhi Peach-Coloured & Blue Embroid...
8,9,no,18624652,-,0.6762,Product: panchhi Green & Gold Sequinned Semi-S...
9,10,no,19046354,-,0.6739,Product: panchhi Maroon Embellished Sequinned ...
10,11,no,18069992,-,0.6657,Product: panchhi Maroon Embroidered Sequinned ...
11,12,no,19046340,-,0.6644,Product: panchhi Yellow & Teal Embellished Sem...
12,13,no,19046358,-,0.6596,Product: panchhi Sea Green & Red Embroidered S...
13,14,no,18069988,-,0.6553,Product: panchhi Coral & Embroidered Sequinned...
14,15,no,18624644,-,0.6518,Product: panchhi Olive Green Embroidered Sequi...
15,16,no,19046324,-,0.6422,Product: panchhi Navy Blue & Mustard Embellish...
16,17,no,18069986,-,0.6268,Product: panchhi Navy Blue Embroidered Sequinn...
17,18,no,13421470,-,0.6181,Product: panchhi Mustard & Pink Embroidered Se...
18,19,no,13421500,-,0.5507,Product: panchhi Lime Green & Lime Green Embro...
19,20,no,12003688,-,0.5255,Product: panchhi Green & Yellow Embellished Se...
20,21,no,12668248,-,0.5245,Product: panchhi Peach-Coloured & Green Semi-S...
21,22,no,12003618,-,0.5093,Product: panchhi Green & Green Embroidered Sem...
22,23,no,13515246,-,0.4955,Product: panchhi Blue Embroidered Semi-Stitche...
23,24,no,13872486,-,0.3973,Product: panchhi Mustard & Pink Embroidered Se...
24,25,no,12668254,-,0.3931,Product: panchhi Red Codding Embroidered Semi-...
25,26,no,13661140,-,0.3710,Product: panchhi Orange Jacquard Woven Banaras...
26,27,no,13872488,-,0.3680,Product: panchhi Cream-Coloured & Yellow Embro...
27,28,no,17848104,-,0.3647,Product: panchhi Nude-Coloured Embellished Seq...
28,29,no,15393564,-,0.3629,Product: panchhi Beige & Peach-Coloured Embroi...
29,30,no,16172382,-,0.3523,Product: NEUDIS Red Cowl Neck Satin Regular To...

,rank,hit,section_id,title,score,preview
0,1,no,16858560,-,0.5000,Product: NEUDIS Women Black Comfort Flared Tro...
1,2,no,17612960,-,0.5000,Product: 250 DESIGNS Women Navy Blue Floral Co...
2,3,no,16172382,-,0.3460,Product: NEUDIS Red Cowl Neck Satin Regular To...
3,4,no,18489222,-,0.3423,Product: NEUDIS Red Cowl Neck Satin Top Brand:...
4,5,no,17255464,-,0.3381,Product: NEUDIS Women Satin Red Embillished So...
5,6,no,18057660,-,0.2999,Product: NEUDIS Women White Self-Design A-Line...
6,7,no,17336142,-,0.2845,Product: UNDER ARMOUR Women Pink Loose Fit Tra...
7,8,no,2507000,-,0.2833,Product: Roadster Pink Knitted Lace Top Brand:...
8,9,no,18290992,-,0.2507,Product: Superminis Girls Brown & Embroidered ...
9,10,no,18806012,-,0.2368,Product: awesome Red & Gold-Toned Woven Design...
10,11,no,16034502,-,0.2357,Product: Berrylush Women Bright Yellow Printed...
11,12,no,18284594,-,0.2283,Product: HERSHEINBOX Women Purple Printed Noug...
12,13,no,17238348,-,0.2258,Product: NEUDIS Beige Cowl Neck Sheen Satin Fi...
13,14,no,17209256,-,0.2256,Product: Unnati Silks Cream-Coloured & Black E...
14,15,no,16372904,-,0.2232,Product: Netram Beige Embroidered Semi-Stitche...
15,16,no,15381904,-,0.2192,Product: Berrylush Women Pink Solid Ruffled Ju...
16,17,no,18512872,-,0.2180,Product: Amrutam Fab Cream-Coloured & Navy Blu...
17,18,no,18290988,-,0.2091,Product: Superminis Girls Lime Green & Beige E...
18,19,no,16758920,-,0.2067,Product: ZIYAA Women Classic White Printed Cin...
19,20,no,15589086,-,0.1978,Product: Netram Lavender & Silver-Toned Semi-S...
20,21,no,17725246,-,0.1965,Product: DIVASTRI Red & Mustard Banarasi Silk ...
21,22,no,15508760,-,0.1928,Product: SASSAFRAS Women Deep Navy Blue Solid ...
22,23,no,18258322,-,0.1912,Product: Netram Red & Gold-Toned Embroidered S...
23,24,no,18309022,-,0.1860,Product: PURVAJA Olive Green & Red Semi-Stitch...
24,25,no,15071832,-,0.1775,Product: all about you Blue & Violet Floral Or...
25,26,no,19104000,-,0.1768,Product: Granthva Fab Blue & White Embroidered...
26,27,no,17638538,-,0.1767,Product: V SALES Grey & Orange Embellished Sem...
27,28,no,16311568,-,0.1741,Product: all about you Grey Leheriya Organza S...
28,29,no,16311702,-,0.1737,Product: all about you Pink Woven Design Silk ...
29,30,no,16311684,-,0.1731,Product: all about you Blue Leheriya Organza S...

,rank,hit,section_id,title,score,preview
0,1,no,14869156,-,0.9795,Product: Indo Era Deep Black Solid Lehenga wit...
1,2,no,16188740,-,0.9397,Product: Indo Era Women Green Solid Cotton Pal...
2,3,yes,12122360,-,0.9396,Product: Indo Era Brown & Golden Woven Design ...
3,4,no,16950290,-,0.8957,Product: Indo Era Sea Green Floral Print Tie-U...
4,5,yes,12040878,-,0.8867,Product: Indo Era Orange & Pink Striped Dupatt...
5,6,no,16950218,-,0.8832,Product: Indo Era Blue Ethnic Motif Printed Pe...
6,7,yes,11459668,-,0.8817,Product: Indo Era Navy Blue & Gold-Toned Strip...
7,8,yes,12040868,-,0.8682,Product: Indo Era Navy Blue & Golden Striped D...
8,9,no,17577466,-,0.8648,Product: Indo Era Women Bright Orange Ethnic F...
9,10,no,17577464,-,0.8619,Product: Indo Era Women Stunning Blue Floral E...
10,11,no,13810898,-,0.8604,Product: Indo Era Women Blue & Green Printed K...
11,12,no,17577456,-,0.8599,Product: Indo Era Women Classic Off-White Ethn...
12,13,no,16713198,-,0.8472,Product: Indo Era Grey Silk Blend Scalloped Ed...
13,14,no,15098594,-,0.8440,Product: Indo Era Women Teal Green & Golden Et...
14,15,no,12122358,-,0.8409,Product: Indo Era Women Black & Teal Blue Yoke...
15,16,no,15258422,-,0.8383,Product: Indo Era Floral Cotton Blend Calf Len...
16,17,no,17069054,-,0.8358,Product: Indo Era Women Black Ethnic Motifs Yo...
17,18,no,15098616,-,0.8245,Product: Indo Era Women Burgundy & Golden Ethn...
18,19,no,14235030,-,0.8222,Product: Indo Era Women Black Floral Printed P...
19,20,no,17553556,-,0.8217,Product: Indo Era Green & Gold-Toned Woven Des...
20,21,no,12418804,-,0.8211,Product: Indo Era Women Maroon & Orange Yoke D...
21,22,no,17911130,-,0.8207,Product: Indo Era Women Burgundy Sequined Kurt...
22,23,no,11459658,-,0.8176,Product: Indo Era Folksy Floral Screen Print C...
23,24,no,15654150,-,0.8175,Product: Indo Era Women Green Ethnic Motifs Yo...
24,25,no,15794640,-,0.8153,Product: Indo Era Woven Design Velvet Kurta Se...
25,26,no,14967448,-,0.8139,Product: Indo Era Women Green Ethnic Motifs Pr...
26,27,no,16713256,-,0.8132,Product: Indo Era Mustard Liva Calf Length Kur...
27,28,no,15794634,-,0.8072,Product: Indo Era Embroidered Velvet Kurta Set...
28,29,no,13962300,-,0.8057,Product: Indo Era Classy Off White And Yellow ...
29,30,yes,15520698,-,0.7969,Product: Indo Era Women Navy Blue Floral Yoke ...

,rank,hit,section_id,title,score,preview
0,1,yes,18626222,-,1.0000,Product: ONLY Women Blue Straight Fit High-Ris...
1,2,no,16372376,-,0.9342,Product: ONLY Women Blue Slim Fit High-Rise Mi...
2,3,no,18620390,-,0.9280,Product: ONLY Women Blue Skinny Fit High-Rise ...
3,4,no,18626210,-,0.9218,Product: ONLY Women Blue Skinny Fit High-Rise ...
4,5,no,19089706,-,0.9062,Product: ONLY Women Blue Slim Fit High-Rise Mi...
5,6,no,16699772,-,0.8736,Product: ONLY Women Blue High-Rise Mildly Dist...
6,7,no,19089710,-,0.6762,Product: ONLY Women Blue Flared Mildly Distres...
7,8,no,19089668,-,0.6100,Product: ONLY Women Blue Straight Fit High-Ris...
8,9,no,17122946,-,0.6051,Product: Moda Rapido Women Blue Straight Fit H...
9,10,no,17914728,-,0.6003,Product: ONLY Women Blue Straight Fit High-Ris...
10,11,no,19089694,-,0.5978,Product: ONLY Women Blue Straight Fit High-Ris...
11,12,no,19143972,-,0.5760,Product: ONLY Women Blue Straight Fit High-Ris...
12,13,no,18620400,-,0.5546,Product: ONLY Women Blue Skinny Fit High-Rise ...
13,14,no,18626226,-,0.4906,Product: ONLY Women Blue Straight Fit High-Ris...
14,15,no,18338282,-,0.4874,Product: SHOWOFF Women Blue Slim Fit High-Rise...
15,16,no,18822974,-,0.4842,Product: RAREISM Women Blue High-Rise Mildly D...
16,17,no,19089666,-,0.4835,Product: ONLY Women Blue Slim Fit High-Rise Lo...
17,18,no,18769600,-,0.4424,Product: Trendyol Women Blue Wide Leg High-Ris...
18,19,no,17988964,-,0.4420,Product: Flying Machine Women Grey Straight Fi...
19,20,no,18769900,-,0.4334,Product: Trendyol Women Blue Pure Cotton Mom F...
20,21,no,17541860,-,0.4286,Product: RAREISM Women Blue High-Rise Mildly D...
21,22,no,19089682,-,0.4214,Product: ONLY Women Black Straight Fit Low-Ris...
22,23,no,18626254,-,0.4055,Product: ONLY Women Blue Bootcut High-Rise Low...
23,24,no,15327310,-,0.3932,Product: AMERICAN EAGLE OUTFITTERS Women Blue ...
24,25,no,15773152,-,0.3681,Product: Roadster Women Blue Wide Leg High-Ris...
25,26,no,18439034,-,0.3628,Product: 20Dresses Women Blue Mildly Distresse...
26,27,no,15852504,-,0.3613,Product: URBANIC Women Blue Cotton Mildly Dist...
27,28,no,16916588,-,0.3604,Product: ONLY Women Blue Mom-Fit High-Rise Lig...
28,29,no,18626232,-,0.3542,Product: ONLY Women Blue Skinny Fit High-Rise ...
29,30,no,8963467,-,0.3533,Product: The Roadster Lifestyle Co Women Navy ...

,rank,hit,section_id,title,score,preview
0,1,yes,17944738,-,0.9580,Product: Uptownie Lite Grey Solid Pleated Form...
1,2,no,11425706,-,0.8761,Product: Uptownie Lite Black Satin Pleated Fla...
2,3,yes,11425704,-,0.8584,Product: Uptownie Lite Brown Satin Pleated Fla...
3,4,yes,13467524,-,0.8134,Product: Uptownie Lite Women Red Solid Pleated...
4,5,yes,11511460,-,0.7939,Product: Uptownie Lite Women Maroon Solid Plea...
5,6,no,11335786,-,0.7707,Product: Uptownie Lite Women Gold-Coloured Sol...
6,7,no,15355338,-,0.7594,Product: Uptownie Lite Girls Black Crepe Print...
7,8,yes,16608122,-,0.7517,Product: Uptownie Lite Girls Black & Pink Prin...
8,9,no,11234642,-,0.7130,Product: Uptownie Lite Women Black Solid Basic...
9,10,no,10418102,-,0.7038,Product: Uptownie Lite Women Maroon Solid Ruff...
10,11,no,11234652,-,0.6713,Product: Uptownie Lite Women Burgundy Solid Ba...
11,12,no,19169942,-,0.6106,Product: Uptownie Lite Women Yellow Crepe Smoc...
12,13,no,17267836,-,0.6053,Product: Uptownie Lite Red & Yellow Striped Ba...
13,14,no,11322090,-,0.6013,Product: Uptownie Lite Women Black Solid Basic...
14,15,no,13501842,-,0.5645,Product: Uptownie Lite Women Black Solid Dhoti...
15,16,no,18057660,-,0.2634,Product: NEUDIS Women White Self-Design A-Line...
16,17,no,16172382,-,0.2375,Product: NEUDIS Red Cowl Neck Satin Regular To...
17,18,no,18489222,-,0.2352,Product: NEUDIS Red Cowl Neck Satin Top Brand:...
18,19,no,17255464,-,0.2327,Product: NEUDIS Women Satin Red Embillished So...
19,20,no,18057656,-,0.2164,Product: NEUDIS Women Navy Blue Mirror Work Du...
20,21,no,17238348,-,0.1900,Product: NEUDIS Beige Cowl Neck Sheen Satin Fi...
21,22,no,16931760,-,0.1504,Product: all about you Black Tiered Maxi Skirt...
22,23,no,14381366,-,0.1321,Product: all about you Peach-Coloured & Orange...
23,24,no,14458644,-,0.1293,Product: all about you Women Black Flared High...
24,25,no,16860376,-,0.1247,Product: all about you Women Navy Blue Flared ...
25,26,no,13452734,-,0.1204,Product: I AM FOR YOU Women Green & Grey Print...
26,27,no,15852580,-,0.1174,Product: URBANIC Black & White Printed Ruffle ...
27,28,no,13792342,-,0.1055,Product: U&F Purple Flared Maxi Skirt Brand: U...
28,29,no,17133488,-,0.1050,Product: all about you Women Black Solid Flare...
29,30,no,16858560,-,0.1033,Product: NEUDIS Women Black Comfort Flared Tro...

,rank,hit,section_id,title,score,preview
0,1,yes,16950080,-,0.9786,Product: Mitera Grey Embellished Sequinned Sem...
1,2,no,16950094,-,0.7956,Product: Mitera Red & Silver-Toned Embellished...
2,3,no,16316606,-,0.7523,Product: Mitera Black Velvet Sequinned Semi-St...
3,4,no,16950086,-,0.7145,Product: Mitera Pink Embellished Sequinned Sem...
4,5,no,18813862,-,0.6941,Product: Mitera White & Green Embroidered Sequ...
5,6,no,18813860,-,0.6930,Product: Mitera White & Green Embroidered Sequ...
6,7,no,18759692,-,0.6835,Product: Mitera Blue Embroidered Sequinned Sem...
7,8,no,18813850,-,0.6627,Product: Mitera White & Maroon Embroidered Seq...
8,9,no,18813864,-,0.6316,Product: Mitera Peach-Coloured & Silver-Toned ...
9,10,no,15390366,-,0.6041,Product: Shaily Grey Embroidered Sequinned Sem...
10,11,no,14009588,-,0.5291,Product: JATRIQQ Grey & Silver-Toned Embellish...
11,12,no,16950082,-,0.5104,Product: Mitera Green & Grey Embroidered Sequi...
12,13,no,18787332,-,0.4829,Product: Mitera Mauve & Silver-Toned Embroider...
13,14,no,11753804,-,0.4680,Product: Mitera Mustard Green & Pink Mirror Se...
14,15,no,18605472,-,0.4645,Product: Sangria Green & Pink Embellished Sequ...
15,16,no,19046354,-,0.4585,Product: panchhi Maroon Embellished Sequinned ...
16,17,no,13515390,-,0.4440,Product: Mitera Blue & Gold-Toned Embroidered ...
17,18,no,12003688,-,0.4353,Product: panchhi Green & Yellow Embellished Se...
18,19,no,18726440,-,0.4334,Product: Mitera Green & White Embroidered Sequ...
19,20,no,19046324,-,0.4264,Product: panchhi Navy Blue & Mustard Embellish...
20,21,no,16291316,-,0.4134,Product: Mitera Green & Golden Embroidered Sem...
21,22,no,18726438,-,0.3981,Product: Mitera Rust & White Embroidered Sequi...
22,23,no,16291342,-,0.3818,Product: Mitera Red & Golden Embroidered Semi-...
23,24,no,16291330,-,0.3764,Product: Mitera Red & Golden Embroidered Semi-...
24,25,no,16950084,-,0.3757,Product: Mitera Magenta Embroidered Sequinned ...
25,26,no,18512872,-,0.3751,Product: Amrutam Fab Cream-Coloured & Navy Blu...
26,27,no,19046346,-,0.3745,Product: panchhi Pink & Sea Green Embellished ...
27,28,no,19257046,-,0.3719,Product: SHADOW & SAINING Green Embellished Se...
28,29,no,15748944,-,0.3631,Product: LOOKNBOOK ART Cream-Coloured Embellis...
29,30,no,17594266,-,0.3618,Product: VRSALES Green Embellished Sequinned S...

,rank,hit,section_id,title,score,preview
0,1,yes,15243956,-,1.0000,Product: Suta Beige & White Pure Linen Zari Sa...
1,2,no,14988194,-,0.6817,Product: Suta Gold-Toned Solid Zari Pure Linen...
2,3,no,15244002,-,0.6462,Product: Suta Pink & Gold-Toned Zari Pure Line...
3,4,no,16909578,-,0.4304,Product: Suta Violet & Green Embellished Zari ...
4,5,no,14988280,-,0.4246,Product: Suta Beige & Black Pure Cotton solid ...
5,6,no,16909636,-,0.4138,Product: Suta Maroon & Pink Colourblocked Zari...
6,7,no,16909300,-,0.4013,Product: Suta Off White & Black Zari Silk Cott...
7,8,no,15244224,-,0.3920,Product: Suta Beige & White Floral Embroidered...
8,9,no,17638770,-,0.3637,Product: Silk Land Beige & Red Ethnic Motifs Z...
9,10,no,15244024,-,0.3242,Product: Suta Beige Pink Floral Motifs PolyCot...
10,11,no,15244106,-,0.3183,Product: Suta White & Pink Polka Dot Printed P...
11,12,no,16532732,-,0.2859,Product: Charukriti Green & Pink Zari Pure Lin...
12,13,no,15511808,-,0.2786,Product: Suta Grey & Maroon Colourblocked Pure...
13,14,no,17638792,-,0.2726,Product: Silk Land White & Blue Zari Pure Silk...
14,15,no,15244118,-,0.2724,Product: Suta White & Black Ethnic Motifs Jamd...
15,16,no,14988276,-,0.2687,Product: Suta Peach Blue Warli Printed Pure Co...
16,17,no,16909486,-,0.2660,Product: Suta Blue & Yellow Colourblocked Zari...
17,18,no,18302978,-,0.2608,Product: Mitera Grey & Silver-Toned Floral Zar...
18,19,no,15243974,-,0.2554,Product: Suta Maroon White Hand Blocked Pure C...
19,20,no,18390702,-,0.2414,Product: Suta Off White & Golden Striped Saree...
20,21,no,15244104,-,0.2312,Product: Suta Lavender Solid Pure Cotton Ruffl...
21,22,no,17900824,-,0.2222,Product: Silk Land Peach-Coloured & Blue Kalam...
22,23,no,16635316,-,0.2209,Product: Thara Sarees Women Off White & Golden...
23,24,no,14597636,-,0.2072,Product: Sangria Turquoise Blue & Yellow Strip...
24,25,no,16930382,-,0.2023,Product: KALINI White & Black Floral Zari Pure...
25,26,no,18166926,-,0.1997,Product: Suta Women White Embroidered Cotton S...
26,27,no,16909440,-,0.1960,Product: Suta Multicoloured Checked Pure Cotto...
27,28,no,18806012,-,0.1955,Product: awesome Red & Gold-Toned Woven Design...
28,29,no,17781762,-,0.1932,Product: Silk Land Beige & Pink Woven Design Z...
29,30,no,15243876,-,0.1929,Product: Suta Brown & Black Polka Dots Printed...

,rank,hit,section_id,title,score,preview
0,1,no,18069150,-,0.9988,Product: Levis Women Blue Skinny Fit Light Fad...
1,2,no,18903336,-,0.9915,Product: Levis Women Blue 725 Bootcut Light Fa...
2,3,no,18903198,-,0.9834,Product: Levis Women Blue Skinny Fit Light Fad...
3,4,no,18903182,-,0.9730,Product: Levis Women Blue Straight Fit High-Ri...
4,5,yes,18069260,-,0.9641,Product: Levis Women Blue 710 Super Skinny Fit...
5,6,no,18903152,-,0.9540,Product: Levis Women Blue Skinny Fit High-Rise...
6,7,no,18069202,-,0.9512,Product: Levis Women Blue 710 Super Skinny Fit...
7,8,no,18069276,-,0.9456,Product: Levis Women Blue Skinny Fit Light Fad...
8,9,no,18903286,-,0.9375,Product: Levis Women Blue 711 Skinny Fit Light...
9,10,yes,16653786,-,0.9374,Product: Levis Women Blue 714 Straight Fit Hig...
10,11,no,16653698,-,0.9345,Product: Levis Women Blue Straight Fit High-Ri...
11,12,yes,16653608,-,0.9284,Product: Levis Women Blue Skinny Fit Light Fad...
12,13,no,16653772,-,0.9270,Product: Levis Women Blue Skinny Fit Light Fad...
13,14,yes,18069298,-,0.9202,Product: Levis Women Blue 710 Super Skinny Fit...
14,15,yes,18069226,-,0.9184,Product: Levis Women Blue 710 Super Skinny Fit...
15,16,no,16653658,-,0.9128,Product: Levis Women Blue 311 Shaping Skinny F...
16,17,no,16794836,-,0.9111,Product: Levis Women Blue 721 Skinny Fit High-...
17,18,no,13326354,-,0.9064,Product: Levis Women Blue Super Skinny Fit Hig...
18,19,no,12259048,-,0.9059,Product: Levis Women Blue 710 Super Skinny Fit...
19,20,yes,16532142,-,0.8956,Product: Levis Women Blue 711 Skinny Fit Light...
20,21,yes,16653750,-,0.8955,Product: Levis Women Blue 711 Skinny Fit Mid R...
21,22,no,16653760,-,0.8933,Product: Levis Women Blue 711 Skinny Fit Mid R...
22,23,yes,16653678,-,0.8881,Product: Levis Women Blue 711 Skinny Fit Heavy...
23,24,no,16865718,-,0.8525,Product: Levis X Deepika Padukone Women Blue 7...
24,25,no,15022668,-,0.8274,Product: Levis Women Navy Blue Super Skinny Fi...
25,26,no,18069146,-,0.7618,Product: Levis Women Blue Printed Drop-Shoulde...
26,27,no,16781554,-,0.7269,Product: Levis X Deepika Padukone Blue Ribbed ...
27,28,no,14860462,-,0.7235,Product: Levis Women Blue Round Neck Printed S...
28,29,no,16794818,-,0.6891,Product: Levis Women Blue 501 Straight Fit Hig...
29,30,no,15506368,-,0.6876,Product: Levi's x Deepika Padukone Women Navy ...

,rank,hit,section_id,title,score,preview
0,1,no,9478497,-,0.8035,Product: The Roadster Lifestyle Co Women Black...
1,2,yes,15198584,-,0.7407,Product: H&M Women Black Sweatshirt Brand: H&M...
2,3,no,15845464,-,0.7263,Product: URBANIC Women Black Solid Cotton Swea...
3,4,no,15642616,-,0.6873,Product: Aesthetic Bodies Women Black Cotton S...
4,5,no,10575458,-,0.6801,Product: The Roadster Lifestyle Co Women Black...
5,6,no,6726577,-,0.6637,Product: Mast & Harbour Women Black Solid Pull...
6,7,no,10714640,-,0.6526,Product: Taanz Women Black Solid Sweatshirt Br...
7,8,no,17038044,-,0.6297,Product: Levis Women Black Pullover Sweater Br...
8,9,no,9477715,-,0.6218,Product: The Roadster Lifestyle Co Women Black...
9,10,no,10683730,-,0.6196,Product: STREET 9 Women Black Solid Sweater Br...
10,11,no,13615048,-,0.6109,Product: Flying Machine Women Black Solid Swea...
11,12,no,15630060,-,0.6091,Product: H&M Women Black Solid Hoodie Brand: H...
12,13,no,19266888,-,0.5892,Product: H&M Women Black Solid Collared Sweats...
13,14,no,10791506,-,0.5796,Product: The Vanca Women Black & Navy Blue Sol...
14,15,no,14331596,-,0.5711,Product: Roadster Women Black Solid Turtle Nec...
15,16,yes,15964092,-,0.5619,Product: MANGO Women Black Solid Pullover Bran...
16,17,no,14080898,-,0.5492,Product: DressBerry Women Black Print Detail S...
17,18,no,11109236,-,0.5424,Product: DOLCE CRUDO Women Black Solid Hooded ...
18,19,no,13593756,-,0.5416,Product: BEVERLY BLUES Women Black Solid Sweat...
19,20,no,16583226,-,0.5279,Product: 20Dresses Women Black Plus Size Cotto...
20,21,no,10747958,-,0.5239,Product: Alsace Lorraine Paris Women Black & Y...
21,22,no,12048466,-,0.4901,Product: INVICTUS Women Black Solid Pullover B...
22,23,no,14512956,-,0.4794,Product: Powerpuff Girls by Kook N Keech Women...
23,24,no,7275903,-,0.4740,Product: Belle Fille Women Black Solid Sweatsh...
24,25,no,15870014,-,0.4720,Product: New Balance Women Black Sweatshirt Br...
25,26,no,19269372,-,0.4678,Product: BoStreet Women Black Colourblocked Lo...
26,27,no,14080668,-,0.4659,Product: DressBerry Women Black Solid Sweatshi...
27,28,no,10611428,-,0.4605,Product: Alsace Lorraine Paris Women Black Sol...
28,29,no,10819950,-,0.4510,Product: Antheaa Women Black Solid Embellished...
29,30,no,18004440,-,0.4342,Product: Aeropostale Women Black Printed Hoode...

,rank,hit,section_id,title,score,preview
0,1,no,17403640,-,0.5000,Product: I Saw It First Women Khaki Crinkled T...
1,2,no,13843640,-,0.5000,Product: Stylee LIFESTYLE Navy Blue & Gold-Ton...
2,3,no,17403254,-,0.4860,Product: I Saw It First Women Blue Skinny Fit ...
3,4,no,13452734,-,0.4836,Product: I AM FOR YOU Women Green & Grey Print...
4,5,no,17403434,-,0.4779,Product: I Saw It First Women White & Blue Flo...
5,6,no,17365722,-,0.4746,Product: I Saw It First Women Beige Striped Hi...
6,7,no,17403428,-,0.4731,Product: I Saw It First Women Blue Skinny Fit ...
7,8,no,14159320,-,0.4680,Product: I AM FOR YOU Women Yellow & White Emb...
8,9,no,17403380,-,0.4669,Product: I Saw It First Women Blue Slash Knee ...
9,10,no,17403300,-,0.4636,Product: I Saw It First Women Blue Light Fade ...
10,11,no,17365728,-,0.4605,Product: I Saw It First Women Dusty Pink & Whi...
11,12,no,17365720,-,0.4540,Product: I Saw It First Women Green Solid Plea...
12,13,no,17136852,-,0.4325,Product: Readiprint Fashions Blue & Silver Emb...
13,14,no,18750730,-,0.4127,Product: Stylee LIFESTYLE Olive Green & Red Un...
14,15,no,19392350,-,0.4003,Product: Ethnic Yard Green & Grey Embroidered ...
15,16,no,17287376,-,0.3916,Product: Stylee LIFESTYLE Yellow & Gold-Toned ...
16,17,no,18766164,-,0.3703,Product: Stylee LIFESTYLE Black & Gold-Toned P...
17,18,no,17570416,-,0.3682,Product: SHOWOFF Women Black Straight Fit Stre...
18,19,no,19097390,-,0.3590,Product: I Love She Women White Relaxed High-R...
19,20,no,18245104,-,0.3560,Product: Miss Chase Women Blue Jogger High-Ris...
20,21,no,18142614,-,0.3558,Product: SHOWOFF Women Lavender Jogger High-Ri...
21,22,no,14925780,-,0.3543,Product: Roadster Women Blue Wide Leg Stretcha...
22,23,no,19396408,-,0.3484,Product: Stylee LIFESTYLE Womens Beige Embroid...
23,24,no,12629360,-,0.3478,Product: Roadster Women Rust Red Regular Fit M...
24,25,no,18245110,-,0.3477,Product: Miss Chase Women Blue High-Rise Mildl...
25,26,no,19097392,-,0.3432,Product: I Love She Women Maroon Relaxed Skinn...
26,27,no,14954878,-,0.3426,Product: Roadster Women Charcoal Mid-Rise Stra...
27,28,no,11284776,-,0.3389,Product: Mast & Harbour Women Blue Mid-Rise Cl...
28,29,no,17570328,-,0.3381,Product: SHOWOFF Women Blue Wide Leg High-Rise...
29,30,no,16533888,-,0.3350,Product: Ethnic Junction Navy Blue & Gold-Tone...

,rank,hit,section_id,title,score,preview
0,1,yes,11244988,-,0.9585,Product: Mitera Pink & Gold-Toned Silk Blend W...
1,2,no,13886174,-,0.9414,Product: Mitera Pink & White Pure Cotton Woven...
2,3,no,11218670,-,0.8919,Product: Mitera Pink & Gold-Toned Silk Blend W...
3,4,yes,15012182,-,0.8775,Product: Mitera Pink & Silver-Toned Paisley Za...
4,5,yes,18302880,-,0.8478,Product: Mitera Pink & Gold-Toned Woven Design...
5,6,no,18287324,-,0.7822,Product: Mitera Floral Saree Brand: Mitera Col...
6,7,yes,11454958,-,0.7756,Product: Mitera Pink & Golden Woven Design Ban...
7,8,no,14850332,-,0.7741,Product: Mitera Pink & Gold-Toned Woven Design...
8,9,no,17552342,-,0.6674,Product: Mitera Floral Saree with Embroidered ...
9,10,no,18377598,-,0.5553,Product: Mitera Teal Green & Pink Ethnic Motif...
10,11,no,17044538,-,0.5431,Product: Mitera Tie and Dye Pleated Saree Bran...
11,12,no,11096590,-,0.5399,Product: Mitera Orange & Pink Silk Blend Woven...
12,13,no,15519332,-,0.5312,Product: Mitera Purple & Pink Bandhani Saree B...
13,14,no,17669470,-,0.5013,Product: Mitera Colourblocked Satin Saree Bran...
14,15,no,18802314,-,0.5011,Product: Mitera Pink & Green Ethnic Motifs Wov...
15,16,no,11117288,-,0.4978,Product: Mitera Mustard & Pink Silk Blend Wove...
16,17,no,12668502,-,0.4736,Product: Mitera Pink & Blue Woven Design Semi-...
17,18,no,11458584,-,0.4634,Product: Mitera Yellow Silk Blend Woven Design...
18,19,no,16125582,-,0.4452,Product: Mitera Pink Embellished Mirror Work H...
19,20,no,12679536,-,0.4367,Product: Mitera Pink & White Pure Georgette Em...
20,21,no,16950086,-,0.4072,Product: Mitera Pink Embellished Sequinned Sem...
21,22,no,13895786,-,0.4064,Product: Mitera Off-White & Green Pure Cotton ...
22,23,no,15810740,-,0.4049,Product: Mitera Mauve & Gold-Toned Silk Cotton...
23,24,no,17141262,-,0.3880,Product: Mitera Women Brown & Dusty Pink Ombre...
24,25,no,16219622,-,0.3762,Product: Mitera Pink Thread Work Semi-Stitched...
25,26,no,15601780,-,0.3717,Product: Mitera Teal & Silver-Toned Woven Desi...
26,27,no,17141474,-,0.3702,Product: Mitera Women Yellow Embroidered Pure ...
27,28,no,11292438,-,0.3694,Product: Mitera Green & Red Silk Blend Woven D...
28,29,no,11530714,-,0.3684,Product: Mitera Pink & Gold-Toned Woven Design...
29,30,no,16587928,-,0.3637,Product: Mitera Orange & Golden Paisley Design...

,rank,hit,section_id,title,score,preview
0,1,no,18782606,-,0.9951,Product: max Women Black Printed Sweatshirt Br...
1,2,no,18995122,-,0.9663,Product: max Women Black Printed Sweatshirt Br...
2,3,yes,19204850,-,0.8772,Product: max Women Peach-Coloured Printed Slip...
3,4,no,19204868,-,0.7971,Product: max Women Lime Green Printed Sweatshi...
4,5,no,15878938,-,0.7938,Product: max Women Grey Printed Round Neck Swe...
5,6,no,15878978,-,0.7700,Product: max Women Green Solid Round Neck Swea...
6,7,no,15670702,-,0.7648,Product: max Women Rust Pullover with Embellis...
7,8,yes,15878996,-,0.7327,Product: max Women Olive Green Printed Round n...
8,9,no,15673658,-,0.7142,Product: max Women Peach-Coloured Printed Swea...
9,10,yes,16156132,-,0.6664,Product: max Women Olive Green Printed Sweatsh...
10,11,no,18321088,-,0.5000,Product: HRITIKA Grey & Red Saree Brand: HRITI...
11,12,no,18877470,-,0.4825,Product: HRITIKA Red Satin Saree Brand: HRITIK...
12,13,no,16100932,-,0.4653,Product: Tokyo Talkies Women Charming Purple S...
13,14,no,19165458,-,0.4518,Product: HRITIKA Women Pink Georgette Floral C...
14,15,no,17336142,-,0.4495,Product: UNDER ARMOUR Women Pink Loose Fit Tra...
15,16,no,18224860,-,0.4453,Product: HRITIKA Black Sequinned Saree Brand: ...
16,17,no,19324656,-,0.3567,Product: FASHOR Women Pink Floral Embroidered ...
17,18,no,18964098,-,0.3555,Product: FASHOR Women Turquoise Blue Geometric...
18,19,no,18778410,-,0.3465,Product: FASHOR Women Multicoloured & nirvana ...
19,20,no,19198378,-,0.3419,Product: FASHOR Women Green Yoke Design Thread...
20,21,no,19324666,-,0.3419,Product: FASHOR Women Red Ethnic Motifs Thread...
21,22,no,14976268,-,0.3373,Product: FASHOR Women Red Bandhani Printed & Z...
22,23,no,17155520,-,0.3354,Product: H&M Woman Grey Hoodie Brand: H&M Colo...
23,24,no,19140952,-,0.3320,Product: FASHOR Women Blue Geometric Printed G...
24,25,no,13523706,-,0.3318,Product: Varanga Women Black & White Geometric...
25,26,no,15630060,-,0.3318,Product: H&M Women Black Solid Hoodie Brand: H...
26,27,no,15047458,-,0.3317,Product: FASHOR Women Multicoloured Ethnic Mot...
27,28,no,16486578,-,0.3241,Product: FASHOR Women Maroon Geometric Printed...
28,29,no,16072014,-,0.3197,Product: FASHOR Women Lavender Striped Keyhole...
29,30,no,16984006,-,0.3175,Product: FASHOR Women Pink Ethnic Motifs Yoke ...

,rank,hit,section_id,title,score,preview
0,1,yes,14094106,-,0.9717,Product: Roadster Women Deep Navy Blue High-Ri...
1,2,no,11296068,-,0.8698,Product: Roadster Women Navy Blue Solid Bell S...
2,3,yes,15897498,-,0.7905,Product: The Roadster Lifestyle Co Women Navy ...
3,4,no,5447351,-,0.7534,Product: Roadster Women Navy Blue Striped Card...
4,5,no,14094050,-,0.7342,Product: Roadster Women Deep Navy Blue High-Ri...
5,6,yes,12278652,-,0.7202,Product: Roadster Women Navy Blue Bootcut Mid-...
6,7,no,17074032,-,0.7118,Product: Roadster Women Navy Blue & White Stri...
7,8,yes,12278640,-,0.7099,Product: Roadster Women Navy Blue Flared Fit H...
8,9,no,13700180,-,0.6596,Product: Roadster Women Navy Blue Solid Straig...
9,10,no,14925764,-,0.6273,Product: Roadster Women Navy Blue Pure Cotton ...
10,11,no,14331672,-,0.6225,Product: Roadster Women Navy Blue & Pink Strip...
11,12,yes,16187090,-,0.6211,Product: The Roadster Lifestyle Co Women Navy ...
12,13,yes,8963467,-,0.6128,Product: The Roadster Lifestyle Co Women Navy ...
13,14,no,14535816,-,0.5483,Product: Roadster Women Pure Cotton Navy Blue ...
14,15,no,14356168,-,0.5299,Product: Roadster Women Navy Blue & Maroon Col...
15,16,yes,8803831,-,0.5275,Product: Roadster Women Navy Blue Skinny Fit M...
16,17,no,14356146,-,0.5094,Product: Roadster Women Navy Blue Convertible ...
17,18,no,13789616,-,0.4895,Product: all about you Women Navy Blue Skinny ...
18,19,no,16172382,-,0.4710,Product: NEUDIS Red Cowl Neck Satin Regular To...
19,20,no,18489222,-,0.4664,Product: NEUDIS Red Cowl Neck Satin Top Brand:...
20,21,no,14535784,-,0.4638,Product: Roadster Women Deep Navy Blue Solid D...
21,22,no,17255464,-,0.4614,Product: NEUDIS Women Satin Red Embillished So...
22,23,yes,11987092,-,0.4584,Product: Roadster Women Navy Blue & Green Chec...
23,24,no,15088232,-,0.4509,Product: Roadster Women Navy Blue Solid Half-Z...
24,25,no,13334168,-,0.4477,Product: The Roadster Lifestyle Co Blue Solid ...
25,26,no,18057660,-,0.4462,Product: NEUDIS Women White Self-Design A-Line...
26,27,no,16336042,-,0.4371,Product: all about you Navy Blue Woven Design ...
27,28,no,16503948,-,0.4335,Product: all about you Navy Blue & Grey Woven ...
28,29,no,14356150,-,0.4326,Product: Roadster Women Navy Blue Grey Striped...
29,30,no,11688510,-,0.4275,Product: Roadster Women Navy Blue Washed Regul...

,rank,hit,section_id,title,score,preview
0,1,no,14541316,-,0.7696,Product: KALINI Orange & Gold-Toned Ethnic Mot...
1,2,no,17066888,-,0.7228,Product: KALINI Brown & Orange Abstract Printe...
2,3,yes,14490860,-,0.7017,Product: KALINI Orange & Gold-Toned Pure Chiff...
3,4,no,16915002,-,0.4868,Product: KALINI Women Green & Pink Ethnic Moti...
4,5,no,16625250,-,0.4461,Product: KALINI Maroon & Yellow Floral Saree B...
5,6,no,16421936,-,0.4378,Product: KALINI Pink & Gold-Toned Paisley Sare...
6,7,no,16915122,-,0.4247,Product: KALINI Green & White Bandhani Art Sil...
7,8,no,12754022,-,0.4135,Product: KALINI Black & Red Jute Silk Embroide...
8,9,no,16914910,-,0.4044,Product: KALINI Pink Poly Georgette Casual Sar...
9,10,no,17035752,-,0.4007,Product: KALINI Coral & Golden Woven Design Sa...
10,11,no,18482974,-,0.4006,Product: KALINI Women Red Solid Saree Brand: K...
11,12,no,16848432,-,0.3995,Product: KALINI Maroon & Gold-Toned Ethnic Mot...
12,13,no,17035744,-,0.3916,Product: KALINI Black & Golden Woven Design Sa...
13,14,no,16989798,-,0.3738,Product: KALINI Sea Green & Pink Ethnic Motifs...
14,15,no,14986192,-,0.3722,Product: KALINI Blue & Yellow Floral Saree Bra...
15,16,no,15102290,-,0.3648,Product: KALINI Pink & Gold-Toned Woven Design...
16,17,no,18579630,-,0.3604,Product: KALINI Green & White Printed Leheriya...
17,18,no,16915192,-,0.3517,Product: KALINI Navy Blue & Beige Ethnic Motif...
18,19,no,17584716,-,0.3485,Product: KALINI Purple & Orange Floral Bagh Sa...
19,20,no,16988904,-,0.3469,Product: KALINI Mustard Yellow Ethnic Motifs Z...
20,21,no,14905990,-,0.3353,Product: KALINI Taupe & Red Floral Printed Zar...
21,22,no,15991770,-,0.3309,Product: KALINI Mustard & Brown Printed Saree ...
22,23,no,15102284,-,0.3275,Product: KALINI Green & Pink Ethnic Motifs Art...
23,24,no,17810904,-,0.3260,Product: KALINI Cream-Coloured & Gold-Toned St...
24,25,no,18829042,-,0.3179,Product: KALINI Yellow & Green Woven Design Si...
25,26,no,16948530,-,0.3114,Product: KALINI Pink & Grey Paisley Printed Ch...
26,27,no,16186362,-,0.3112,Product: KALINI White & Red Ethnic Motifs Sare...
27,28,no,14678908,-,0.3001,Product: KALINI Pink & Yellow Floral Pure Chif...
28,29,no,18829038,-,0.2901,Product: KALINI Yellow & Red Ethnic Motifs Sil...
29,30,no,18265998,-,0.2778,Product: KALINI Teal Green & Gold-Toned Stripe...

,rank,hit,section_id,title,score,preview
0,1,no,15789256,-,0.9105,Product: Slazenger Women Grey Brand Logo Runni...
1,2,yes,14646546,-,0.8489,Product: HRX By Hrithik Roshan Outdoor Women W...
2,3,no,11383846,-,0.6167,Product: Alcis Nari Women Black Solid Lightwei...
3,4,no,15684018,-,0.6069,Product: Puma x FIRST MILE Women Purple & Whit...
4,5,no,15849954,-,0.5771,Product: URBANIC Women Black & White Houndstoo...
5,6,no,13095488,-,0.5617,Product: Off Label Women Black Solid Lightweig...
6,7,no,14462864,-,0.5557,Product: HERE&NOW Women Black Solid Tailored J...
7,8,no,1052282,-,0.5174,Product: SASSAFRAS Black Embellished Slim Fit ...
8,9,no,18522690,-,0.5157,Product: H&M Women Black & White Baseball-Styl...
9,10,no,8067177,-,0.5000,Product: Ira Soleil Women Black Printed Crop T...
10,11,no,14646288,-,0.4978,Product: HRX By Hrithik Roshan Outdoor Women R...
11,12,no,15789142,-,0.4894,Product: Slazenger Women Black Running Sporty ...
12,13,no,14231172,-,0.4729,Product: all about you Women Tan Brown Solid A...
13,14,no,17069364,-,0.4645,Product: Jockey Women Black Solid Hooded Sport...
14,15,no,16191476,-,0.4606,Product: H&M Woman Black Faux-fur-trimmed jack...
15,16,no,15953824,-,0.4201,Product: Columbia Women Black Joy Peak Mid Hoo...
16,17,no,15634138,-,0.3978,Product: URBANIC Women Black Tailored Jacket B...
17,18,no,14957090,-,0.3974,Product: Zastraa Women Black Lightweight Tailo...
18,19,no,6827804,-,0.3819,Product: NIZA Women Black Self Design Tailored...
19,20,no,1010438,-,0.3748,Product: Belle Fille Red Tailored Jacket Brand...
20,21,no,11063538,-,0.3676,Product: EROTISSCH Women Black & Off-White Ani...
21,22,no,15743742,-,0.3585,Product: ADIDAS Women Black Solid Essential In...
22,23,no,13609880,-,0.3543,Product: HRX by Hrithik Roshan Men Jet Black S...
23,24,no,18282028,-,0.3527,Product: CL SPORT Women Black Reversible Longl...
24,25,no,13039008,-,0.3453,Product: STREET 9 Women Black Checked Lightwei...
25,26,no,17069368,-,0.3327,Product: Jockey Women Navy Blue Longline Tailo...
26,27,no,18144568,-,0.3304,Product: Marks & Spencer Women Black Padded Ja...
27,28,no,15389978,-,0.3264,Product: PERFKT-U Women Black & Mustard Yellow...
28,29,no,17069340,-,0.3043,Product: Jockey Women Purple Tailored Jacket B...
29,30,no,15953844,-,0.3013,Product: Columbia Women Black Delta Ridge Down...

,rank,hit,section_id,title,score,preview
0,1,yes,16835204,-,0.7309,Product: Roadster Women Grey Slim Flared High-...
1,2,yes,16835178,-,0.7144,Product: Roadster Women Grey Slim Flared High-...
2,3,yes,16835166,-,0.6851,Product: The Roadster Lifestyle Co Women Grey ...
3,4,yes,13339544,-,0.6280,Product: The Roadster Lifestyle Co Women Grey ...
4,5,yes,8319213,-,0.6050,Product: Roadster Women Grey Skinny Fit Mid-Ri...
5,6,no,14954602,-,0.5422,Product: Roadster Women Alluring Grey High-Ris...
6,7,yes,14954872,-,0.5386,Product: Roadster Women Grey Slouchy Fit Mid-R...
7,8,no,14536020,-,0.5363,Product: Roadster Woman Beautiful Grey Solid D...
8,9,no,14535748,-,0.5341,Product: Roadster Women Alluring Grey Washed D...
9,10,no,16172382,-,0.5000,Product: NEUDIS Red Cowl Neck Satin Regular To...
10,11,no,18489222,-,0.4955,Product: NEUDIS Red Cowl Neck Satin Top Brand:...
11,12,no,17255464,-,0.4904,Product: NEUDIS Women Satin Red Embillished So...
12,13,no,14535994,-,0.4847,Product: Roadster Women Grey Solid Denim Truck...
13,14,no,18057660,-,0.4822,Product: NEUDIS Women White Self-Design A-Line...
14,15,no,18321088,-,0.4342,Product: HRITIKA Grey & Red Saree Brand: HRITI...
15,16,no,17238348,-,0.4183,Product: NEUDIS Beige Cowl Neck Sheen Satin Fi...
16,17,no,11990670,-,0.4091,Product: Roadster Women Grey & Green Colourblo...
17,18,no,15441284,-,0.4075,Product: The Roadster Lifestyle Co Women Grey ...
18,19,yes,10388213,-,0.4018,Product: Roadster Women Grey Skinny Fit Mid-Ri...
19,20,no,18877470,-,0.3733,Product: HRITIKA Red Satin Saree Brand: HRITIK...
20,21,no,18057656,-,0.3677,Product: NEUDIS Women Navy Blue Mirror Work Du...
21,22,yes,13756948,-,0.3612,Product: Roadster Women Alluring Grey Mid-Rise...
22,23,no,11672562,-,0.3602,Product: Roadster Women Grey Regular Fit Solid...
23,24,no,19165458,-,0.3586,Product: HRITIKA Women Pink Georgette Floral C...
24,25,no,18224860,-,0.3554,Product: HRITIKA Black Sequinned Saree Brand: ...
25,26,no,19207552,-,0.3143,Product: UNITED LIBERTY Women Purple & Gold-To...
26,27,no,14535802,-,0.3064,Product: Roadster Women Beautiful Grey Self-De...
27,28,no,18699156,-,0.2742,Product: Sidhidata Green & Gold-Toned Checked ...
28,29,no,18699148,-,0.2737,Product: Sidhidata Navy Blue & Silver-Toned Ch...
29,30,no,16311568,-,0.2714,Product: all about you Grey Leheriya Organza S...

,rank,hit,section_id,title,score,preview
0,1,no,16931960,-,1.0000,Product: all about you Teal Blue Self Design K...
1,2,no,4374524,-,0.7053,Product: RARE Women Green Self Design Peplum T...
2,3,no,5617740,-,0.6865,Product: plusS Sea Green Self Design Peplum To...
3,4,yes,16504028,-,0.6540,Product: ANVI Be Yourself Women Stunning Blue ...
4,5,no,18514120,-,0.5930,Product: Paralians Turquoise Blue Peplum Top B...
5,6,no,14641744,-,0.5881,Product: FabAlley Blue Puff Sleeve Chambray Pe...
6,7,no,13382002,-,0.5663,Product: plusS Women Black Self-Design Smocked...
7,8,no,11607414,-,0.5359,Product: Bhama Couture Women Blue Printed Pepl...
8,9,no,11607374,-,0.5075,Product: Bhama Couture Women Blue Printed Pepl...
9,10,no,17132282,-,0.5065,Product: Athena Women Pretty Pink Self-Design ...
10,11,no,18805426,-,0.4444,Product: BoStreet Blue Checked Peplum Top Bran...
11,12,no,14602502,-,0.4322,Product: Vishudh Black Geometric Mandarin Coll...
12,13,no,17872080,-,0.4138,Product: Taavi Women Indigo & White Indigo Pri...
13,14,no,17445656,-,0.3792,Product: Vishudh Blue Floral Print Peplum Top ...
14,15,no,10783322,-,0.3676,Product: Sera Women Navy Blue Printed Peplum P...
15,16,no,8715089,-,0.3547,Product: plusS Women Blue Printed Peplum Top B...
16,17,no,17627582,-,0.3402,Product: kipek Women Deep Navy Blue Solid Top ...
17,18,no,15766290,-,0.3341,Product: Pepe Jeans Women Blue Pure Cotton Tro...
18,19,no,14867398,-,0.2881,Product: Janasya Women Blue & White Floral Ruf...
19,20,no,13013166,-,0.2757,Product: SALWAR STUDIO Women Orange Solid Pepl...
20,21,no,14424654,-,0.2539,Product: ROOTED Navy Blue Printed Peplum Top B...
21,22,no,16935640,-,0.2475,Product: flaher Women Blue Solid Art Silk Padd...
22,23,no,14231406,-,0.2381,Product: all about you Women Blue Self-Design ...
23,24,no,14658916,-,0.2362,Product: Pepe Jeans Women Blue Washed Mid-Rise...
24,25,no,16950218,-,0.2156,Product: Indo Era Blue Ethnic Motif Printed Pe...
25,26,no,18604646,-,0.2041,Product: Zink London Women Blue Floral Lace De...
26,27,no,18998716,-,0.2034,Product: KALINI Blue Print Indigo Pure Cotton ...
27,28,no,17557370,-,0.2030,Product: Pepe Jeans Women Navy Blue Printed Sh...
28,29,no,17566228,-,0.1811,Product: Inddus Women Blue Woven Design Top & ...
29,30,no,17403254,-,0.1708,Product: I Saw It First Women Blue Skinny Fit ...

,rank,hit,section_id,title,score,preview
0,1,yes,16533076,-,0.9950,Product: Madame Women Peach-Coloured Self Desi...
1,2,no,18948340,-,0.8105,Product: Madame Peach-Coloured Cuffed Sleeves ...
2,3,no,14556346,-,0.8037,Product: Madame Women White Solid Fuzzy Pullov...
3,4,no,15756110,-,0.6470,Product: Madame Women Pink Pullover Woolen Swe...
4,5,no,16512732,-,0.6163,Product: Madame Women Beige Self Design Pullov...
5,6,no,15997770,-,0.5886,Product: Madame Women Yellow & White Checked P...
6,7,no,16566862,-,0.4745,Product: Madame Women Mauve Lightweight Puffer...
7,8,no,15964118,-,0.4597,Product: Madame Women Charcoal Front-Open Swea...
8,9,no,16512720,-,0.4022,Product: Madame Women Grey Solid Cardigan Swea...
9,10,no,10891532,-,0.4019,Product: Alsace Lorraine Paris Women Peach-Col...
10,11,no,18858332,-,0.3948,Product: Madame Women Navy Blue Stretchable Je...
11,12,no,18858360,-,0.3877,Product: Madame Women Blue Light Fade Stretcha...
12,13,no,19269812,-,0.3855,Product: Madame Women Green Tie-Up Shrug Brand...
13,14,no,18846880,-,0.3853,Product: Madame Rust Orange Mandarin Collar To...
14,15,no,14231418,-,0.3827,Product: all about you Women Peach-Coloured Op...
15,16,no,18948328,-,0.3735,Product: Madame Pink Solid Crop Top Brand: Mad...
16,17,no,18846868,-,0.3427,Product: Madame Black Studded Top Brand: Madam...
17,18,no,15616452,-,0.3380,Product: The Dry State Women Peach-Coloured Ho...
18,19,no,10611410,-,0.3339,Product: Alsace Lorraine Paris Women Peach-Col...
19,20,no,11991442,-,0.3095,Product: Roadster Women Peach-Coloured Solid O...
20,21,no,14279444,-,0.3028,Product: Harvard Women Peach-Coloured & Red Co...
21,22,no,18858310,-,0.3000,Product: Madame Women Grey Melange Shorts Bran...
22,23,no,15963876,-,0.2987,Product: MANGO Women Peach-Coloured Cable Knit...
23,24,no,17403640,-,0.2857,Product: I Saw It First Women Khaki Crinkled T...
24,25,no,10611424,-,0.2799,Product: Alsace Lorraine Paris Women Peach-Col...
25,26,no,17403254,-,0.2792,Product: I Saw It First Women Blue Skinny Fit ...
26,27,no,13452734,-,0.2780,Product: I AM FOR YOU Women Green & Grey Print...
27,28,no,17403434,-,0.2754,Product: I Saw It First Women White & Blue Flo...
28,29,no,17365722,-,0.2739,Product: I Saw It First Women Beige Striped Hi...
29,30,no,17403428,-,0.2732,Product: I Saw It First Women Blue Skinny Fit ...

      precision  recall    mrr   ndcg  context_relevance
mean      0.081   0.745  0.597  0.617              0.895

,question,relevant_docs,retrieved_docs,precision,recall,mrr,ndcg,context_relevance
0,Show me Regular trousers within a budget of 2000.,"[17817750, 18770002, 18769968, 18769944, 18769...","[16279046, 14220194, 13523706, 13647622, 13769...",0.000000,0.000,0.000000,0.000000,0.75
1,"Can you find something similar to ""Athena Wome...",[11166548],"[11166548, 16752820, 16154596, 16565622, 10856...",0.033333,1.000,1.000000,1.000000,1.00
2,"Show me products like ""InWeave Women Red Print...",[18921114],"[18921114, 17168254, 15322490, 15447990, 17168...",0.033333,1.000,1.000000,1.000000,1.00
3,I need product with a Woven design pattern in ...,"[12824928, 18262088]","[10451734, 18122478, 19218994, 17663018, 16719...",0.000000,0.000,0.000000,0.000000,1.00
4,I'm looking for products from MANGO for everyd...,"[15315768, 15265896, 15265898, 16892568, 15977...","[14006764, 16124612, 17607938, 18321088, 18877...",0.000000,0.000,0.000000,0.000000,1.00
5,What do you have from Sweet Dreams in Playsuit...,"[11581420, 11581366]","[11581420, 11581448, 11581366, 12882594, 13270...",0.066667,1.000,1.000000,0.919721,1.00
6,I'm looking for Kurta set by Vishudh.,"[13536726, 15997054, 18262138, 13119222, 18263...","[9867983, 13799826, 14860664, 18929144, 135367...",0.266667,1.000,0.250000,0.604468,1.00
7,I'm looking for A-line by Ancestry.,"[15407228, 19152780, 14873702]","[14873856, 15407228, 14873702, 19152780, 14873...",0.100000,1.000,0.500000,0.732829,1.00
8,"Can you find something similar to ""FASHOR Wome...",[19140952],"[19140952, 18964098, 11561972, 17487138, 18964...",0.033333,1.000,1.000000,1.000000,1.00
9,Show me Blue Tailored jacket from Darzi.,[14460680],"[14460680, 17513236, 14460654, 14460662, 17666...",0.033333,1.000,1.000000,1.000000,1.00
10,"Can you find something similar to ""U.S. Polo A...",[13703470],"[13703470, 13690162, 2185647, 17983210, 155554...",0.033333,1.000,1.000000,1.000000,1.00
11,Does Mitera have any Bandhani for a festive oc...,[15637468],"[15637468, 17141480, 17141474, 15519332, 15519...",0.033333,1.000,1.000000,1.000000,0.50
12,Show me Pencil within a budget of 1500.,"[15940138, 9552849, 15301318, 12086086, 188349...","[14011652, 1294879, 18215398, 14798956, 178991...",0.000000,0.000,0.000000,0.000000,0.50
13,Do you have any Mustard Blouson for everyday w...,[13532718],"[14935802, 13532718, 11184982, 7942995, 192075...",0.033333,1.000,0.500000,0.630930,1.00
14,I need Blue Joggers by STREET 9.,"[13038932, 13071994]","[13071994, 13038932, 13038926, 13071970, 13038...",0.066667,1.000,1.000000,1.000000,1.00
15,Show me Front-open within a budget of 2800.,"[16382036, 16382150, 5829334, 5829327, 1199121...","[14382336, 16082246, 17685090, 19087856, 22231...",0.033333,0.125,0.037037,0.052616,0.50
16,Do you have anything from FILA in Red for ever...,[13255768],"[13255768, 16705336, 16172382, 18489222, 16705...",0.033333,1.000,1.000000,1.000000,0.50
17,I'm looking for products that cost no more tha...,"[13135238, 15241584, 13181706, 17739302, 15218...","[17403640, 2117164, 17403254, 13452734, 174034...",0.000000,0.000,0.000000,0.000000,0.50
18,Do you have anything from Bhama Couture in A-l...,"[12151804, 10355827, 10356731, 12151824, 10717...","[12151824, 9430121, 9430115, 13969870, 1167298...",0.266667,1.000,1.000000,0.736003,1.00
19,Do you have any Pink Peg trousers for everyday...,[15473916],"[13740956, 15473916, 1986896, 11040098, 899948...",0.033333,1.000,0.500000,0.630930,1.00
20,Show me Regular shorts within a budget of 1800.,"[15402090, 14170730, 18283554, 18747132, 16164...","[13523706, 14272032, 13647622, 13769372, 96214...",0.033333,0.125,0.125000,0.079795,1.00
21,I'm looking for Regular by H&M.,"[17964932, 17883620, 18652012, 14258606, 18084...","[17674588, 17965024, 12383500, 17883650, 17883...",0.200000,0.750,1.000000,0.588310,1.00
22,I need Pink Saree by KALINI.,"[15858094, 17852902, 15102290, 14678908, 16421...","[16914910, 16421936, 15102290, 16915002, 16948...",0.166667,1.000,0.500000,0.703025,1.00
23,Show me products within a budget of 1800.,"[17094636, 13905652, 13905672, 13905666, 23229...","[13523706, 17226172, 13647622, 13769372, 17570...",0.000000,0.000,0.000000,0.000000,0.50
24,I need product with a Other woven design patte...,"[16379852, 16379914, 15768366]","[16379914, 15768366, 16379852, 2138931, 113798...",0.100000,1.000,1.000000,1.000000,1.00
25,Do you have anything from SERONA FABRICS in Wh...,[15917640],"[15917640, 16258082, 18845142, 18845144, 15907...",0.033333,1.000,1.000000,1.000000,1.00
26,Do you have any Green Kurta set for a festive ...,"[17140156, 16505434, 14121912, 16825614, 16707...","[17447636, 15508896, 16707970, 15258422, 15054...",0.266667,1.000,0.333333,0.589746,1.00
27,I'm looking for something Black from URBANIC f...,"[15849954, 15634138, 18929182, 15086606, 15633...","[15852292, 15632460, 16102760, 18542924, 15844...",0.100000,0.375,0.166667,0.207458,1.00
28,Show me Black products for everyday wear.,"[9440729, 18207452, 18992236, 16612058, 907371...","[14006764, 19270830, 18224860, 17351596, 19187...",0.000000,0.000,0.000000,0.000000,1.00
29,I'm looking for something Blue from Swasti for...,[18819296],"[18819296, 17403254, 17403428, 17403380, 17403...",0.033333,1.000,1.000000,1.000000,1.00
30,I need Shirt style with a Abstract printed pat...,[13244594],"[13244594, 15841446, 19195222, 12641134, 19201...",0.033333,1.000,1.000000,1.000000,0.75
31,I'm looking for products by Atsevam.,"[17754230, 17754250, 17754248, 19217168, 19217...","[17754230, 17754248, 19217170, 17584576, 19217...",0.233333,1.000,1.000000,0.976633,1.00
32,What do you have from panchhi in products and ...,"[19046346, 12003682]","[18070000, 19046346, 18175384, 19046338, 12003...",0.066667,1.000,0.500000,0.624051,1.00
33,What do you have in products under 2500?,"[11765970, 17662818, 15514544, 18068482, 16989...","[16858560, 17612960, 16172382, 18489222, 17255...",0.000000,0.000,0.000000,0.000000,1.00
34,Show me products from Indo Era.,"[14239788, 11459668, 12040868, 15520698, 12040...","[14869156, 16188740, 12122360, 16950290, 12040...",0.166667,0.625,0.333333,0.439488,1.00
35,"Show me products like ""ONLY Women Blue Straigh...",[18626222],"[18626222, 16372376, 18620390, 18626210, 19089...",0.033333,1.000,1.000000,1.000000,1.00
36,Do you have anything from Uptownie Lite in Fla...,"[17944738, 16608122, 11511460, 11425704, 13467...","[17944738, 11425706, 11425704, 13467524, 11511...",0.166667,1.000,1.000000,0.893007,1.00
37,"Can you find something similar to ""Mitera Grey...",[16950080],"[16950080, 16950094, 16316606, 16950086, 18813...",0.033333,1.000,1.000000,1.000000,1.00
38,"Do you have anything similar to ""Suta Beige & ...",[15243956],"[15243956, 14988194, 15244002, 16909578, 14988...",0.033333,1.000,1.000000,1.000000,1.00
39,"Show me options from Levis for everyday wear, ...","[18069226, 16532142, 18069298, 18069260, 16653...","[18069150, 18903336, 18903198, 18903182, 18069...",0.266667,1.000,0.200000,0.536778,1.00
40,Show me Pullover that are Black and have Solid...,"[16707678, 16124454, 13534776, 15964092, 15274...","[9478497, 15198584, 15845464, 15642616, 105754...",0.066667,0.250,0.500000,0.221472,1.00
41,I'm looking for Dress that cost no more than 5...,"[13878542, 17705690, 18365368, 16921564, 16921...","[17403640, 13843640, 17403254, 13452734, 17403...",0.000000,0.000,0.000000,0.000000,0.50
42,I'm looking for something Pink from Mitera for...,"[15012182, 11454958, 11244988, 18302880]","[11244988, 13886174, 11218670, 15012182, 18302...",0.133333,1.000,1.000000,0.839654,1.00
43,I'm looking for Pullover from max for everyday...,"[19204850, 15878996, 16156132]","[18782606, 18995122, 19204850, 19204868, 15878...",0.100000,1.000,0.333333,0.518332,0.50
44,What do you have from Roadster in products and...,"[12278640, 11987092, 8803831, 8963467, 1227865...","[14094106, 11296068, 15897498, 5447351, 140940...",0.266667,1.000,1.000000,0.801149,1.00
45,Show me Orange Saree from KALINI.,[14490860],"[14541316, 17066888, 14490860, 16915002, 16625...",0.033333,1.000,0.333333,0.500000,1.00
46,Do you have any Black Tailored jacket for sports?,[14646546],"[15789256, 14646546, 11383846, 15684018, 15849...",0.033333,1.000,0.500000,0.630930,0.75
47,Do you have anything from Roadster in Grey for...,"[13756948, 8319213, 13339544, 14954872, 103882...","[16835204, 16835178, 16835166, 13339544, 83192...",0.266667,1.000,1.000000,0.944548,1.00
48,I need Peplum with a Self design solid pattern...,[16504028],"[16931960, 4374524, 5617740, 16504028, 1851412...",0.033333,1.000,0.250000,0.430677,0.50
49,I need Peach Pullover by Madame.,[16533076],"[16533076, 18948340, 14556346, 15756110, 16512...",0.033333,1.000,1.000000,1.000000,1.00