In [1]:
import sys
sys.path.append("../../")

from retrieval.product_retriever import search_product_hybrid, metadata_extractor
from retrieval.reranker import rerank
import pandas as pd

from pathlib import Path
from html import escape
from IPython.display import HTML, display

from evaluation.eval import product_load_tests, evaluate_retrieval, context_relevance
from evaluation.classes import ContextRelevanceWrapper
from evaluation.reporting import (
    build_eval_question_report,
    build_retrieval_doc_rows,
    display_eval_question_report,
    export_retrieval_report_to_markdown,
    get_node_text,
)

/Users/ayeustsihneyeu/PythonProjects/hybrid-rag-system/.hybrag/lib/python3.14/site-packages/langchain_core/_api/deprecation.py:25: UserWarning: Core Pydantic V1 functionality isn't compatible with Python 3.14 or greater.
  from pydantic.v1.fields import FieldInfo as FieldInfoV1
/Users/ayeustsihneyeu/PythonProjects/hybrid-rag-system/.hybrag/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/Users/ayeustsihneyeu/PythonProjects/hybrid-rag-system/.hybrag/lib/python3.14/site-packages/ragas/_analytics.py:86: ResourceWarning: unclosed file <_io.TextIOWrapper name='/Users/ayeustsihneyeu/Library/Application Support/ragas/uuid.json' mode='r' encoding='UTF-8'>
  user_id = json.load(open(uuid_filepath))["userid"]
ResourceWarning: Enable tracemalloc to get the object allocation traceback

In [2]:
tests = product_load_tests()

In [3]:
def format_metadata_filters(filters):
    if filters is None:
        return "none"

    filter_items = getattr(filters, "filters", None) or []
    if not filter_items:
        return "none"

    parts = []
    for item in filter_items:
        nested_filters = getattr(item, "filters", None)
        if nested_filters is not None:
            nested_text = format_metadata_filters(item)
            condition = str(getattr(item, "condition", "or")).upper()
            parts.append(f"({nested_text}) [{condition}]")
            continue

        parts.append(
            f"{item.key} {getattr(item.operator, 'value', item.operator)} {item.value}"
        )

    return ", ".join(parts)


def retrieving(test, top_k):
    filter = metadata_extractor(query=test.question)
    context = search_product_hybrid(test.question, top_k=top_k, filters=filter)
    nodes = getattr(context, "nodes", context)
    retrieval_metadata = format_metadata_filters(filter)
    return nodes, retrieval_metadata

In [4]:
async def evaluate_all_retrieval(limit=None, top_k=5, markdown_path=None):
    
    tests = product_load_tests()
    selected_tests = tests[:limit] if limit is not None else tests
    rows = []
    question_reports = []

    for index, test in enumerate(selected_tests, start=1):
        nodes, retrieval_metadata = retrieving(test, top_k)
        
        metrics = evaluate_retrieval(test, nodes, k=top_k)
        
        result = await context_relevance(ContextRelevanceWrapper(question=test.question, contexts=[get_node_text(item) for item in nodes]))
        metrics["context_relevance"] = result
        rows.append({**metrics, "retrieval_metadata": retrieval_metadata})
        filtered_metrics = {
            key: value
            for key, value in metrics.items()
            if key.startswith("precision") or key.startswith("recall") or key == "mrr" or key.startswith("ndcg") or key == "context_relevance"
        }
        doc_rows = build_retrieval_doc_rows(nodes, test.relevant_docs)
        display_eval_question_report(
            question=test.question,
            relevant_docs=test.relevant_docs,
            metrics=filtered_metrics,
            text_blocks=[("Retrieval metadata", retrieval_metadata)],
            doc_rows=doc_rows,
            index=index,
            total=len(selected_tests),
            metric_columns=4,
        )
        question_report = build_eval_question_report(
            question=test.question,
            relevant_docs=test.relevant_docs,
            retrieved_docs=metrics["retrieved_docs"],
            doc_rows=doc_rows,
            extra_fields={"metrics": filtered_metrics, "retrieval_metadata": retrieval_metadata},
            index=index,
            total=len(selected_tests),
        )
        question_reports.append(question_report)

    
    report_df = pd.DataFrame(rows)
    metric_columns = [column for column in report_df.columns if column.startswith(("precision", "recall", "ndcg")) or column in {"mrr", "context_relevance"}]
    summary_df = report_df[metric_columns].mean().to_frame(name="mean").T.round(3)

    display(HTML("<h2 style='margin:32px 0 12px;color:#24292f;'>Final metrics</h2>"))
    display(summary_df)

    if markdown_path is not None:
        saved_path = export_retrieval_report_to_markdown(
            report_df,
            question_reports,
            Path(markdown_path),
            notebook_path="notebooks/product/09_product_metadata_retrieval.ipynb",
        )
        display(HTML(f"<p style='margin:12px 0 0;color:#1a7f37;'>Markdown report saved to: <code>{escape(str(saved_path))}</code></p>"))

    return report_df

In [5]:
await evaluate_all_retrieval(markdown_path="../../reports/product_metadata_retrieving_evaluation.md", top_k=30, limit=50)

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,16950080,-,1.0000,"brand=Mitera, color=Grey, price=5999.0",Product: Mitera Grey Embellished Sequinned Sem...
1,2,no,17413544,-,0.3415,"brand=Mitera, color=Grey, category=Saree, occa...",Product: Mitera Women Grey & Black Premium Cru...
2,3,no,19276886,-,0.1619,"brand=Mitera, color=Grey, category=Saree, occa...",Product: Mitera Grey Floral Embroidered Net Fu...
3,4,no,16615812,-,0.1325,"brand=Mitera, color=Grey, category=Saree, occa...",Product: Mitera Floral Saree With Embroidered ...
4,5,no,18302978,-,0.0691,"brand=Mitera, color=Grey, category=Banarasi, o...",Product: Mitera Grey & Silver-Toned Floral Zar...
5,6,no,16587914,-,0.0554,"brand=Mitera, color=Grey, category=Banarasi, o...",Product: Mitera Grey & Gold-Toned Woven Design...

,rank,hit,section_id,title,score,metadata,preview
0,1,no,16279046,-,0.7403,"brand=20Dresses, color=Blue, category=Regular ...",Product: 20Dresses Women Blue Trousers Brand: ...
1,2,no,14220194,-,0.6205,"brand=DressBerry, color=Burgundy, category=Reg...",Product: DressBerry Women Burgundy Trousers Br...
2,3,no,13523706,-,0.5000,"brand=Varanga, color=Black, occasion=Daily, pr...",Product: Varanga Women Black & White Geometric...
3,4,no,13647622,-,0.4860,"brand=Varanga, color=Pink, occasion=Daily, pri...",Product: Varanga Women Pink & White Leheriya P...
4,5,no,13769372,-,0.4852,"brand=Varanga, color=Black, occasion=Daily, pr...",Product: Varanga Classic Black and White Bandh...
5,6,no,11421530,-,0.4290,"brand=Ginni Arora Label, color=Red, category=R...",Product: Ginni Arora Label Women Red Slim Fit ...
6,7,no,17393956,-,0.4245,"brand=Fabindia, color=Beige, category=Regular ...",Product: Fabindia Women Beige & Red Striped Co...
7,8,no,16044098,-,0.4189,"brand=SASSAFRAS, color=Blue, category=Regular ...",Product: SASSAFRAS Women Blue Ribbed Trousers ...
8,9,no,18770032,-,0.3983,"brand=Trendyol, color=Black, category=Regular ...",Product: Trendyol Women Black High-Rise Trouse...
9,10,no,17378344,-,0.3859,"brand=Saffron Threads, color=Black, category=R...",Product: Saffron Threads Women Black Original ...
10,11,no,17625016,-,0.3823,"brand=Fabindia, color=Off White, category=Regu...",Product: Fabindia Women Off White Cotton Trous...
11,12,no,17104470,-,0.3703,"brand=Fabindia, color=Blue, category=Regular t...",Product: Fabindia Women Blue Striped Relaxed T...
12,13,no,18838354,-,0.3589,"brand=Styli, color=Multi, category=Regular tro...",Product: Styli Women Multicoloured Printed Hig...
13,14,no,19011990,-,0.3550,"brand=Trendyol, color=Blue, category=Regular t...",Product: Trendyol Women Blue Pure Cotton Solid...
14,15,no,18769616,-,0.3466,"brand=Trendyol, color=Beige, category=Regular ...",Product: Trendyol Women Beige & Brown Pure Cot...
15,16,no,17608014,-,0.3465,"brand=MANGO, color=Green, category=Regular tro...",Product: MANGO Women Green Chain Printed Trous...
16,17,no,10440556,-,0.3452,"brand=DressBerry, color=Olive, category=Regula...",Product: DressBerry Women Olive Green Regular ...
17,18,no,14220222,-,0.3442,"brand=DressBerry, color=Green, category=Regula...",Product: DressBerry Women Green Trousers Brand...
18,19,no,18770054,-,0.3432,"brand=Trendyol, color=Blue, category=Regular t...",Product: Trendyol Women Blue & Yellow Ethnic M...
19,20,no,17046802,-,0.3431,"brand=Chemistry, color=Black, category=Regular...",Product: Chemistry Women Black Pleated Trouser...
20,21,no,14514992,-,0.3420,"brand=RIVI, color=Blue, category=Regular trous...",Product: RIVI Women Blue Regular Trousers Bran...
21,22,no,17197754,-,0.3383,"brand=Mast & Harbour, color=Blue, category=Reg...",Product: Mast & Harbour Women Blue Pure Cotton...
22,23,no,18867438,-,0.3378,"brand=URBANIC, color=Black, category=Regular t...",Product: URBANIC Women Black Trousers Brand: U...
23,24,no,18811270,-,0.3357,"brand=BoStreet, color=White, category=Regular ...",Product: BoStreet Women White Loose Fit Trouse...
24,25,no,18838276,-,0.3296,"brand=Styli, color=Pink, category=Regular trou...",Product: Styli Women Pink Skinny Fit High-Rise...
25,26,no,18838318,-,0.3292,"brand=Styli, color=White, category=Regular tro...",Product: Styli Women White Tapered Fit High-Ri...
26,27,no,18838300,-,0.3284,"brand=Styli, color=Black, category=Regular tro...",Product: Styli Women Black Straight Fit High-R...
27,28,no,17830914,-,0.3252,"brand=KALINI, color=Grey, category=Regular tro...",Product: KALINI Women Grey Pleated Trousers Br...
28,29,no,17864146,-,0.3216,"brand=plusS, color=Olive, category=Regular tro...",Product: plusS Women Olive Green Trousers Bran...
29,30,no,15693320,-,0.3194,"brand=Fabindia, color=Beige, category=Regular ...",Product: Fabindia Women Beige Ethnic Trousers ...

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,11166548,-,1.0000,"brand=Athena, color=Burgundy, category=Tailore...",Product: Athena Women Burgundy Solid Tailored ...
1,2,no,10758214,-,0.0849,"brand=Athena, color=Burgundy, category=Pullove...",Product: Athena Women Burgundy Solid Pullover ...
2,3,no,12086086,-,0.0158,"brand=Athena, color=Burgundy, category=Pencil,...",Product: Athena Women Burgundy Solid Pencil Mi...
3,4,no,11634534,-,0.0058,"brand=Athena, color=Burgundy, category=Basic j...",Product: Athena Women Burgundy Solid Basic Jum...
4,5,no,11634536,-,0.0036,"brand=Athena, color=Burgundy, category=Basic j...",Product: Athena Women Burgundy Solid Basic Jum...

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,18921114,-,1.0000,"brand=InWeave, color=Red, category=A-line, occ...",Product: InWeave Women Red Printed A-Line Skir...
1,2,no,17168254,-,0.9076,"brand=InWeave, color=Red, category=A-line, occ...",Product: InWeave Women Red Printed Pure Cotton...
2,3,no,15760840,-,0.3796,"brand=InWeave, color=Red, category=Regular, oc...",Product: InWeave Red & Gold-Toned Regular Crop...
3,4,no,13497800,-,0.1076,"brand=InWeave, color=Red, category=Regular, oc...",Product: InWeave Women Red Striped A-Line Top ...
4,5,no,18922178,-,0.0765,"brand=InWeave, color=Red, occasion=Western, pr...",Product: InWeave Women Red Flared Palazzos Bra...

,rank,hit,section_id,title,score,metadata,preview
0,1,no,10451734,-,0.8545,"brand=WEAVERS VILLA, color=Mustard, occasion=D...",Product: WEAVERS VILLA Women Mustard Yellow & ...
1,2,no,19218994,-,0.6963,"brand=Mitera, color=Mustard, category=Kanjeeva...",Product: Mitera Mustard & Red Woven Design Zar...
2,3,no,18122478,-,0.6744,"brand=PERFECTBLUE, color=Mustard, category=Sar...",Product: PERFECTBLUE Mustard Yellow & Fuchsia ...
3,4,no,17663018,-,0.6605,"brand=Dupatta Bazaar, color=Mustard, occasion=...",Product: Dupatta Bazaar Mustard Yellow Ethnic ...
4,5,no,16719554,-,0.6425,"brand=Banarasi Style, color=Mustard, occasion=...",Product: Banarasi Style Mustard Woven Design D...
5,6,no,11117288,-,0.6263,"brand=Mitera, color=Mustard, category=Kanjeeva...",Product: Mitera Mustard & Pink Silk Blend Wove...
6,7,no,18135092,-,0.5665,"brand=Mitera, color=Mustard, category=Banarasi...",Product: Mitera Mustard Yellow Ethnic Motifs Z...
7,8,no,16921550,-,0.4961,"brand=Safaa, color=Mustard, category=Dress, oc...",Product: Safaa Women Mustard Woven Design Wool...
8,9,no,18141434,-,0.4889,"brand=MANOHARI, color=Mustard, category=Saree,...",Product: MANOHARI Mustard & Gold-Toned Woven D...
9,10,no,14071540,-,0.4309,"brand=DressBerry, color=Mustard, category=Fron...",Product: DressBerry Women Stylish Mustard Self...
10,11,no,19240508,-,0.4082,"brand=max, color=Mustard, occasion=Daily, pric...",Product: max Women Mustard Yellow Yoke Design ...
11,12,no,18696924,-,0.4012,"brand=RANGMANCH BY PANTALOONS, color=Mustard, ...",Product: RANGMANCH BY PANTALOONS Women Mustard...
12,13,yes,12824928,-,0.4004,"brand=DIVASTRI, color=Mustard, occasion=Festiv...",Product: DIVASTRI Mustard & Pink Woven Design ...
13,14,no,15379610,-,0.3975,"brand=Chhabra 555, color=Mustard, price=7900.0",Product: Chhabra 555 Mustard Yellow & Red Semi...
14,15,no,18196770,-,0.3935,"brand=LOOKNBOOK ART, color=Mustard, price=6800.0",Product: LOOKNBOOK ART Mustard Yellow & Red Se...
15,16,no,18509068,-,0.3909,"brand=SANGAM PRINTS, color=Mustard, category=S...",Product: SANGAM PRINTS Mustard & Golden Ethnic...
16,17,no,14402632,-,0.3885,"brand=InWeave, color=Mustard, category=A-line,...",Product: InWeave Mustard Yellow & Blue A-Line ...
17,18,no,13676084,-,0.3758,"brand=Vishudh, color=Mustard, occasion=Ethnic,...",Product: Vishudh Women Mustard Yellow Solid He...
18,19,no,15287502,-,0.3551,"brand=Mast & Harbour, color=Mustard, category=...",Product: Mast & Harbour Mustard Yellow Dobby W...
19,20,no,12130790,-,0.3546,"brand=Inddus, color=Mustard, category=Kurta se...",Product: Inddus Women Mustard Yellow & Red Wov...
20,21,no,1319900,-,0.3465,"brand=Desi Weavess, color=Mustard, price=1890.0",Product: Desi Weavess Mustard Orange & Red Pri...
21,22,no,5567866,-,0.3300,"brand=DressBerry, color=Mustard, category=Pull...",Product: DressBerry Women Mustard Yellow Self ...
22,23,no,19145502,-,0.3208,"brand=The Chennai Silks, color=Mustard, catego...",Product: The Chennai Silks Mustard & Brown Pur...
23,24,no,15019972,-,0.3190,"brand=Cayman, color=Mustard, category=Pullover...",Product: Cayman Women Mustard Yellow Self Desi...
24,25,no,14096934,-,0.3127,"brand=NEUDIS, color=Mustard, category=Pencil, ...",Product: NEUDIS Women Mustard Yellow Self Desi...
25,26,no,17138148,-,0.3081,"brand=SHECZZAR, color=Mustard, category=Pullov...",Product: SHECZZAR Women Mustard Yellow & Orang...
26,27,yes,18262088,-,0.3027,"brand=Chhabra 555, color=Mustard, price=7990.0",Product: Chhabra 555 Mustard & Red Beads and S...
27,28,no,16931650,-,0.2872,"brand=all about you, color=Mustard, category=R...",Product: all about you Mustard Yellow Self-Des...
28,29,no,14087386,-,0.2657,"brand=SASSAFRAS, color=Mustard, category=A-lin...",Product: SASSAFRAS Women Mustard Yellow & Pink...
29,30,no,18801976,-,0.2512,"brand=Mitera, color=Mustard, category=Kanjeeva...",Product: Mitera Mustard & Purple Striped Zari ...

Empty DataFrame
Columns: []
Index: []

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,11581420,-,1.0000,"brand=Sweet Dreams, color=Pink, category=Plays...",Product: Sweet Dreams Women Pink & Green Heart...
1,2,no,11581448,-,0.9252,"brand=Sweet Dreams, color=Pink, category=Plays...",Product: Sweet Dreams Women Pink & Green Heart...
2,3,yes,11581366,-,0.9240,"brand=Sweet Dreams, color=Pink, category=Plays...",Product: Sweet Dreams Women Pink & Green Heart...
3,4,no,12882594,-,0.0000,"brand=Sweet Dreams, color=Pink, category=Pullo...",Product: Sweet Dreams Women Peach-Coloured & B...

,rank,hit,section_id,title,score,metadata,preview
0,1,no,13799826,-,0.9755,"brand=Vishudh, color=Grey, category=Kurta set,...",Product: Vishudh Women Grey & Gold-Coloured Ch...
1,2,no,14860664,-,0.9470,"brand=Vishudh, color=Black, category=Kurta set...",Product: Vishudh Women Black Regular Printed K...
2,3,yes,13536726,-,0.9397,"brand=Vishudh, color=Yellow, category=Kurta se...",Product: Vishudh Women Yellow & Off-White Prin...
3,4,no,7572969,-,0.9296,"brand=Vishudh, color=Red, category=Kurta set, ...",Product: Vishudh Women Red & Orange Self Desig...
4,5,yes,15997054,-,0.9244,"brand=Vishudh, color=Yellow, category=Kurta se...",Product: Vishudh Women Yellow Floral Embroider...
5,6,no,9867983,-,0.9057,"brand=Vishudh, color=Navy Blue, category=Kurta...",Product: Vishudh Women Navy Blue Floral Printe...
6,7,no,7572958,-,0.8915,"brand=Vishudh, color=Mauve, category=Kurta set...",Product: Vishudh Women Mauve Regular Kurta wit...
7,8,yes,13119222,-,0.8912,"brand=Vishudh, color=Black, category=Kurta set...",Product: Vishudh Women Black & Off-White Check...
8,9,no,13433674,-,0.8783,"brand=Vishudh, color=Sea Green, category=Kurta...",Product: Vishudh Women Sea Green & White Print...
9,10,yes,18929144,-,0.8322,"brand=Vishudh, color=Purple, category=Kurta se...",Product: Vishudh Women Purple Ethnic Straight ...
10,11,no,16858486,-,0.8275,"brand=Vishudh, color=Red, category=Kurta set, ...",Product: Vishudh Women Red Embroidered Pure Co...
11,12,no,17656860,-,0.8273,"brand=Vishudh, color=Turquoise Blue, category=...",Product: Vishudh Women Turquoise Blue Floral P...
12,13,yes,18262138,-,0.8221,"brand=Vishudh, color=Yellow, category=Kurta se...",Product: Vishudh Women Yellow & Grey Ethnic Mo...
13,14,no,13975624,-,0.8067,"brand=Vishudh, color=Off White, category=Kurta...",Product: Vishudh Women Off-White Checked Kurta...
14,15,yes,15639890,-,0.7978,"brand=Vishudh, color=Green, category=Kurta set...",Product: Vishudh Women Green & White Floral Pr...
15,16,yes,15820432,-,0.7907,"brand=Vishudh, color=Off White, category=Kurta...",Product: Vishudh Women Off White Embroidered R...
16,17,no,18929396,-,0.7842,"brand=Vishudh, color=Pink, category=Kurta set,...",Product: Vishudh Women Pink Thread Work Kurta ...
17,18,no,18261878,-,0.7791,"brand=Vishudh, color=Blue, category=Kurta set,...",Product: Vishudh Women Blue Floral Printed Kur...
18,19,no,16123926,-,0.7757,"brand=Vishudh, color=Mauve, category=Kurta set...",Product: Vishudh Women Mauve Floral Embroidere...
19,20,no,9673749,-,0.7756,"brand=Vishudh, color=Turquoise Blue, category=...",Product: Vishudh Women Turquoise Blue & Gold-T...
20,21,yes,18263032,-,0.7748,"brand=Vishudh, color=Green, category=Kurta set...",Product: Vishudh Women Checked Pure Cotton Kur...
21,22,no,17445358,-,0.7562,"brand=Vishudh, color=Purple, category=Kurta se...",Product: Vishudh Women Purple Printed Kurta wi...
22,23,no,15335772,-,0.7513,"brand=Vishudh, color=Yellow, category=Kurta se...",Product: Vishudh Women Yellow Striped Regular ...
23,24,no,18688392,-,0.7417,"brand=Vishudh, color=Red, category=Kurta set, ...",Product: Vishudh Women Printed Kurta with Dupa...
24,25,no,17132180,-,0.7190,"brand=Vishudh, color=Black, category=Kurta set...",Product: Vishudh Women Black & Teal Blue Check...
25,26,no,18929148,-,0.4960,"brand=Vishudh, color=Turquoise Blue, category=...",Product: Vishudh Women Turquoise Blue Pleated ...
26,27,no,836967,-,0.4660,"brand=Vishudh, color=White, occasion=Casual, p...",Product: Vishudh White & Green Shirt with Skir...
27,28,no,2467322,-,0.4551,"brand=Vishudh, color=Navy Blue, occasion=Daily...",Product: Vishudh Women Navy Blue & Mustard Pri...
28,29,no,6613532,-,0.4322,"brand=Vishudh, color=Navy Blue, occasion=Daily...",Product: Vishudh Women Navy Blue Yoke Design S...
29,30,no,7334039,-,0.4225,"brand=Vishudh, color=White, occasion=Daily, pr...",Product: Vishudh Women White & Pink Printed A-...

,rank,hit,section_id,title,score,metadata,preview
0,1,no,14873856,-,0.9541,"brand=Ancestry, color=Grey, category=A-line, o...",Product: Ancestry Women Grey & White Striped A...
1,2,yes,15407228,-,0.7767,"brand=Ancestry, color=Pink, category=A-line, o...",Product: Ancestry Pink Pure Cotton Self Design...
2,3,yes,14873702,-,0.7312,"brand=Ancestry, color=Pink, category=A-line, o...",Product: Ancestry Women Pink Melange Effect Pu...
3,4,yes,19152780,-,0.5055,"brand=Ancestry, color=Pink, category=A-line, o...",Product: Ancestry Women Pink Regular Top Brand...
4,5,no,14873748,-,0.4138,"brand=Ancestry, color=Beige, occasion=Ethnic, ...",Product: Ancestry Women Taupe Embroidered Long...
5,6,no,15407188,-,0.2249,"brand=Ancestry, color=Navy Blue, occasion=Casu...",Product: Ancestry Women Navy Blue & White Pure...
6,7,no,19152792,-,0.2205,"brand=Ancestry, color=Gold, category=Tailored ...",Product: Ancestry Women Gold-Toned Longline Ta...
7,8,no,16588088,-,0.1919,"brand=Ancestry, color=Pink, category=Regular, ...",Product: Ancestry Pink & Black Ethnic Motifs P...
8,9,no,17149934,-,0.1754,"brand=Ancestry, color=Maroon, category=Tailore...",Product: Ancestry Women Maroon Crop Tailored J...
9,10,no,19152772,-,0.0799,"brand=Ancestry, color=Mustard, occasion=Party,...",Product: Ancestry Mustard Embroidered Organza ...
10,11,no,17326880,-,0.0466,"brand=Ancestry, color=Pink, category=Parallel ...",Product: Ancestry Women Pink Regular Fit Pleat...
11,12,no,15407164,-,0.0138,"brand=Ancestry, color=White, category=Shirt st...",Product: Ancestry White & Red Pure Cotton Geom...

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,19140952,-,1.0000,"brand=FASHOR, color=Blue, occasion=Daily, pric...",Product: FASHOR Women Blue Geometric Printed G...
1,2,no,18964098,-,0.4267,"brand=FASHOR, color=Turquoise Blue, occasion=D...",Product: FASHOR Women Turquoise Blue Geometric...
2,3,no,19198414,-,0.0640,"brand=FASHOR, color=Navy Blue, occasion=Daily,...",Product: FASHOR Women Navy Blue Floral Embroid...
3,4,no,19324632,-,0.0492,"brand=FASHOR, color=Blue, occasion=Festive, pr...",Product: FASHOR Women Blue & White Yoke Design...

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,14460680,-,1.0,"brand=Darzi, color=Blue, category=Tailored jac...",Product: Darzi Women Blue Tailored Jacket Bran...
1,2,no,17665702,-,0.0,"brand=Darzi, color=Navy Blue, category=Bomber,...",Product: Darzi Women Navy Blue Colourblocked F...

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,13703470,-,1.0,"brand=U.S. Polo Assn., color=Beige, category=B...",Product: U.S. Polo Assn. Women Beige Solid Bik...

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,15637468,-,1.0000,"brand=Mitera, color=Yellow, category=Bandhani,...",Product: Mitera Yellow & Multicoloured Floral ...
1,2,no,17325496,-,0.4884,"brand=Mitera, color=Green, category=Dress, occ...",Product: Mitera Green & Off-White Embroidered ...
2,3,no,17325492,-,0.4883,"brand=Mitera, color=Green, category=Dress, occ...",Product: Mitera Green & Golden Embroidered Uns...
3,4,no,17325498,-,0.4801,"brand=Mitera, color=Maroon, category=Dress, oc...",Product: Mitera Maroon & Golden Embroidered Un...
4,5,no,17325490,-,0.4743,"brand=Mitera, color=Black, category=Dress, occ...",Product: Mitera Black & Golden Embroidered Uns...
5,6,no,17392504,-,0.4677,"brand=Mitera, color=Blue, category=Kanjeevaram...",Product: Mitera Blue & Gold-Toned Ethnic Motif...
6,7,no,16595928,-,0.4543,"brand=Mitera, color=Maroon, category=Saree, oc...",Product: Mitera Maroon & Golden Ethnic Motifs ...
7,8,no,11530694,-,0.4250,"brand=Mitera, color=Peach, occasion=Festive, p...",Product: Mitera Peach-Coloured & Gold-Toned Em...
8,9,no,16588146,-,0.3992,"brand=Mitera, color=Blue, category=Saree, occa...",Product: Mitera Blue & Purple Ethnic Motifs Si...
9,10,no,18189984,-,0.3929,"brand=Mitera, color=Green, category=Saree, occ...",Product: Mitera Leheriya Saree with Woven Desi...
10,11,no,13515386,-,0.3885,"brand=Mitera, color=Mustard, occasion=Festive,...",Product: Mitera Mustard Yellow & Red Embroider...
11,12,no,16286084,-,0.3823,"brand=Mitera, color=Black, category=Dress, occ...",Product: Mitera Black & Gold-Toned Unstitched ...
12,13,no,18647316,-,0.3668,"brand=Mitera, color=Blue, category=Saree, occa...",Product: Mitera Blue & Black Embellished Sequi...
13,14,no,17206828,-,0.3667,"brand=Mitera, color=Black, category=Dress, occ...",Product: Mitera Black & Beige Embroidered Unst...
14,15,no,16286120,-,0.3554,"brand=Mitera, color=Red, category=Dress, occas...",Product: Mitera Red & Green Silk Blend Unstitc...
15,16,no,16171474,-,0.3547,"brand=Mitera, color=Red, category=Dress, occas...",Product: Mitera Red & Gold-Toned Dupion Silk B...
16,17,no,12668502,-,0.3533,"brand=Mitera, color=Pink, occasion=Festive, pr...",Product: Mitera Pink & Blue Woven Design Semi-...
17,18,no,12668552,-,0.3521,"brand=Mitera, color=Turquoise Blue, occasion=F...",Product: Mitera Turquoise Blue & Red Woven Des...
18,19,no,18302882,-,0.3448,"brand=Mitera, color=Teal, category=Saree, occa...",Product: Mitera Teal & Gold-Toned Woven Design...
19,20,no,15480316,-,0.3441,"brand=Mitera, color=Teal, category=Saree, occa...",Product: Mitera Teal Blue Sequinned Ready to W...
20,21,no,18107770,-,0.3357,"brand=Mitera, color=Orange, category=Saree, oc...",Product: Mitera Orange & Gold-Toned Embellishe...
21,22,no,15012204,-,0.3255,"brand=Mitera, color=Pink, category=Banarasi, o...",Product: Mitera Pink & Gold-Toned Woven Design...
22,23,no,14479084,-,0.3243,"brand=Mitera, color=Red, category=Saree, occas...",Product: Mitera Red & Gold-Toned Zari Silk Ble...
23,24,no,16967652,-,0.3135,"brand=Mitera, color=Gold, category=Saree, occa...",Product: Mitera Gold-Toned & Pink Woven Design...
24,25,no,18121996,-,0.3109,"brand=Mitera, color=Red, category=Saree, occas...",Product: Mitera Red Striped Sequinned Organza ...
25,26,no,18656200,-,0.3036,"brand=Mitera, color=Yellow, category=Saree, oc...",Product: Mitera Yellow & Brown Embellished Seq...
26,27,no,16967650,-,0.3014,"brand=Mitera, color=Beige, category=Saree, occ...",Product: Mitera Beige & Red Ethnic Motifs Zari...
27,28,no,16286118,-,0.2999,"brand=Mitera, color=Navy Blue, category=Dress,...",Product: Mitera Navy Blue & Red Unstitched Dre...
28,29,no,18585472,-,0.2874,"brand=Mitera, color=Black, category=Saree, occ...",Product: Mitera Black & Pink Floral Pure Linen...
29,30,no,16576216,-,0.2810,"brand=Mitera, color=Red, category=Banarasi, oc...",Product: Mitera Red & Golden Ethnic Motifs Ban...

,rank,hit,section_id,title,score,metadata,preview
0,1,no,14011652,-,0.7973,"brand=FableStreet, color=Black, category=Penci...",Product: FableStreet Black Mini Pencil Skirt B...
1,2,no,1294879,-,0.7672,"brand=Purple Feather, color=Black, category=Pe...",Product: Purple Feather Black Pencil Skirt Wit...
2,3,no,18215398,-,0.6947,"brand=Popwings, color=Camel Brown, category=Pe...",Product: Popwings Women Camel Brown Pencil Sli...
3,4,no,14798956,-,0.6868,"brand=Trendyol, color=Taupe, category=Pencil, ...",Product: Trendyol Women Taupe Solid Pencil Mid...
4,5,no,17899166,-,0.6707,"brand=PATRORNA, color=Green, category=Pencil, ...",Product: PATRORNA Women Green Solid Pencil Abo...
5,6,no,14372466,-,0.6644,"brand=Chemistry, color=Black, category=Pencil,...",Product: Chemistry Black Pure Cotton Ribbed Mi...
6,7,no,17739956,-,0.6351,"brand=Kotty, color=Black, category=Pencil, occ...",Product: Kotty Women Black Solid Faux Leather ...
7,8,no,13496046,-,0.6197,"brand=FableStreet, color=Olive, category=Penci...",Product: FableStreet Olive Green Knitted Penci...
8,9,no,17931744,-,0.6126,"brand=PATRORNA, color=Green, category=Pencil, ...",Product: PATRORNA Women Green & Black Solid Kn...
9,10,no,19072638,-,0.6080,"brand=DRAAX Fashions, color=Maroon, category=P...",Product: DRAAX Fashions Women Maroon Solid Min...
10,11,no,17403200,-,0.6045,"brand=BROADSTAR, color=Black, category=Pencil,...",Product: BROADSTAR Women Black Solid Pencil Mi...
11,12,no,19181106,-,0.5933,"brand=Bitterlime, color=Olive, category=Pencil...",Product: Bitterlime Women Olive Green & Black ...
12,13,no,18215396,-,0.5891,"brand=Popwings, color=Black, category=Pencil, ...",Product: Popwings Women Above Knee-Length Blac...
13,14,no,17306262,-,0.5836,"brand=Purple Feather, color=Black, category=Pe...",Product: Purple Feather Women Black Solid Stre...
14,15,no,17927414,-,0.5713,"brand=PATRORNA, color=Sea Green, category=Penc...",Product: PATRORNA Women Sea Green Solid Above ...
15,16,no,17899190,-,0.5638,"brand=PATRORNA, color=Purple, category=Pencil,...",Product: PATRORNA Women Purple Solid Pencil Ab...
16,17,no,17898168,-,0.5568,"brand=PATRORNA, color=Black, category=Pencil, ...",Product: PATRORNA Women Black Solid Knee Lengt...
17,18,no,17365546,-,0.5441,"brand=BROADSTAR, color=Black, category=Pencil,...",Product: BROADSTAR Women Black Solid Pencil Kn...
18,19,no,17795314,-,0.5387,"brand=Trend Arrest, color=Navy Blue, category=...",Product: Trend Arrest Women Navy Blue Sequence...
19,20,no,18034350,-,0.5376,"brand=Missguided, color=Olive, category=Pencil...",Product: Missguided Women Olive Green Solid Mi...
20,21,no,14024850,-,0.5293,"brand=OTORVA, color=Blue, category=Pencil, occ...",Product: OTORVA Women Denim Blue Solid Pencil ...
21,22,no,18841536,-,0.5286,"brand=Styli, color=Burgundy, category=Pencil, ...",Product: Styli Women Burgundy Solid Pencil Ski...
22,23,no,15315920,-,0.5222,"brand=MANGO, color=Green, category=Pencil, occ...",Product: MANGO Women Mint Green Solid Pure Cot...
23,24,no,18977850,-,0.5163,"brand=Popwings, color=Black, category=Pencil, ...",Product: Popwings Women Black Solid Pencil Ski...
24,25,no,12086090,-,0.5141,"brand=Athena, color=Pink, category=Pencil, occ...",Product: Athena Women Pink Solid Midi Pencil S...
25,26,no,17694094,-,0.5124,"brand=Antheaa, color=Black, category=Pencil, o...",Product: Antheaa Women Black Embellished Penci...
26,27,no,18629568,-,0.4955,"brand=IX IMPRESSION, color=Gold, category=Penc...",Product: IX IMPRESSION Women Gold Solid Pencil...
27,28,no,18173820,-,0.4830,"brand=Kotty, color=Brown, category=Pencil, occ...",Product: Kotty Women Brown Solid Faux Leather ...
28,29,no,14270952,-,0.4765,"brand=NEUDIS, color=Black, category=Pencil, oc...",Product: NEUDIS Women Pack Of 2 Solid Velvet P...
29,30,no,16042324,-,0.4748,"brand=STYL CO., color=Green, category=Pencil, ...",Product: STYL CO. Women Green & Orange Graphic...

,rank,hit,section_id,title,score,metadata,preview
0,1,no,18456682,-,0.8136,"brand=Fabindia, color=Mustard, occasion=Daily,...",Product: Fabindia Women Mustard Yellow Pure Co...
1,2,no,10451734,-,0.7408,"brand=WEAVERS VILLA, color=Mustard, occasion=D...",Product: WEAVERS VILLA Women Mustard Yellow & ...
2,3,no,17090522,-,0.7397,"brand=Anouk, color=Mustard, occasion=Daily, pr...",Product: Anouk Women Mustard Yellow Pathani Ku...
3,4,no,2076112,-,0.7365,"brand=Vishudh, color=Mustard, occasion=Daily, ...",Product: Vishudh Women Mustard Yellow Floral P...
4,5,no,18198270,-,0.6501,"brand=Biba, color=Mustard, occasion=Daily, pri...",Product: Biba Women Mustard Yellow & Pink Flor...
5,6,no,17044784,-,0.6492,"brand=Studio Shringaar, color=Mustard, occasio...",Product: Studio Shringaar Mustard Yellow Embro...
6,7,no,13337668,-,0.6434,"brand=Kvsfab, color=Mustard, category=Dress, o...",Product: Kvsfab Mustard Yellow & Off-White Emb...
7,8,no,12413214,-,0.6431,"brand=Varanga, color=Mustard, occasion=Daily, ...",Product: Varanga Women Mustard Yellow Floral Y...
8,9,no,17455814,-,0.6353,"brand=Anouk, color=Mustard, category=Kurta set...",Product: Anouk Women Mustard Yellow Ethnic Mot...
9,10,no,17096082,-,0.5980,"brand=Anouk, color=Mustard, occasion=Daily, pr...",Product: Anouk Women Mustard Yellow Geometric ...
10,11,no,14925332,-,0.5979,"brand=Anouk, color=Mustard, occasion=Daily, pr...",Product: Anouk Women Mustard Yellow & Red Geom...
11,12,no,17094636,-,0.5835,"brand=Anouk, color=Mustard, occasion=Daily, pr...",Product: Anouk Women Mustard Yellow & White Ch...
12,13,no,13861554,-,0.5575,"brand=mf, color=Mustard, category=Dress, occas...",Product: mf Mustard & Pink Cotton Blend Unstit...
13,14,no,10513948,-,0.5573,"brand=Anubhutee, color=Mustard, occasion=Daily...",Product: Anubhutee Women Mustard Yellow & Brow...
14,15,no,19240508,-,0.5487,"brand=max, color=Mustard, occasion=Daily, pric...",Product: max Women Mustard Yellow Yoke Design ...
15,16,no,13381632,-,0.5295,"brand=Yuris, color=Mustard, category=Kurta set...",Product: Yuris Women Mustard Yellow & Pink Pur...
16,17,no,15781530,-,0.4941,"brand=max, color=Mustard, occasion=Daily, pric...",Product: max Mustard Viscose Rayon Dupatta Bra...
17,18,no,18696924,-,0.4852,"brand=RANGMANCH BY PANTALOONS, color=Mustard, ...",Product: RANGMANCH BY PANTALOONS Women Mustard...
18,19,no,18874302,-,0.4830,"brand=SHANVIKA, color=Mustard, category=Block ...",Product: SHANVIKA Mustard Ethnic Motifs Pure C...
19,20,no,17480778,-,0.4496,"brand=SALWAR STUDIO, color=Mustard, category=D...",Product: SALWAR STUDIO Mustard & Brown Printed...
20,21,no,17104804,-,0.4434,"brand=Anouk, color=Mustard, category=Kurta set...",Product: Anouk Women Mustard Yellow Printed Pu...
21,22,no,17090232,-,0.4360,"brand=Anouk, color=Mustard, category=Kurta set...",Product: Anouk Women Mustard Yellow Solid Kaft...
22,23,no,13001114,-,0.4182,"brand=YASH GALLERY, color=Mustard, occasion=Da...",Product: YASH GALLERY Women Plus Size Mustard ...
23,24,no,18727242,-,0.4158,"brand=Clora Creation, color=Mustard, occasion=...",Product: Clora Creation Mustard & White Ethnic...
24,25,no,16719554,-,0.4030,"brand=Banarasi Style, color=Mustard, occasion=...",Product: Banarasi Style Mustard Woven Design D...
25,26,no,14224394,-,0.3890,"brand=Nayo, color=Mustard, category=Kurta set,...",Product: Nayo Women Mustard Printed Straight K...
26,27,no,19040576,-,0.3747,"brand=KARAJ JAIPUR, color=Mustard, category=Ku...",Product: KARAJ JAIPUR Women Mustard Yellow Yok...
27,28,no,18431602,-,0.3641,"brand=SHAVYA, color=Mustard, category=Dress, o...",Product: SHAVYA Mustard & Blue Printed Unstitc...
28,29,no,10265397,-,0.3588,"brand=Saadgi, color=Mustard, occasion=Daily, p...",Product: Saadgi Mustard Yellow Gotta Patti Dup...
29,30,no,15892784,-,0.3587,"brand=HERE&NOW, color=Mustard, category=Kurta ...",Product: HERE&NOW Women Mustard Yellow & Black...

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,13071994,-,1.0000,"brand=STREET 9, color=Blue, category=Joggers, ...",Product: STREET 9 Women Blue Regular Fit Solid...
1,2,yes,13038932,-,0.9682,"brand=STREET 9, color=Blue, category=Joggers, ...",Product: STREET 9 Women Blue Regular Fit Solid...
2,3,no,5389019,-,0.5738,"brand=STREET 9, color=Blue, category=Culotte j...",Product: STREET 9 Women Blue Striped Culotte J...
3,4,no,15803276,-,0.4885,"brand=STREET 9, color=Blue, category=Basic jum...",Product: STREET 9 Blue Basic Jumpsuit Brand: S...
4,5,no,6608510,-,0.4507,"brand=STREET 9, color=Navy Blue, category=Basi...",Product: STREET 9 Navy Blue Solid Basic Jumpsu...
5,6,no,12277584,-,0.4359,"brand=STREET 9, color=Navy Blue, category=Carg...",Product: STREET 9 Women Navy Blue Regular Fit ...
6,7,no,12693476,-,0.3405,"brand=STREET 9, color=Blue, occasion=Casual, p...",Product: STREET 9 Women Blue Straight Fit Mid-...
7,8,no,12693490,-,0.3360,"brand=STREET 9, color=Blue, occasion=Casual, p...",Product: STREET 9 Women Blue Straight Fit Mid-...
8,9,no,9781829,-,0.3191,"brand=STREET 9, color=Blue, category=A-line, o...",Product: STREET 9 Blue Denim Pleated Mini A-Li...
9,10,no,13041492,-,0.2693,"brand=STREET 9, color=Blue, category=Pullover,...",Product: STREET 9 Women Blue Solid Sweatshirt ...
10,11,no,13038878,-,0.2687,"brand=STREET 9, color=Blue, category=Pullover,...",Product: STREET 9 Women Blue Solid Sweatshirt ...
11,12,no,14136072,-,0.2676,"brand=STREET 9, color=Blue, category=Parallel ...",Product: STREET 9 Women Blue Flared Faded Para...
12,13,no,12682016,-,0.2634,"brand=STREET 9, color=Blue, occasion=Casual, p...",Product: STREET 9 Women Blue Skinny Fit Mid-Ri...
13,14,no,12682038,-,0.2530,"brand=STREET 9, color=Blue, occasion=Casual, p...",Product: STREET 9 Women Blue Skinny Fit Mid-Ri...
14,15,no,17904100,-,0.2508,"brand=STREET 9, color=Blue, occasion=Casual, p...",Product: STREET 9 Women Blue Hottie Relaxed Fi...
15,16,no,15884810,-,0.2490,"brand=STREET 9, color=Navy Blue, category=Dres...",Product: STREET 9 Navy Blue Satin Midi Dress B...
16,17,no,14136188,-,0.2379,"brand=STREET 9, color=Blue, occasion=Casual, p...",Product: STREET 9 Women Blue Relaxed Fit Mid-R...
17,18,no,13738560,-,0.1587,"brand=STREET 9, color=Turquoise Blue, category...",Product: STREET 9 Women Turquoise Blue Lightwe...
18,19,no,14136152,-,0.1563,"brand=STREET 9, color=Navy Blue, category=Basi...",Product: STREET 9 Women Navy Blue Solid Cotton...
19,20,no,18497968,-,0.1149,"brand=STREET 9, color=Blue, category=Top, occa...",Product: STREET 9 Women Blue & Red Printed Pur...
20,21,no,14136180,-,0.1078,"brand=STREET 9, color=Navy Blue, category=Play...",Product: STREET 9 Women Navy Blue Solid Denim ...
21,22,no,13904884,-,0.0360,"brand=STREET 9, color=Navy Blue, category=Regu...",Product: Street 9 Navy Blue Embellished Halter...
22,23,no,17637532,-,0.0148,"brand=STREET 9, color=Turquoise Blue, category...",Product: STREET 9 Women Enchanting Turquoise B...

,rank,hit,section_id,title,score,metadata,preview
0,1,no,14382336,-,0.5512,"brand=DressBerry, color=Pink, category=Front-o...",Product: DressBerry Women Pink Melange Effect ...
1,2,no,16082246,-,0.5000,"brand=plusS, color=Grey, category=Front-open, ...",Product: plusS Women Grey Hooded Sweatshirt Br...
2,3,no,17685090,-,0.5000,"brand=BUY NEW TREND, color=Red, category=Open ...",Product: BUY NEW TREND Women Red Black Colourb...
3,4,no,19087856,-,0.4903,"brand=ONLY, color=Beige, category=Front-open, ...",Product: ONLY Women Beige & Navy Blue Colourbl...
4,5,no,2223198,-,0.4367,"brand=W, color=Red, category=Front-open, occas...",Product: W Women Red Solid Front-Open Longline...
5,6,no,11952000,-,0.4314,"brand=DressBerry, color=Navy Blue, category=Fr...",Product: DressBerry Women Navy Blue Ribbed Lon...
6,7,no,7736701,-,0.4277,"brand=W, color=Teal, category=Front-open, occa...",Product: W Women Teal Blue Solid Front-Open Lo...
7,8,no,14071540,-,0.4065,"brand=DressBerry, color=Mustard, category=Fron...",Product: DressBerry Women Stylish Mustard Self...
8,9,no,15844140,-,0.4034,"brand=URBANIC, color=Grey, category=Front-open...",Product: URBANIC Women Grey & Black Colourbloc...
9,10,no,15137944,-,0.3868,"brand=AND, color=Black, category=Open front ja...",Product: AND Women Black & White Geometric Ope...
10,11,no,13523706,-,0.3229,"brand=Varanga, color=Black, occasion=Daily, pr...",Product: Varanga Women Black & White Geometric...
11,12,no,15353040,-,0.3213,"brand=ether, color=Maroon, category=Front-open...",Product: ether Women Maroon Solid Front Open S...
12,13,no,14210706,-,0.3203,"brand=MANGO, color=Peach, category=Front-open,...",Product: MANGO Women Peach-Coloured Solid Open...
13,14,no,15413660,-,0.3165,"brand=Cayman, color=Black, category=Front-open...",Product: Cayman Women Black & Beige Longline F...
14,15,no,12524642,-,0.3159,"brand=MANGO, color=Olive, category=Front-open,...",Product: MANGO Women Olive Green Solid Longlin...
15,16,no,11973294,-,0.3123,"brand=Mast & Harbour, color=Pink, category=Fro...",Product: Mast & Harbour Women Dusty Pink Shimm...
16,17,no,13647622,-,0.3092,"brand=Varanga, color=Pink, occasion=Daily, pri...",Product: Varanga Women Pink & White Leheriya P...
17,18,no,13769372,-,0.3085,"brand=Varanga, color=Black, occasion=Daily, pr...",Product: Varanga Classic Black and White Bandh...
18,19,no,15415146,-,0.3061,"brand=Flying Machine, color=Charcoal, category...",Product: Flying Machine Women Charcoal Typogra...
19,20,no,18210214,-,0.2905,"brand=FABRIC FITOOR, color=Black, category=Kaf...",Product: FABRIC FITOOR Black Pure Cotton Print...
20,21,no,2322431,-,0.2839,"brand=Hypernation, color=Navy Blue, occasion=C...",Product: Hypernation Navy Blue Solid Open Fron...
21,22,no,7811561,-,0.2820,"brand=Hypernation, color=Orange, occasion=Casu...",Product: Hypernation Orange Solid Open Front S...
22,23,no,15415116,-,0.2802,"brand=Flying Machine, color=Blue, category=Fro...",Product: Flying Machine Women Blue Solid Mock-...
23,24,no,8928317,-,0.2745,"brand=Hypernation, color=Rust, occasion=Casual...",Product: Hypernation Rust Brown Solid Open Fro...
24,25,no,11102094,-,0.2651,"brand=Alcis, color=Charcoal, category=Front-op...",Product: Alcis Women Charcoal Grey Solid Hoode...
25,26,no,16154282,-,0.2635,"brand=JC Mode, color=Brown, category=Open fron...",Product: JC Mode Women Brown Open Front Jacket...
26,27,yes,16382036,-,0.2395,"brand=Vero Moda, color=Cream, category=Front-o...",Product: Vero Moda Women Cream-Coloured Longli...
27,28,no,16044812,-,0.2321,"brand=Forever New, color=Green, occasion=Casua...",Product: Forever New Women Green Solid Comfort...
28,29,no,17685350,-,0.2257,"brand=BUY NEW TREND, color=Maroon, category=Op...",Product: BUY NEW TREND Women Maroon Lightweigh...
29,30,no,17226172,-,0.2251,"brand=SHOWOFF, color=Orange, occasion=Casual, ...",Product: SHOWOFF Women Orange Mom Fit High-Ris...

Empty DataFrame
Columns: []
Index: []

,rank,hit,section_id,title,score,metadata,preview
0,1,no,17403640,-,0.5000,"brand=I Saw It First, color=Khaki, occasion=Ca...",Product: I Saw It First Women Khaki Crinkled T...
1,2,no,2117164,-,0.5000,"brand=Noi, color=Cream, occasion=Daily, price=...",Product: Noi Cream-Coloured & Brown Printed Sh...
2,3,no,17403254,-,0.4854,"brand=I Saw It First, color=Blue, occasion=Cas...",Product: I Saw It First Women Blue Skinny Fit ...
3,4,no,13452734,-,0.4829,"brand=I AM FOR YOU, color=Green, occasion=West...",Product: I AM FOR YOU Women Green & Grey Print...
4,5,no,17403434,-,0.4770,"brand=I Saw It First, color=White, category=Pl...",Product: I Saw It First Women White & Blue Flo...
5,6,no,17365722,-,0.4736,"brand=I Saw It First, color=Beige, category=Re...",Product: I Saw It First Women Beige Striped Hi...
6,7,no,17403428,-,0.4720,"brand=I Saw It First, color=Blue, occasion=Cas...",Product: I Saw It First Women Blue Skinny Fit ...
7,8,no,14159320,-,0.4667,"brand=I AM FOR YOU, color=Yellow, category=A-l...",Product: I AM FOR YOU Women Yellow & White Emb...
8,9,no,17403380,-,0.4655,"brand=I Saw It First, color=Blue, occasion=Cas...",Product: I Saw It First Women Blue Slash Knee ...
9,10,no,17403300,-,0.4620,"brand=I Saw It First, color=Blue, occasion=Cas...",Product: I Saw It First Women Blue Light Fade ...
10,11,no,17365728,-,0.4588,"brand=I Saw It First, color=Pink, category=Fla...",Product: I Saw It First Women Dusty Pink & Whi...
11,12,no,17365720,-,0.4521,"brand=I Saw It First, color=Green, category=Fl...",Product: I Saw It First Women Green Solid Plea...
12,13,no,17570416,-,0.3625,"brand=SHOWOFF, color=Black, occasion=Casual, p...",Product: SHOWOFF Women Black Straight Fit Stre...
13,14,no,19097390,-,0.3529,"brand=I Love She, color=White, category=Regula...",Product: I Love She Women White Relaxed High-R...
14,15,no,18245104,-,0.3498,"brand=Miss Chase, color=Blue, occasion=Casual,...",Product: Miss Chase Women Blue Jogger High-Ris...
15,16,no,18142614,-,0.3495,"brand=SHOWOFF, color=Lavender, occasion=Casual...",Product: SHOWOFF Women Lavender Jogger High-Ri...
16,17,no,14925780,-,0.3480,"brand=Roadster, color=Blue, occasion=Casual, p...",Product: Roadster Women Blue Wide Leg Stretcha...
17,18,no,12629360,-,0.3412,"brand=Roadster, color=Rust, occasion=Casual, p...",Product: Roadster Women Rust Red Regular Fit M...
18,19,no,18245110,-,0.3411,"brand=Miss Chase, color=Blue, occasion=Casual,...",Product: Miss Chase Women Blue High-Rise Mildl...
19,20,no,19097392,-,0.3364,"brand=I Love She, color=Maroon, category=Regul...",Product: I Love She Women Maroon Relaxed Skinn...
20,21,no,14954878,-,0.3358,"brand=Roadster, color=Charcoal, occasion=Casua...",Product: Roadster Women Charcoal Mid-Rise Stra...
21,22,no,11284776,-,0.3319,"brand=Mast & Harbour, color=Blue, occasion=Cas...",Product: Mast & Harbour Women Blue Mid-Rise Cl...
22,23,no,17570328,-,0.3312,"brand=SHOWOFF, color=Blue, occasion=Casual, pr...",Product: SHOWOFF Women Blue Wide Leg High-Rise...
23,24,no,17570364,-,0.3267,"brand=SHOWOFF, color=Blue, occasion=Casual, pr...",Product: SHOWOFF Women Blue Straight Fit High-...
24,25,no,16524266,-,0.3267,"brand=LOOKNBOOK ART, color=Orange, price=4500.0",Product: LOOKNBOOK ART Orange Semi-Stitched Le...
25,26,no,13878270,-,0.3141,"brand=High Star, color=Blue, occasion=Casual, ...",Product: High Star Women Blue Straight Fit Hig...
26,27,no,15559842,-,0.3080,"brand=High Star, color=Grey, occasion=Casual, ...",Product: High Star Women Grey Jogger High-Rise...
27,28,no,15474590,-,0.3058,"brand=High Star, color=Rust, occasion=Casual, ...",Product: High Star Women Rust Jogger High-Rise...
28,29,no,15266700,-,0.2160,"brand=max, color=Beige, occasion=Daily, price=...",Product: max Beige Pure Cotton Dupatta Brand: ...
29,30,no,15312982,-,0.2086,"brand=LOOKNBOOK ART, color=Black, price=3900.0",Product: LOOKNBOOK ART Black & Beige Embellish...

,rank,hit,section_id,title,score,metadata,preview
0,1,no,9430121,-,0.9775,"brand=Bhama Couture, color=Black, category=A-l...",Product: Bhama Couture Black Embroidered A-Lin...
1,2,no,9430115,-,0.9654,"brand=Bhama Couture, color=Navy Blue, category...",Product: Bhama Couture Women Navy Blue Embroid...
2,3,no,13969870,-,0.9651,"brand=Bhama Couture, color=Navy Blue, category...",Product: Bhama Couture Navy Blue & Red Embroid...
3,4,no,11672988,-,0.9621,"brand=Bhama Couture, color=White, category=A-l...",Product: Bhama Couture Women White & Green Flo...
4,5,no,9717189,-,0.9509,"brand=Bhama Couture, color=Navy Blue, category...",Product: Bhama Couture Women Navy Blue Embroid...
5,6,yes,10355827,-,0.9470,"brand=Bhama Couture, color=Blue, category=A-li...",Product: Bhama Couture Women Blue Embroidered ...
6,7,yes,12151824,-,0.9403,"brand=Bhama Couture, color=Maroon, category=A-...",Product: Bhama Couture Women Maroon Printed A-...
7,8,no,13969820,-,0.9316,"brand=Bhama Couture, color=Maroon, category=A-...",Product: Bhama Couture Maroon & Black Embroide...
8,9,no,8339967,-,0.9197,"brand=Bhama Couture, color=Red, category=A-lin...",Product: Bhama Couture Women Red Embroidered D...
9,10,yes,12151804,-,0.9125,"brand=Bhama Couture, color=Blue, category=A-li...",Product: Bhama Couture Women Blue & Pink Flora...
10,11,yes,10356731,-,0.9057,"brand=Bhama Couture, color=Blue, category=A-li...",Product: Bhama Couture Women Blue Embroidered ...
11,12,no,11625546,-,0.8992,"brand=Bhama Couture, color=Red, category=A-lin...",Product: Bhama Couture Women Red & White Strip...
12,13,yes,10355839,-,0.8925,"brand=Bhama Couture, color=Red, category=A-lin...",Product: Bhama Couture Women Red Solid A-Line ...
13,14,yes,9430103,-,0.8885,"brand=Bhama Couture, color=Red, category=A-lin...",Product: Bhama Couture Women Red Solid A-Line ...
14,15,yes,10717820,-,0.8878,"brand=Bhama Couture, color=Navy Blue, category...",Product: Bhama Couture Women Blue Embroidered ...
15,16,yes,9430109,-,0.8661,"brand=Bhama Couture, color=Mustard, category=A...",Product: Bhama Couture Mustard Yellow A-Line P...
16,17,no,13969880,-,0.8348,"brand=Bhama Couture, color=Yellow, category=A-...",Product: Bhama Couture Yellow & White Printed ...
17,18,no,12795840,-,0.8308,"brand=Bhama Couture, color=Black, occasion=Dai...",Product: Bhama Couture Women Black & Pink Yoke...
18,19,no,10745490,-,0.7689,"brand=Bhama Couture, color=Mustard, category=A...",Product: Bhama Couture Women Mustard Yellow So...
19,20,no,4380660,-,0.7024,"brand=Bhama Couture, color=Peach, category=A-l...",Product: Bhama Couture Women Peach-Coloured Pr...
20,21,no,4380652,-,0.6883,"brand=Bhama Couture, color=Off White, category...",Product: Bhama Couture Women Off-White Printed...
21,22,no,9816649,-,0.5862,"brand=Bhama Couture, color=Red, category=Kurta...",Product: Bhama Couture Women Red Solid Kurta w...
22,23,no,10343559,-,0.5562,"brand=Bhama Couture, color=Blue, category=Kurt...",Product: Bhama Couture Women Blue & White Band...
23,24,no,1823751,-,0.5486,"brand=Bhama Couture, color=Black, occasion=Eth...",Product: Bhama Couture Black Tunic with Embroi...
24,25,no,2129862,-,0.5415,"brand=Bhama Couture, color=Off White, category...",Product: Bhama Couture Women Off-White Embroid...
25,26,no,18288422,-,0.5309,"brand=Bhama Couture, color=Off White, occasion...",Product: Bhama Couture Women Off White Floral ...
26,27,no,13969840,-,0.5229,"brand=Bhama Couture, color=White, occasion=Eth...",Product: Bhama Couture Women White & Red Embro...
27,28,no,9285083,-,0.5196,"brand=Bhama Couture, color=Mustard, category=K...",Product: Bhama Couture Women Mustard Yellow Yo...
28,29,no,15367618,-,0.5102,"brand=Bhama Couture, color=Purple, occasion=Fe...",Product: Bhama Couture Women Purple & Gold-Ton...
29,30,no,2129857,-,0.5067,"brand=Bhama Couture, color=Off White, category...",Product: Bhama Couture Women Off-White Solid P...

,rank,hit,section_id,title,score,metadata,preview
0,1,no,15749796,-,0.8652,"brand=W, color=Pink, category=Kurta set, occas...",Product: W Women Pink Striped Kurta with Trous...
1,2,no,16891228,-,0.6604,"brand=Jaipur Kurti, color=Pink, category=Kurta...",Product: Jaipur Kurti Women Pink Floral Gotta ...
2,3,no,14708328,-,0.6587,"brand=all about you, color=Pink, occasion=Dail...",Product: all about you Women Pink & Gold-Toned...
3,4,no,15582360,-,0.5663,"brand=Anouk, color=Pink, category=Kurta set, o...",Product: Anouk Women Pink Floral Embroidered P...
4,5,no,10317793,-,0.5570,"brand=Jaipur Kurti, color=Pink, category=Kurta...",Product: Jaipur Kurti Women Pink & Green Print...
5,6,no,16844726,-,0.5224,"brand=Sangria, color=Pink, category=Kurta set,...",Product: Sangria Women Pink & Blue Geometric P...
6,7,no,15445194,-,0.5000,"brand=PIRKO, color=Pink, category=Dress, occas...",Product: PIRKO Pink & Off White Printed Pure C...
7,8,no,12307502,-,0.4920,"brand=Prakhya, color=Pink, category=Kurta set,...",Product: Prakhya Women Pink Self Design Kurta ...
8,9,no,13078244,-,0.4735,"brand=W, color=Pink, occasion=Daily, price=1599.0",Product: W Women Pink Solid Straight Kurta Bra...
9,10,no,17096098,-,0.4734,"brand=Anouk, color=Pink, category=Kurta set, o...",Product: Anouk Women Pink Pure Cotton Kurta wi...
10,11,no,17090142,-,0.4638,"brand=Anouk, color=Pink, category=Kurta set, o...",Product: Anouk Women Pink Solid Kurta with Tro...
11,12,no,16872392,-,0.4602,"brand=Sangria, color=Pink, category=Kurta set,...",Product: Sangria Women Pink Printed Keyhole Ne...
12,13,no,12663796,-,0.4567,"brand=EXTRA LOVE BY LIBAS, color=Pink, categor...",Product: EXTRA LOVE BY LIBAS Plus Size Women P...
13,14,no,14949672,-,0.4552,"brand=Stylum, color=Pink, category=Kurta set, ...",Product: Stylum Women Pink Ethnic Motifs Print...
14,15,no,16874556,-,0.4485,"brand=Sangria, color=Pink, category=Kurta set,...",Product: Sangria Women Pink Printed Pure Cotto...
15,16,no,12105006,-,0.4399,"brand=Sangria, color=Pink, category=Kurta set,...",Product: Sangria Women Pink & Golden Printed P...
16,17,no,12873874,-,0.4332,"brand=Anubhutee, color=Pink, category=Kurta se...",Product: Anubhutee Women Pink & White Printed ...
17,18,no,19040404,-,0.4226,"brand=KARAJ JAIPUR, color=Pink, category=Kurti...",Product: KARAJ JAIPUR Women Pink Embroidered K...
18,19,no,15440308,-,0.3967,"brand=HERE&NOW, color=Pink, category=Kurta set...",Product: HERE&NOW Women Pink & Grey Ethnic Mot...
19,20,no,19040436,-,0.3857,"brand=KARAJ JAIPUR, color=Pink, category=Kurta...",Product: KARAJ JAIPUR Women Pink Pure Cotton A...
20,21,no,15582352,-,0.3739,"brand=Anouk, color=Pink, occasion=Daily, price...",Product: Anouk Women Pink Pure Cotton Straight...
21,22,no,13932860,-,0.3714,"brand=anayna, color=Pink, category=Kurta set, ...",Product: anayna Women Pink Printed Kurta with ...
22,23,no,19325284,-,0.3655,"brand=POONAM DESIGNER, color=Pink, occasion=Da...",Product: POONAM DESIGNER Women Pink Ethnic Mot...
23,24,no,17094694,-,0.3616,"brand=Anouk, color=Pink, category=Kurta set, o...",Product: Anouk Women Pink & Orange Bandhani Pr...
24,25,no,14880040,-,0.3531,"brand=ADA, color=Pink, category=Dress, occasio...",Product: ADA Pink Embroidered Sustainable Unst...
25,26,no,15271046,-,0.3503,"brand=AHIKA, color=Pink, category=Kurta set, o...",Product: AHIKA Women Pink & White Bandhani Pri...
26,27,no,15816496,-,0.3206,"brand=Fabindia, color=Pink, occasion=Daily, pr...",Product: Fabindia Pink Yoke Design V-Neck Kurt...
27,28,no,18509098,-,0.3202,"brand=SANGAM PRINTS, color=Pink, category=Sare...",Product: SANGAM PRINTS Pink Floral Poly George...
28,29,no,19324656,-,0.3168,"brand=FASHOR, color=Pink, occasion=Daily, pric...",Product: FASHOR Women Pink Floral Embroidered ...
29,30,no,10356859,-,0.3078,"brand=Libas, color=Pink, category=Kurta set, o...",Product: Libas Floral Bliss Side Pocket Cotton...

,rank,hit,section_id,title,score,metadata,preview
0,1,no,13523706,-,0.5000,"brand=Varanga, color=Black, occasion=Daily, pr...",Product: Varanga Women Black & White Geometric...
1,2,no,14272032,-,0.5000,"brand=Oxolloxo, color=Orange, category=Regular...",Product: Oxolloxo Women Orange Solid Regular F...
2,3,no,13647622,-,0.4861,"brand=Varanga, color=Pink, occasion=Daily, pri...",Product: Varanga Women Pink & White Leheriya P...
3,4,no,13769372,-,0.4853,"brand=Varanga, color=Black, occasion=Daily, pr...",Product: Varanga Classic Black and White Bandh...
4,5,no,9621439,-,0.4696,"brand=WISSTLER, color=Blue, category=Regular s...",Product: WISSTLER Women Blue Printed Regular F...
5,6,no,11101312,-,0.4676,"brand=WISSTLER, color=Blue, category=Regular s...",Product: WISSTLER Women Blue Printed Regular F...
6,7,no,17251600,-,0.4584,"brand=Athena, color=Black, category=Regular sh...",Product: Athena Women Black Shorts Brand: Athe...
7,8,yes,15083714,-,0.4429,"brand=DressBerry, color=Green, category=Regula...",Product: DressBerry Women Green Striped Regula...
8,9,no,16836260,-,0.4075,"brand=Roadster, color=Blue, category=Regular s...",Product: Roadster Women Indigo Shaded Mid Rise...
9,10,no,14027018,-,0.3821,"brand=Oxolloxo, color=Olive, category=Regular ...",Product: Oxolloxo Women Olive Green Solid Regu...
10,11,no,14272016,-,0.3784,"brand=Oxolloxo, color=Green, category=Regular ...",Product: Oxolloxo Women Green Solid Regular Fi...
11,12,no,14340718,-,0.3676,"brand=MANGO, color=Peach, category=Regular sho...",Product: MANGO Women Peach-Coloured Solid Regu...
12,13,no,14388576,-,0.3658,"brand=Oxolloxo, color=Black, category=Regular ...",Product: Oxolloxo Women Black & Yellow Polka D...
13,14,no,19235420,-,0.3553,"brand=Oxolloxo, color=Brown, category=Regular ...",Product: Oxolloxo Women Brown Shorts Brand: Ox...
14,15,no,13529198,-,0.3522,"brand=Harvard, color=White, category=Regular s...",Product: Harvard Women White & Navy Striped Re...
15,16,no,12969482,-,0.3389,"brand=Hypernation, color=Olive, category=Regul...",Product: Hypernation Women Olive Green Solid S...
16,17,no,13060194,-,0.3343,"brand=QUARANTINE, color=Off White, category=Re...",Product: QUARANTINE Women Off-White Printed Re...
17,18,no,13985432,-,0.3335,"brand=Belle Fille, color=Blue, category=Regula...",Product: Belle Fille Women Blue Solid Regular ...
18,19,no,14672892,-,0.3329,"brand=Colour Me by Melange, color=Navy Blue, c...",Product: Colour Me by Melange Women Navy Blue ...
19,20,no,19047410,-,0.3317,"brand=Roadster, color=Black, category=Regular ...",Product: Roadster Women Black Solid Shorts Bra...
20,21,no,17256464,-,0.3172,"brand=Athena, color=Blue, category=Regular sho...",Product: Athena Women Blue Shorts Brand: Athen...
21,22,no,14219670,-,0.3061,"brand=DressBerry, color=Navy Blue, category=Re...",Product: DressBerry Women Navy Blue Shorts Bra...
22,23,no,15103054,-,0.2973,"brand=MANGO, color=Yellow, category=Regular sh...",Product: MANGO Women Yellow Floral Printed Hig...
23,24,no,15083698,-,0.2943,"brand=DressBerry, color=Pink, category=Regular...",Product: DressBerry Women Pink Striped Regular...
24,25,no,13391802,-,0.2871,"brand=Mast & Harbour, color=Grey Melange, cate...",Product: Mast & Harbour Women Grey Melange Sol...
25,26,no,12929508,-,0.2856,"brand=Mast & Harbour, color=Navy Blue, categor...",Product: Mast & Harbour Women Navy Blue Solid ...
26,27,no,11012420,-,0.2677,"brand=HRX by Hrithik Roshan, color=Black, cate...",Product: HRX by Hrithik Roshan Women Black & O...
27,28,no,18611674,-,0.2665,"brand=Honey by Pantaloons, color=Khaki, catego...",Product: Honey by Pantaloons Women Khaki Strip...
28,29,no,14954482,-,0.2651,"brand=Roadster, color=Olive, category=Regular ...",Product: Roadster Women Olive Green Loose Fit ...
29,30,no,16885654,-,0.2603,"brand=Alsace Lorraine Paris, color=Pink, categ...",Product: Alsace Lorraine Paris Women Pink Shor...

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,17674588,-,1.0000,"brand=H&M, color=Brown, category=Regular, occa...",Product: H&M Women Brown Mesh Top Brand: H&M C...
1,2,no,17965024,-,0.8614,"brand=H&M, color=Orange, category=Regular trou...",Product: H&M Orange Ankle-Length Trousers Bran...
2,3,no,12383500,-,0.7830,"brand=H&M, color=Black, category=Regular, occa...",Product: H&M Women Black Solid Long-Sleeved Je...
3,4,no,17883650,-,0.7347,"brand=H&M, color=Beige, category=Regular trous...",Product: H&M Beige Pattern-Knit Trousers Brand...
4,5,no,17842774,-,0.7207,"brand=H&M, color=Beige, category=Regular trous...",Product: H&M Beige Wide Linen-Blend Trousers B...
5,6,no,18131688,-,0.7098,"brand=H&M, color=Black, category=Regular trous...",Product: H&M Women Black Wide Linen-blend Trou...
6,7,yes,14258606,-,0.7007,"brand=H&M, color=White, category=Regular, occa...",Product: H&M Girls White Solid Jersey Top Bran...
7,8,yes,17964932,-,0.6807,"brand=H&M, color=Yellow, category=Regular, occ...",Product: H&M Women Yellow Rapid-Dry Sports Top...
8,9,no,17842776,-,0.6660,"brand=H&M, color=Beige, category=Regular trous...",Product: H&M Women Beige Striped Wide Linen-Bl...
9,10,no,17883622,-,0.6602,"brand=H&M, color=Beige, category=Regular, occa...",Product: H&M Girls Beige Cotton Jersey Cropped...
10,11,yes,19074168,-,0.6245,"brand=H&M, color=Green, category=Regular, occa...",Product: H&M Women Green Ribbed Cropped Top Br...
11,12,no,16396394,-,0.6242,"brand=H&M, color=Green, category=Joggers, occa...",Product: H&M Women Green Fine-Knit Joggers Bra...
12,13,no,18747130,-,0.6109,"brand=H&M, color=Beige, category=Regular short...",Product: H&M Women Beige Sweatshirt Shorts Bra...
13,14,no,17855308,-,0.6086,"brand=H&M, color=Orange, category=Regular shor...",Product: H&M Women Orange Pointelle-Knit Cotto...
14,15,no,19074138,-,0.6078,"brand=H&M, color=Pink, category=Regular, occas...",Product: H&M Women Pink Ribbed Cut-Out Top Bra...
15,16,no,18747106,-,0.6070,"brand=H&M, color=Orange, category=Regular shor...",Product: H&M Women Orange Sweatshirt Shorts Br...
16,17,no,17185856,-,0.6060,"brand=H&M, color=Blue, occasion=Casual, price=...",Product: H&M Women Blue Straight High Jeans Br...
17,18,yes,17883620,-,0.6023,"brand=H&M, color=Yellow, category=Regular, occ...",Product: H&M Yellow Puff-Sleeved Jersey Top Br...
18,19,no,17575906,-,0.5981,"brand=H&M, color=Blue, occasion=Casual, price=...",Product: H&M Women Blue Solid Skinny Regular J...
19,20,no,16175534,-,0.5931,"brand=H&M, color=Red, category=Joggers, occasi...",Product: H&M Women Red Cotton Blend Sweatpants...
20,21,no,17185466,-,0.5930,"brand=H&M, color=Beige, category=Regular short...",Product: H&M Women Beige & Grey Solid Sweatshi...
21,22,no,19071830,-,0.5900,"brand=H&M, color=Blue, occasion=Casual, price=...",Product: H&M Women Blue Wide High Jeans Brand:...
22,23,no,19175092,-,0.5864,"brand=H&M, color=Beige, category=Regular trous...",Product: H&M Women Beige Solid Pull-On Lyocell...
23,24,no,18747132,-,0.5759,"brand=H&M, color=Green, category=Regular short...",Product: H&M Women Green Terry Shorts Brand: H...
24,25,yes,18170658,-,0.5473,"brand=H&M, color=White, category=Regular, occa...",Product: H&M White Cotton Vest Top Brand: H&M ...
25,26,no,18834764,-,0.5340,"brand=H&M, color=Black, category=Parallel trou...",Product: H&M Women Black Corduroy trousers Bra...
26,27,no,19174870,-,0.5273,"brand=H&M, color=Black, category=Regular short...",Product: H&M Women Black Low-Waisted Bermuda S...
27,28,no,18747182,-,0.5106,"brand=H&M, color=Yellow, category=Regular shor...",Product: H&M Women Yellow Sweatshirt Shorts Br...
28,29,no,19266944,-,0.5106,"brand=H&M, color=Blue, category=Regular, occas...",Product: H&M Women Blue Stand-up Collar Satin ...
29,30,no,19176992,-,0.5092,"brand=H&M, color=Green, category=Regular, occa...",Product: H&M Women Green Ribbed Cut-out Top Br...

,rank,hit,section_id,title,score,metadata,preview
0,1,no,16914910,-,0.9058,"brand=KALINI, color=Pink, category=Saree, occa...",Product: KALINI Pink Poly Georgette Casual Sar...
1,2,yes,16421936,-,0.8364,"brand=KALINI, color=Pink, category=Saree, occa...",Product: KALINI Pink & Gold-Toned Paisley Sare...
2,3,yes,15102290,-,0.7576,"brand=KALINI, color=Pink, category=Saree, occa...",Product: KALINI Pink & Gold-Toned Woven Design...
3,4,yes,17852902,-,0.7260,"brand=KALINI, color=Pink, category=Saree, occa...",Product: KALINI Pink & Gold-Toned Zari Saree B...
4,5,yes,14678908,-,0.7232,"brand=KALINI, color=Pink, category=Saree, occa...",Product: KALINI Pink & Yellow Floral Pure Chif...
5,6,yes,15858094,-,0.6357,"brand=KALINI, color=Pink, category=Saree, occa...",Product: KALINI Pack of 2 Pink & Blue Floral S...
6,7,no,16948530,-,0.6021,"brand=KALINI, color=Pink, category=Bandhani, o...",Product: KALINI Pink & Grey Paisley Printed Ch...
7,8,no,14798392,-,0.5476,"brand=KALINI, color=Pink, category=Kota, occas...",Product: KALINI Pink & Green Ethnic Motifs Kot...
8,9,no,12961094,-,0.5336,"brand=KALINI, color=Pink, category=Kanjeevaram...",Product: KALINI Pink & Navy Blue Half & Half P...
9,10,no,17414120,-,0.5273,"brand=KALINI, color=Pink, category=Block print...",Product: KALINI Pink & White Batik Zari Block ...
10,11,no,16505402,-,0.1161,"brand=KALINI, color=Pink, occasion=Daily, pric...",Product: KALINI Women Pink Bandhani Printed An...
11,12,no,18952254,-,0.0384,"brand=KALINI, color=Pink, occasion=Daily, pric...",Product: KALINI Women Pink Ethnic Motifs Embro...
12,13,no,18503778,-,0.0160,"brand=KALINI, color=Pink, category=Kurti set, ...",Product: KALINI Women Pink Floral Embroidered ...

,rank,hit,section_id,title,score,metadata,preview
0,1,no,13523706,-,0.5000,"brand=Varanga, color=Black, occasion=Daily, pr...",Product: Varanga Women Black & White Geometric...
1,2,no,17226172,-,0.5000,"brand=SHOWOFF, color=Orange, occasion=Casual, ...",Product: SHOWOFF Women Orange Mom Fit High-Ris...
2,3,no,13647622,-,0.4858,"brand=Varanga, color=Pink, occasion=Daily, pri...",Product: Varanga Women Pink & White Leheriya P...
3,4,no,13769372,-,0.4850,"brand=Varanga, color=Black, occasion=Daily, pr...",Product: Varanga Classic Black and White Bandh...
4,5,no,17570458,-,0.4718,"brand=SHOWOFF, color=Brown, occasion=Casual, p...",Product: SHOWOFF Women Brown Jogger High-Rise ...
5,6,no,18142596,-,0.4305,"brand=SHOWOFF, color=Blue, occasion=Casual, pr...",Product: SHOWOFF Women Blue Jogger High-Rise L...
6,7,no,17790642,-,0.3998,"brand=SHOWOFF, color=Orange, category=Culotte ...",Product: SHOWOFF Orange & White Printed Culott...
7,8,no,17685090,-,0.3992,"brand=BUY NEW TREND, color=Red, category=Open ...",Product: BUY NEW TREND Women Red Black Colourb...
8,9,no,17250550,-,0.3898,"brand=SHOWOFF, color=Black, category=Top, occa...",Product: SHOWOFF Women Black Embellished Top w...
9,10,no,18388758,-,0.3895,"brand=SHOWOFF, color=Burgundy, category=Culott...",Product: SHOWOFF Burgundy Solid Culotte Jumpsu...
10,11,no,17801950,-,0.3895,"brand=SHOWOFF, color=Peach, occasion=Daily, pr...",Product: SHOWOFF Peach-Coloured & White Ethnic...
11,12,no,18189378,-,0.3437,"brand=SHOWOFF, color=Blue, category=Capri jump...",Product: SHOWOFF Blue Strapless Capri Jumpsuit...
12,13,no,17672184,-,0.3231,"brand=SHOWOFF, color=Blue, occasion=Casual, pr...",Product: SHOWOFF Women Blue High-Rise Heavy Fa...
13,14,no,18210214,-,0.2896,"brand=FABRIC FITOOR, color=Black, category=Kaf...",Product: FABRIC FITOOR Black Pure Cotton Print...
14,15,no,19276886,-,0.2882,"brand=Mitera, color=Grey, category=Saree, occa...",Product: Mitera Grey Floral Embroidered Net Fu...
15,16,no,18468196,-,0.2811,"brand=KAMI KUBI, color=Blue, category=Regular,...",Product: KAMI KUBI Women Blue schiffli-Embroid...
16,17,no,18338282,-,0.2726,"brand=SHOWOFF, color=Blue, occasion=Casual, pr...",Product: SHOWOFF Women Blue Slim Fit High-Rise...
17,18,no,14006764,-,0.2694,"brand=Saree mall, color=Green, category=Banara...",Product: Saree mall Floral Silk Blend Saree wi...
18,19,no,18056594,-,0.2689,"brand=Martini, color=Black, category=Flared, o...",Product: Martini Women Black Pleated Flared Mi...
19,20,no,17570450,-,0.2683,"brand=SHOWOFF, color=Black, occasion=Casual, p...",Product: SHOWOFF Women Black Slim Fit Stretcha...
20,21,no,18425088,-,0.2665,"brand=SHOWOFF, color=Navy Blue, category=Pullo...",Product: SHOWOFF Women Navy Blue Striped Hoode...
21,22,no,17872080,-,0.2645,"brand=Taavi, color=Blue, category=Peplum, occa...",Product: Taavi Women Indigo & White Indigo Pri...
22,23,no,18263720,-,0.2636,"brand=SHOWOFF, color=Grey, category=Top, occas...",Product: SHOWOFF Women Grey & Maroon Floral Pr...
23,24,no,18067038,-,0.2601,"brand=BUY NEW TREND, color=Blue, occasion=West...",Product: BUY NEW TREND Blue Flared Knitted Pal...
24,25,no,16309970,-,0.2572,"brand=aarke Ritu Kumar, color=Olive, category=...",Product: aarke Ritu Kumar Women Olive Green So...
25,26,no,17570446,-,0.2505,"brand=SHOWOFF, color=Blue, occasion=Casual, pr...",Product: SHOWOFF Women Blue Boyfriend Fit High...
26,27,no,18142614,-,0.2412,"brand=SHOWOFF, color=Lavender, occasion=Casual...",Product: SHOWOFF Women Lavender Jogger High-Ri...
27,28,no,17093664,-,0.2400,"brand=Roadster, color=Black, category=Denim sh...",Product: The Roadster Lifestyle Co Women Black...
28,29,no,17570328,-,0.2388,"brand=SHOWOFF, color=Blue, occasion=Casual, pr...",Product: SHOWOFF Women Blue Wide Leg High-Rise...
29,30,no,17093660,-,0.2384,"brand=Roadster, color=Charcoal, category=Denim...",Product: The Roadster Lifestyle Co Women Charc...

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,16379914,-,1.0000,"brand=Safaa, color=Red, occasion=Daily, price=...",Product: Safaa Women Red Woven Design Acrylic ...
1,2,yes,15768366,-,0.9931,"brand=VERO AMORE, color=Red, occasion=Daily, p...",Product: VERO AMORE Women Red & Beige Woven-De...
2,3,yes,16379852,-,0.9358,"brand=Safaa, color=Red, occasion=Daily, price=...",Product: Safaa Women Red & Black Woven Design ...
3,4,no,11379820,-,0.7680,"brand=SHINGORA, color=Red, occasion=Daily, pri...",Product: SHINGORA Women Red & Blue Woven Desig...
4,5,no,13104106,-,0.6658,"brand=Pashmoda, color=Red, occasion=Daily, pri...",Product: Pashmoda Women Red Woven Design Shawl...
5,6,no,13616810,-,0.6502,"brand=Dupatta Bazaar, color=Red, occasion=Dail...",Product: Dupatta Bazaar Red & Orange Woven Des...
6,7,no,15121622,-,0.6421,"brand=Cayman, color=Red, occasion=Daily, price...",Product: Cayman Women Red & Beige Woollen Wove...
7,8,no,15874790,-,0.6337,"brand=Pashmoda, color=Red, occasion=Daily, pri...",Product: Pashmoda Women Red Woven Design Jamaw...
8,9,no,19366710,-,0.6328,"brand=RIVAMA, color=Red, occasion=Daily, price...",Product: RIVAMA Red & Green Ethnic Motifs Wove...
9,10,no,17662882,-,0.6140,"brand=Dupatta Bazaar, color=Red, occasion=Part...",Product: Dupatta Bazaar Red Woven Design Dupat...
10,11,no,4444074,-,0.5900,"brand=Dupatta Bazaar, color=Red, occasion=Part...",Product: Dupatta Bazaar Red & Orange Woven Des...
11,12,no,16874574,-,0.5692,"brand=Mitera, color=Red, category=Paithani, oc...",Product: Mitera Red Woven Design Zari Silk Ble...
12,13,no,18205188,-,0.5321,"brand=Inddus, color=Red, category=Patola, occa...",Product: Inddus Red & Gold-Toned Woven Design ...
13,14,no,11149776,-,0.5156,"brand=Style Quotient, color=Red, occasion=Dail...",Product: Style Quotient Women Red & Black Chec...
14,15,no,18806012,-,0.5004,"brand=awesome, color=Red, category=Banarasi, o...",Product: awesome Red & Gold-Toned Woven Design...
15,16,no,13497800,-,0.4720,"brand=InWeave, color=Red, category=Regular, oc...",Product: InWeave Women Red Striped A-Line Top ...
16,17,no,8278529,-,0.4699,"brand=Faserz, color=Red, occasion=Party, price...",Product: Faserz Red Woven Design Banarasi Dupa...
17,18,no,16197692,-,0.4377,"brand=Pashmoda, color=Red, occasion=Daily, pri...",Product: Pashmoda Womens Red Kaani Woven Desig...
18,19,no,17764814,-,0.4324,"brand=Silk Land, color=Red, occasion=Party, pr...",Product: Silk Land Red & Gold-Toned Ethnic Mot...
19,20,no,17929928,-,0.4294,"brand=Silk Land, color=Red, occasion=Party, pr...",Product: Silk Land Red & Gold-Toned Ethnic Mot...
20,21,no,10358133,-,0.4265,"brand=Dupatta Bazaar, color=Red, occasion=Dail...",Product: Dupatta Bazaar Red & Gold-Coloured Wo...
21,22,no,13552260,-,0.4259,"brand=Dupatta Bazaar, color=Red, occasion=Part...",Product: Dupatta Bazaar Red & Yellow Woven Des...
22,23,no,19029736,-,0.4219,"brand=Mitera, color=Red, category=Patola, occa...",Product: Mitera Red & Gold-Toned Woven Design ...
23,24,no,17693086,-,0.4069,"brand=Silk Land, color=Red, category=Banarasi,...",Product: Silk Land Red & Gold-Toned Woven Desi...
24,25,no,6581979,-,0.4037,"brand=Dupatta Bazaar, color=Red, occasion=Part...",Product: Dupatta Bazaar Red & Gold-Toned Woven...
25,26,no,7079364,-,0.3642,"brand=Blissta, color=Red, occasion=Party, pric...",Product: Blissta Red & Gold-Toned Woven Design...
26,27,no,17764826,-,0.3597,"brand=Silk Land, color=Red, occasion=Party, pr...",Product: Silk Land Women Red Jacquared Banaras...
27,28,no,17735542,-,0.3540,"brand=Iris, color=Red, category=Saree, occasio...",Product: Iris Red Floral Net Saree Brand: Iris...
28,29,no,6849866,-,0.3511,"brand=Sugathari, color=Red, occasion=Party, pr...",Product: Sugathari Red & Gold-Toned Woven Desi...
29,30,no,17764856,-,0.3201,"brand=Silk Land, color=Red, occasion=Party, pr...",Product: Silk Land Red & Gold-Toned Ethnic Mot...

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,15917640,-,1.0,"brand=SERONA FABRICS, color=White, occasion=Da...",Product: SERONA FABRICS White & Pink Floral Em...

,rank,hit,section_id,title,score,metadata,preview
0,1,no,15258422,-,0.8362,"brand=Indo Era, color=Green, category=Kurta se...",Product: Indo Era Floral Cotton Blend Calf Len...
1,2,no,17447636,-,0.8046,"brand=Khushal K, color=Green, category=Kurta s...",Product: Khushal K Women Green Ethnic Motifs P...
2,3,yes,17232410,-,0.7961,"brand=InWeave, color=Green, category=Kurta set...",Product: InWeave Green Pure Cotton Print Parad...
3,4,yes,16707970,-,0.7949,"brand=mokshi, color=Green, category=Kurta set,...",Product: mokshi Ethnic Motifs Viscose Rayon Ku...
4,5,no,12989804,-,0.7910,"brand=mokshi, color=Green, category=Kurta set,...",Product: mokshi Women Green & Maroon Foil Prin...
5,6,no,15654150,-,0.7870,"brand=Indo Era, color=Green, category=Kurta se...",Product: Indo Era Women Green Ethnic Motifs Yo...
6,7,no,15508896,-,0.7642,"brand=Indo Era, color=Green, category=Kurta se...",Product: Indo Era Women Green Ethnic Motifs Yo...
7,8,no,15054430,-,0.7382,"brand=Biba, color=Green, category=Kurta set, o...",Product: Biba Women Green Ethnic Motifs Printe...
8,9,yes,15677426,-,0.7148,"brand=SWAGG INDIA, color=Green, category=Kurta...",Product: SWAGG INDIA Women Green Floral Embroi...
9,10,yes,17140156,-,0.7074,"brand=Myshka, color=Green, category=Kurta set,...",Product: Myshka Women Green Kurta with Palazzo...
10,11,no,15258010,-,0.6924,"brand=Libas, color=Green, category=Kurta set, ...",Product: Libas Women Green & White Floral Embr...
11,12,yes,16825614,-,0.6620,"brand=Stylum, color=Green, category=Kurta set,...",Product: Stylum Women Green Embroidered Pure C...
12,13,yes,14920000,-,0.6449,"brand=Indo Era, color=Green, category=Kurta se...",Product: Indo Era Women Green Floral Embroider...
13,14,yes,16505434,-,0.6389,"brand=KALINI, color=Green, category=Kurta set,...",Product: KALINI Women Green Floral Printed Pur...
14,15,yes,14121912,-,0.6364,"brand=Anouk, color=Green, category=Kurta set, ...",Product: Anouk Women Dark Green Embroidered Pl...
15,16,no,13392426,-,0.6306,"brand=Khushal K, color=Lime Green, category=Ku...",Product: Khushal K Women Lime Green Printed Ku...
16,17,no,18002690,-,0.6186,"brand=SINGNI, color=Green, category=Kurta set,...",Product: SINGNI Women Green Embroidered Printe...
17,18,no,18551726,-,0.5941,"brand=POONAM DESIGNER, color=Lime Green, categ...",Product: POONAM DESIGNER Women Lime Green Gott...
18,19,no,18765612,-,0.5581,"brand=mirari, color=Green, category=Kurta set,...",Product: mirari Women Green Floral Printed Pur...
19,20,no,16773346,-,0.5351,"brand=KALINI, color=Sea Green, category=Kurta ...",Product: KALINI Women Sea Green Printed Gotta ...
20,21,no,15224706,-,0.4678,"brand=Stylee LIFESTYLE, color=Green, category=...",Product: Stylee LIFESTYLE Green Embellished Se...
21,22,no,17889600,-,0.4490,"brand=EXTRA LOVE BY LIBAS, color=Sea Green, ca...",Product: EXTRA LOVE BY LIBAS Women Plus Size S...
22,23,no,15508612,-,0.4103,"brand=Saree mall, color=Green, category=Dress,...",Product: Saree mall Green Embroidered Unstitch...
23,24,no,15098762,-,0.3920,"brand=Rajnandini, color=Green, category=Dress,...",Product: Rajnandini Green & Black Printed Unst...
24,25,no,18748558,-,0.3902,"brand=JATRIQQ, color=Green, category=Dress, oc...",Product: JATRIQQ Green Art Silk Semi-Stitched ...
25,26,no,17634760,-,0.3901,"brand=JATRIQQ, color=Green, category=Dress, oc...",Product: JATRIQQ Green Embroidered Silk George...
26,27,no,17747744,-,0.3838,"brand=JATRIQQ, color=Green, category=Dress, oc...",Product: JATRIQQ Women Green Embroidered Silk ...
27,28,no,16017444,-,0.3819,"brand=Readiprint Fashions, color=Green, catego...",Product: Readiprint Fashions Green Embroidered...
28,29,no,18533460,-,0.3588,"brand=KALINI, color=Green, category=Dress, occ...",Product: KALINI Green Embroidered Unstitched D...
29,30,no,16017486,-,0.3532,"brand=Readiprint Fashions, color=Green, catego...",Product: Readiprint Fashions Green Embroidered...

Empty DataFrame
Columns: []
Index: []

,rank,hit,section_id,title,score,metadata,preview
0,1,no,16379842,-,0.6514,"brand=Safaa, color=Black, occasion=Daily, pric...",Product: Safaa Women Black & Beige Woven Desig...
1,2,no,16379878,-,0.5770,"brand=Safaa, color=Black, occasion=Daily, pric...",Product: Safaa Women Black & Blue Woven Design...
2,3,no,2380261,-,0.5635,"brand=Janasya, color=Black, category=Saree, oc...",Product: Janasya Black Solid Saree Blouse Bran...
3,4,no,19296144,-,0.5611,"brand=La Vastraa, color=Black, occasion=Daily,...",Product: La Vastraa Women Black & Brown Woven ...
4,5,no,10451770,-,0.5444,"brand=WEAVERS VILLA, color=Black, occasion=Dai...",Product: WEAVERS VILLA Women Black & Beige Wov...
5,6,no,16379928,-,0.5438,"brand=Safaa, color=Black, occasion=Daily, pric...",Product: Safaa Women Black & Beige Woven Desig...
6,7,no,16736530,-,0.5138,"brand=SHINGORA, color=Black, occasion=Daily, p...",Product: SHINGORA Women Black & Brown Woven-De...
7,8,no,2380278,-,0.5077,"brand=Janasya, color=Black, category=Saree, oc...",Product: Janasya Black Cotton Lycra Saree Blou...
8,9,no,13552234,-,0.5032,"brand=Dupatta Bazaar, color=Black, occasion=Da...",Product: Dupatta Bazaar Black Solid Dupatta Br...
9,10,no,17351596,-,0.5000,"brand=anayna, color=Black, occasion=Daily, pri...",Product: anayna Women Black & White Ethnic Mot...
10,11,no,11387498,-,0.4969,"brand=Inddus, color=Black, category=Saree, occ...",Product: Inddus Black Cotton Stretchable Solid...
11,12,no,18207362,-,0.4846,"brand=Dupatta Bazaar, color=Black, occasion=Da...",Product: Dupatta Bazaar Black Linen Dupatta Br...
12,13,no,2082103,-,0.4670,"brand=Saree mall, color=Black, category=Dress,...",Product: Saree mall Black Unstitched Dress Mat...
13,14,no,15952994,-,0.4351,"brand=Prakrti, color=Black, occasion=Daily, pr...",Product: Prakrti Black Printed Kurti Brand: Pr...
14,15,no,15768382,-,0.4196,"brand=VERO AMORE, color=Black, occasion=Daily,...",Product: VERO AMORE Women Black & Orange Woven...
15,16,no,9369411,-,0.4176,"brand=Myshka, color=Black, occasion=Daily, pri...",Product: Myshka Women Black & White Striped St...
16,17,no,16608222,-,0.4125,"brand=VERO AMORE, color=Black, occasion=Daily,...",Product: VERO AMORE Women Black & Red Woven De...
17,18,no,18272052,-,0.4074,"brand=HERE&NOW, color=Black, category=Saree, o...",Product: HERE&NOW Striped Saree with Embroider...
18,19,no,2528692,-,0.4003,"brand=Moda Rapido, color=Black, occasion=Daily...",Product: Moda Rapido Women Black Solid Straigh...
19,20,no,15953036,-,0.3963,"brand=Prakrti, color=Black, occasion=Daily, pr...",Product: Prakrti Black Solid Kurti Brand: Prak...
20,21,no,12159600,-,0.3868,"brand=WEAVERS VILLA, color=Black, occasion=Dai...",Product: WEAVERS VILLA Women Black & Orange Em...
21,22,no,18636196,-,0.3858,"brand=Tweedle, color=Black, occasion=Daily, pr...",Product: Tweedle Women Black & Red Striped Wov...
22,23,no,15768348,-,0.3739,"brand=VERO AMORE, color=Black, occasion=Daily,...",Product: VERO AMORE Women Black & Red Woven-De...
23,24,no,12967812,-,0.3672,"brand=Dupatta Bazaar, color=Black, occasion=Da...",Product: Dupatta Bazaar Black Printed Kalamkar...
24,25,no,15768400,-,0.3487,"brand=VERO AMORE, color=Black, occasion=Daily,...",Product: VERO AMORE Women Black & Red Woven-De...
25,26,no,16197678,-,0.3313,"brand=Pashmoda, color=Black, occasion=Daily, p...",Product: Pashmoda Women Black Kaani Woven Shaw...
26,27,no,13833448,-,0.3287,"brand=Sangria, color=Black, category=Saree, oc...",Product: Sangria Black & White Dyed Celebrity ...
27,28,no,15768324,-,0.3234,"brand=VERO AMORE, color=Black, occasion=Daily,...",Product: VERO AMORE Women Black & Red Woven Ku...
28,29,no,17077530,-,0.3218,"brand=SATYAM WEAVES, color=Black, category=Dre...",Product: SATYAM WEAVES Women Black & Red Unsti...
29,30,no,17093788,-,0.3177,"brand=Anouk, color=Black, occasion=Daily, pric...",Product: Anouk Women Black Solid Pleated Round...

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,18819296,-,1.0,"brand=Swasti, color=Blue, occasion=Daily, pric...",Product: Swasti Women Blue Ethnic Motifs Print...

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,13244594,-,1.0000,"brand=Mayra, color=Pink, category=Shirt style,...",Product: Mayra Women Pink Printed Shirt Style ...
1,2,no,15841446,-,0.8101,"brand=URBANIC, color=Pink, category=Shirt styl...",Product: URBANIC Pink & Beige Floral Print Shi...
2,3,no,19195222,-,0.7444,"brand=PRASTHAN, color=Pink, category=Shirt sty...",Product: PRASTHAN Women Pink Floral Print Crep...
3,4,no,19201936,-,0.6712,"brand=H&M, color=Pink, category=Shirt style, o...",Product: H&M Women Pink Pure Cotton Frill-Coll...
4,5,no,18605378,-,0.5946,"brand=Vishal Prints, color=Pink, category=Sare...",Product: Vishal Prints Pink & Grey Abstract Pr...
5,6,no,19325284,-,0.4601,"brand=POONAM DESIGNER, color=Pink, occasion=Da...",Product: POONAM DESIGNER Women Pink Ethnic Mot...
6,7,no,17820020,-,0.4517,"brand=Mast & Harbour, color=Pink, category=Shi...",Product: Mast & Harbour Pink Floral Print Mand...
7,8,no,19188354,-,0.4316,"brand=Colour Me by Melange, color=Pink, catego...",Product: Colour Me by Melange Women Pink Manda...
8,9,no,11762378,-,0.4316,"brand=AKKRITI BY PANTALOONS, color=Pink, categ...",Product: AKKRITI BY PANTALOONS Women Pink Prin...
9,10,no,17348862,-,0.4124,"brand=JC Collection, color=Pink, category=Shir...",Product: JC Collection Women Pink & Green Prin...
10,11,no,15632410,-,0.3954,"brand=URBANIC, color=Pink, category=T-shirt, o...",Product: URBANIC Women Pink Solid T-shirt with...
11,12,no,18076132,-,0.3825,"brand=Saree mall, color=Pink, category=Saree, ...",Product: Saree mall Pink & Black Printed Saree...
12,13,no,17000316,-,0.3428,"brand=Marks & Spencer, color=Pink, category=Sh...",Product: Marks & Spencer Pink Shirt Style Top ...
13,14,no,15791350,-,0.3387,"brand=iki chic, color=Pink, category=T-shirt, ...",Product: iki chic Women Pink & Black Printed T...
14,15,no,18529956,-,0.3169,"brand=JC Collection, color=Pink, category=Shir...",Product: JC Collection Women Pink & White Prin...
15,16,no,10720170,-,0.3000,"brand=Style Quotient, color=Pink, occasion=Cas...",Product: Style Quotient Women Pink Self Design...
16,17,no,15851572,-,0.2992,"brand=URBANIC, color=Pink, category=T-shirt, o...",Product: URBANIC Women Pink Solid T-shirt with...
17,18,no,15720246,-,0.2962,"brand=HIGHLIGHT FASHION EXPORT, color=Pink, ca...",Product: HIGHLIGHT FASHION EXPORT Pink Embroid...
18,19,no,16955084,-,0.2916,"brand=Kook N Keech Disney, color=Pink, categor...",Product: Kook N Keech Disney Women Charming Pi...
19,20,no,18667672,-,0.2912,"brand=Stylee LIFESTYLE, color=Pink, category=D...",Product: Stylee LIFESTYLE Pink & Red Satin Uns...
20,21,no,19032532,-,0.2572,"brand=BUY NEW TREND, color=Pink, occasion=Casu...",Product: BUY NEW TREND Women Pink & Yellow Pri...
21,22,no,18087234,-,0.2522,"brand=Tikhi Imli, color=Pink, category=Saree, ...",Product: Tikhi Imli Pink & Blue Butterfly Prin...
22,23,no,9301311,-,0.2432,"brand=Tissu, color=Pink, occasion=Daily, price...",Product: Tissu Women Pink & Off-White Floral P...
23,24,no,19280832,-,0.2382,"brand=VividArtsy, color=Pink, category=Sweatsh...",Product: VividArtsy Women Pink Tie & Dye Print...
24,25,no,15228856,-,0.2357,"brand=Blissta, color=Pink, category=Dress, occ...",Product: Blissta Pink Unstitched Dress Materia...
25,26,no,17365728,-,0.2341,"brand=I Saw It First, color=Pink, category=Fla...",Product: I Saw It First Women Dusty Pink & Whi...
26,27,no,17973842,-,0.2307,"brand=MANGO, color=Pink, category=Regular trou...",Product: MANGO Women Pink & Black Printed Stra...
27,28,no,14955108,-,0.2254,"brand=Roadster, color=Pink, category=T-shirt, ...",Product: Roadster Women Pink & Grey Camouflage...
28,29,no,16887876,-,0.2128,"brand=TANKHI, color=Pink, occasion=Ethnic, pri...",Product: TANKHI Women Pink Floral Printed Tuni...
29,30,no,15496398,-,0.2102,"brand=JC Collection, color=Pink, category=Top,...",Product: JC Collection Women Pink & Brown Prin...

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,17754230,-,0.8718,"brand=Atsevam, color=Cream, price=5001.0",Product: Atsevam Cream-Coloured & Red Semi-Sti...
1,2,yes,17754248,-,0.8090,"brand=Atsevam, color=Red, price=5001.0",Product: Atsevam Red Embroidered Thread Work S...
2,3,yes,19217168,-,0.4328,"brand=Atsevam, color=Green, price=5599.0",Product: Atsevam Green & Gold-Toned Embroidere...
3,4,yes,17754250,-,0.4200,"brand=Atsevam, color=Pink, price=5001.0",Product: Atsevam Women Pink Embroidered Semi-S...
4,5,no,19217196,-,0.4110,"brand=Atsevam, color=Pink, price=7349.0",Product: Atsevam Pink Embroidered Thread Work ...
5,6,yes,19217170,-,0.3937,"brand=Atsevam, color=Red, price=6699.0",Product: Atsevam Red & Gold-Toned Embroidered ...
6,7,no,17834516,-,0.3871,"brand=Atsevam, color=Blue, price=5000.0",Product: Atsevam Blue & Pink Ready to Wear Leh...
7,8,no,19217186,-,0.3837,"brand=Atsevam, color=Green, price=5349.0",Product: Atsevam Women Green & Pink Printed Ti...
8,9,yes,17584576,-,0.3825,"brand=Atsevam, color=Orange, price=6999.0",Product: Atsevam Orange & Red Printed Tie and ...
9,10,yes,19217176,-,0.2739,"brand=Atsevam, color=White, price=7999.0",Product: Atsevam White & Pink Tie and Dye Semi...

,rank,hit,section_id,title,score,metadata,preview
0,1,no,18070000,-,1.0000,"brand=panchhi, color=Pink, price=12999.0",Product: panchhi Pink Embroidered Sequinned Un...
1,2,yes,19046346,-,0.3823,"brand=panchhi, color=Pink, price=12999.0",Product: panchhi Pink & Sea Green Embellished ...
2,3,no,18175384,-,0.1356,"brand=panchhi, color=Pink, price=12999.0",Product: panchhi Pink Net Embroidered Sequinne...
3,4,yes,12003682,-,0.0950,"brand=panchhi, color=Pink, occasion=Festive, p...",Product: panchhi Pink & Beige Embellished Semi...

,rank,hit,section_id,title,score,metadata,preview
0,1,no,16858560,-,0.5000,"brand=NEUDIS, color=Black, category=Regular tr...",Product: NEUDIS Women Black Comfort Flared Tro...
1,2,no,19177952,-,0.5000,"brand=250 DESIGNS, color=Black, occasion=Casua...",Product: 250 DESIGNS Women Black & Brown Print...
2,3,no,17612960,-,0.4619,"brand=250 DESIGNS, color=Navy Blue, category=T...",Product: 250 DESIGNS Women Navy Blue Floral Co...
3,4,no,16172382,-,0.3460,"brand=NEUDIS, color=Red, category=Regular, occ...",Product: NEUDIS Red Cowl Neck Satin Regular To...
4,5,no,18489222,-,0.3423,"brand=NEUDIS, color=Red, category=Regular, occ...",Product: NEUDIS Red Cowl Neck Satin Top Brand:...
5,6,no,17255464,-,0.3381,"brand=NEUDIS, color=Red, category=Styled back,...",Product: NEUDIS Women Satin Red Embillished So...
6,7,no,18057660,-,0.2999,"brand=NEUDIS, color=White, category=A-line, oc...",Product: NEUDIS Women White Self-Design A-Line...
7,8,no,17336142,-,0.2845,"brand=UNDER ARMOUR, color=Pink, category=Sport...",Product: UNDER ARMOUR Women Pink Loose Fit Tra...
8,9,no,2507000,-,0.2606,"brand=Roadster, color=Pink, category=Regular, ...",Product: Roadster Pink Knitted Lace Top Brand:...
9,10,no,18806012,-,0.2368,"brand=awesome, color=Red, category=Banarasi, o...",Product: awesome Red & Gold-Toned Woven Design...
10,11,no,16034502,-,0.2357,"brand=Berrylush, color=Yellow, category=Playsu...",Product: Berrylush Women Bright Yellow Printed...
11,12,no,18290992,-,0.2303,"brand=Superminis, color=Brown, price=2499.0",Product: Superminis Girls Brown & Embroidered ...
12,13,no,18284594,-,0.2283,"brand=HERSHEINBOX, color=Purple, category=Basi...",Product: HERSHEINBOX Women Purple Printed Noug...
13,14,no,17238348,-,0.2258,"brand=NEUDIS, color=Beige, category=Regular, o...",Product: NEUDIS Beige Cowl Neck Sheen Satin Fi...
14,15,no,15381904,-,0.2192,"brand=Berrylush, color=Pink, category=Basic ju...",Product: Berrylush Women Pink Solid Ruffled Ju...
15,16,no,17209256,-,0.2071,"brand=Unnati Silks, color=Cream, category=Bana...",Product: Unnati Silks Cream-Coloured & Black E...
16,17,no,16758920,-,0.2067,"brand=ZIYAA, color=White, category=Basic jumps...",Product: ZIYAA Women Classic White Printed Cin...
17,18,no,16372904,-,0.2049,"brand=Netram, color=Beige, price=13206.0",Product: Netram Beige Embroidered Semi-Stitche...
18,19,no,18512872,-,0.2000,"brand=Amrutam Fab, color=Cream, price=11999.0",Product: Amrutam Fab Cream-Coloured & Navy Blu...
19,20,no,15508760,-,0.1928,"brand=SASSAFRAS, color=Navy Blue, category=Bas...",Product: SASSAFRAS Women Deep Navy Blue Solid ...
20,21,no,18290988,-,0.1917,"brand=Superminis, color=Lime Green, price=2499.0",Product: Superminis Girls Lime Green & Beige E...
21,22,no,15589086,-,0.1812,"brand=Netram, color=Lavender, price=11409.0",Product: Netram Lavender & Silver-Toned Semi-S...
22,23,no,17725246,-,0.1800,"brand=DIVASTRI, color=Red, price=5999.0",Product: DIVASTRI Red & Mustard Banarasi Silk ...
23,24,no,15071832,-,0.1775,"brand=all about you, color=Blue, category=Sare...",Product: all about you Blue & Violet Floral Or...
24,25,no,18258322,-,0.1751,"brand=Netram, color=Red, price=10340.0",Product: Netram Red & Gold-Toned Embroidered S...
25,26,no,16311568,-,0.1741,"brand=all about you, color=Grey, category=Sare...",Product: all about you Grey Leheriya Organza S...
26,27,no,16311702,-,0.1737,"brand=all about you, color=Pink, category=Kanj...",Product: all about you Pink Woven Design Silk ...
27,28,no,16311684,-,0.1731,"brand=all about you, color=Blue, category=Sare...",Product: all about you Blue Leheriya Organza S...
28,29,no,16311576,-,0.1730,"brand=all about you, color=Pink, category=Sare...",Product: all about you Pink Embroidered with B...
29,30,no,16828018,-,0.1727,"brand=all about you, color=Pink, category=Sare...",Product: all about you Women Pink & Silver Flo...

,rank,hit,section_id,title,score,metadata,preview
0,1,no,14869156,-,0.9606,"brand=Indo Era, color=Black, price=5999.0",Product: Indo Era Deep Black Solid Lehenga wit...
1,2,no,16188740,-,0.8809,"brand=Indo Era, color=Green, occasion=Western,...",Product: Indo Era Women Green Solid Cotton Pal...
2,3,yes,12122360,-,0.8806,"brand=Indo Era, color=Brown, occasion=Daily, p...",Product: Indo Era Brown & Golden Woven Design ...
3,4,no,16950290,-,0.7959,"brand=Indo Era, color=Sea Green, category=Regu...",Product: Indo Era Sea Green Floral Print Tie-U...
4,5,yes,12040878,-,0.7751,"brand=Indo Era, color=Orange, occasion=Daily, ...",Product: Indo Era Orange & Pink Striped Dupatt...
5,6,no,16950218,-,0.7707,"brand=Indo Era, color=Blue, category=Peplum, o...",Product: Indo Era Blue Ethnic Motif Printed Pe...
6,7,yes,11459668,-,0.7655,"brand=Indo Era, color=Navy Blue, occasion=Part...",Product: Indo Era Navy Blue & Gold-Toned Strip...
7,8,yes,12040868,-,0.7391,"brand=Indo Era, color=Navy Blue, occasion=Part...",Product: Indo Era Navy Blue & Golden Striped D...
8,9,no,17577466,-,0.7344,"brand=Indo Era, color=Orange, category=A-line,...",Product: Indo Era Women Bright Orange Ethnic F...
9,10,no,17577464,-,0.7287,"brand=Indo Era, color=Blue, category=A-line, o...",Product: Indo Era Women Stunning Blue Floral E...
10,11,no,13810898,-,0.7285,"brand=Indo Era, color=Blue, category=Kurta set...",Product: Indo Era Women Blue & Green Printed K...
11,12,no,17577456,-,0.7250,"brand=Indo Era, color=Off White, category=A-li...",Product: Indo Era Women Classic Off-White Ethn...
12,13,no,16713198,-,0.7025,"brand=Indo Era, color=Grey, category=Kurta set...",Product: Indo Era Grey Silk Blend Scalloped Ed...
13,14,no,15098594,-,0.6939,"brand=Indo Era, color=Teal, occasion=Daily, pr...",Product: Indo Era Women Teal Green & Golden Et...
14,15,no,12122358,-,0.6898,"brand=Indo Era, color=Black, category=Kurta se...",Product: Indo Era Women Black & Teal Blue Yoke...
15,16,no,15258422,-,0.6849,"brand=Indo Era, color=Green, category=Kurta se...",Product: Indo Era Floral Cotton Blend Calf Len...
16,17,no,17069054,-,0.6802,"brand=Indo Era, color=Black, category=Kurta se...",Product: Indo Era Women Black Ethnic Motifs Yo...
17,18,no,17553556,-,0.6563,"brand=Indo Era, color=Green, occasion=Daily, p...",Product: Indo Era Green & Gold-Toned Woven Des...
18,19,no,15098616,-,0.6552,"brand=Indo Era, color=Burgundy, occasion=Festi...",Product: Indo Era Women Burgundy & Golden Ethn...
19,20,no,14235030,-,0.6528,"brand=Indo Era, color=Black, category=Kurta se...",Product: Indo Era Women Black Floral Printed P...
20,21,no,12418804,-,0.6507,"brand=Indo Era, color=Maroon, category=Kurta s...",Product: Indo Era Women Maroon & Orange Yoke D...
21,22,no,17911130,-,0.6498,"brand=Indo Era, color=Burgundy, category=Kurta...",Product: Indo Era Women Burgundy Sequined Kurt...
22,23,no,15654150,-,0.6437,"brand=Indo Era, color=Green, category=Kurta se...",Product: Indo Era Women Green Ethnic Motifs Yo...
23,24,no,11459658,-,0.6436,"brand=Indo Era, color=Burgundy, category=Kurta...",Product: Indo Era Folksy Floral Screen Print C...
24,25,no,15794640,-,0.6388,"brand=Indo Era, color=Maroon, category=Kurta s...",Product: Indo Era Woven Design Velvet Kurta Se...
25,26,no,14967448,-,0.6367,"brand=Indo Era, color=Green, category=Kurta se...",Product: Indo Era Women Green Ethnic Motifs Pr...
26,27,no,16713256,-,0.6313,"brand=Indo Era, color=Mustard, category=Kurta ...",Product: Indo Era Mustard Liva Calf Length Kur...
27,28,no,15794634,-,0.6226,"brand=Indo Era, color=Red, category=Kurta set,...",Product: Indo Era Embroidered Velvet Kurta Set...
28,29,no,13962300,-,0.6203,"brand=Indo Era, color=Off White, category=Kurt...",Product: Indo Era Classy Off White And Yellow ...
29,30,yes,15520698,-,0.6003,"brand=Indo Era, color=Navy Blue, occasion=Fest...",Product: Indo Era Women Navy Blue Floral Yoke ...

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,18626222,-,1.0000,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Straight Fit High-Ris...
1,2,no,18620390,-,0.9462,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Skinny Fit High-Rise ...
2,3,no,16372376,-,0.9459,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Slim Fit High-Rise Mi...
3,4,no,18626210,-,0.9446,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Skinny Fit High-Rise ...
4,5,no,19089706,-,0.9326,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Slim Fit High-Rise Mi...
5,6,no,16699772,-,0.9133,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue High-Rise Mildly Dist...
6,7,no,19089710,-,0.7789,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Flared Mildly Distres...
7,8,no,19089694,-,0.7549,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Straight Fit High-Ris...
8,9,no,19089668,-,0.7532,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Straight Fit High-Ris...
9,10,no,17914728,-,0.7480,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Straight Fit High-Ris...
10,11,no,19143972,-,0.7455,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Straight Fit High-Ris...
11,12,no,18620400,-,0.7363,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Skinny Fit High-Rise ...
12,13,no,19089666,-,0.7164,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Slim Fit High-Rise Lo...
13,14,no,18626226,-,0.7015,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Straight Fit High-Ris...
14,15,no,16916588,-,0.6638,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Mom-Fit High-Rise Lig...
15,16,no,18626254,-,0.6630,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Bootcut High-Rise Low...
16,17,no,18626232,-,0.6580,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Skinny Fit High-Rise ...
17,18,no,18620404,-,0.6544,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Skinny Fit High-Rise ...
18,19,no,18626248,-,0.6540,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Skinny Fit High-Rise ...
19,20,no,17914732,-,0.6483,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Skinny Fit High-Rise ...
20,21,no,19089662,-,0.6252,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Skinny Fit High-Rise ...
21,22,no,18809318,-,0.5168,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Skinny Fit Light Fade...
22,23,no,18809310,-,0.5167,"brand=ONLY, color=Blue, occasion=Casual, price...",Product: ONLY Women Blue Skinny Fit Light Fade...
23,24,no,19175980,-,0.4392,"brand=ONLY, color=Blue, category=Regular trous...",Product: ONLY Women Blue High-Rise Trousers Br...
24,25,no,19175662,-,0.3586,"brand=ONLY, color=Blue, category=Denim jacket,...",Product: ONLY Women Blue Washed Crop Denim Jac...
25,26,no,19175664,-,0.3565,"brand=ONLY, color=Blue, category=Denim jacket,...",Product: ONLY Women Blue Washed Colourblocked ...
26,27,no,18624784,-,0.3448,"brand=ONLY, color=Blue, category=Denim jacket,...",Product: ONLY Women Blue Crop Denim Jacket wit...
27,28,no,19175660,-,0.3415,"brand=ONLY, color=Blue, category=Denim jacket,...",Product: ONLY Women Blue Colourblocked Crop De...
28,29,no,19175872,-,0.3280,"brand=ONLY, color=Blue, category=A-line, occas...",Product: ONLY Women Blue Solid Denim Mini Skir...
29,30,no,19175668,-,0.3129,"brand=ONLY, color=Blue, category=Denim jacket,...",Product: ONLY Women Blue Washed Denim Jacket B...

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,17944738,-,0.9225,"brand=Uptownie Lite, color=Grey, category=Flar...",Product: Uptownie Lite Grey Solid Pleated Form...
1,2,yes,11425704,-,0.7587,"brand=Uptownie Lite, color=Brown, category=Fla...",Product: Uptownie Lite Brown Satin Pleated Fla...
2,3,no,11425706,-,0.7442,"brand=Uptownie Lite, color=Black, category=Fla...",Product: Uptownie Lite Black Satin Pleated Fla...
3,4,yes,13467524,-,0.6765,"brand=Uptownie Lite, color=Red, category=Flare...",Product: Uptownie Lite Women Red Solid Pleated...
4,5,yes,11511460,-,0.6402,"brand=Uptownie Lite, color=Maroon, category=Fl...",Product: Uptownie Lite Women Maroon Solid Plea...
5,6,no,15355338,-,0.5776,"brand=Uptownie Lite, color=Black, category=Fla...",Product: Uptownie Lite Girls Black Crepe Print...
6,7,yes,16608122,-,0.5639,"brand=Uptownie Lite, color=Black, category=Fla...",Product: Uptownie Lite Girls Black & Pink Prin...
7,8,no,11335786,-,0.5505,"brand=Uptownie Lite, color=Gold, category=Flar...",Product: Uptownie Lite Women Gold-Coloured Sol...
8,9,no,11234642,-,0.3464,"brand=Uptownie Lite, color=Black, category=Bas...",Product: Uptownie Lite Women Black Solid Basic...
9,10,no,10418102,-,0.3294,"brand=Uptownie Lite, color=Maroon, category=Ba...",Product: Uptownie Lite Women Maroon Solid Ruff...
10,11,no,11234652,-,0.2691,"brand=Uptownie Lite, color=Burgundy, category=...",Product: Uptownie Lite Women Burgundy Solid Ba...
11,12,no,19169942,-,0.1728,"brand=Uptownie Lite, color=Yellow, category=Ba...",Product: Uptownie Lite Women Yellow Crepe Smoc...
12,13,no,17267836,-,0.1631,"brand=Uptownie Lite, color=Red, category=Basic...",Product: Uptownie Lite Red & Yellow Striped Ba...
13,14,no,11322090,-,0.1557,"brand=Uptownie Lite, color=Black, category=Bas...",Product: Uptownie Lite Women Black Solid Basic...
14,15,no,13501842,-,0.0879,"brand=Uptownie Lite, color=Black, category=Bas...",Product: Uptownie Lite Women Black Solid Dhoti...

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,15243956,-,1.0000,"brand=Suta, color=Beige, category=Saree, occas...",Product: Suta Beige & White Pure Linen Zari Sa...
1,2,no,14988280,-,0.3607,"brand=Suta, color=Beige, category=Saree, occas...",Product: Suta Beige & Black Pure Cotton solid ...
2,3,no,16909300,-,0.3020,"brand=Suta, color=Off White, category=Maheshwa...",Product: Suta Off White & Black Zari Silk Cott...
3,4,no,15244224,-,0.2877,"brand=Suta, color=Beige, category=Saree, occas...",Product: Suta Beige & White Floral Embroidered...
4,5,no,15244106,-,0.2196,"brand=Suta, color=White, category=Saree, occas...",Product: Suta White & Pink Polka Dot Printed P...
5,6,no,15244024,-,0.2040,"brand=Suta, color=Beige, category=Saree, occas...",Product: Suta Beige Pink Floral Motifs PolyCot...
6,7,no,15244118,-,0.1305,"brand=Suta, color=White, category=Saree, occas...",Product: Suta White & Black Ethnic Motifs Jamd...
7,8,no,18390702,-,0.0826,"brand=Suta, color=Off White, category=Saree, o...",Product: Suta Off White & Golden Striped Saree...
8,9,no,18166926,-,0.0000,"brand=Suta, color=White, category=Saree, occas...",Product: Suta Women White Embroidered Cotton S...

Empty DataFrame
Columns: []
Index: []

,rank,hit,section_id,title,score,metadata,preview
0,1,no,19266888,-,0.7831,"brand=H&M, color=Black, category=Pullover, occ...",Product: H&M Women Black Solid Collared Sweats...
1,2,no,15845464,-,0.7491,"brand=URBANIC, color=Black, category=Pullover,...",Product: URBANIC Women Black Solid Cotton Swea...
2,3,no,17038044,-,0.7396,"brand=Levis, color=Black, category=Pullover, o...",Product: Levis Women Black Pullover Sweater Br...
3,4,no,9478497,-,0.7353,"brand=Roadster, color=Black, category=Pullover...",Product: The Roadster Lifestyle Co Women Black...
4,5,no,14080898,-,0.7252,"brand=DressBerry, color=Black, category=Pullov...",Product: DressBerry Women Black Print Detail S...
5,6,no,10575458,-,0.7166,"brand=Roadster, color=Black, category=Pullover...",Product: The Roadster Lifestyle Co Women Black...
6,7,no,15642616,-,0.7107,"brand=Aesthetic Bodies, color=Black, category=...",Product: Aesthetic Bodies Women Black Cotton S...
7,8,no,15630060,-,0.6969,"brand=H&M, color=Black, category=Pullover, occ...",Product: H&M Women Black Solid Hoodie Brand: H...
8,9,no,6726577,-,0.6925,"brand=Mast & Harbour, color=Black, category=Pu...",Product: Mast & Harbour Women Black Solid Pull...
9,10,no,12048466,-,0.6889,"brand=INVICTUS, color=Black, category=Pullover...",Product: INVICTUS Women Black Solid Pullover B...
10,11,no,14331596,-,0.6801,"brand=Roadster, color=Black, category=Pullover...",Product: Roadster Women Black Solid Turtle Nec...
11,12,no,10714640,-,0.6798,"brand=Taanz, color=Black, category=Pullover, o...",Product: Taanz Women Black Solid Sweatshirt Br...
12,13,no,14512956,-,0.6758,"brand=Powerpuff Girls by Kook N Keech, color=B...",Product: Powerpuff Girls by Kook N Keech Women...
13,14,no,15870014,-,0.6670,"brand=New Balance, color=Black, category=Pullo...",Product: New Balance Women Black Sweatshirt Br...
14,15,no,14080668,-,0.6631,"brand=DressBerry, color=Black, category=Pullov...",Product: DressBerry Women Black Solid Sweatshi...
15,16,yes,15198584,-,0.6626,"brand=H&M, color=Black, category=Pullover, occ...",Product: H&M Women Black Sweatshirt Brand: H&M...
16,17,no,10611428,-,0.6603,"brand=Alsace Lorraine Paris, color=Black, cate...",Product: Alsace Lorraine Paris Women Black Sol...
17,18,no,19269372,-,0.6534,"brand=BoStreet, color=Black, category=Pullover...",Product: BoStreet Women Black Colourblocked Lo...
18,19,no,10683730,-,0.6482,"brand=STREET 9, color=Black, category=Pullover...",Product: STREET 9 Women Black Solid Sweater Br...
19,20,no,13615048,-,0.6384,"brand=Flying Machine, color=Black, category=Pu...",Product: Flying Machine Women Black Solid Swea...
20,21,no,10791506,-,0.6115,"brand=The Vanca, color=Black, category=Pullove...",Product: The Vanca Women Black & Navy Blue Sol...
21,22,yes,15964092,-,0.5944,"brand=MANGO, color=Black, category=Pullover, o...",Product: MANGO Women Black Solid Pullover Bran...
22,23,no,16533910,-,0.5871,"brand=RAREISM, color=Black, category=Pullover,...",Product: RAREISM Women Black Hooded Sweatshirt...
23,24,no,18004440,-,0.5839,"brand=Aeropostale, color=Black, category=Pullo...",Product: Aeropostale Women Black Printed Hoode...
24,25,no,11109236,-,0.5838,"brand=DOLCE CRUDO, color=Black, category=Pullo...",Product: DOLCE CRUDO Women Black Solid Hooded ...
25,26,yes,15963804,-,0.5818,"brand=MANGO, color=Black, category=Pullover, o...",Product: MANGO Women Black Solid Pullover Swea...
26,27,no,13593756,-,0.5724,"brand=BEVERLY BLUES, color=Black, category=Pul...",Product: BEVERLY BLUES Women Black Solid Sweat...
27,28,no,16583226,-,0.5580,"brand=20Dresses, color=Black, category=Pullove...",Product: 20Dresses Women Black Plus Size Cotto...
28,29,no,10747958,-,0.5549,"brand=Alsace Lorraine Paris, color=Black, cate...",Product: Alsace Lorraine Paris Women Black & Y...
29,30,no,18144562,-,0.5532,"brand=Marks & Spencer, color=Black, category=P...",Product: Marks & Spencer Women Black Sherpa Sw...

,rank,hit,section_id,title,score,metadata,preview
0,1,no,17403640,-,0.5000,"brand=I Saw It First, color=Khaki, occasion=Ca...",Product: I Saw It First Women Khaki Crinkled T...
1,2,no,13843640,-,0.5000,"brand=Stylee LIFESTYLE, color=Navy Blue, categ...",Product: Stylee LIFESTYLE Navy Blue & Gold-Ton...
2,3,no,17403254,-,0.4860,"brand=I Saw It First, color=Blue, occasion=Cas...",Product: I Saw It First Women Blue Skinny Fit ...
3,4,no,13452734,-,0.4836,"brand=I AM FOR YOU, color=Green, occasion=West...",Product: I AM FOR YOU Women Green & Grey Print...
4,5,no,17403434,-,0.4779,"brand=I Saw It First, color=White, category=Pl...",Product: I Saw It First Women White & Blue Flo...
5,6,no,17365722,-,0.4746,"brand=I Saw It First, color=Beige, category=Re...",Product: I Saw It First Women Beige Striped Hi...
6,7,no,17403428,-,0.4731,"brand=I Saw It First, color=Blue, occasion=Cas...",Product: I Saw It First Women Blue Skinny Fit ...
7,8,no,14159320,-,0.4680,"brand=I AM FOR YOU, color=Yellow, category=A-l...",Product: I AM FOR YOU Women Yellow & White Emb...
8,9,no,17403380,-,0.4669,"brand=I Saw It First, color=Blue, occasion=Cas...",Product: I Saw It First Women Blue Slash Knee ...
9,10,no,17403300,-,0.4636,"brand=I Saw It First, color=Blue, occasion=Cas...",Product: I Saw It First Women Blue Light Fade ...
10,11,no,17365728,-,0.4605,"brand=I Saw It First, color=Pink, category=Fla...",Product: I Saw It First Women Dusty Pink & Whi...
11,12,no,17365720,-,0.4540,"brand=I Saw It First, color=Green, category=Fl...",Product: I Saw It First Women Green Solid Plea...
12,13,no,17136852,-,0.4325,"brand=Readiprint Fashions, color=Blue, occasio...",Product: Readiprint Fashions Blue & Silver Emb...
13,14,no,18750730,-,0.4127,"brand=Stylee LIFESTYLE, color=Olive, category=...",Product: Stylee LIFESTYLE Olive Green & Red Un...
14,15,no,19392350,-,0.4003,"brand=Ethnic Yard, color=Green, category=Dress...",Product: Ethnic Yard Green & Grey Embroidered ...
15,16,no,17287376,-,0.3916,"brand=Stylee LIFESTYLE, color=Yellow, category...",Product: Stylee LIFESTYLE Yellow & Gold-Toned ...
16,17,no,18766164,-,0.3703,"brand=Stylee LIFESTYLE, color=Black, category=...",Product: Stylee LIFESTYLE Black & Gold-Toned P...
17,18,no,17570416,-,0.3682,"brand=SHOWOFF, color=Black, occasion=Casual, p...",Product: SHOWOFF Women Black Straight Fit Stre...
18,19,no,19097390,-,0.3590,"brand=I Love She, color=White, category=Regula...",Product: I Love She Women White Relaxed High-R...
19,20,no,18245104,-,0.3560,"brand=Miss Chase, color=Blue, occasion=Casual,...",Product: Miss Chase Women Blue Jogger High-Ris...
20,21,no,18142614,-,0.3558,"brand=SHOWOFF, color=Lavender, occasion=Casual...",Product: SHOWOFF Women Lavender Jogger High-Ri...
21,22,no,14925780,-,0.3543,"brand=Roadster, color=Blue, occasion=Casual, p...",Product: Roadster Women Blue Wide Leg Stretcha...
22,23,no,19396408,-,0.3484,"brand=Stylee LIFESTYLE, color=Beige, category=...",Product: Stylee LIFESTYLE Womens Beige Embroid...
23,24,no,12629360,-,0.3478,"brand=Roadster, color=Rust, occasion=Casual, p...",Product: Roadster Women Rust Red Regular Fit M...
24,25,no,18245110,-,0.3477,"brand=Miss Chase, color=Blue, occasion=Casual,...",Product: Miss Chase Women Blue High-Rise Mildl...
25,26,no,19097392,-,0.3432,"brand=I Love She, color=Maroon, category=Regul...",Product: I Love She Women Maroon Relaxed Skinn...
26,27,no,14954878,-,0.3426,"brand=Roadster, color=Charcoal, occasion=Casua...",Product: Roadster Women Charcoal Mid-Rise Stra...
27,28,no,11284776,-,0.3389,"brand=Mast & Harbour, color=Blue, occasion=Cas...",Product: Mast & Harbour Women Blue Mid-Rise Cl...
28,29,no,17570328,-,0.3381,"brand=SHOWOFF, color=Blue, occasion=Casual, pr...",Product: SHOWOFF Women Blue Wide Leg High-Rise...
29,30,no,16533888,-,0.3350,"brand=Ethnic Junction, color=Navy Blue, catego...",Product: Ethnic Junction Navy Blue & Gold-Tone...

,rank,hit,section_id,title,score,metadata,preview
0,1,no,13886174,-,1.0000,"brand=Mitera, color=Pink, category=Taant, occa...",Product: Mitera Pink & White Pure Cotton Woven...
1,2,no,11218670,-,0.7871,"brand=Mitera, color=Pink, category=Kanjeevaram...",Product: Mitera Pink & Gold-Toned Silk Blend W...
2,3,yes,11244988,-,0.5276,"brand=Mitera, color=Pink, category=Kanjeevaram...",Product: Mitera Pink & Gold-Toned Silk Blend W...
3,4,yes,18302880,-,0.4567,"brand=Mitera, color=Pink, category=Kanjeevaram...",Product: Mitera Pink & Gold-Toned Woven Design...
4,5,yes,11454958,-,0.3676,"brand=Mitera, color=Pink, category=Banarasi, o...",Product: Mitera Pink & Golden Woven Design Ban...
5,6,yes,15012182,-,0.3011,"brand=Mitera, color=Pink, category=Banarasi, o...",Product: Mitera Pink & Silver-Toned Paisley Za...
6,7,no,14850332,-,0.1085,"brand=Mitera, color=Pink, category=Banarasi, o...",Product: Mitera Pink & Gold-Toned Woven Design...

,rank,hit,section_id,title,score,metadata,preview
0,1,no,18782340,-,0.9049,"brand=max, color=Brown, occasion=Daily, price=...",Product: max Women Brown Kurta Brand: max Colo...
1,2,no,19240558,-,0.8884,"brand=max, color=Rust, occasion=Daily, price=5...",Product: max Women Rust Kurta Brand: max Color...
2,3,no,17748850,-,0.7073,"brand=max, color=Black, occasion=Daily, price=...",Product: max Black Pure Cotton Dupatta Brand: ...
3,4,no,18782346,-,0.6569,"brand=max, color=Blue, occasion=Daily, price=4...",Product: max Women Blue Paisley Kurta Brand: m...
4,5,no,16464196,-,0.6318,"brand=max, color=Black, occasion=Daily, price=...",Product: max Black Solid Dupatta Brand: max Co...
5,6,no,19240492,-,0.6169,"brand=max, color=Blue, occasion=Daily, price=5...",Product: max Women Blue Yoke Design Kurta Bran...
6,7,no,15266700,-,0.6087,"brand=max, color=Beige, occasion=Daily, price=...",Product: max Beige Pure Cotton Dupatta Brand: ...
7,8,no,19240508,-,0.5903,"brand=max, color=Mustard, occasion=Daily, pric...",Product: max Women Mustard Yellow Yoke Design ...
8,9,no,15119222,-,0.5898,"brand=max, color=Red, occasion=Daily, price=499.0",Product: max Women Red Ethnic Motifs Printed K...
9,10,no,19068142,-,0.5799,"brand=max, color=Blue, occasion=Daily, price=1...",Product: max Women Blue Floral Printed Flared ...
10,11,no,15119204,-,0.5596,"brand=max, color=Black, occasion=Daily, price=...",Product: max Women Black Ethnic Motifs Yoke De...
11,12,no,19069132,-,0.5578,"brand=max, color=Yellow, occasion=Daily, price...",Product: max Yellow & Silver-Toned Embroidered...
12,13,no,15266776,-,0.5401,"brand=max, color=Navy Blue, occasion=Daily, pr...",Product: max Navy Blue Pure Cotton Dupatta wit...
13,14,no,19240582,-,0.5267,"brand=max, color=Green, occasion=Daily, price=...",Product: max Women Green Flared Sleeves Kurta ...
14,15,no,17469612,-,0.5256,"brand=max, color=Maroon, occasion=Daily, price...",Product: max Women Maroon Floral Embroidered K...
15,16,no,15781530,-,0.5200,"brand=max, color=Mustard, occasion=Daily, pric...",Product: max Mustard Viscose Rayon Dupatta Bra...
16,17,no,19240524,-,0.5130,"brand=max, color=Olive, occasion=Daily, price=...",Product: max Women Olive Green Geometric Print...
17,18,no,15266714,-,0.5031,"brand=max, color=Coral, occasion=Daily, price=...",Product: max Coral Pure Cotton Dupatta Brand: ...
18,19,no,18782350,-,0.4988,"brand=max, color=Fuchsia, occasion=Daily, pric...",Product: max Women Fuchsia Kurta Brand: max Co...
19,20,no,19068162,-,0.4667,"brand=max, color=Rust, occasion=Daily, price=5...",Product: max Women Rust Ethnic Motifs Printed ...
20,21,no,15781516,-,0.4624,"brand=max, color=Green, occasion=Daily, price=...",Product: max Green Viscose Rayon Solid Dupatta...
21,22,no,15266736,-,0.4556,"brand=max, color=Blue, occasion=Daily, price=2...",Product: max Blue Pure Cotton Dupatta with Tas...
22,23,no,19240544,-,0.4379,"brand=max, color=Green, occasion=Daily, price=...",Product: max Women Green Geometric Embroidered...
23,24,no,19240516,-,0.3951,"brand=max, color=Fuchsia, occasion=Daily, pric...",Product: max Women Fuchsia Ethnic Motifs Kurta...
24,25,no,19068150,-,0.3878,"brand=max, color=Green, occasion=Daily, price=...",Product: max Women Green Keyhole Neck Thread W...
25,26,no,15266716,-,0.3835,"brand=max, color=Red, occasion=Daily, price=399.0",Product: max Red Dupatta with Tasseled Border ...
26,27,no,14443728,-,0.3456,"brand=max, color=Orange, occasion=Daily, price...",Product: max Orange Dupatta with Beads and Sto...
27,28,no,19241696,-,0.3334,"brand=max, color=Blue, category=Kurti, occasio...",Product: max Women Blue Printed Kurti with Pal...
28,29,no,16228478,-,0.0767,"brand=max, color=Green, occasion=Daily, price=...",Product: max Green Geometric Embroidered Threa...

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,14094106,-,0.9659,"brand=Roadster, color=Navy Blue, occasion=Casu...",Product: Roadster Women Deep Navy Blue High-Ri...
1,2,no,5447351,-,0.8905,"brand=Roadster, color=Navy Blue, category=Card...",Product: Roadster Women Navy Blue Striped Card...
2,3,yes,12278640,-,0.8312,"brand=Roadster, color=Navy Blue, occasion=Casu...",Product: Roadster Women Navy Blue Flared Fit H...
3,4,no,11296068,-,0.8257,"brand=Roadster, color=Navy Blue, category=Regu...",Product: Roadster Women Navy Blue Solid Bell S...
4,5,no,13700180,-,0.7619,"brand=Roadster, color=Navy Blue, category=Stra...",Product: Roadster Women Navy Blue Solid Straig...
5,6,no,14331672,-,0.6854,"brand=Roadster, color=Navy Blue, category=Pull...",Product: Roadster Women Navy Blue & Pink Strip...
6,7,no,14094050,-,0.6821,"brand=Roadster, color=Navy Blue, occasion=Casu...",Product: Roadster Women Deep Navy Blue High-Ri...
7,8,yes,12278652,-,0.6348,"brand=Roadster, color=Navy Blue, occasion=Casu...",Product: Roadster Women Navy Blue Bootcut Mid-...
8,9,no,14535816,-,0.6276,"brand=Roadster, color=Navy Blue, category=Deni...",Product: Roadster Women Pure Cotton Navy Blue ...
9,10,yes,16187090,-,0.6190,"brand=Roadster, color=Navy Blue, occasion=Casu...",Product: The Roadster Lifestyle Co Women Navy ...
10,11,no,17074032,-,0.5982,"brand=Roadster, color=Navy Blue, category=Regu...",Product: Roadster Women Navy Blue & White Stri...
11,12,no,14356168,-,0.5707,"brand=Roadster, color=Navy Blue, category=Padd...",Product: Roadster Women Navy Blue & Maroon Col...
12,13,yes,15897498,-,0.5503,"brand=Roadster, color=Navy Blue, occasion=Casu...",Product: The Roadster Lifestyle Co Women Navy ...
13,14,no,14356146,-,0.5484,"brand=Roadster, color=Navy Blue, category=Tail...",Product: Roadster Women Navy Blue Convertible ...
14,15,yes,8963467,-,0.5450,"brand=Roadster, color=Navy Blue, occasion=Casu...",Product: The Roadster Lifestyle Co Women Navy ...
15,16,no,14925764,-,0.5320,"brand=Roadster, color=Navy Blue, occasion=Casu...",Product: Roadster Women Navy Blue Pure Cotton ...
16,17,yes,11987092,-,0.5319,"brand=Roadster, color=Navy Blue, occasion=Casu...",Product: Roadster Women Navy Blue & Green Chec...
17,18,no,15088232,-,0.4963,"brand=Roadster, color=Navy Blue, category=Swea...",Product: Roadster Women Navy Blue Solid Half-Z...
18,19,no,11688510,-,0.4914,"brand=Roadster, color=Navy Blue, category=Deni...",Product: Roadster Women Navy Blue Washed Regul...
19,20,no,14356150,-,0.4588,"brand=Roadster, color=Navy Blue, category=Bomb...",Product: Roadster Women Navy Blue Grey Striped...
20,21,no,14535784,-,0.3238,"brand=Roadster, color=Navy Blue, category=Deni...",Product: Roadster Women Deep Navy Blue Solid D...
21,22,no,16833828,-,0.2958,"brand=Roadster, color=Navy Blue, category=Top,...",Product: The Roadster Lifestyle Co Women Navy ...
22,23,yes,8803831,-,0.2414,"brand=Roadster, color=Navy Blue, occasion=Casu...",Product: Roadster Women Navy Blue Skinny Fit M...
23,24,no,13756790,-,0.2348,"brand=Roadster, color=Navy Blue, category=Deni...",Product: Roadster X DISCOVERY ADVENTURES Women...

,rank,hit,section_id,title,score,metadata,preview
0,1,no,14541316,-,0.9660,"brand=KALINI, color=Orange, category=Saree, oc...",Product: KALINI Orange & Gold-Toned Ethnic Mot...
1,2,yes,14490860,-,0.8267,"brand=KALINI, color=Orange, category=Saree, oc...",Product: KALINI Orange & Gold-Toned Pure Chiff...
2,3,no,18390376,-,0.0000,"brand=KALINI, color=Orange, category=Kurta set...",Product: KALINI Women Orange Printed Pure Cott...

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,14646546,-,1.0000,"brand=HRX by Hrithik Roshan, color=Black, cate...",Product: HRX By Hrithik Roshan Outdoor Women W...
1,2,no,11383846,-,0.8000,"brand=Alcis, color=Black, category=Sporty jack...",Product: Alcis Nari Women Black Solid Lightwei...
2,3,no,15789142,-,0.7347,"brand=Slazenger, color=Black, category=Sporty ...",Product: Slazenger Women Black Running Sporty ...
3,4,no,15953824,-,0.7066,"brand=Columbia, color=Black, category=Padded j...",Product: Columbia Women Black Joy Peak Mid Hoo...
4,5,no,15743742,-,0.6817,"brand=ADIDAS, color=Black, category=Sporty jac...",Product: ADIDAS Women Black Solid Essential In...
5,6,no,18144568,-,0.6765,"brand=Marks & Spencer, color=Black, category=P...",Product: Marks & Spencer Women Black Padded Ja...
6,7,no,13609880,-,0.6679,"brand=HRX by Hrithik Roshan, color=Black, cate...",Product: HRX by Hrithik Roshan Men Jet Black S...
7,8,no,15389978,-,0.6631,"brand=PERFKT-U, color=Black, category=Sporty j...",Product: PERFKT-U Women Black & Mustard Yellow...
8,9,no,15963194,-,0.6345,"brand=Columbia, color=Black, category=Sporty j...",Product: Columbia Women Black Kruser Ridge II ...
9,10,no,15953844,-,0.6276,"brand=Columbia, color=Black, category=Quilted ...",Product: Columbia Women Black Delta Ridge Down...
10,11,no,15953812,-,0.6224,"brand=Columbia, color=Black, category=Quilted ...",Product: Columbia Women Black Delta Ridge Down...
11,12,no,14562576,-,0.5952,"brand=HRX by Hrithik Roshan, color=Black, cate...",Product: HRX by Hrithik Roshan Women Black & W...
12,13,no,14968448,-,0.5781,"brand=Chkokko, color=Black, category=Sporty ja...",Product: Chkokko Women Black & Red Gym Sporty ...
13,14,no,1753301,-,0.5609,"brand=Amante, color=Black, category=Sports sho...",Product: Amante Women Black Sports Shorts Bran...
14,15,no,8386077,-,0.5594,"brand=The Pink Moon, color=Black, category=Spo...",Product: The Pink Moon Plus Size Women Black S...
15,16,no,16182100,-,0.4227,"brand=Ajile by Pantaloons, color=Black, catego...",Product: Ajile by Pantaloons Women Black Pure ...
16,17,no,14704920,-,0.4191,"brand=HRX by Hrithik Roshan, color=Black, cate...",Product: HRX By Hrithik Roshan Lifestyle Women...
17,18,no,17750194,-,0.4080,"brand=Jinfo, color=Black, category=Sports shor...",Product: Jinfo Women Black Cycling Sports Shor...
18,19,no,17199012,-,0.3977,"brand=JUMP USA, color=Black, category=Sports s...",Product: JUMP USA Women Black Outdoor Sports S...
19,20,no,17378518,-,0.3599,"brand=HRX by Hrithik Roshan, color=Black, cate...",Product: HRX By Hrithik Roshan Lifestyle Women...
20,21,no,17760320,-,0.3547,"brand=Jinfo, color=Black, category=Sports shor...",Product: Jinfo Women Black & White Set of 3 So...
21,22,no,12940070,-,0.3333,"brand=Revolution, color=Black, category=Sports...",Product: Revolution Women Plus Size Black Soli...
22,23,no,12865416,-,0.2637,"brand=Chkokko, color=Black, category=Sports sh...",Product: Chkokko Women Black Side Panelled Reg...
23,24,no,11687104,-,0.1457,"brand=Besiva, color=Black, category=Top, occas...",Product: Besiva Women Black & Off-White Printe...
24,25,no,18750114,-,0.1444,"brand=DeFacto, color=Black, category=Biker sho...",Product: DeFacto Women Black Skinny Fit Biker ...
25,26,no,16960714,-,0.1413,"brand=EVERDION, color=Black, category=Top, occ...",Product: EVERDION Women Black Top With Shorts ...
26,27,no,13695224,-,0.1334,"brand=HRX by Hrithik Roshan, color=Black, cate...",Product: HRX By Hrithik Roshan Women Jet Black...
27,28,no,17760310,-,0.1282,"brand=Jinfo, color=Black, category=Biker short...",Product: Jinfo Women Black Solid Cycling Short...
28,29,no,17760268,-,0.1235,"brand=Jinfo, color=Black, category=Biker short...",Product: Jinfo Women Black Solid Cycling Short...
29,30,no,16995282,-,0.1201,"brand=ADIDAS, color=Black, category=Regular sh...",Product: ADIDAS Women Black & Yellow Run Fast ...

Empty DataFrame
Columns: []
Index: []

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,16504028,-,0.8484,"brand=ANVI Be Yourself, color=Blue, category=P...",Product: ANVI Be Yourself Women Stunning Blue ...
1,2,no,14641744,-,0.7464,"brand=FabAlley, color=Blue, category=Peplum, o...",Product: FabAlley Blue Puff Sleeve Chambray Pe...
2,3,no,18514120,-,0.7447,"brand=Paralians, color=Turquoise Blue, categor...",Product: Paralians Turquoise Blue Peplum Top B...
3,4,no,11607414,-,0.6649,"brand=Bhama Couture, color=Blue, category=Pepl...",Product: Bhama Couture Women Blue Printed Pepl...
4,5,no,11607374,-,0.6359,"brand=Bhama Couture, color=Blue, category=Pepl...",Product: Bhama Couture Women Blue Printed Pepl...
5,6,no,18805426,-,0.5692,"brand=BoStreet, color=Blue, category=Peplum, o...",Product: BoStreet Blue Checked Peplum Top Bran...
6,7,no,17445656,-,0.5165,"brand=Vishudh, color=Blue, category=Peplum, oc...",Product: Vishudh Blue Floral Print Peplum Top ...
7,8,no,17872080,-,0.5146,"brand=Taavi, color=Blue, category=Peplum, occa...",Product: Taavi Women Indigo & White Indigo Pri...
8,9,no,8715089,-,0.5028,"brand=plusS, color=Blue, category=Peplum, occa...",Product: plusS Women Blue Printed Peplum Top B...
9,10,no,10783322,-,0.5014,"brand=Sera, color=Navy Blue, category=Peplum, ...",Product: Sera Women Navy Blue Printed Peplum P...
10,11,no,14231406,-,0.4441,"brand=all about you, color=Blue, category=Pull...",Product: all about you Women Blue Self-Design ...
11,12,no,14867398,-,0.4260,"brand=Janasya, color=Blue, category=Peplum, oc...",Product: Janasya Women Blue & White Floral Ruf...
12,13,no,18604646,-,0.4090,"brand=Zink London, color=Blue, category=A-line...",Product: Zink London Women Blue Floral Lace De...
13,14,no,14424654,-,0.3975,"brand=ROOTED, color=Navy Blue, category=Peplum...",Product: ROOTED Navy Blue Printed Peplum Top B...
14,15,no,17566228,-,0.3952,"brand=Inddus, color=Blue, category=Top, occasi...",Product: Inddus Women Blue Woven Design Top & ...
15,16,no,16950218,-,0.3588,"brand=Indo Era, color=Blue, category=Peplum, o...",Product: Indo Era Blue Ethnic Motif Printed Pe...
16,17,no,17627582,-,0.3560,"brand=kipek, color=Navy Blue, category=Top, oc...",Product: kipek Women Deep Navy Blue Solid Top ...
17,18,no,15766290,-,0.3501,"brand=Pepe Jeans, color=Blue, category=Regular...",Product: Pepe Jeans Women Blue Pure Cotton Tro...
18,19,no,18998716,-,0.3475,"brand=KALINI, color=Blue, category=Peplum, occ...",Product: KALINI Blue Print Indigo Pure Cotton ...
19,20,no,13385158,-,0.3364,"brand=Gipsy, color=Blue, category=Pullover, oc...",Product: Gipsy Women Blue Self Design Sweatshi...
20,21,no,2137522,-,0.3333,"brand=Tokyo Talkies, color=Blue, category=Regu...",Product: Tokyo Talkies Women Blue Self Design ...
21,22,no,18454274,-,0.3208,"brand=Albion, color=Blue, category=A-line, occ...",Product: Albion Girls Blue Solid Denim A-Line ...
22,23,no,17132226,-,0.3135,"brand=Athena, color=Blue, category=Regular, oc...",Product: Athena Women Stunning Blue Self-Desig...
23,24,no,13495564,-,0.2960,"brand=GRACIT, color=Navy Blue, occasion=Ethnic...",Product: GRACIT Women Navy Blue Self Design Co...
24,25,no,19087886,-,0.2899,"brand=ONLY, color=Blue, category=Pullover, occ...",Product: ONLY Women Blue Acrylic Pullover Bran...
25,26,no,13499958,-,0.2846,"brand=Oxolloxo, color=Navy Blue, occasion=Casu...",Product: Oxolloxo Women Navy Blue Self-Design ...
26,27,no,16935640,-,0.2656,"brand=flaher, color=Blue, occasion=Festive, pr...",Product: flaher Women Blue Solid Art Silk Padd...
27,28,no,14658916,-,0.2545,"brand=Pepe Jeans, color=Blue, category=Regular...",Product: Pepe Jeans Women Blue Washed Mid-Rise...
28,29,no,17403254,-,0.2428,"brand=I Saw It First, color=Blue, occasion=Cas...",Product: I Saw It First Women Blue Skinny Fit ...
29,30,no,17403428,-,0.2365,"brand=I Saw It First, color=Blue, occasion=Cas...",Product: I Saw It First Women Blue Skinny Fit ...

,rank,hit,section_id,title,score,metadata,preview
0,1,yes,16533076,-,1.0,"brand=Madame, color=Peach, category=Pullover, ...",Product: Madame Women Peach-Coloured Self Desi...
1,2,no,18948340,-,0.0,"brand=Madame, color=Peach, category=Styled bac...",Product: Madame Peach-Coloured Cuffed Sleeves ...

      precision  recall    mrr   ndcg  context_relevance
mean      0.212    0.64  0.516  0.551              0.795

,question,relevant_docs,retrieved_docs,precision,recall,mrr,ndcg,context_relevance,retrieval_metadata
0,"Can you find something similar to ""Mitera Grey...",[16950080],"[16950080, 17413544, 19276886, 16615812, 18302...",0.166667,1.000,1.000000,1.000000,1.00,"brand == Mitera, color == Grey"
1,Show me Regular trousers within a budget of 2000.,"[17817750, 18770002, 18769968, 18769944, 18769...","[16279046, 14220194, 13523706, 13647622, 13769...",0.000000,0.000,0.000000,0.000000,0.75,price <= 2000.0
2,"Can you find something similar to ""Athena Wome...",[11166548],"[11166548, 10758214, 12086086, 11634534, 11634...",0.200000,1.000,1.000000,1.000000,1.00,"brand == Athena, color == Burgundy"
3,"Show me products like ""InWeave Women Red Print...",[18921114],"[18921114, 17168254, 15760840, 13497800, 18922...",0.200000,1.000,1.000000,1.000000,1.00,"brand == InWeave, color == Red"
4,I need product with a Woven design pattern in ...,"[12824928, 18262088]","[10451734, 19218994, 18122478, 17663018, 16719...",0.066667,1.000,0.076923,0.288586,1.00,color == Mustard
5,I'm looking for products from MANGO for everyd...,"[15315768, 15265896, 15265898, 16892568, 15977...",[],0.000000,0.000,0.000000,0.000000,0.00,"brand == MANGO, occasion == Daily, price <= 56..."
6,What do you have from Sweet Dreams in Playsuit...,"[11581420, 11581366]","[11581420, 11581448, 11581366, 12882594]",0.500000,1.000,1.000000,0.919721,1.00,"brand == Sweet Dreams, color == Pink"
7,I'm looking for Kurta set by Vishudh.,"[13536726, 15997054, 18262138, 13119222, 18263...","[13799826, 14860664, 13536726, 7572969, 159970...",0.266667,1.000,0.333333,0.625509,1.00,brand == Vishudh
8,I'm looking for A-line by Ancestry.,"[15407228, 19152780, 14873702]","[14873856, 15407228, 14873702, 19152780, 14873...",0.250000,1.000,0.500000,0.732829,1.00,brand == Ancestry
9,"Can you find something similar to ""FASHOR Wome...",[19140952],"[19140952, 18964098, 19198414, 19324632]",0.250000,1.000,1.000000,1.000000,1.00,"brand == FASHOR, color == Blue"
10,Show me Blue Tailored jacket from Darzi.,[14460680],"[14460680, 17665702]",0.500000,1.000,1.000000,1.000000,1.00,"brand == Darzi, color == Blue"
11,"Can you find something similar to ""U.S. Polo A...",[13703470],[13703470],1.000000,1.000,1.000000,1.000000,0.50,"brand == U.S. Polo Assn., color == Beige"
12,Does Mitera have any Bandhani for a festive oc...,[15637468],"[15637468, 17325496, 17325492, 17325498, 17325...",0.033333,1.000,1.000000,1.000000,0.50,"brand == Mitera, occasion == Festive, price <=..."
13,Show me Pencil within a budget of 1500.,"[15940138, 9552849, 15301318, 12086086, 188349...","[14011652, 1294879, 18215398, 14798956, 178991...",0.000000,0.000,0.000000,0.000000,0.50,price <= 1500.0
14,Do you have any Mustard Blouson for everyday w...,[13532718],"[18456682, 10451734, 17090522, 2076112, 181982...",0.000000,0.000,0.000000,0.000000,0.75,"color == Mustard, occasion == Daily"
15,I need Blue Joggers by STREET 9.,"[13038932, 13071994]","[13071994, 13038932, 5389019, 15803276, 660851...",0.086957,1.000,1.000000,1.000000,1.00,"brand == STREET 9, color == Blue"
16,Show me Front-open within a budget of 2800.,"[16382036, 16382150, 5829334, 5829327, 1199121...","[14382336, 16082246, 17685090, 19087856, 22231...",0.033333,0.125,0.037037,0.052616,0.50,price <= 2800.0
17,Do you have anything from FILA in Red for ever...,[13255768],[],0.000000,0.000,0.000000,0.000000,0.00,"brand == FILA, color == Red, occasion == Daily"
18,I'm looking for products that cost no more tha...,"[13135238, 15241584, 13181706, 17739302, 15218...","[17403640, 2117164, 17403254, 13452734, 174034...",0.000000,0.000,0.000000,0.000000,0.50,price <= 1100.0
19,Do you have anything from Bhama Couture in A-l...,"[12151804, 10355827, 10356731, 12151824, 10717...","[9430121, 9430115, 13969870, 11672988, 9717189...",0.266667,1.000,0.166667,0.574384,1.00,brand == Bhama Couture
20,Do you have any Pink Peg trousers for everyday...,[15473916],"[15749796, 16891228, 14708328, 15582360, 10317...",0.000000,0.000,0.000000,0.000000,1.00,"color == Pink, occasion == Daily"
21,Show me Regular shorts within a budget of 1800.,"[15402090, 14170730, 18283554, 18747132, 16164...","[13523706, 14272032, 13647622, 13769372, 96214...",0.033333,0.125,0.125000,0.079795,1.00,price <= 1800.0
22,I'm looking for Regular by H&M.,"[17964932, 17883620, 18652012, 14258606, 18084...","[17674588, 17965024, 12383500, 17883650, 17842...",0.200000,0.750,1.000000,0.600966,1.00,brand == H&M
23,I need Pink Saree by KALINI.,"[15858094, 17852902, 15102290, 14678908, 16421...","[16914910, 16421936, 15102290, 17852902, 14678...",0.384615,1.000,0.500000,0.781651,1.00,"brand == KALINI, color == Pink"
24,Show me products within a budget of 1800.,"[17094636, 13905652, 13905672, 13905666, 23229...","[13523706, 17226172, 13647622, 13769372, 17570...",0.000000,0.000,0.000000,0.000000,0.50,price <= 1800.0
25,I need product with a Other woven design patte...,"[16379852, 16379914, 15768366]","[16379914, 15768366, 16379852, 11379820, 13104...",0.100000,1.000,1.000000,1.000000,1.00,color == Red
26,Do you have anything from SERONA FABRICS in Wh...,[15917640],[15917640],1.000000,1.000,1.000000,1.000000,1.00,"brand == SERONA FABRICS, color == White, occas..."
27,Do you have any Green Kurta set for a festive ...,"[17140156, 16505434, 14121912, 16825614, 16707...","[15258422, 17447636, 17232410, 16707970, 12989...",0.266667,1.000,0.333333,0.647436,1.00,"color == Green, occasion == Festive"
28,I'm looking for something Black from URBANIC f...,"[15849954, 15634138, 18929182, 15086606, 15633...",[],0.000000,0.000,0.000000,0.000000,0.00,"brand == URBANIC, color == Black, occasion == ..."
29,Show me Black products for everyday wear.,"[9440729, 18207452, 18992236, 16612058, 907371...","[16379842, 16379878, 2380261, 19296144, 104517...",0.000000,0.000,0.000000,0.000000,1.00,"color == Black, occasion == Daily"
30,I'm looking for something Blue from Swasti for...,[18819296],[18819296],1.000000,1.000,1.000000,1.000000,1.00,"brand == Swasti, color == Blue, occasion == Daily"
31,I need Shirt style with a Abstract printed pat...,[13244594],"[13244594, 15841446, 19195222, 19201936, 18605...",0.033333,1.000,1.000000,1.000000,0.75,color == Pink
32,I'm looking for products by Atsevam.,"[17754230, 17754250, 17754248, 19217168, 19217...","[17754230, 17754248, 19217168, 17754250, 19217...",0.700000,1.000,1.000000,0.964241,1.00,brand == Atsevam
33,What do you have from panchhi in products and ...,"[19046346, 12003682]","[18070000, 19046346, 18175384, 12003682]",0.500000,1.000,0.500000,0.650921,1.00,"brand == panchhi, color == Pink"
34,What do you have in products under 2500?,"[11765970, 17662818, 15514544, 18068482, 16989...","[16858560, 19177952, 17612960, 16172382, 18489...",0.000000,0.000,0.000000,0.000000,1.00,price <= 2500.0
35,Show me products from Indo Era.,"[14239788, 11459668, 12040868, 15520698, 12040...","[14869156, 16188740, 12122360, 16950290, 12040...",0.166667,0.625,0.333333,0.439488,1.00,brand == Indo Era
36,"Show me products like ""ONLY Women Blue Straigh...",[18626222],"[18626222, 18620390, 16372376, 18626210, 19089...",0.033333,1.000,1.000000,1.000000,1.00,"brand == ONLY, color == Blue"
37,Do you have anything from Uptownie Lite in Fla...,"[17944738, 16608122, 11511460, 11425704, 13467...","[17944738, 11425704, 11425706, 13467524, 11511...",0.333333,1.000,1.000000,0.943473,1.00,brand == Uptownie Lite
38,"Do you have anything similar to ""Suta Beige & ...",[15243956],"[15243956, 14988280, 16909300, 15244224, 15244...",0.111111,1.000,1.000000,1.000000,1.00,"brand == Suta, (color == Beige, color == White..."
39,"Show me options from Levis for everyday wear, ...","[18069226, 16532142, 18069298, 18069260, 16653...",[],0.000000,0.000,0.000000,0.000000,0.00,"brand == Levis, color == Blue, occasion == Daily"
40,Show me Pullover that are Black and have Solid...,"[16707678, 16124454, 13534776, 15964092, 15274...","[19266888, 15845464, 17038044, 9478497, 140808...",0.100000,0.375,0.062500,0.170996,1.00,color == Black
41,I'm looking for Dress that cost no more than 5...,"[13878542, 17705690, 18365368, 16921564, 16921...","[17403640, 13843640, 17403254, 13452734, 17403...",0.000000,0.000,0.000000,0.000000,0.50,price <= 5300.0
42,I'm looking for something Pink from Mitera for...,"[15012182, 11454958, 11244988, 18302880]","[13886174, 11218670, 11244988, 18302880, 11454...",0.571429,1.000,0.333333,0.653393,1.00,"brand == Mitera, color == Pink, occasion == Tr..."
43,I'm looking for Pullover from max for everyday...,"[19204850, 15878996, 16156132]","[18782340, 19240558, 17748850, 18782346, 16464...",0.000000,0.000,0.000000,0.000000,0.50,"brand == max, occasion == Daily, price <= 600.0"
44,What do you have from Roadster in products and...,"[12278640, 11987092, 8803831, 8963467, 1227865...","[14094106, 5447351, 12278640, 11296068, 137001...",0.333333,1.000,1.000000,0.777823,1.00,"brand == Roadster, color == Navy Blue"
45,Show me Orange Saree from KALINI.,[14490860],"[14541316, 14490860, 18390376]",0.333333,1.000,0.500000,0.630930,1.00,"brand == KALINI, color == Orange"
46,Do you have any Black Tailored jacket for sports?,[14646546],"[14646546, 11383846, 15789142, 15953824, 15743...",0.033333,1.000,1.000000,1.000000,1.00,"color == Black, occasion == Sports"
47,Do you have anything from Roadster in Grey for...,"[13756948, 8319213, 13339544, 14954872, 103882...",[],0.000000,0.000,0.000000,0.000000,0.00,"brand == Roadster, color == Grey, occasion == ..."
48,I need Peplum with a Self design solid pattern...,[16504028],"[16504028, 14641744, 18514120, 11607414, 11607...",0.033333,1.000,1.000000,1.000000,0.50,color == Blue
49,I need Peach Pullover by Madame.,[16533076],"[16533076, 18948340]",0.500000,1.000,1.000000,1.000000,1.00,"brand == Madame, color == Peach"