In [1]:
# get faq retriever
# create list queries
# get documents
# evaluation result (use precesion@k, recall@k, mrr, nDCG)

In [2]:
import sys
sys.path.append("../")

In [3]:
# get faq retriever
from pathlib import Path

from html import escape

import pandas as pd
from IPython.display import HTML, display

from evaluation.eval import evaluate_retrieval, load_tests, context_relevance
from evaluation.classes import ContextRelevanceWrapper
from evaluation.reporting import export_retrieval_report_to_markdown
from retrieval.faq_retriever import search_faq_hybrid

/Users/ayeustsihneyeu/PythonProjects/hybrid-rag-system/.hybrag/lib/python3.14/site-packages/langchain_core/_api/deprecation.py:25: UserWarning: Core Pydantic V1 functionality isn't compatible with Python 3.14 or greater.
  from pydantic.v1.fields import FieldInfo as FieldInfoV1
/Users/ayeustsihneyeu/PythonProjects/hybrid-rag-system/.hybrag/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
def retrieving(test, top_k):
    context = search_faq_hybrid(test.question, top_k=top_k)
    nodes = getattr(context, "nodes", context)
    return nodes

In [5]:
def _node_metadata(item):
    if hasattr(item, "node"):
        return getattr(item.node, "metadata", {}) or {}
    return getattr(item, "metadata", {}) or {}


def _node_score(item):
    score = getattr(item, "score", None)
    return round(score, 4) if isinstance(score, (int, float)) else None


def _node_text(item):
    node = getattr(item, "node", item)
    if hasattr(node, "get_content"):
        return node.get_content()
    return getattr(node, "text", "") or ""


def _preview(text, max_len=180):
    cleaned = " ".join(str(text).split())
    if len(cleaned) <= max_len:
        return cleaned
    return cleaned[: max_len - 3] + "..."


def _render_metrics(metrics):
    metrics_html = "".join(
        f"""
        <div style='padding:12px 14px;border:1px solid #d0d7de;border-radius:10px;background:#f6f8fa;'>
            <div style='font-size:12px;color:#57606a;text-transform:uppercase;letter-spacing:.04em;'>{escape(name)}</div>
            <div style='font-size:24px;font-weight:700;color:#24292f;'>{value:.3f}</div>
        </div>
        """
        for name, value in metrics.items()
    )
    display(HTML(f"<div style='display:grid;grid-template-columns:repeat(4, minmax(0, 1fr));gap:12px;margin:12px 0 18px;'>{metrics_html}</div>"))


def _render_question_report(test, nodes, metrics, index, total):
    relevant_docs = set(test.relevant_docs)
    doc_rows = []

    for rank, item in enumerate(nodes, start=1):
        metadata = _node_metadata(item)
        section_id = metadata.get("section_id")
        doc_rows.append(
            {
                "rank": rank,
                "hit": "yes" if section_id in relevant_docs else "no",
                "section_id": section_id,
                "title": metadata.get("section_title", "-"),
                "score": _node_score(item),
                "preview": _preview(_node_text(item)),
            }
        )

    header_html = f"""
    <div style='margin:28px 0 10px;'>
        <div style='font-size:12px;color:#57606a;text-transform:uppercase;letter-spacing:.08em;'>Question {index}/{total}</div>
        <div style='font-size:22px;font-weight:700;margin:6px 0 10px;color:#24292f;'>{escape(test.question)}</div>
        <div style='padding:12px 14px;background:#fff8c5;border:1px solid #e3d279;border-radius:10px;'>
            <div style='font-size:12px;color:#57606a;text-transform:uppercase;letter-spacing:.04em;margin-bottom:6px;'>Relevant docs</div>
            <div style='font-size:16px;font-weight:600;color:#24292f;'>{escape(str(test.relevant_docs))}</div>
        </div>
    </div>
    """
    display(HTML(header_html))
    display(pd.DataFrame(doc_rows))
    filtered_metrics = {
            key: value
            for key, value in metrics.items()
            if key.startswith("precision") or key.startswith("recall") or key == "mrr" or key.startswith("ndcg") or key == "context_relevance"
    }
    _render_metrics(filtered_metrics)
    return {
        "question": test.question,
        "relevant_docs": list(test.relevant_docs),
        "metrics": filtered_metrics,
        "doc_rows": doc_rows,
    }


async def evaluate_all_retrieval(limit=None, top_k=5, markdown_path=None):
    """Render a readable retrieval report for the FAQ notebook."""

    tests = load_tests()
    selected_tests = tests[:limit] if limit is not None else tests
    rows = []
    question_reports = []

    for index, test in enumerate(selected_tests, start=1):
        nodes = retrieving(test, top_k)
        
        metrics = evaluate_retrieval(test, nodes, k=top_k)
        
        result = await context_relevance(ContextRelevanceWrapper(question=test.question, contexts=[_node_text(item) for item in nodes]))
        metrics["context_relevance"] = result
        rows.append(metrics)
        question_report = _render_question_report(test, nodes, metrics, index=index, total=len(selected_tests))
        question_report.update({"index": index, "total": len(selected_tests)})
        question_reports.append(question_report)

    
    report_df = pd.DataFrame(rows)
    metric_columns = [column for column in report_df.columns if column.startswith(("precision", "recall", "ndcg")) or column in {"mrr", "context_relevance"}]
    summary_df = report_df[metric_columns].mean().to_frame(name="mean").T.round(3)

    display(HTML("<h2 style='margin:32px 0 12px;color:#24292f;'>Final metrics</h2>"))
    display(summary_df)

    if markdown_path is not None:
        saved_path = export_retrieval_report_to_markdown(
            report_df,
            question_reports,
            Path(markdown_path),
            notebook_path="notebooks/08_faq_retrieving.ipynb",
        )
        display(HTML(f"<p style='margin:12px 0 0;color:#1a7f37;'>Markdown report saved to: <code>{escape(str(saved_path))}</code></p>"))

    return report_df

In [6]:
await evaluate_all_retrieval(markdown_path="../reports/faq_retrieving_evaluation.md")

,rank,hit,section_id,title,score,preview
0,1,yes,1,How to register with an email,1.0000,How to register with an email Open the registr...
1,2,no,2,How to register with Google or Facebook account,0.7572,How to register with Google or Facebook accoun...
2,3,no,6,Can I have more than one HopShop account,0.6783,"Can I have more than one HopShop account Yes, ..."
3,4,no,4,How to register with your phone number,0.6718,How to register with your phone number Open th...
4,5,no,49,How to provide shipping details?,0.5984,How to provide shipping details? If you have a...

,rank,hit,section_id,title,score,preview
0,1,yes,2,How to register with Google or Facebook account,1.0000,How to register with Google or Facebook accoun...
1,2,no,6,Can I have more than one HopShop account,0.3925,"Can I have more than one HopShop account Yes, ..."
2,3,no,1,How to register with an email,0.3479,How to register with an email Open the registr...
3,4,no,3,Signing in with a password and email address,0.3165,Signing in with a password and email address I...
4,5,no,75,How to find a pick-up point or parcel locker c...,0.2981,How to find a pick-up point or parcel locker c...

,rank,hit,section_id,title,score,preview
0,1,yes,3,Signing in with a password and email address,1.0000,Signing in with a password and email address I...
1,2,no,1,How to register with an email,0.5002,How to register with an email Open the registr...
2,3,no,2,How to register with Google or Facebook account,0.4137,How to register with Google or Facebook accoun...
3,4,no,51,How can I track a parcel?,0.2763,How can I track a parcel? You can track your p...
4,5,no,49,How to provide shipping details?,0.2745,How to provide shipping details? If you have a...

,rank,hit,section_id,title,score,preview
0,1,yes,4,How to register with your phone number,0.9981,How to register with your phone number Open th...
1,2,yes,4,How to register with your phone number,0.7469,"your account within 3 business days, and retur..."
2,3,no,1,How to register with an email,0.7295,How to register with an email Open the registr...
3,4,no,2,How to register with Google or Facebook account,0.7202,How to register with Google or Facebook accoun...
4,5,no,6,Can I have more than one HopShop account,0.5973,"Can I have more than one HopShop account Yes, ..."

,rank,hit,section_id,title,score,preview
0,1,yes,5,GDPR — how you can download your personal data...,1.0000,GDPR — how you can download your personal data...
1,2,no,7,How to close your HopShop account,0.4022,How to close your HopShop account You can end ...
2,3,no,8,Withdrawing from the agreement with HopShop,0.3430,Withdrawing from the agreement with HopShop
3,4,no,6,Can I have more than one HopShop account,0.3419,"Can I have more than one HopShop account Yes, ..."
4,5,no,11,What happens next,0.3291,"What happens next Usually, we consider the app..."

,rank,hit,section_id,title,score,preview
0,1,yes,6,Can I have more than one HopShop account,1.0000,"Can I have more than one HopShop account Yes, ..."
1,2,no,50,I am buying many products — which delivery met...,0.4687,I am buying many products — which delivery met...
2,3,no,40,HopShop gift cards,0.3480,HopShop gift cards If you are not sure what to...
3,4,no,46,Delivery options on HopShop,0.3384,Delivery options on HopShop When buying on Hop...
4,5,no,17,How to buy on HopShop,0.3276,"How to buy on HopShop In this article, you wil..."

,rank,hit,section_id,title,score,preview
0,1,yes,7,How to close your HopShop account,1.0000,How to close your HopShop account You can end ...
1,2,no,16,What you should do before the notice period ends,0.6209,What you should do before the notice period en...
2,3,no,6,Can I have more than one HopShop account,0.5572,"Can I have more than one HopShop account Yes, ..."
3,4,no,14,How to terminate the agreement,0.5248,How to terminate the agreement To terminate th...
4,5,no,2,How to register with Google or Facebook account,0.4653,How to register with Google or Facebook accoun...

,rank,hit,section_id,title,score,preview
0,1,no,9,When you can withdraw from the agreement,0.9444,When you can withdraw from the agreement You c...
1,2,yes,8,Withdrawing from the agreement with HopShop,0.7763,Withdrawing from the agreement with HopShop
2,3,no,10,How to withdraw from the agreement,0.7102,How to withdraw from the agreement To withdraw...
3,4,no,7,How to close your HopShop account,0.6644,How to close your HopShop account You can end ...
4,5,no,14,How to terminate the agreement,0.6312,How to terminate the agreement To terminate th...

,rank,hit,section_id,title,score,preview
0,1,yes,9,When you can withdraw from the agreement,0.9893,When you can withdraw from the agreement You c...
1,2,no,8,Withdrawing from the agreement with HopShop,0.7763,Withdrawing from the agreement with HopShop
2,3,no,10,How to withdraw from the agreement,0.6321,How to withdraw from the agreement To withdraw...
3,4,no,12,Termination of the agreement with HopShop,0.6318,Termination of the agreement with HopShop
4,5,no,13,When you can terminate the agreement,0.5695,When you can terminate the agreement You can t...

,rank,hit,section_id,title,score,preview
0,1,yes,10,How to withdraw from the agreement,1.0000,How to withdraw from the agreement To withdraw...
1,2,no,9,When you can withdraw from the agreement,0.8893,When you can withdraw from the agreement You c...
2,3,no,15,What happens next,0.6465,What happens next From the moment you submit t...
3,4,no,11,What happens next,0.6408,"What happens next Usually, we consider the app..."
4,5,no,13,When you can terminate the agreement,0.5964,When you can terminate the agreement You can t...

,rank,hit,section_id,title,score,preview
0,1,no,15,What happens next,0.8798,What happens next From the moment you submit t...
1,2,yes,11,What happens next,0.7769,"What happens next Usually, we consider the app..."
2,3,no,10,How to withdraw from the agreement,0.6791,How to withdraw from the agreement To withdraw...
3,4,no,6,Can I have more than one HopShop account,0.5799,"Can I have more than one HopShop account Yes, ..."
4,5,no,107,I have received a defective product. What shou...,0.5685,I have received a defective product. What shou...

,rank,hit,section_id,title,score,preview
0,1,no,14,How to terminate the agreement,0.9968,How to terminate the agreement To terminate th...
1,2,yes,12,Termination of the agreement with HopShop,0.7228,Termination of the agreement with HopShop
2,3,no,13,When you can terminate the agreement,0.7156,When you can terminate the agreement You can t...
3,4,no,7,How to close your HopShop account,0.7144,How to close your HopShop account You can end ...
4,5,no,8,Withdrawing from the agreement with HopShop,0.6965,Withdrawing from the agreement with HopShop

,rank,hit,section_id,title,score,preview
0,1,yes,13,When you can terminate the agreement,1.0000,When you can terminate the agreement You can t...
1,2,no,14,How to terminate the agreement,0.7686,How to terminate the agreement To terminate th...
2,3,no,9,When you can withdraw from the agreement,0.5905,When you can withdraw from the agreement You c...
3,4,no,12,Termination of the agreement with HopShop,0.4680,Termination of the agreement with HopShop
4,5,no,8,Withdrawing from the agreement with HopShop,0.4129,Withdrawing from the agreement with HopShop

,rank,hit,section_id,title,score,preview
0,1,yes,14,How to terminate the agreement,0.9968,How to terminate the agreement To terminate th...
1,2,no,12,Termination of the agreement with HopShop,0.7228,Termination of the agreement with HopShop
2,3,no,13,When you can terminate the agreement,0.7155,When you can terminate the agreement You can t...
3,4,no,7,How to close your HopShop account,0.7145,How to close your HopShop account You can end ...
4,5,no,8,Withdrawing from the agreement with HopShop,0.6965,Withdrawing from the agreement with HopShop

,rank,hit,section_id,title,score,preview
0,1,no,11,What happens next,0.9991,"What happens next Usually, we consider the app..."
1,2,yes,15,What happens next,0.9622,What happens next From the moment you submit t...
2,3,no,12,Termination of the agreement with HopShop,0.8042,Termination of the agreement with HopShop
3,4,no,14,How to terminate the agreement,0.7090,How to terminate the agreement To terminate th...
4,5,no,7,How to close your HopShop account,0.6650,How to close your HopShop account You can end ...

,rank,hit,section_id,title,score,preview
0,1,yes,16,What you should do before the notice period ends,1.0000,What you should do before the notice period en...
1,2,no,15,What happens next,0.5297,What happens next From the moment you submit t...
2,3,no,12,Termination of the agreement with HopShop,0.4207,Termination of the agreement with HopShop
3,4,no,8,Withdrawing from the agreement with HopShop,0.4162,Withdrawing from the agreement with HopShop
4,5,no,7,How to close your HopShop account,0.4125,How to close your HopShop account You can end ...

,rank,hit,section_id,title,score,preview
0,1,yes,17,How to buy on HopShop,0.9051,"How to buy on HopShop In this article, you wil..."
1,2,no,26,How to make recurring purchases,0.8334,How to make recurring purchases If you buy a p...
2,3,no,18,How to buy a product on HopShop,0.6538,How to buy a product on HopShop
3,4,no,25,How to buy again all products from a previous ...,0.5345,How to buy again all products from a previous ...
4,5,no,40,HopShop gift cards,0.4727,HopShop gift cards If you are not sure what to...

,rank,hit,section_id,title,score,preview
0,1,yes,18,How to buy a product on HopShop,0.9778,How to buy a product on HopShop
1,2,no,17,How to buy on HopShop,0.8400,"How to buy on HopShop In this article, you wil..."
2,3,no,51,How can I track a parcel?,0.7052,How can I track a parcel? You can track your p...
3,4,no,24,How to buy again a single product,0.6996,How to buy again a single product Go to the Pu...
4,5,no,6,Can I have more than one HopShop account,0.6807,"Can I have more than one HopShop account Yes, ..."

,rank,hit,section_id,title,score,preview
0,1,yes,19,1. Find the product you need,1.0000,1. Find the product you need Use the search en...
1,2,no,57,Additional information,0.5375,Additional information You can filter search r...
2,3,no,18,How to buy a product on HopShop,0.5152,How to buy a product on HopShop
3,4,no,24,How to buy again a single product,0.5077,How to buy again a single product Go to the Pu...
4,5,no,23,5. Rate the seller and the product,0.4984,5. Rate the seller and the product You can lea...

,rank,hit,section_id,title,score,preview
0,1,yes,20,2. Read the product description and seller’s r...,1.0000,2. Read the product description and seller’s r...
1,2,no,23,5. Rate the seller and the product,0.4194,5. Rate the seller and the product You can lea...
2,3,no,29,The seller's contact information,0.4084,The seller's contact information After complet...
3,4,no,51,How can I track a parcel?,0.3310,How can I track a parcel? You can track your p...
4,5,no,50,I am buying many products — which delivery met...,0.3299,I am buying many products — which delivery met...

,rank,hit,section_id,title,score,preview
0,1,yes,21,3. Select the way of purchasing the product,0.8052,3. Select the way of purchasing the product Ma...
1,2,no,17,How to buy on HopShop,0.7653,"How to buy on HopShop In this article, you wil..."
2,3,no,18,How to buy a product on HopShop,0.7483,How to buy a product on HopShop
3,4,no,24,How to buy again a single product,0.7267,How to buy again a single product Go to the Pu...
4,5,no,50,I am buying many products — which delivery met...,0.6662,I am buying many products — which delivery met...

,rank,hit,section_id,title,score,preview
0,1,no,34,How to choose a delivery option,0.9467,How to choose a delivery option If you buy at ...
1,2,no,46,Delivery options on HopShop,0.8637,Delivery options on HopShop When buying on Hop...
2,3,no,50,I am buying many products — which delivery met...,0.8462,I am buying many products — which delivery met...
3,4,no,90,I have been waiting a long time for my order d...,0.7135,I have been waiting a long time for my order d...
4,5,yes,22,4. Select the delivery option and payment method,0.6940,4. Select the delivery option and payment meth...

,rank,hit,section_id,title,score,preview
0,1,yes,23,5. Rate the seller and the product,1.0000,5. Rate the seller and the product You can lea...
1,2,no,20,2. Read the product description and seller’s r...,0.5547,2. Read the product description and seller’s r...
2,3,no,29,The seller's contact information,0.4888,The seller's contact information After complet...
3,4,no,94,How to open a Discussion,0.4744,How to open a Discussion In the Purchase Histo...
4,5,no,107,I have received a defective product. What shou...,0.4577,I have received a defective product. What shou...

,rank,hit,section_id,title,score,preview
0,1,no,25,How to buy again all products from a previous ...,0.9767,How to buy again all products from a previous ...
1,2,yes,24,How to buy again a single product,0.7483,How to buy again a single product Go to the Pu...
2,3,no,23,5. Rate the seller and the product,0.6036,5. Rate the seller and the product You can lea...
3,4,no,26,How to make recurring purchases,0.4484,How to make recurring purchases If you buy a p...
4,5,no,17,How to buy on HopShop,0.4477,"How to buy on HopShop In this article, you wil..."

,rank,hit,section_id,title,score,preview
0,1,yes,25,How to buy again all products from a previous ...,1.0000,How to buy again all products from a previous ...
1,2,no,24,How to buy again a single product,0.4761,How to buy again a single product Go to the Pu...
2,3,no,78,I want to change the delivery day. What should...,0.4608,I want to change the delivery day. What should...
3,4,no,23,5. Rate the seller and the product,0.4513,5. Rate the seller and the product You can lea...
4,5,no,51,How can I track a parcel?,0.4395,How can I track a parcel? You can track your p...

,rank,hit,section_id,title,score,preview
0,1,no,25,How to buy again all products from a previous ...,0.8460,How to buy again all products from a previous ...
1,2,yes,26,How to make recurring purchases,0.8320,How to make recurring purchases If you buy a p...
2,3,no,50,I am buying many products — which delivery met...,0.7244,I am buying many products — which delivery met...
3,4,no,17,How to buy on HopShop,0.6459,"How to buy on HopShop In this article, you wil..."
4,5,no,24,How to buy again a single product,0.6003,How to buy again a single product Go to the Pu...

,rank,hit,section_id,title,score,preview
0,1,yes,27,How to contact the seller,1.0000,How to contact the seller You can contact the ...
1,2,no,29,The seller's contact information,0.6391,The seller's contact information After complet...
2,3,no,78,I want to change the delivery day. What should...,0.6303,I want to change the delivery day. What should...
3,4,no,77,I want to change the pick-up point or parcel l...,0.5946,I want to change the pick-up point or parcel l...
4,5,no,28,Ask a question,0.5468,Ask a question If you want to ask the seller a...

,rank,hit,section_id,title,score,preview
0,1,no,27,How to contact the seller,0.9849,How to contact the seller You can contact the ...
1,2,yes,28,Ask a question,0.9612,Ask a question If you want to ask the seller a...
2,3,no,29,The seller's contact information,0.5956,The seller's contact information After complet...
3,4,no,70,How to file a complaint about an HopShop Deliv...,0.5778,How to file a complaint about an HopShop Deliv...
4,5,no,40,HopShop gift cards,0.5414,HopShop gift cards If you are not sure what to...

,rank,hit,section_id,title,score,preview
0,1,yes,29,The seller's contact information,1.0000,The seller's contact information After complet...
1,2,no,27,How to contact the seller,0.6030,How to contact the seller You can contact the ...
2,3,no,78,I want to change the delivery day. What should...,0.5143,I want to change the delivery day. What should...
3,4,no,77,I want to change the pick-up point or parcel l...,0.4588,I want to change the pick-up point or parcel l...
4,5,no,51,How can I track a parcel?,0.4569,How can I track a parcel? You can track your p...

,rank,hit,section_id,title,score,preview
0,1,no,27,How to contact the seller,1.0000,How to contact the seller You can contact the ...
1,2,no,51,How can I track a parcel?,0.6657,How can I track a parcel? You can track your p...
2,3,yes,30,The Message Center,0.6623,The Message Center If you do not want to exit ...
3,4,no,29,The seller's contact information,0.6498,The seller's contact information After complet...
4,5,no,62,How to check the status of an HopShop Delivery...,0.5734,How to check the status of an HopShop Delivery...

,rank,hit,section_id,title,score,preview
0,1,no,107,I have received a defective product. What shou...,1.0000,I have received a defective product. What shou...
1,2,no,90,I have been waiting a long time for my order d...,0.8996,I have been waiting a long time for my order d...
2,3,no,90,I have been waiting a long time for my order d...,0.7909,are and how they work If you have not received...
3,4,no,87,What you should do if you do not receive your ...,0.7704,What you should do if you do not receive your ...
4,5,no,78,I want to change the delivery day. What should...,0.7223,I want to change the delivery day. What should...

,rank,hit,section_id,title,score,preview
0,1,yes,32,How to pay for orders made from multiple sellers,1.0000,How to pay for orders made from multiple selle...
1,2,no,36,How to pay with one payment for orders from an...,0.5225,How to pay with one payment for orders from an...
2,3,no,50,I am buying many products — which delivery met...,0.5144,I am buying many products — which delivery met...
3,4,no,34,How to choose a delivery option,0.4784,How to choose a delivery option If you buy at ...
4,5,no,38,How to split the payment,0.4305,How to split the payment In the Purchase Histo...

,rank,hit,section_id,title,score,preview
0,1,yes,33,One delivery address,1.0000,One delivery address Select one delivery addre...
1,2,no,50,I am buying many products — which delivery met...,0.5207,I am buying many products — which delivery met...
2,3,no,49,How to provide shipping details?,0.4545,How to provide shipping details? If you have a...
3,4,no,34,How to choose a delivery option,0.4132,How to choose a delivery option If you buy at ...
4,5,no,36,How to pay with one payment for orders from an...,0.3522,How to pay with one payment for orders from an...

,rank,hit,section_id,title,score,preview
0,1,yes,34,How to choose a delivery option,0.9672,How to choose a delivery option If you buy at ...
1,2,no,50,I am buying many products — which delivery met...,0.9640,I am buying many products — which delivery met...
2,3,no,32,How to pay for orders made from multiple sellers,0.7982,How to pay for orders made from multiple selle...
3,4,no,36,How to pay with one payment for orders from an...,0.5473,How to pay with one payment for orders from an...
4,5,no,22,4. Select the delivery option and payment method,0.5240,4. Select the delivery option and payment meth...

,rank,hit,section_id,title,score,preview
0,1,yes,35,Determine the delivery cost,1.0000,Determine the delivery cost If the seller has ...
1,2,no,48,How much does delivery cost?,0.7850,How much does delivery cost? The cost of deliv...
2,3,no,50,I am buying many products — which delivery met...,0.5591,I am buying many products — which delivery met...
3,4,no,34,How to choose a delivery option,0.4472,How to choose a delivery option If you buy at ...
4,5,no,60,How much HopShop Delivery is,0.4421,How much HopShop Delivery is Delivery within H...

,rank,hit,section_id,title,score,preview
0,1,yes,36,How to pay with one payment for orders from an...,1.0000,How to pay with one payment for orders from an...
1,2,no,37,Payment methods,0.6601,Payment methods You cannot link payment with i...
2,3,no,32,How to pay for orders made from multiple sellers,0.6050,How to pay for orders made from multiple selle...
3,4,no,24,How to buy again a single product,0.5091,How to buy again a single product Go to the Pu...
4,5,no,38,How to split the payment,0.4949,How to split the payment In the Purchase Histo...

,rank,hit,section_id,title,score,preview
0,1,yes,37,Payment methods,0.8601,Payment methods You cannot link payment with i...
1,2,no,36,How to pay with one payment for orders from an...,0.8026,How to pay with one payment for orders from an...
2,3,no,32,How to pay for orders made from multiple sellers,0.5799,How to pay for orders made from multiple selle...
3,4,no,22,4. Select the delivery option and payment method,0.5238,4. Select the delivery option and payment meth...
4,5,no,6,Can I have more than one HopShop account,0.5174,"Can I have more than one HopShop account Yes, ..."

,rank,hit,section_id,title,score,preview
0,1,no,32,How to pay for orders made from multiple sellers,1.0000,How to pay for orders made from multiple selle...
1,2,yes,38,How to split the payment,0.8438,How to split the payment In the Purchase Histo...
2,3,no,36,How to pay with one payment for orders from an...,0.6783,How to pay with one payment for orders from an...
3,4,no,50,I am buying many products — which delivery met...,0.4913,I am buying many products — which delivery met...
4,5,no,37,Payment methods,0.4838,Payment methods You cannot link payment with i...

,rank,hit,section_id,title,score,preview
0,1,yes,39,How to pay with PayPal,1.0000,How to pay with PayPal When you are ready to p...
1,2,no,38,How to split the payment,0.5520,How to split the payment In the Purchase Histo...
2,3,no,90,I have been waiting a long time for my order d...,0.5091,are and how they work If you have not received...
3,4,no,79,The pick-up code does not work. What should I do?,0.4715,The pick-up code does not work. What should I ...
4,5,no,32,How to pay for orders made from multiple sellers,0.4659,How to pay for orders made from multiple selle...

,rank,hit,section_id,title,score,preview
0,1,yes,40,HopShop gift cards,0.9655,HopShop gift cards If you are not sure what to...
1,2,no,105,A gift card,0.8698,A gift card If you return an order for which y...
2,3,yes,40,HopShop gift cards,0.6471,the email notification. How to get an invoice ...
3,4,no,17,How to buy on HopShop,0.5604,"How to buy on HopShop In this article, you wil..."
4,5,no,62,How to check the status of an HopShop Delivery...,0.5323,How to check the status of an HopShop Delivery...

,rank,hit,section_id,title,score,preview
0,1,yes,41,Why your payment is pending or canceled,1.0000,Why your payment is pending or canceled Your p...
1,2,no,44,Other reasons why your payment may be pending,0.7422,Other reasons why your payment may be pending ...
2,3,no,43,Note,0.4803,Note Every payment starts with the Pending sta...
3,4,no,45,My payment has not gone through. How to retry ...,0.4629,My payment has not gone through. How to retry ...
4,5,no,42,What to do next,0.4227,What to do next If the payment is Canceled and...

,rank,hit,section_id,title,score,preview
0,1,yes,42,What to do next,0.8824,What to do next If the payment is Canceled and...
1,2,no,45,My payment has not gone through. How to retry ...,0.7171,My payment has not gone through. How to retry ...
2,3,no,41,Why your payment is pending or canceled,0.6641,Why your payment is pending or canceled Your p...
3,4,no,78,I want to change the delivery day. What should...,0.6586,I want to change the delivery day. What should...
4,5,no,77,I want to change the pick-up point or parcel l...,0.6006,I want to change the pick-up point or parcel l...

,rank,hit,section_id,title,score,preview
0,1,no,44,Other reasons why your payment may be pending,0.8168,Other reasons why your payment may be pending ...
1,2,no,41,Why your payment is pending or canceled,0.7552,Why your payment is pending or canceled Your p...
2,3,yes,43,Note,0.7348,Note Every payment starts with the Pending sta...
3,4,no,78,I want to change the delivery day. What should...,0.6254,I want to change the delivery day. What should...
4,5,no,45,My payment has not gone through. How to retry ...,0.6113,My payment has not gone through. How to retry ...

,rank,hit,section_id,title,score,preview
0,1,yes,44,Other reasons why your payment may be pending,1.0000,Other reasons why your payment may be pending ...
1,2,no,41,Why your payment is pending or canceled,0.8163,Why your payment is pending or canceled Your p...
2,3,no,104,Wire transfer,0.6457,Wire transfer You will get the refund within 3...
3,4,no,78,I want to change the delivery day. What should...,0.5694,I want to change the delivery day. What should...
4,5,no,102,Bank transfer,0.5590,Bank transfer You will get the refund to the b...

,rank,hit,section_id,title,score,preview
0,1,yes,45,My payment has not gone through. How to retry ...,1.0000,My payment has not gone through. How to retry ...
1,2,no,43,Note,0.5445,Note Every payment starts with the Pending sta...
2,3,no,42,What to do next,0.5415,What to do next If the payment is Canceled and...
3,4,no,37,Payment methods,0.4440,Payment methods You cannot link payment with i...
4,5,no,41,Why your payment is pending or canceled,0.3841,Why your payment is pending or canceled Your p...

,rank,hit,section_id,title,score,preview
0,1,yes,46,Delivery options on HopShop,1.0000,Delivery options on HopShop When buying on Hop...
1,2,no,58,The HopShop Delivery program — information for...,0.7936,The HopShop Delivery program — information for...
2,3,no,61,How to order a parcel with HopShop Delivery,0.6430,How to order a parcel with HopShop Delivery Wh...
3,4,no,18,How to buy a product on HopShop,0.6292,How to buy a product on HopShop
4,5,no,60,How much HopShop Delivery is,0.6173,How much HopShop Delivery is Delivery within H...

,rank,hit,section_id,title,score,preview
0,1,yes,47,What is the delivery time?,1.0000,What is the delivery time? The estimated deliv...
1,2,no,56,Where you can see the estimated delivery time,0.9352,Where you can see the estimated delivery time ...
2,3,no,53,Estimated delivery time,0.7927,Estimated delivery time For every offer on Hop...
3,4,no,54,How we calculate the estimated delivery time,0.7239,How we calculate the estimated delivery time A...
4,5,no,55,The estimated delivery time may differ from th...,0.7237,The estimated delivery time may differ from th...

,rank,hit,section_id,title,score,preview
0,1,yes,48,How much does delivery cost?,0.9975,How much does delivery cost? The cost of deliv...
1,2,no,35,Determine the delivery cost,0.8214,Determine the delivery cost If the seller has ...
2,3,no,50,I am buying many products — which delivery met...,0.7170,I am buying many products — which delivery met...
3,4,no,78,I want to change the delivery day. What should...,0.5480,I want to change the delivery day. What should...
4,5,no,51,How can I track a parcel?,0.5263,How can I track a parcel? You can track your p...

,rank,hit,section_id,title,score,preview
0,1,yes,49,How to provide shipping details?,1.0000,How to provide shipping details? If you have a...
1,2,no,61,How to order a parcel with HopShop Delivery,0.6695,How to order a parcel with HopShop Delivery Wh...
2,3,no,77,I want to change the pick-up point or parcel l...,0.6501,I want to change the pick-up point or parcel l...
3,4,no,90,I have been waiting a long time for my order d...,0.6346,I have been waiting a long time for my order d...
4,5,no,51,How can I track a parcel?,0.6228,How can I track a parcel? You can track your p...

,rank,hit,section_id,title,score,preview
0,1,yes,50,I am buying many products — which delivery met...,0.9540,I am buying many products — which delivery met...
1,2,no,32,How to pay for orders made from multiple sellers,0.9094,How to pay for orders made from multiple selle...
2,3,no,34,How to choose a delivery option,0.7691,How to choose a delivery option If you buy at ...
3,4,no,48,How much does delivery cost?,0.6097,How much does delivery cost? The cost of deliv...
4,5,no,25,How to buy again all products from a previous ...,0.5953,How to buy again all products from a previous ...

      precision@5  recall@5    mrr  ndcg@5  context_relevance
mean        0.198      0.98  0.857   0.889               0.96

,question,relevant_docs,retrieved_docs,precision@5,recall@5,mrr,ndcg@5,context_relevance
0,How do I register for a HopShop account using ...,[1],"[1, 2, 6, 4, 49]",0.20,1.0,1.000000,1.000000,1.0
1,How can I sign up using my Google or Facebook ...,[2],"[2, 6, 1, 3, 75]",0.20,1.0,1.000000,1.000000,1.0
2,How can I enable signing in with my email addr...,[3],"[3, 1, 2, 51, 49]",0.20,1.0,1.000000,1.000000,1.0
3,How do I register for a HopShop account using ...,[4],"[4, 1, 2, 6]",0.25,1.0,1.000000,1.000000,1.0
4,How can I download my personal data from my Ho...,[5],"[5, 7, 8, 6, 11]",0.20,1.0,1.000000,1.000000,1.0
5,Am I allowed to have multiple HopShop accounts...,[6],"[6, 50, 40, 46, 17]",0.20,1.0,1.000000,1.000000,1.0
6,How do I close my HopShop account?,[7],"[7, 16, 6, 14, 2]",0.20,1.0,1.000000,1.000000,1.0
7,How can I withdraw from my agreement with HopS...,[8],"[9, 8, 10, 7, 14]",0.20,1.0,0.500000,0.630930,1.0
8,Under what conditions can I withdraw from my a...,[9],"[9, 8, 10, 12, 13]",0.20,1.0,1.000000,1.000000,1.0
9,How can I withdraw from my agreement and what ...,[10],"[10, 9, 15, 11, 13]",0.20,1.0,1.000000,1.000000,1.0
10,What are the possible outcomes after I submit ...,[11],"[15, 11, 10, 6, 107]",0.20,1.0,0.500000,0.630930,1.0
11,How can I terminate my agreement with HopShop?,[12],"[14, 12, 13, 7, 8]",0.20,1.0,0.500000,0.630930,1.0
12,When am I allowed to terminate the agreement?,[13],"[13, 14, 9, 12, 8]",0.20,1.0,1.000000,1.000000,1.0
13,How can I terminate my agreement with HopShop?,[14],"[14, 12, 13, 7, 8]",0.20,1.0,1.000000,1.000000,1.0
14,What happens after I submit my account termina...,[15],"[11, 15, 12, 14, 7]",0.20,1.0,0.500000,0.630930,1.0
15,What steps do I need to take before my notice ...,[16],"[16, 15, 12, 8, 7]",0.20,1.0,1.000000,1.000000,1.0
16,How do I buy products or make recurring purcha...,[17],"[17, 26, 18, 25, 40]",0.20,1.0,1.000000,1.000000,1.0
17,How can I purchase a product on HopShop?,[18],"[18, 17, 51, 24, 6]",0.20,1.0,1.000000,1.000000,1.0
18,How can I search for a specific product and fi...,[19],"[19, 57, 18, 24, 23]",0.20,1.0,1.000000,1.000000,1.0
19,How can I check a seller’s ratings and read th...,[20],"[20, 23, 29, 51, 50]",0.20,1.0,1.000000,1.000000,1.0
20,What are the different ways I can buy a product?,[21],"[21, 17, 18, 24, 50]",0.20,1.0,1.000000,1.000000,1.0
21,How do I choose my delivery and payment option...,[22],"[34, 46, 50, 90, 22]",0.20,1.0,0.200000,0.386853,1.0
22,How do I rate the seller and the product after...,[23],"[23, 20, 29, 94, 107]",0.20,1.0,1.000000,1.000000,1.0
23,How can I repurchase an individual product fro...,[24],"[25, 24, 23, 26, 17]",0.20,1.0,0.500000,0.630930,1.0
24,How can I reorder all items from a previous pu...,[25],"[25, 24, 78, 23, 51]",0.20,1.0,1.000000,1.000000,1.0
25,How can I quickly reorder products I buy regul...,[26],"[25, 26, 50, 17, 24]",0.20,1.0,0.500000,0.630930,1.0
26,What are the ways I can contact a seller on Ho...,[27],"[27, 29, 78, 77, 28]",0.20,1.0,1.000000,1.000000,1.0
27,How can I contact a seller with a question abo...,[28],"[27, 28, 29, 70, 40]",0.20,1.0,0.500000,0.630930,1.0
28,How can I find the seller's contact informatio...,[29],"[29, 27, 78, 77, 51]",0.20,1.0,1.000000,1.000000,1.0
29,How can I contact a seller on HopShop without ...,[30],"[27, 51, 30, 29, 62]",0.20,1.0,0.333333,0.500000,1.0
30,What should I do if I have an issue with my or...,[31],"[107, 90, 87, 78]",0.00,0.0,0.000000,0.000000,1.0
31,How can I pay for items from multiple sellers ...,[32],"[32, 36, 50, 34, 38]",0.20,1.0,1.000000,1.000000,1.0
32,Can I choose just one delivery address and one...,[33],"[33, 50, 49, 34, 36]",0.20,1.0,1.000000,1.000000,1.0
33,How do I choose a delivery option when buying ...,[34],"[34, 50, 32, 36, 22]",0.20,1.0,1.000000,1.000000,1.0
34,How is the delivery cost calculated if there a...,[35],"[35, 48, 50, 34, 60]",0.20,1.0,1.000000,1.000000,1.0
35,How can I pay for both auction items and buy n...,[36],"[36, 37, 32, 24, 38]",0.20,1.0,1.000000,1.000000,1.0
36,Can I use installments or HopShop Pay to pay f...,[37],"[37, 36, 32, 22, 6]",0.20,1.0,1.000000,1.000000,0.0
37,Can I split the payment for multiple orders or...,[38],"[32, 38, 36, 50, 37]",0.20,1.0,0.500000,0.630930,0.5
38,"How do I pay for my order using PayPal, and ho...",[39],"[39, 38, 90, 79, 32]",0.20,1.0,1.000000,1.000000,1.0
39,How can I use a HopShop gift card to make a pu...,[40],"[40, 105, 17, 62]",0.25,1.0,1.000000,1.000000,1.0
40,Why is my payment marked as pending or canceled?,[41],"[41, 44, 43, 45, 42]",0.20,1.0,1.000000,1.000000,1.0
41,What should I do if my payment was canceled an...,[42],"[42, 45, 41, 78, 77]",0.20,1.0,1.000000,1.000000,1.0
42,What should I do if my payment status is stuck...,[43],"[44, 41, 43, 78, 45]",0.20,1.0,0.333333,0.500000,1.0
43,"Why is my payment still pending, and what shou...",[44],"[44, 41, 104, 78, 102]",0.20,1.0,1.000000,1.000000,1.0
44,How can I retry a payment that didn’t go through?,[45],"[45, 43, 42, 37, 41]",0.20,1.0,1.000000,1.000000,1.0
45,How can I find out what delivery options are a...,[46],"[46, 58, 61, 18, 60]",0.20,1.0,1.000000,1.000000,1.0
46,How is the delivery time provided for each offer?,[47],"[47, 56, 53, 54, 55]",0.20,1.0,1.000000,1.000000,1.0
47,How can I find out the delivery cost for a pro...,[48],"[48, 35, 50, 78, 51]",0.20,1.0,1.000000,1.000000,1.0
48,How can I add or change my shipping address on...,[49],"[49, 61, 77, 90, 51]",0.20,1.0,1.000000,1.000000,0.5
49,How does delivery work if I buy multiple produ...,[50],"[50, 32, 34, 48, 25]",0.20,1.0,1.000000,1.000000,1.0