In [1]:
import sys
from numbers import Real
from pathlib import Path
from html import escape

import pandas as pd
from IPython.display import HTML, display

sys.path.append("../")

from evaluation.classes import ResponseGroundednessWrapper
from evaluation.eval import groundedness, load_tests
from evaluation.reporting import export_groundedness_report_to_markdown
from pipelines.faq_pipeline import FaqPipeline

/Users/ayeustsihneyeu/PythonProjects/hybrid-rag-system/.hybrag/lib/python3.14/site-packages/langchain_core/_api/deprecation.py:25: UserWarning: Core Pydantic V1 functionality isn't compatible with Python 3.14 or greater.
  from pydantic.v1.fields import FieldInfo as FieldInfoV1
/Users/ayeustsihneyeu/PythonProjects/hybrid-rag-system/.hybrag/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
def _node_metadata(item):
    if hasattr(item, "node"):
        return getattr(item.node, "metadata", {}) or {}
    return getattr(item, "metadata", {}) or {}


def _node_text(item):
    node = getattr(item, "node", item)
    if hasattr(node, "get_content"):
        return node.get_content()
    return getattr(node, "text", "") or ""


def _node_score(item):
    score = getattr(item, "score", None)
    return round(float(score), 4) if isinstance(score, Real) else None


def _preview(text, max_len=220):
    cleaned = " ".join(str(text).split())
    if len(cleaned) <= max_len:
        return cleaned
    return cleaned[: max_len - 3] + "..."


def _render_metrics(metrics):
    metrics_html = "".join(
        f"""
        <div style='padding:12px 14px;border:1px solid #d0d7de;border-radius:10px;background:#f6f8fa;'>
            <div style='font-size:12px;color:#57606a;text-transform:uppercase;letter-spacing:.04em;'>{escape(name)}</div>
            <div style='font-size:24px;font-weight:700;color:#24292f;'>{value:.3f}</div>
        </div>
        """
        for name, value in metrics.items()
    )
    display(HTML(f"<div style='display:grid;grid-template-columns:repeat(2, minmax(0, 1fr));gap:12px;margin:12px 0 18px;'>{metrics_html}</div>"))


def _render_question_report(test, row, doc_rows, index, total):
    header_html = f"""
    <div style='margin:28px 0 10px;'>
        <div style='font-size:12px;color:#57606a;text-transform:uppercase;letter-spacing:.08em;'>Question {index}/{total}</div>
        <div style='font-size:22px;font-weight:700;margin:6px 0 10px;color:#24292f;'>{escape(test.question)}</div>
        <div style='padding:12px 14px;background:#fff8c5;border:1px solid #e3d279;border-radius:10px;'>
            <div style='font-size:12px;color:#57606a;text-transform:uppercase;letter-spacing:.04em;margin-bottom:6px;'>Relevant docs</div>
            <div style='font-size:16px;font-weight:600;color:#24292f;'>{escape(str(test.relevant_docs))}</div>
        </div>
    </div>
    """
    display(HTML(header_html))
    _render_metrics({"groundedness": row["groundedness"]})
    display(HTML(f"<p style='margin:8px 0 4px;'><strong>Reference answer:</strong> {escape(str(row['reference_answer']))}</p>"))
    display(HTML(f"<p style='margin:8px 0 12px;'><strong>Generated answer:</strong> {escape(str(row['generated_answer']))}</p>"))
    display(pd.DataFrame(doc_rows))
    return {
        "question": test.question,
        "relevant_docs": list(test.relevant_docs),
        "retrieved_docs": row["retrieved_docs"],
        "reference_answer": row["reference_answer"],
        "generated_answer": row["generated_answer"],
        "groundedness": row["groundedness"],
        "doc_rows": doc_rows,
    }


async def evaluate_all_groundedness(limit=None, markdown_path=None):
    tests = load_tests()
    selected_tests = tests[:limit] if limit is not None else tests
    pipeline = FaqPipeline()
    rows = []
    question_reports = []

    for index, test in enumerate(selected_tests, start=1):
        pipeline_result = pipeline.run(test.question)
        nodes = pipeline_result["nodes"]
        contexts = [_node_text(item) for item in nodes]
        answer = pipeline_result["answer"]

        score = await groundedness(
            ResponseGroundednessWrapper(
                contexts=contexts,
                answer=answer,
            )
        )

        retrieved_docs = []
        doc_rows = []
        for rank, item in enumerate(nodes, start=1):
            metadata = _node_metadata(item)
            section_id = metadata.get("section_id")
            retrieved_docs.append(section_id)
            doc_rows.append(
                {
                    "rank": rank,
                    "section_id": section_id,
                    "title": metadata.get("section_title", "-"),
                    "rerank_score": _node_score(item),
                    "preview": _preview(_node_text(item)),
                }
            )

        row = {
            "question": test.question,
            "reference_answer": test.reference_answer,
            "generated_answer": answer,
            "relevant_docs": test.relevant_docs,
            "retrieved_docs": retrieved_docs,
            "groundedness": score,
        }
        rows.append(row)

        question_report = _render_question_report(
            test,
            row,
            doc_rows,
            index=index,
            total=len(selected_tests),
        )
        question_report.update({"index": index, "total": len(selected_tests)})
        question_reports.append(question_report)

    report_df = pd.DataFrame(rows)
    summary_df = report_df[["groundedness"]].mean().to_frame(name="mean").T.round(3)

    display(HTML("<h2 style='margin:32px 0 12px;color:#24292f;'>Final metrics</h2>"))
    display(summary_df)

    if markdown_path is not None:
        saved_path = export_groundedness_report_to_markdown(
            report_df,
            question_reports,
            Path(markdown_path),
            notebook_path="notebooks/12_faq_groundedness_evaluating.ipynb",
        )
        display(HTML(f"<p style='margin:12px 0 0;color:#1a7f37;'>Markdown report saved to: <code>{escape(str(saved_path))}</code></p>"))

    return report_df

In [3]:
await evaluate_all_groundedness(markdown_path="../reports/faq_groundedness_evaluation.md")

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 19564.07it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,1,How to register with an email,8.5447,How to register with an email Open the registr...
1,2,2,How to register with Google or Facebook account,5.6311,How to register with Google or Facebook accoun...
2,3,49,How to provide shipping details?,5.2245,How to provide shipping details? If you have a...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 11725.71it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,2,How to register with Google or Facebook account,7.5312,How to register with Google or Facebook accoun...
1,2,3,Signing in with a password and email address,-6.3560,Signing in with a password and email address I...
2,3,1,How to register with an email,-8.5365,How to register with an email Open the registr...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 9517.01it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,3,Signing in with a password and email address,6.6539,Signing in with a password and email address I...
1,2,1,How to register with an email,0.1883,How to register with an email Open the registr...
2,3,2,How to register with Google or Facebook account,-5.2824,How to register with Google or Facebook accoun...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 10589.15it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,4,How to register with your phone number,6.7877,"your account within 3 business days, and retur..."
1,2,4,How to register with your phone number,6.7864,How to register with your phone number Open th...
2,3,1,How to register with an email,6.1614,How to register with an email Open the registr...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 16075.95it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,5,GDPR — how you can download your personal data...,10.3471,GDPR — how you can download your personal data...
1,2,11,What happens next,0.3384,"What happens next Usually, we consider the app..."
2,3,6,Can I have more than one HopShop account,0.1561,"Can I have more than one HopShop account Yes, ..."

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 12993.67it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,6,Can I have more than one HopShop account,6.8265,"Can I have more than one HopShop account Yes, ..."
1,2,40,HopShop gift cards,-5.0002,HopShop gift cards If you are not sure what to...
2,3,46,Delivery options on HopShop,-6.8066,Delivery options on HopShop When buying on Hop...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13698.64it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,7,How to close your HopShop account,8.6370,How to close your HopShop account You can end ...
1,2,16,What you should do before the notice period ends,5.7982,What you should do before the notice period en...
2,3,14,How to terminate the agreement,3.5283,How to terminate the agreement To terminate th...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 12904.37it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,9,When you can withdraw from the agreement,7.6242,When you can withdraw from the agreement You c...
1,2,7,How to close your HopShop account,6.4244,How to close your HopShop account You can end ...
2,3,8,Withdrawing from the agreement with HopShop,6.2203,Withdrawing from the agreement with HopShop

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13509.63it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,9,When you can withdraw from the agreement,7.0227,When you can withdraw from the agreement You c...
1,2,8,Withdrawing from the agreement with HopShop,5.0874,Withdrawing from the agreement with HopShop
2,3,12,Termination of the agreement with HopShop,1.6312,Termination of the agreement with HopShop

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 14762.99it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,10,How to withdraw from the agreement,6.2706,How to withdraw from the agreement To withdraw...
1,2,9,When you can withdraw from the agreement,3.9312,When you can withdraw from the agreement You c...
2,3,11,What happens next,0.9397,"What happens next Usually, we consider the app..."

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 15526.16it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,11,What happens next,-5.0821,"What happens next Usually, we consider the app..."
1,2,10,How to withdraw from the agreement,-5.1605,How to withdraw from the agreement To withdraw...
2,3,15,What happens next,-5.8243,What happens next From the moment you submit t...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 16052.99it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,14,How to terminate the agreement,7.5278,How to terminate the agreement To terminate th...
1,2,7,How to close your HopShop account,7.4835,How to close your HopShop account You can end ...
2,3,12,Termination of the agreement with HopShop,5.2500,Termination of the agreement with HopShop

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 14276.73it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,13,When you can terminate the agreement,6.7622,When you can terminate the agreement You can t...
1,2,14,How to terminate the agreement,1.8960,How to terminate the agreement To terminate th...
2,3,9,When you can withdraw from the agreement,-0.3316,When you can withdraw from the agreement You c...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 15150.33it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,14,How to terminate the agreement,7.5278,How to terminate the agreement To terminate th...
1,2,7,How to close your HopShop account,7.4835,How to close your HopShop account You can end ...
2,3,12,Termination of the agreement with HopShop,5.2500,Termination of the agreement with HopShop

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13897.58it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,15,What happens next,7.2904,What happens next From the moment you submit t...
1,2,11,What happens next,5.5930,"What happens next Usually, we consider the app..."
2,3,14,How to terminate the agreement,4.6104,How to terminate the agreement To terminate th...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 10783.79it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,16,What you should do before the notice period ends,6.0687,What you should do before the notice period en...
1,2,15,What happens next,3.0385,What happens next From the moment you submit t...
2,3,7,How to close your HopShop account,-1.8614,How to close your HopShop account You can end ...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13461.96it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,17,How to buy on HopShop,6.8002,"How to buy on HopShop In this article, you wil..."
1,2,26,How to make recurring purchases,6.7741,How to make recurring purchases If you buy a p...
2,3,40,HopShop gift cards,3.4191,HopShop gift cards If you are not sure what to...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 10906.28it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,17,How to buy on HopShop,6.9367,"How to buy on HopShop In this article, you wil..."
1,2,18,How to buy a product on HopShop,5.6124,How to buy a product on HopShop
2,3,6,Can I have more than one HopShop account,3.0766,"Can I have more than one HopShop account Yes, ..."

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 12400.60it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,19,1. Find the product you need,4.8713,1. Find the product you need Use the search en...
1,2,57,Additional information,-0.2093,Additional information You can filter search r...
2,3,23,5. Rate the seller and the product,-7.1907,5. Rate the seller and the product You can lea...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13238.72it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,20,2. Read the product description and seller’s r...,8.2301,2. Read the product description and seller’s r...
1,2,23,5. Rate the seller and the product,4.8020,5. Rate the seller and the product You can lea...
2,3,29,The seller's contact information,1.7512,The seller's contact information After complet...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 18195.17it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,21,3. Select the way of purchasing the product,5.6790,3. Select the way of purchasing the product Ma...
1,2,50,I am buying many products — which delivery met...,2.5935,I am buying many products — which delivery met...
2,3,24,How to buy again a single product,0.4752,How to buy again a single product Go to the Pu...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 15252.84it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,22,4. Select the delivery option and payment method,6.2733,4. Select the delivery option and payment meth...
1,2,34,How to choose a delivery option,5.7498,How to choose a delivery option If you buy at ...
2,3,50,I am buying many products — which delivery met...,2.6887,I am buying many products — which delivery met...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 12685.15it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,23,5. Rate the seller and the product,8.6724,5. Rate the seller and the product You can lea...
1,2,29,The seller's contact information,1.9519,The seller's contact information After complet...
2,3,94,How to open a Discussion,0.5960,How to open a Discussion In the Purchase Histo...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13324.30it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,25,How to buy again all products from a previous ...,0.6415,How to buy again all products from a previous ...
1,2,23,5. Rate the seller and the product,-3.8273,5. Rate the seller and the product You can lea...
2,3,24,How to buy again a single product,-6.3751,How to buy again a single product Go to the Pu...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13306.84it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,25,How to buy again all products from a previous ...,5.4526,How to buy again all products from a previous ...
1,2,23,5. Rate the seller and the product,-1.9783,5. Rate the seller and the product You can lea...
2,3,24,How to buy again a single product,-4.9440,How to buy again a single product Go to the Pu...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 14669.48it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,26,How to make recurring purchases,6.0553,How to make recurring purchases If you buy a p...
1,2,25,How to buy again all products from a previous ...,-1.7293,How to buy again all products from a previous ...
2,3,24,How to buy again a single product,-3.2566,How to buy again a single product Go to the Pu...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13112.30it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,27,How to contact the seller,8.8640,How to contact the seller You can contact the ...
1,2,28,Ask a question,5.9827,Ask a question If you want to ask the seller a...
2,3,29,The seller's contact information,-0.5761,The seller's contact information After complet...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13068.80it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,28,Ask a question,8.3916,Ask a question If you want to ask the seller a...
1,2,27,How to contact the seller,7.6237,How to contact the seller You can contact the ...
2,3,40,HopShop gift cards,3.1820,HopShop gift cards If you are not sure what to...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 14182.10it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,29,The seller's contact information,9.4128,The seller's contact information After complet...
1,2,27,How to contact the seller,3.7432,How to contact the seller You can contact the ...
2,3,78,I want to change the delivery day. What should...,3.0401,I want to change the delivery day. What should...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 16077.49it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,30,The Message Center,8.1944,The Message Center If you do not want to exit ...
1,2,27,How to contact the seller,5.7301,How to contact the seller You can contact the ...
2,3,51,How can I track a parcel?,0.0348,How can I track a parcel? You can track your p...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 15101.48it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,87,What you should do if you do not receive your ...,5.3191,What you should do if you do not receive your ...
1,2,90,I have been waiting a long time for my order d...,1.3025,are and how they work If you have not received...
2,3,90,I have been waiting a long time for my order d...,-0.7058,I have been waiting a long time for my order d...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13842.81it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,32,How to pay for orders made from multiple sellers,6.7422,How to pay for orders made from multiple selle...
1,2,36,How to pay with one payment for orders from an...,1.9097,How to pay with one payment for orders from an...
2,3,38,How to split the payment,0.2667,How to split the payment In the Purchase Histo...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 15513.02it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,33,One delivery address,8.1016,One delivery address Select one delivery addre...
1,2,34,How to choose a delivery option,-2.6206,How to choose a delivery option If you buy at ...
2,3,49,How to provide shipping details?,-3.9602,How to provide shipping details? If you have a...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 18178.69it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,34,How to choose a delivery option,8.1002,How to choose a delivery option If you buy at ...
1,2,50,I am buying many products — which delivery met...,5.0803,I am buying many products — which delivery met...
2,3,32,How to pay for orders made from multiple sellers,2.2930,How to pay for orders made from multiple selle...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 16357.30it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,35,Determine the delivery cost,8.1505,Determine the delivery cost If the seller has ...
1,2,48,How much does delivery cost?,2.6388,How much does delivery cost? The cost of deliv...
2,3,50,I am buying many products — which delivery met...,1.3195,I am buying many products — which delivery met...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 14941.96it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,36,How to pay with one payment for orders from an...,6.4396,How to pay with one payment for orders from an...
1,2,37,Payment methods,4.9989,Payment methods You cannot link payment with i...
2,3,32,How to pay for orders made from multiple sellers,-1.6083,How to pay for orders made from multiple selle...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 15038.17it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,37,Payment methods,8.0521,Payment methods You cannot link payment with i...
1,2,36,How to pay with one payment for orders from an...,0.6119,How to pay with one payment for orders from an...
2,3,22,4. Select the delivery option and payment method,0.5143,4. Select the delivery option and payment meth...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 17170.51it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,32,How to pay for orders made from multiple sellers,6.5767,How to pay for orders made from multiple selle...
1,2,38,How to split the payment,5.8611,How to split the payment In the Purchase Histo...
2,3,50,I am buying many products — which delivery met...,-0.3766,I am buying many products — which delivery met...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 11649.56it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,39,How to pay with PayPal,7.7781,How to pay with PayPal When you are ready to p...
1,2,38,How to split the payment,0.2073,How to split the payment In the Purchase Histo...
2,3,32,How to pay for orders made from multiple sellers,-3.9859,How to pay for orders made from multiple selle...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 9604.84it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,40,HopShop gift cards,7.1746,HopShop gift cards If you are not sure what to...
1,2,105,A gift card,4.0874,A gift card If you return an order for which y...
2,3,17,How to buy on HopShop,1.6232,"How to buy on HopShop In this article, you wil..."

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13324.51it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,41,Why your payment is pending or canceled,8.5169,Why your payment is pending or canceled Your p...
1,2,44,Other reasons why your payment may be pending,7.3346,Other reasons why your payment may be pending ...
2,3,43,Note,0.1722,Note Every payment starts with the Pending sta...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13325.35it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,42,What to do next,8.0613,What to do next If the payment is Canceled and...
1,2,41,Why your payment is pending or canceled,3.1052,Why your payment is pending or canceled Your p...
2,3,45,My payment has not gone through. How to retry ...,2.5896,My payment has not gone through. How to retry ...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13105.37it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,44,Other reasons why your payment may be pending,5.7397,Other reasons why your payment may be pending ...
1,2,43,Note,5.3358,Note Every payment starts with the Pending sta...
2,3,41,Why your payment is pending or canceled,5.3067,Why your payment is pending or canceled Your p...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 12400.24it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,44,Other reasons why your payment may be pending,7.9046,Other reasons why your payment may be pending ...
1,2,41,Why your payment is pending or canceled,4.8126,Why your payment is pending or canceled Your p...
2,3,104,Wire transfer,-3.3245,Wire transfer You will get the refund within 3...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13979.85it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,45,My payment has not gone through. How to retry ...,8.2447,My payment has not gone through. How to retry ...
1,2,42,What to do next,7.0963,What to do next If the payment is Canceled and...
2,3,43,Note,6.0549,Note Every payment starts with the Pending sta...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13437.50it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,46,Delivery options on HopShop,7.6925,Delivery options on HopShop When buying on Hop...
1,2,58,The HopShop Delivery program — information for...,5.6849,The HopShop Delivery program — information for...
2,3,61,How to order a parcel with HopShop Delivery,3.9104,How to order a parcel with HopShop Delivery Wh...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 11307.37it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,47,What is the delivery time?,6.8099,What is the delivery time? The estimated deliv...
1,2,56,Where you can see the estimated delivery time,6.5255,Where you can see the estimated delivery time ...
2,3,53,Estimated delivery time,4.3629,Estimated delivery time For every offer on Hop...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13097.22it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,48,How much does delivery cost?,6.2241,How much does delivery cost? The cost of deliv...
1,2,35,Determine the delivery cost,5.4270,Determine the delivery cost If the seller has ...
2,3,50,I am buying many products — which delivery met...,2.9231,I am buying many products — which delivery met...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 12554.80it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,49,How to provide shipping details?,4.6625,How to provide shipping details? If you have a...
1,2,90,I have been waiting a long time for my order d...,-0.0519,I have been waiting a long time for my order d...
2,3,61,How to order a parcel with HopShop Delivery,-0.2747,How to order a parcel with HopShop Delivery Wh...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 16793.59it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,50,I am buying many products — which delivery met...,5.7683,I am buying many products — which delivery met...
1,2,34,How to choose a delivery option,5.5872,How to choose a delivery option If you buy at ...
2,3,32,How to pay for orders made from multiple sellers,2.5484,How to pay for orders made from multiple selle...

      groundedness
mean         0.995

,question,reference_answer,generated_answer,relevant_docs,retrieved_docs,groundedness
0,How do I register for a HopShop account using ...,Open the registration page. Choose whether you...,"To register with your email address, open the ...",[1],"[1, 2, 49]",1.00
1,How can I sign up using my Google or Facebook ...,Open the sign in page.\nSelect signing in thro...,To sign up using your Google or Facebook accou...,[2],"[2, 3, 1]",1.00
2,How can I enable signing in with my email addr...,If you want to be able to sign in to your acco...,To enable signing in with your email address a...,[3],"[3, 1, 2]",1.00
3,How do I register for a HopShop account using ...,Open the registration page. Select whether you...,"To register with your phone number, open the r...",[4],"[4, 4, 1]",1.00
4,How can I download my personal data from my Ho...,"On the Copies of your data page, you can downl...",To download your personal data from your HopSh...,[5],"[5, 11, 6]",1.00
5,Am I allowed to have multiple HopShop accounts...,"Yes, you can have a few accounts, as long as y...","Yes, you can have multiple HopShop accounts as...",[6],"[6, 40, 46]",1.00
6,How do I close my HopShop account?,You can end your activity on HopShop by:\nwith...,You can close your HopShop account by withdraw...,[7],"[7, 16, 14]",1.00
7,How can I withdraw from my agreement with HopS...,\n Section_Id: 8,You can withdraw from your agreement with HopS...,[8],"[9, 7, 8]",1.00
8,Under what conditions can I withdraw from my a...,You can easily withdraw from the agreement wit...,You can withdraw from your agreement with HopS...,[9],"[9, 8, 12]",1.00
9,How can I withdraw from my agreement and what ...,"To withdraw from the agreement, submit this ap...","To withdraw from the agreement, submit the app...",[10],"[10, 9, 11]",1.00
10,What are the possible outcomes after I submit ...,"Usually, we consider the application right awa...","After you submit an account deletion request, ...",[11],"[11, 10, 15]",1.00
11,How can I terminate my agreement with HopShop?,Section_Id: 12,"To terminate your agreement with HopShop, subm...",[12],"[14, 7, 12]",1.00
12,When am I allowed to terminate the agreement?,You can terminate the agreement any time ― als...,"You can terminate the agreement at any time, e...",[13],"[13, 14, 9]",1.00
13,How can I terminate my agreement with HopShop?,"To terminate the agreement with HopShop, submi...","To terminate your agreement with HopShop, subm...",[14],"[14, 7, 12]",1.00
14,What happens after I submit my account termina...,"From the moment you submit the application, we...","From the moment you submit the application, a ...",[15],"[15, 11, 14]",1.00
15,What steps do I need to take before my notice ...,Pay any arrears to HopShop.\nIf you have an op...,"Before your notice period ends with HopShop, y...",[16],"[16, 15, 7]",1.00
16,How do I buy products or make recurring purcha...,"In this article, you will learn\nhow to buy a ...","To buy products on HopShop, add them to your c...",[17],"[17, 26, 40]",1.00
17,How can I purchase a product on HopShop?,How to buy a product on HopShop,Buying on HopShop is simple and you can do it ...,[18],"[17, 18, 6]",1.00
18,How can I search for a specific product and fi...,Use the search engine to find the product you ...,Use the search engine to find the product you ...,[19],"[19, 57, 23]",1.00
19,How can I check a seller’s ratings and read th...,Go to the selected offer — read the product de...,Go to the selected offer and read the product ...,[20],"[20, 23, 29]",1.00
20,What are the different ways I can buy a product?,Make an instant purchase — click [buy and pay]...,You can buy a product in three ways:\n1. Make ...,[21],"[21, 50, 24]",1.00
21,How do I choose my delivery and payment option...,Complete the delivery and payment form — selec...,Complete the delivery and payment form by sele...,[22],"[22, 34, 50]",1.00
22,How do I rate the seller and the product after...,You can leave a rating after purchasing the pr...,You can leave a rating after purchasing the pr...,[23],"[23, 29, 94]",1.00
23,How can I repurchase an individual product fro...,Go to the Purchase History tab.\nClick [purcha...,"Go to the Purchase History tab, click [purchas...",[24],"[25, 23, 24]",0.75
24,How can I reorder all items from a previous pu...,Go to the Purchase History tab.\nClick [purcha...,"To reorder all items from a previous purchase,...",[25],"[25, 23, 24]",1.00
25,How can I quickly reorder products I buy regul...,"If you buy a particular product regularly, you...",You can quickly reorder products you buy regul...,[26],"[26, 25, 24]",1.00
26,What are the ways I can contact a seller on Ho...,You can contact the seller on HopShop in a few...,You can contact a seller on HopShop by:\n- Cli...,[27],"[27, 28, 29]",1.00
27,How can I contact a seller with a question abo...,If you want to ask the seller about an item or...,You can contact the seller by clicking [Ask a ...,[28],"[28, 27, 40]",1.00
28,How can I find the seller's contact informatio...,"After completing each transaction, we will ema...","After making a purchase, you can find the sell...",[29],"[29, 27, 78]",1.00
29,How can I contact a seller on HopShop without ...,If you do not want to exit the HopShop website...,You can contact the seller through the Message...,[30],"[30, 27, 51]",1.00
30,What should I do if I have an issue with my or...,If the product you ordered does not conform wi...,If you have not received your order or have an...,[31],"[87, 90, 90]",1.00
31,How can I pay for items from multiple sellers ...,In order to pay for items from one or more sel...,To pay for items from multiple sellers with on...,[32],"[32, 36, 38]",1.00
32,Can I choose just one delivery address and one...,Select one delivery address and one set of VAT...,"Yes, you can select one delivery address and o...",[33],"[33, 34, 49]",1.00
33,How do I choose a delivery option when buying ...,If you buy at least two items:\nfrom the same ...,"If you buy from one seller, select a delivery ...",[34],"[34, 50, 32]",1.00
34,How is the delivery cost calculated if there a...,If the seller has set price lists in all the o...,If the seller has set price lists in all the o...,[35],"[35, 48, 50]",1.00
35,How can I pay for both auction items and buy n...,You can pay for items from an auction or an of...,To pay for both auction items and buy now purc...,[36],"[36, 37, 32]",1.00
36,Can I use installments or HopShop Pay to pay f...,You cannot link payment with installments or H...,"No, you cannot use installments or HopShop Pay...",[37],"[37, 36, 22]",1.00
37,Can I split the payment for multiple orders or...,"In the Purchase History tab, tick only those o...",You can split the payment for multiple orders ...,[38],"[32, 38, 50]",1.00
38,"How do I pay for my order using PayPal, and ho...","When you are ready to pay for your order, go t...","To pay with PayPal, go to the delivery and pay...",[39],"[39, 38, 32]",1.00
39,How can I use a HopShop gift card to make a pu...,If you are not sure what to buy someone as a g...,You can use your HopShop gift card to make a p...,[40],"[40, 105, 17]",1.00
40,Why is my payment marked as pending or canceled?,Your payment may have the Canceled status if:\...,Your payment may be marked as pending or cance...,[41],"[41, 44, 43]",1.00
41,What should I do if my payment was canceled an...,If the payment is Canceled and your bank accou...,If your payment was canceled and your bank acc...,[42],"[42, 41, 45]",1.00
42,What should I do if my payment status is stuck...,Every payment starts with the Pending status.\...,"If your payment status is stuck on Pending, ch...",[43],"[44, 43, 41]",1.00
43,"Why is my payment still pending, and what shou...",If you have chosen to pay by a wire transfer i...,"If you paid by wire transfer, the payment can ...",[44],"[44, 41, 104]",1.00
44,How can I retry a payment that didn’t go through?,Go to the Purchase History tab and find a rele...,"To retry a payment that didn’t go through, go ...",[45],"[45, 42, 43]",1.00
45,How can I find out what delivery options are a...,"When buying on HopShop, you have a wide range ...",To find out what delivery options are availabl...,[46],"[46, 58, 61]",1.00
46,How is the delivery time provided for each offer?,The estimated delivery time is usually a few d...,The estimated delivery time is displayed indiv...,[47],"[47, 56, 53]",1.00
47,How can I find out the delivery cost for a pro...,The cost of delivery is always set by the sell...,You can check the delivery costs during transa...,[48],"[48, 35, 50]",1.00
48,How can I add or change my shipping address on...,"If you have a registered HopShop account, you ...","If you have a registered HopShop account, you ...",[49],"[49, 90, 61]",1.00
49,How does delivery work if I buy multiple produ...,You cannot merge delivery costs if you buy fro...,"If you buy from different sellers, you cannot ...",[50],"[50, 34, 32]",1.00