In [1]:
import sys
from pathlib import Path
from html import escape

import pandas as pd
from IPython.display import HTML, display

sys.path.append("../")

from evaluation.classes import AnswerRelevanceWrapper
from evaluation.eval import answer_relevance, load_tests
from evaluation.reporting import (
    build_eval_question_report,
    build_retrieved_doc_rows,
    display_eval_question_report,
    export_answer_relevance_report_to_markdown,
)
from pipelines.faq_pipeline import FaqPipeline

/Users/ayeustsihneyeu/PythonProjects/hybrid-rag-system/.hybrag/lib/python3.14/site-packages/langchain_core/_api/deprecation.py:25: UserWarning: Core Pydantic V1 functionality isn't compatible with Python 3.14 or greater.
  from pydantic.v1.fields import FieldInfo as FieldInfoV1
/Users/ayeustsihneyeu/PythonProjects/hybrid-rag-system/.hybrag/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
async def evaluate_all_answer_relevance(limit=None, markdown_path=None):
    tests = load_tests()
    selected_tests = tests[:limit] if limit is not None else tests
    pipeline = FaqPipeline()
    rows = []
    question_reports = []

    for index, test in enumerate(selected_tests, start=1):
        pipeline_result = pipeline.run(test.question)
        nodes = pipeline_result["nodes"]
        answer = pipeline_result["answer"]

        score = await answer_relevance(
            AnswerRelevanceWrapper(
                question=test.question,
                answer=answer,
            )
        )

        retrieved_docs, doc_rows = build_retrieved_doc_rows(nodes)

        row = {
            "question": test.question,
            "reference_answer": test.reference_answer,
            "generated_answer": answer,
            "relevant_docs": test.relevant_docs,
            "retrieved_docs": retrieved_docs,
            "answer_relevance": score,
        }
        rows.append(row)

        display_eval_question_report(
            question=test.question,
            relevant_docs=test.relevant_docs,
            metrics={"answer_relevance": row["answer_relevance"]},
            text_blocks=[
                ("Reference answer", row["reference_answer"]),
                ("Generated answer", row["generated_answer"]),
            ],
            doc_rows=doc_rows,
            index=index,
            total=len(selected_tests),
        )

        question_report = build_eval_question_report(
            question=test.question,
            relevant_docs=test.relevant_docs,
            retrieved_docs=row["retrieved_docs"],
            doc_rows=doc_rows,
            extra_fields={
                "reference_answer": row["reference_answer"],
                "generated_answer": row["generated_answer"],
                "answer_relevance": row["answer_relevance"],
            },
            index=index,
            total=len(selected_tests),
        )
        question_reports.append(question_report)

    report_df = pd.DataFrame(rows)
    summary_df = report_df[["answer_relevance"]].mean().to_frame(name="mean").T.round(3)

    display(HTML("<h2 style='margin:32px 0 12px;color:#24292f;'>Final metrics</h2>"))
    display(summary_df)

    if markdown_path is not None:
        saved_path = export_answer_relevance_report_to_markdown(
            report_df,
            question_reports,
            Path(markdown_path),
            notebook_path="notebooks/13_faq_answer_relevance_evaluating.ipynb",
        )
        display(HTML(f"<p style='margin:12px 0 0;color:#1a7f37;'>Markdown report saved to: <code>{escape(str(saved_path))}</code></p>"))

    return report_df

In [3]:
await evaluate_all_answer_relevance(markdown_path="../reports/faq_answer_relevance_evaluation.md")

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 15635.87it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,93,What to do if the seller does not issue a refund,2.5227,What to do if the seller does not issue a refu...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 16450.18it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,25,One delivery address,3.2498,One delivery address Select one delivery addre...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 14109.00it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,33,Why your payment is pending or canceled,7.9972,Why your payment is pending or canceled Your p...
1,2,34,Other reasons why your payment may be pending,6.8418,Other reasons why your payment may be pending ...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 12727.86it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,21,The seller's contact information,7.8049,The seller's contact information After complet...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 14256.45it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,69,The parcel is damaged. What should I do?,9.0282,The parcel is damaged. What should I do? If yo...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13906.29it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,3,How to register with Google or Facebook account,7.88,How to register with Google or Facebook accoun...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13169.65it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,42,Where to check the parcel tracking number and ...,8.9569,Where to check the parcel tracking number and ...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 12101.91it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,83,How much refund you can get from the seller,6.9497,How much refund you can get from the seller Th...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13693.96it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,91,Wire transfer,8.1456,Wire transfer You will get the refund within 3...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 12757.90it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,43,Estimated delivery time,7.2103,Estimated delivery time For every offer on Hop...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 14138.10it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,92,A gift card,7.6769,A gift card If you return an order for which y...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 12244.81it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,16,How to buy again a single product,3.848,How to buy again a single product Go to the Pu...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 17016.98it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,84,How you will learn about the refund,0.0026,How you will learn about the refund We will le...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13532.84it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,71,How to open a Discussion for a canceled order,9.2629,How to open a Discussion for a canceled order ...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 12441.41it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,45,The estimated delivery time may differ from th...,8.9381,The estimated delivery time may differ from th...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13067.99it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,72,Consumer purchase from an entrepreneur,8.5873,Consumer purchase from an entrepreneur If a co...
1,2,73,Purchases from private individuals or transact...,7.3386,Purchases from private individuals or transact...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 12250.86it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,68,The pick-up code does not work. What should I do?,8.5973,The pick-up code does not work. What should I ...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 15907.00it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,79,What if you resign from purchases repeatedly,7.0156,What if you resign from purchases repeatedly I...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13469.06it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,69,The parcel is damaged. What should I do?,6.957,The parcel is damaged. What should I do? If yo...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13689.07it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,90,BLIK,7.4633,BLIK You will get the refund to your bank acco...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 15526.16it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,31,How to pay with PayPal,7.8776,How to pay with PayPal When you are ready to p...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13251.42it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,66,I want to change the pick-up point or parcel l...,6.717,I want to change the pick-up point or parcel l...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 19362.33it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,58,How to return an HopShop Delivery parcel,7.2446,How to return an HopShop Delivery parcel You c...
1,2,47,The HopShop Delivery program — information for...,6.2510,The HopShop Delivery program — information for...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 16093.75it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,57,How much time you have to collect a parcel,6.0985,How much time you have to collect a parcel The...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 14743.62it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,69,The parcel is damaged. What should I do?,2.2867,The parcel is damaged. What should I do? If yo...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 12896.07it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,63,Why can I not find a pick-up point or a parcel...,1.9457,Why can I not find a pick-up point or a parcel...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13548.28it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,80,Check the Discussion time frame,5.8764,Check the Discussion time frame If 2 years (73...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 14075.32it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,56,How to collect a parcel from a parcel locker,9.7764,How to collect a parcel from a parcel locker Y...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 14901.29it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,54,How to share the pick-up code with others,9.641,How to share the pick-up code with others You ...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 15680.95it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,86,A debit card,7.9847,A debit card You will receive a refund to your...
1,2,87,A credit card,5.5557,A credit card You will get your refund to the ...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 15387.31it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,41,How can I track a parcel?,6.8152,How can I track a parcel? You can track your p...
1,2,51,How to check the status of an HopShop Delivery...,6.6868,How to check the status of an HopShop Delivery...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13071.43it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,36,Delivery options on HopShop,7.2828,Delivery options on HopShop When buying on Hop...
1,2,15,How to buy a product on HopShop,6.5039,How to buy a product on HopShop 1. Find the pr...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13417.82it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,10,How to withdraw from the agreement,8.2671,How to withdraw from the agreement To withdraw...
1,2,9,When you can withdraw from the agreement,6.4137,When you can withdraw from the agreement You c...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 14343.04it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,14,How to buy on HopShop,5.4903,"How to buy on HopShop In this article, you wil..."

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 11494.85it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,24,How to pay for orders made from multiple sellers,6.7077,How to pay for orders made from multiple selle...
1,2,30,How to split the payment,5.5755,How to split the payment In the Purchase Histo...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13494.28it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,95,Deadline for processing a complaint,7.6477,Deadline for processing a complaint When the s...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 14635.36it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,4,Signing in with a password and email address,5.4918,Signing in with a password and email address I...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 12137.45it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,19,How to contact the seller,8.8654,How to contact the seller You can contact the ...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13095.39it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,46,Where you can see the estimated delivery time,8.6738,Where you can see the estimated delivery time ...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 14522.91it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,40,I am buying many products — which delivery met...,6.6207,I am buying many products — which delivery met...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 14388.08it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,1,How to register on HopShop,6.9747,How to register on HopShop If you want to be a...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 46995.66it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,63,Why can I not find a pick-up point or a parcel...,6.0865,Why can I not find a pick-up point or a parcel...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13759.45it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,34,Other reasons why your payment may be pending,8.2093,Other reasons why your payment may be pending ...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 15831.72it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,94,I have received a defective product. What shou...,6.5064,I have received a defective product. What shou...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 17109.53it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,87,A credit card,8.9288,A credit card You will get your refund to the ...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 12749.80it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,60,For what reasons you can file a complaint abou...,5.6206,For what reasons you can file a complaint abou...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 14576.65it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,8,How to close your HopShop account,8.6657,How to close your HopShop account You can end ...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 12657.15it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,96,Sending a product back to the seller,8.1695,Sending a product back to the seller If you se...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 21242.60it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,67,I want to change the delivery day. What should...,5.3827,I want to change the delivery day. What should...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 13400.76it/s]
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-12-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,rank,section_id,title,rerank_score,preview
0,1,74,What you should do if you do not receive your ...,7.3588,What you should do if you do not receive your ...
1,2,77,I have been waiting a long time for my order d...,6.5365,I have been waiting a long time for my order d...

      answer_relevance
mean             0.827

,question,reference_answer,generated_answer,relevant_docs,retrieved_docs,answer_relevance
0,Will I get a full refund including shipping if...,The seller refunds you for the returned produc...,The information was not found. You can call th...,[83],[93],0.165476
1,Can I use multiple delivery addresses for one ...,Select one delivery address and one set of VAT...,You can use only one delivery address for the ...,[25],[25],0.870470
2,Why does my payment status show as canceled or...,Your payment may have the Canceled status if:\...,Your payment may show as canceled if the payme...,[33],"[33, 34]",0.879098
3,How can I find the seller's email and phone nu...,"After completing each transaction, we will ema...","After you make a purchase, you can find the se...",[21],[21],0.994199
4,What should I do if my parcel was damaged when...,If you notice the damage in the pick-up point:...,"If you notice the damage at the pick-up point,...",[69],[69],0.886155
5,How do I sign up using my Google or Facebook a...,Open the sign in page.\nSelect signing in thro...,To sign up using your Google or Facebook accou...,[3],[3],0.982205
6,How can I find my parcel's tracking number and...,You can check the delivery status of your parc...,You can find your parcel's tracking number and...,[42],[42],1.000000
7,How will I receive my refund from the seller?,The refund method depends on the payment metho...,The information was not found in the provided ...,[85],[83],0.285321
8,How long does it take to get a refund for a wi...,You will get the refund within 3 business days...,You will get the refund within 3 business days...,[91],[91],0.592771
9,How is the estimated delivery time calculated ...,For every offer on HopShop and on selected pur...,The estimated delivery time on HopShop is calc...,[43],[43],0.992280
10,What happens to my gift card if I return an or...,If you return an order for which you have paid...,"If you return an order paid with a gift card, ...",[92],[92],0.886758
11,How can I reorder a single product from my pas...,Go to the Purchase History tab.\nClick [purcha...,"Go to the Purchase History tab, click [purchas...",[16],[16],0.885962
12,How will I be notified when my refund is proce...,We will let you know by email when the seller ...,You will be notified by email when the seller ...,[84],[84],0.733050
13,How can I open a Discussion if I canceled an o...,If you have paid for your order through HopSho...,You can open a Discussion by yourself in the P...,[71],[71],0.827893
14,Why might my actual delivery time be different...,We calculate the estimated delivery time based...,The actual delivery time may differ from the e...,[45],[45],0.958957
15,Who is responsible if an item is damaged durin...,If a consumer buys an item from an entrepreneu...,"If a consumer buys from an entrepreneur, the e...",[72],"[72, 73]",0.959200
16,What should I do if my pick-up code isn’t work...,"Firstly, make sure you enter the correct pick-...","Firstly, make sure you enter the correct pick-...",[68],[68],0.984579
17,What happens if I frequently cancel or don't p...,If you have failed to pay for the purchase or ...,If you often cancel your orders or fail to pay...,[79],[79],0.913311
18,What do I need to do to pick up my parcel from...,When you get the pick-up code — go to the pick...,The information was not found. You can call th...,[55],[69],0.260302
19,How long does it take to get a BLIK refund and...,You will get the refund to your bank account. ...,You will be refunded within 3 business days. Y...,[90],[90],0.633894
20,How do I pay for my order using PayPal and how...,"When you are ready to pay for your order, go t...","To pay with PayPal, go to the delivery and pay...",[31],[31],0.906331
21,How can I change my parcel locker or pick-up p...,If the seller has yet to dispatch your parcel ...,"If the seller has yet to dispatch your parcel,...",[66],[66],0.852775
22,What are the options for returning a HopShop D...,You can do it in several ways:\nwithin Smart! ...,You can return a HopShop Delivery parcel in se...,[58],"[58, 47]",0.923133
23,How long will my parcel be held at the pick-up...,The parcel will wait for you for:\n2 working d...,Your parcel will be held for 2 working days at...,[57],[57],0.705404
24,What should I do if I'm unsure about my parcel...,If you have any doubts regarding what your par...,The information was not found. You can call th...,[52],[69],0.440842
25,What happens if the parcel locker has no avail...,We will redirect your parcel to a different pa...,The information was not found and you can call...,[65],[63],0.302139
26,Can I open a Discussion for a purchase made mo...,If 2 years (730 days) have passed from making ...,"No, it is impossible to open a Discussion if m...",[80],[80],0.905502
27,How can I collect my parcel from a parcel lock...,You can do it in 2 ways: directly at the locke...,You can collect your parcel from a parcel lock...,[56],[56],0.767007
28,How can I share my HopShop Delivery pick-up co...,You can share the pick-up code of an HopShop D...,You can share your HopShop Delivery pick-up co...,[54],[54],0.976533
29,How long does it take to get a refund to my ba...,You will receive a refund to your bank account...,"If you used a Mastercard debit card, you will ...",[86],"[86, 87]",0.833830
30,How can I track my HopShop Delivery parcel and...,You can check your parcel status in several pl...,You can track your HopShop Delivery parcel and...,[51],"[41, 51]",0.975369
31,How can I find out which delivery options are ...,"When buying on HopShop, you have a wide range ...",To find out which delivery options are availab...,[36],"[36, 15]",1.000000
32,Can I withdraw from the agreement if my accoun...,"To withdraw from the agreement, submit this ap...","No, you cannot withdraw from the agreement if ...",[10],"[10, 9]",0.983724
33,How can I make a purchase or set up recurring ...,"In this article, you will learn\nhow to buy a ...",To make a purchase or set up recurring orders ...,[14],[14],0.993788
34,Can I split payment for multiple orders from d...,"In the Purchase History tab, tick only those o...","Yes, you can split payment for multiple orders...",[30],"[24, 30]",0.997064
35,How long does a seller have to respond to my c...,"When the seller receives your complaint, they ...",The seller has 14 days to respond to your comp...,[95],[95],0.849972
36,How can I enable sign-in with my email and pas...,If you want to be able to sign in to your acco...,To enable sign-in with your email and password...,[4],[4],0.949532
37,What are the ways to contact a seller on HopShop?,You can contact the seller on HopShop in a few...,You can contact a seller on HopShop by clickin...,[19],[19],0.974102
38,Where can I find the estimated delivery time f...,We display the estimated delivery time individ...,You can find the estimated delivery time for a...,[46],[46],0.988038
39,Can I combine shipping costs when buying multi...,You cannot merge delivery costs if you buy fro...,"No, you cannot merge delivery costs if you buy...",[40],[40],0.804899
40,What are the ways to register for a HopShop ac...,"If you want to be an active user of HopShop, r...",You can register for a HopShop account using a...,[1],[1],0.968827
41,Why isn't my usual pick-up point showing on th...,We only display operating pick-up points and p...,If your usual pick-up point isn't showing on t...,[63],[63],0.858996
42,Why is my payment still pending after I paid b...,If you have chosen to pay by a wire transfer i...,If you paid by wire transfer through a third p...,[34],[34],0.549384
43,What should I do if the product I received is ...,,"If you have received a defective product, plea...",[94],[94],0.938470
44,How long does it take to get a refund on my cr...,You will get your refund to the card. In the c...,"For a Mastercard, you will get the refund with...",[87],[87],0.919447
45,What situations allow me to file a complaint a...,You can file a complaint if:\nthe parcel goes ...,You can file a complaint if: your parcel goes ...,[60],[60],0.698187
46,How do I close my HopShop account?,You can end your activity on HopShop by: withd...,You can close your HopShop account by withdraw...,[8],[8],0.985188
47,Do I have to use the original packaging or inc...,If you send the product back as a part of the ...,You are not required to return the product in ...,[96],[96],0.935131
48,How can I change the delivery date before my o...,If the seller has yet to dispatch your parcel ...,"If the seller has yet to dispatch your parcel,...",[67],[67],0.668020
49,What should I do if my order delivery is delay...,Dispatching your order may be delayed if you i...,If your order delivery is delayed and you can'...,[77],"[74, 77]",0.991493