In [1]:
# get faq retriever
# create list queries
# get documents
# evaluation result (use precesion@k, recall@k, mrr, nDCG)

In [ ]:
import sys
sys.path.append("../../")

In [3]:
# get faq retriever
from pathlib import Path

from html import escape

import pandas as pd
from IPython.display import HTML, display

from evaluation.eval import evaluate_retrieval, load_tests, context_relevance
from evaluation.classes import ContextRelevanceWrapper
from evaluation.reporting import (
    build_eval_question_report,
    build_retrieval_doc_rows,
    display_eval_question_report,
    export_retrieval_report_to_markdown,
    get_node_text,
)
from retrieval.faq_retriever import search_faq_hybrid

/Users/ayeustsihneyeu/PythonProjects/hybrid-rag-system/.hybrag/lib/python3.14/site-packages/langchain_core/_api/deprecation.py:25: UserWarning: Core Pydantic V1 functionality isn't compatible with Python 3.14 or greater.
  from pydantic.v1.fields import FieldInfo as FieldInfoV1
/Users/ayeustsihneyeu/PythonProjects/hybrid-rag-system/.hybrag/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
def retrieving(test, top_k):
    context = search_faq_hybrid(test.question, top_k=top_k)
    nodes = getattr(context, "nodes", context)
    return nodes

In [5]:
async def evaluate_all_retrieval(limit=None, top_k=5, markdown_path=None):
    """Render a readable retrieval report for the FAQ notebook."""

    tests = load_tests()
    selected_tests = tests[:limit] if limit is not None else tests
    rows = []
    question_reports = []

    for index, test in enumerate(selected_tests, start=1):
        nodes = retrieving(test, top_k)
        
        metrics = evaluate_retrieval(test, nodes, k=top_k)
        
        result = await context_relevance(ContextRelevanceWrapper(question=test.question, contexts=[get_node_text(item) for item in nodes]))
        metrics["context_relevance"] = result
        rows.append(metrics)
        filtered_metrics = {
            key: value
            for key, value in metrics.items()
            if key.startswith("precision") or key.startswith("recall") or key == "mrr" or key.startswith("ndcg") or key == "context_relevance"
        }
        doc_rows = build_retrieval_doc_rows(nodes, test.relevant_docs)
        display_eval_question_report(
            question=test.question,
            relevant_docs=test.relevant_docs,
            metrics=filtered_metrics,
            text_blocks=[],
            doc_rows=doc_rows,
            index=index,
            total=len(selected_tests),
            metric_columns=4,
        )
        question_report = build_eval_question_report(
            question=test.question,
            relevant_docs=test.relevant_docs,
            retrieved_docs=metrics["retrieved_docs"],
            doc_rows=doc_rows,
            extra_fields={"metrics": filtered_metrics},
            index=index,
            total=len(selected_tests),
        )
        question_reports.append(question_report)

    
    report_df = pd.DataFrame(rows)
    metric_columns = [column for column in report_df.columns if column.startswith(("precision", "recall", "ndcg")) or column in {"mrr", "context_relevance"}]
    summary_df = report_df[metric_columns].mean().to_frame(name="mean").T.round(3)

    display(HTML("<h2 style='margin:32px 0 12px;color:#24292f;'>Final metrics</h2>"))
    display(summary_df)

    if markdown_path is not None:
        saved_path = export_retrieval_report_to_markdown(
            report_df,
            question_reports,
            Path(markdown_path),
            notebook_path="notebooks/08_faq_retrieve_evaluating.ipynb",
        )
        display(HTML(f"<p style='margin:12px 0 0;color:#1a7f37;'>Markdown report saved to: <code>{escape(str(saved_path))}</code></p>"))

    return report_df

In [6]:
await evaluate_all_retrieval(markdown_path="../reports/faq_retrieving_evaluation.md", top_k=10)

,rank,hit,section_id,title,score,preview
0,1,yes,83,How much refund you can get from the seller,0.9059,How much refund you can get from the seller Th...
1,2,no,77,I have been waiting a long time for my order d...,0.7621,I have been waiting a long time for my order d...
2,3,no,93,What to do if the seller does not issue a refund,0.7280,What to do if the seller does not issue a refu...
3,4,no,82,When the seller will issue a refund,0.6756,When the seller will issue a refund The seller...
4,5,no,77,I have been waiting a long time for my order d...,0.6368,are and how they work If you have not received...
5,6,no,70,Can I open a Discussion for a canceled order,0.6089,Can I open a Discussion for a canceled order Y...
6,7,no,94,I have received a defective product. What shou...,0.6048,I have received a defective product. What shou...
7,8,no,40,I am buying many products — which delivery met...,0.5993,I am buying many products — which delivery met...
8,9,no,41,How can I track a parcel?,0.5821,How can I track a parcel? You can track your p...
9,10,no,86,A debit card,0.5739,A debit card You will receive a refund to your...

,rank,hit,section_id,title,score,preview
0,1,yes,25,One delivery address,0.9885,One delivery address Select one delivery addre...
1,2,no,7,Can I have more than one HopShop account,0.8350,"Can I have more than one HopShop account Yes, ..."
2,3,no,40,I am buying many products — which delivery met...,0.7397,I am buying many products — which delivery met...
3,4,no,24,How to pay for orders made from multiple sellers,0.6821,How to pay for orders made from multiple selle...
4,5,no,26,How to choose a delivery option,0.6255,How to choose a delivery option If you buy at ...
5,6,no,47,The HopShop Delivery program — information for...,0.5514,The HopShop Delivery program — information for...
6,7,no,48,What you gain with HopShop Delivery,0.5248,What you gain with HopShop Delivery Convenient...
7,8,no,28,How to pay with one payment for orders from an...,0.5050,How to pay with one payment for orders from an...
8,9,no,77,I have been waiting a long time for my order d...,0.5000,I have been waiting a long time for my order d...
9,10,no,67,I want to change the delivery day. What should...,0.4924,I want to change the delivery day. What should...

,rank,hit,section_id,title,score,preview
0,1,yes,33,Why your payment is pending or canceled,1.0000,Why your payment is pending or canceled Your p...
1,2,no,34,Other reasons why your payment may be pending,0.7570,Other reasons why your payment may be pending ...
2,3,no,35,My payment has not gone through. How to retry ...,0.5757,My payment has not gone through. How to retry ...
3,4,no,29,Payment methods,0.4581,Payment methods You cannot link payment with i...
4,5,no,71,How to open a Discussion for a canceled order,0.4493,How to open a Discussion for a canceled order ...
5,6,no,42,Where to check the parcel tracking number and ...,0.4445,Where to check the parcel tracking number and ...
6,7,no,51,How to check the status of an HopShop Delivery...,0.4258,How to check the status of an HopShop Delivery...
7,8,no,32,HopShop gift cards,0.3963,HopShop gift cards If you are not sure what to...
8,9,no,30,How to split the payment,0.3587,How to split the payment In the Purchase Histo...
9,10,no,77,I have been waiting a long time for my order d...,0.3552,I have been waiting a long time for my order d...

,rank,hit,section_id,title,score,preview
0,1,yes,21,The seller's contact information,1.0000,The seller's contact information After complet...
1,2,no,41,How can I track a parcel?,0.7609,How can I track a parcel? You can track your p...
2,3,no,67,I want to change the delivery day. What should...,0.7249,I want to change the delivery day. What should...
3,4,no,66,I want to change the pick-up point or parcel l...,0.6751,I want to change the pick-up point or parcel l...
4,5,no,77,I have been waiting a long time for my order d...,0.6483,I have been waiting a long time for my order d...
5,6,no,77,I have been waiting a long time for my order d...,0.5740,are and how they work If you have not received...
6,7,no,20,Ask a question the seller,0.5620,Ask a question the seller If you want to ask t...
7,8,no,42,Where to check the parcel tracking number and ...,0.5590,Where to check the parcel tracking number and ...
8,9,no,68,The pick-up code does not work. What should I do?,0.5538,The pick-up code does not work. What should I ...
9,10,no,84,How you will learn about the refund,0.5067,How you will learn about the refund We will le...

,rank,hit,section_id,title,score,preview
0,1,yes,69,The parcel is damaged. What should I do?,1.0000,The parcel is damaged. What should I do? If yo...
1,2,no,66,I want to change the pick-up point or parcel l...,0.7360,I want to change the pick-up point or parcel l...
2,3,no,68,The pick-up code does not work. What should I do?,0.7031,The pick-up code does not work. What should I ...
3,4,no,94,I have received a defective product. What shou...,0.6785,I have received a defective product. What shou...
4,5,no,67,I want to change the delivery day. What should...,0.6213,I want to change the delivery day. What should...
5,6,no,77,I have been waiting a long time for my order d...,0.5066,I have been waiting a long time for my order d...
6,7,no,60,For what reasons you can file a complaint abou...,0.4329,For what reasons you can file a complaint abou...
7,8,no,63,Why can I not find a pick-up point or a parcel...,0.4279,Why can I not find a pick-up point or a parcel...
8,9,no,41,How can I track a parcel?,0.4221,How can I track a parcel? You can track your p...
9,10,no,74,What you should do if you do not receive your ...,0.4188,What you should do if you do not receive your ...

,rank,hit,section_id,title,score,preview
0,1,yes,3,How to register with Google or Facebook account,1.0000,How to register with Google or Facebook accoun...
1,2,no,1,How to register on HopShop,0.4777,How to register on HopShop If you want to be a...
2,3,no,7,Can I have more than one HopShop account,0.3391,"Can I have more than one HopShop account Yes, ..."
3,4,no,2,How to register with an email,0.3365,How to register with an email Open the registr...
4,5,no,4,Signing in with a password and email address,0.3099,Signing in with a password and email address I...
5,6,no,68,The pick-up code does not work. What should I do?,0.3045,The pick-up code does not work. What should I ...
6,7,no,5,How to register with your phone number,0.3011,How to register with your phone number Open th...
7,8,no,54,How to share the pick-up code with others,0.2918,How to share the pick-up code with others You ...
8,9,no,10,How to withdraw from the agreement,0.2874,How to withdraw from the agreement To withdraw...
9,10,no,64,How to find a pick-up point or parcel locker c...,0.2800,How to find a pick-up point or parcel locker c...

,rank,hit,section_id,title,score,preview
0,1,yes,42,Where to check the parcel tracking number and ...,1.0000,Where to check the parcel tracking number and ...
1,2,no,51,How to check the status of an HopShop Delivery...,0.8287,How to check the status of an HopShop Delivery...
2,3,no,41,How can I track a parcel?,0.7543,How can I track a parcel? You can track your p...
3,4,no,77,I have been waiting a long time for my order d...,0.6009,I have been waiting a long time for my order d...
4,5,no,50,How to order a parcel with HopShop Delivery,0.5570,How to order a parcel with HopShop Delivery Wh...
5,6,no,59,How to file a complaint about an HopShop Deliv...,0.5534,How to file a complaint about an HopShop Deliv...
6,7,no,58,How to return an HopShop Delivery parcel,0.4772,How to return an HopShop Delivery parcel You c...
7,8,no,64,How to find a pick-up point or parcel locker c...,0.4540,How to find a pick-up point or parcel locker c...
8,9,no,47,The HopShop Delivery program — information for...,0.4450,The HopShop Delivery program — information for...
9,10,no,49,How much HopShop Delivery is,0.4396,How much HopShop Delivery is Delivery within H...

,rank,hit,section_id,title,score,preview
0,1,no,83,How much refund you can get from the seller,1.0000,How much refund you can get from the seller Th...
1,2,yes,85,How the seller will refund you,0.8511,How the seller will refund you The refund meth...
2,3,no,82,When the seller will issue a refund,0.7898,When the seller will issue a refund The seller...
3,4,no,84,How you will learn about the refund,0.7822,How you will learn about the refund We will le...
4,5,no,93,What to do if the seller does not issue a refund,0.6925,What to do if the seller does not issue a refu...
5,6,no,77,I have been waiting a long time for my order d...,0.6705,I have been waiting a long time for my order d...
6,7,no,77,I have been waiting a long time for my order d...,0.6465,are and how they work If you have not received...
7,8,no,81,How to open a Discussion,0.5969,How to open a Discussion In the Purchase Histo...
8,9,no,74,What you should do if you do not receive your ...,0.5728,What you should do if you do not receive your ...
9,10,no,86,A debit card,0.5703,A debit card You will receive a refund to your...

,rank,hit,section_id,title,score,preview
0,1,yes,91,Wire transfer,1.0000,Wire transfer You will get the refund within 3...
1,2,no,89,Bank transfer,0.5782,Bank transfer You will get the refund to the b...
2,3,no,93,What to do if the seller does not issue a refund,0.5205,What to do if the seller does not issue a refu...
3,4,no,77,I have been waiting a long time for my order d...,0.5025,I have been waiting a long time for my order d...
4,5,no,34,Other reasons why your payment may be pending,0.4529,Other reasons why your payment may be pending ...
5,6,no,83,How much refund you can get from the seller,0.4475,How much refund you can get from the seller Th...
6,7,no,86,A debit card,0.4338,A debit card You will receive a refund to your...
7,8,no,77,I have been waiting a long time for my order d...,0.4299,are and how they work If you have not received...
8,9,no,87,A credit card,0.3979,A credit card You will get your refund to the ...
9,10,no,90,BLIK,0.3792,BLIK You will get the refund to your bank acco...

,rank,hit,section_id,title,score,preview
0,1,yes,43,Estimated delivery time,1.0000,Estimated delivery time For every offer on Hop...
1,2,no,44,How we calculate the estimated delivery time,0.8760,How we calculate the estimated delivery time A...
2,3,no,45,The estimated delivery time may differ from th...,0.8227,The estimated delivery time may differ from th...
3,4,no,46,Where you can see the estimated delivery time,0.7793,Where you can see the estimated delivery time ...
4,5,no,50,How to order a parcel with HopShop Delivery,0.6295,How to order a parcel with HopShop Delivery Wh...
5,6,no,37,What is the delivery time?,0.6250,What is the delivery time? The estimated deliv...
6,7,no,49,How much HopShop Delivery is,0.6059,How much HopShop Delivery is Delivery within H...
7,8,no,47,The HopShop Delivery program — information for...,0.5613,The HopShop Delivery program — information for...
8,9,no,36,Delivery options on HopShop,0.5507,Delivery options on HopShop When buying on Hop...
9,10,no,48,What you gain with HopShop Delivery,0.5380,What you gain with HopShop Delivery Convenient...

,rank,hit,section_id,title,score,preview
0,1,yes,92,A gift card,1.0000,A gift card If you return an order for which y...
1,2,no,32,HopShop gift cards,0.5968,HopShop gift cards If you are not sure what to...
2,3,no,77,I have been waiting a long time for my order d...,0.5865,I have been waiting a long time for my order d...
3,4,no,86,A debit card,0.5294,A debit card You will receive a refund to your...
4,5,no,70,Can I open a Discussion for a canceled order,0.5003,Can I open a Discussion for a canceled order Y...
5,6,no,94,I have received a defective product. What shou...,0.4982,I have received a defective product. What shou...
6,7,no,77,I have been waiting a long time for my order d...,0.4727,are and how they work If you have not received...
7,8,no,68,The pick-up code does not work. What should I do?,0.4609,The pick-up code does not work. What should I ...
8,9,no,67,I want to change the delivery day. What should...,0.4530,I want to change the delivery day. What should...
9,10,no,87,A credit card,0.4470,A credit card You will get your refund to the ...

,rank,hit,section_id,title,score,preview
0,1,yes,16,How to buy again a single product,1.0000,How to buy again a single product Go to the Pu...
1,2,no,15,How to buy a product on HopShop,0.8245,to buy the same product or all products from a...
2,3,no,17,How to buy again all products from a previous ...,0.7427,How to buy again all products from a previous ...
3,4,no,18,How to make recurring purchases,0.6720,How to make recurring purchases If you buy a p...
4,5,no,15,How to buy a product on HopShop,0.5999,How to buy a product on HopShop 1. Find the pr...
5,6,no,35,My payment has not gone through. How to retry ...,0.5246,My payment has not gone through. How to retry ...
6,7,no,14,How to buy on HopShop,0.5109,"How to buy on HopShop In this article, you wil..."
7,8,no,77,I have been waiting a long time for my order d...,0.5028,I have been waiting a long time for my order d...
8,9,no,41,How can I track a parcel?,0.4507,How can I track a parcel? You can track your p...
9,10,no,79,What if you resign from purchases repeatedly,0.4490,What if you resign from purchases repeatedly I...

,rank,hit,section_id,title,score,preview
0,1,yes,84,How you will learn about the refund,0.9845,How you will learn about the refund We will le...
1,2,no,85,How the seller will refund you,0.7460,How the seller will refund you The refund meth...
2,3,no,82,When the seller will issue a refund,0.7407,When the seller will issue a refund The seller...
3,4,no,77,I have been waiting a long time for my order d...,0.6819,I have been waiting a long time for my order d...
4,5,no,83,How much refund you can get from the seller,0.6336,How much refund you can get from the seller Th...
5,6,no,88,Refund and card block,0.6074,Refund and card block If your card has been bl...
6,7,no,35,My payment has not gone through. How to retry ...,0.5612,My payment has not gone through. How to retry ...
7,8,no,90,BLIK,0.5316,BLIK You will get the refund to your bank acco...
8,9,no,87,A credit card,0.5295,A credit card You will get your refund to the ...
9,10,no,77,I have been waiting a long time for my order d...,0.5266,are and how they work If you have not received...

,rank,hit,section_id,title,score,preview
0,1,yes,71,How to open a Discussion for a canceled order,0.9694,How to open a Discussion for a canceled order ...
1,2,no,70,Can I open a Discussion for a canceled order,0.8936,Can I open a Discussion for a canceled order Y...
2,3,no,81,How to open a Discussion,0.6502,How to open a Discussion In the Purchase Histo...
3,4,no,77,I have been waiting a long time for my order d...,0.6143,I have been waiting a long time for my order d...
4,5,no,77,I have been waiting a long time for my order d...,0.5230,are and how they work If you have not received...
5,6,no,33,Why your payment is pending or canceled,0.5178,Why your payment is pending or canceled Your p...
6,7,no,76,Discussion time frames,0.4962,Discussion time frames 1 hour after the purcha...
7,8,no,93,What to do if the seller does not issue a refund,0.4881,What to do if the seller does not issue a refu...
8,9,no,35,My payment has not gone through. How to retry ...,0.4654,My payment has not gone through. How to retry ...
9,10,no,75,If the issue still has not been resolved or th...,0.4641,If the issue still has not been resolved or th...

,rank,hit,section_id,title,score,preview
0,1,yes,45,The estimated delivery time may differ from th...,1.0000,The estimated delivery time may differ from th...
1,2,no,46,Where you can see the estimated delivery time,0.6857,Where you can see the estimated delivery time ...
2,3,no,43,Estimated delivery time,0.6580,Estimated delivery time For every offer on Hop...
3,4,no,44,How we calculate the estimated delivery time,0.6172,How we calculate the estimated delivery time A...
4,5,no,37,What is the delivery time?,0.5938,What is the delivery time? The estimated deliv...
5,6,no,77,I have been waiting a long time for my order d...,0.4814,I have been waiting a long time for my order d...
6,7,no,63,Why can I not find a pick-up point or a parcel...,0.3883,Why can I not find a pick-up point or a parcel...
7,8,no,77,I have been waiting a long time for my order d...,0.3505,are and how they work If you have not received...
8,9,no,34,Other reasons why your payment may be pending,0.3457,Other reasons why your payment may be pending ...
9,10,no,67,I want to change the delivery day. What should...,0.3424,I want to change the delivery day. What should...

,rank,hit,section_id,title,score,preview
0,1,yes,72,Consumer purchase from an entrepreneur,1.0000,Consumer purchase from an entrepreneur If a co...
1,2,no,97,Consumer sales (when a consumer buys from an e...,0.7165,Consumer sales (when a consumer buys from an e...
2,3,no,73,Purchases from private individuals or transact...,0.7056,Purchases from private individuals or transact...
3,4,no,69,The parcel is damaged. What should I do?,0.4745,The parcel is damaged. What should I do? If yo...
4,5,no,40,I am buying many products — which delivery met...,0.4372,I am buying many products — which delivery met...
5,6,no,60,For what reasons you can file a complaint abou...,0.3696,For what reasons you can file a complaint abou...
6,7,no,83,How much refund you can get from the seller,0.3427,How much refund you can get from the seller Th...
7,8,no,36,Delivery options on HopShop,0.3210,Delivery options on HopShop When buying on Hop...
8,9,no,77,I have been waiting a long time for my order d...,0.2978,are and how they work If you have not received...
9,10,no,77,I have been waiting a long time for my order d...,0.2931,I have been waiting a long time for my order d...

,rank,hit,section_id,title,score,preview
0,1,yes,68,The pick-up code does not work. What should I do?,1.0000,The pick-up code does not work. What should I ...
1,2,no,66,I want to change the pick-up point or parcel l...,0.7981,I want to change the pick-up point or parcel l...
2,3,no,53,When you receive a pick-up code,0.6234,When you receive a pick-up code You will recei...
3,4,no,63,Why can I not find a pick-up point or a parcel...,0.6024,Why can I not find a pick-up point or a parcel...
4,5,no,64,How to find a pick-up point or parcel locker c...,0.6015,How to find a pick-up point or parcel locker c...
5,6,no,69,The parcel is damaged. What should I do?,0.5851,The parcel is damaged. What should I do? If yo...
6,7,no,56,How to collect a parcel from a parcel locker,0.5733,How to collect a parcel from a parcel locker Y...
7,8,no,65,What if the parcel locker is full?,0.5530,What if the parcel locker is full? We will red...
8,9,no,55,How to collect a parcel from a pick-up point,0.5470,How to collect a parcel from a pick-up point W...
9,10,no,54,How to share the pick-up code with others,0.5331,How to share the pick-up code with others You ...

,rank,hit,section_id,title,score,preview
0,1,yes,79,What if you resign from purchases repeatedly,1.0000,What if you resign from purchases repeatedly I...
1,2,no,35,My payment has not gone through. How to retry ...,0.8106,My payment has not gone through. How to retry ...
2,3,no,77,I have been waiting a long time for my order d...,0.6600,are and how they work If you have not received...
3,4,no,77,I have been waiting a long time for my order d...,0.6414,I have been waiting a long time for my order d...
4,5,no,12,How to terminate the agreement,0.6363,How to terminate the agreement To terminate th...
5,6,no,13,What you should do before the notice period ends,0.6247,What you should do before the notice period en...
6,7,no,7,Can I have more than one HopShop account,0.6069,"Can I have more than one HopShop account Yes, ..."
7,8,no,32,HopShop gift cards,0.5964,HopShop gift cards If you are not sure what to...
8,9,no,29,Payment methods,0.5739,Payment methods You cannot link payment with i...
9,10,no,14,How to buy on HopShop,0.5678,"How to buy on HopShop In this article, you wil..."

,rank,hit,section_id,title,score,preview
0,1,yes,55,How to collect a parcel from a pick-up point,0.8913,How to collect a parcel from a pick-up point W...
1,2,no,66,I want to change the pick-up point or parcel l...,0.8538,I want to change the pick-up point or parcel l...
2,3,no,64,How to find a pick-up point or parcel locker c...,0.7613,How to find a pick-up point or parcel locker c...
3,4,no,68,The pick-up code does not work. What should I do?,0.7391,The pick-up code does not work. What should I ...
4,5,no,53,When you receive a pick-up code,0.6658,When you receive a pick-up code You will recei...
5,6,no,63,Why can I not find a pick-up point or a parcel...,0.6610,Why can I not find a pick-up point or a parcel...
6,7,no,69,The parcel is damaged. What should I do?,0.6095,The parcel is damaged. What should I do? If yo...
7,8,no,56,How to collect a parcel from a parcel locker,0.5531,How to collect a parcel from a parcel locker Y...
8,9,no,54,How to share the pick-up code with others,0.5184,How to share the pick-up code with others You ...
9,10,no,57,How much time you have to collect a parcel,0.4830,How much time you have to collect a parcel The...

,rank,hit,section_id,title,score,preview
0,1,yes,90,BLIK,1.0000,BLIK You will get the refund to your bank acco...
1,2,no,89,Bank transfer,0.7002,Bank transfer You will get the refund to the b...
2,3,no,86,A debit card,0.5915,A debit card You will receive a refund to your...
3,4,no,87,A credit card,0.5777,A credit card You will get your refund to the ...
4,5,no,77,I have been waiting a long time for my order d...,0.5352,I have been waiting a long time for my order d...
5,6,no,83,How much refund you can get from the seller,0.5324,How much refund you can get from the seller Th...
6,7,no,46,Where you can see the estimated delivery time,0.5088,Where you can see the estimated delivery time ...
7,8,no,91,Wire transfer,0.5051,Wire transfer You will get the refund within 3...
8,9,no,88,Refund and card block,0.4939,Refund and card block If your card has been bl...
9,10,no,93,What to do if the seller does not issue a refund,0.4648,What to do if the seller does not issue a refu...

,rank,hit,section_id,title,score,preview
0,1,yes,31,How to pay with PayPal,1.0000,How to pay with PayPal When you are ready to p...
1,2,no,30,How to split the payment,0.5611,How to split the payment In the Purchase Histo...
2,3,no,77,I have been waiting a long time for my order d...,0.5391,are and how they work If you have not received...
3,4,no,68,The pick-up code does not work. What should I do?,0.5205,The pick-up code does not work. What should I ...
4,5,no,24,How to pay for orders made from multiple sellers,0.4780,How to pay for orders made from multiple selle...
5,6,no,77,I have been waiting a long time for my order d...,0.4359,I have been waiting a long time for my order d...
6,7,no,35,My payment has not gone through. How to retry ...,0.4281,My payment has not gone through. How to retry ...
7,8,no,28,How to pay with one payment for orders from an...,0.4216,How to pay with one payment for orders from an...
8,9,no,40,I am buying many products — which delivery met...,0.3595,I am buying many products — which delivery met...
9,10,no,41,How can I track a parcel?,0.3480,How can I track a parcel? You can track your p...

,rank,hit,section_id,title,score,preview
0,1,yes,66,I want to change the pick-up point or parcel l...,0.9835,I want to change the pick-up point or parcel l...
1,2,no,64,How to find a pick-up point or parcel locker c...,0.8189,How to find a pick-up point or parcel locker c...
2,3,no,63,Why can I not find a pick-up point or a parcel...,0.6652,Why can I not find a pick-up point or a parcel...
3,4,no,68,The pick-up code does not work. What should I do?,0.5376,The pick-up code does not work. What should I ...
4,5,no,67,I want to change the delivery day. What should...,0.5347,I want to change the delivery day. What should...
5,6,no,55,How to collect a parcel from a pick-up point,0.5185,How to collect a parcel from a pick-up point W...
6,7,no,65,What if the parcel locker is full?,0.4857,What if the parcel locker is full? We will red...
7,8,no,56,How to collect a parcel from a parcel locker,0.4648,How to collect a parcel from a parcel locker Y...
8,9,no,53,When you receive a pick-up code,0.4512,When you receive a pick-up code You will recei...
9,10,no,77,I have been waiting a long time for my order d...,0.4490,I have been waiting a long time for my order d...

,rank,hit,section_id,title,score,preview
0,1,no,36,Delivery options on HopShop,0.8986,Delivery options on HopShop When buying on Hop...
1,2,yes,58,How to return an HopShop Delivery parcel,0.8276,How to return an HopShop Delivery parcel You c...
2,3,no,47,The HopShop Delivery program — information for...,0.7467,The HopShop Delivery program — information for...
3,4,no,48,What you gain with HopShop Delivery,0.7124,What you gain with HopShop Delivery Convenient...
4,5,no,50,How to order a parcel with HopShop Delivery,0.6986,How to order a parcel with HopShop Delivery Wh...
5,6,no,61,What are the maximum dimensions and weight of ...,0.6798,What are the maximum dimensions and weight of ...
6,7,no,56,How to collect a parcel from a parcel locker,0.6065,How to collect a parcel from a parcel locker Y...
7,8,no,51,How to check the status of an HopShop Delivery...,0.5812,How to check the status of an HopShop Delivery...
8,9,no,59,How to file a complaint about an HopShop Deliv...,0.5744,How to file a complaint about an HopShop Deliv...
9,10,no,49,How much HopShop Delivery is,0.5626,How much HopShop Delivery is Delivery within H...

,rank,hit,section_id,title,score,preview
0,1,no,64,How to find a pick-up point or parcel locker c...,0.8017,How to find a pick-up point or parcel locker c...
1,2,no,55,How to collect a parcel from a pick-up point,0.7877,How to collect a parcel from a pick-up point W...
2,3,yes,57,How much time you have to collect a parcel,0.7662,How much time you have to collect a parcel The...
3,4,no,66,I want to change the pick-up point or parcel l...,0.6864,I want to change the pick-up point or parcel l...
4,5,no,63,Why can I not find a pick-up point or a parcel...,0.6404,Why can I not find a pick-up point or a parcel...
5,6,no,53,When you receive a pick-up code,0.5826,When you receive a pick-up code You will recei...
6,7,no,65,What if the parcel locker is full?,0.5223,What if the parcel locker is full? We will red...
7,8,no,68,The pick-up code does not work. What should I do?,0.5079,The pick-up code does not work. What should I ...
8,9,no,54,How to share the pick-up code with others,0.5065,How to share the pick-up code with others You ...
9,10,no,77,I have been waiting a long time for my order d...,0.4742,I have been waiting a long time for my order d...

,rank,hit,section_id,title,score,preview
0,1,no,66,I want to change the pick-up point or parcel l...,0.8084,I want to change the pick-up point or parcel l...
1,2,no,67,I want to change the delivery day. What should...,0.7860,I want to change the delivery day. What should...
2,3,no,69,The parcel is damaged. What should I do?,0.7652,The parcel is damaged. What should I do? If yo...
3,4,no,68,The pick-up code does not work. What should I do?,0.7382,The pick-up code does not work. What should I ...
4,5,yes,52,If the parcel status is not clear,0.7329,If the parcel status is not clear If you have ...
5,6,no,94,I have received a defective product. What shou...,0.7065,I have received a defective product. What shou...
6,7,no,77,I have been waiting a long time for my order d...,0.6784,I have been waiting a long time for my order d...
7,8,no,41,How can I track a parcel?,0.6272,How can I track a parcel? You can track your p...
8,9,no,74,What you should do if you do not receive your ...,0.6237,What you should do if you do not receive your ...
9,10,no,42,Where to check the parcel tracking number and ...,0.5685,Where to check the parcel tracking number and ...

,rank,hit,section_id,title,score,preview
0,1,yes,65,What if the parcel locker is full?,0.9721,What if the parcel locker is full? We will red...
1,2,no,66,I want to change the pick-up point or parcel l...,0.7771,I want to change the pick-up point or parcel l...
2,3,no,64,How to find a pick-up point or parcel locker c...,0.7608,How to find a pick-up point or parcel locker c...
3,4,no,69,The parcel is damaged. What should I do?,0.6731,The parcel is damaged. What should I do? If yo...
4,5,no,56,How to collect a parcel from a parcel locker,0.6355,How to collect a parcel from a parcel locker Y...
5,6,no,63,Why can I not find a pick-up point or a parcel...,0.5929,Why can I not find a pick-up point or a parcel...
6,7,no,68,The pick-up code does not work. What should I do?,0.5675,The pick-up code does not work. What should I ...
7,8,no,35,My payment has not gone through. How to retry ...,0.4621,My payment has not gone through. How to retry ...
8,9,no,77,I have been waiting a long time for my order d...,0.4467,I have been waiting a long time for my order d...
9,10,no,61,What are the maximum dimensions and weight of ...,0.4431,What are the maximum dimensions and weight of ...

,rank,hit,section_id,title,score,preview
0,1,no,70,Can I open a Discussion for a canceled order,0.7945,Can I open a Discussion for a canceled order Y...
1,2,yes,80,Check the Discussion time frame,0.7933,Check the Discussion time frame If 2 years (73...
2,3,no,71,How to open a Discussion for a canceled order,0.7005,How to open a Discussion for a canceled order ...
3,4,no,81,How to open a Discussion,0.6872,How to open a Discussion In the Purchase Histo...
4,5,no,76,Discussion time frames,0.6167,Discussion time frames 1 hour after the purcha...
5,6,no,7,Can I have more than one HopShop account,0.5977,"Can I have more than one HopShop account Yes, ..."
6,7,no,75,If the issue still has not been resolved or th...,0.5742,If the issue still has not been resolved or th...
7,8,no,77,I have been waiting a long time for my order d...,0.5281,I have been waiting a long time for my order d...
8,9,no,77,I have been waiting a long time for my order d...,0.5237,are and how they work If you have not received...
9,10,no,79,What if you resign from purchases repeatedly,0.5169,What if you resign from purchases repeatedly I...

,rank,hit,section_id,title,score,preview
0,1,yes,56,How to collect a parcel from a parcel locker,1.0000,How to collect a parcel from a parcel locker Y...
1,2,no,55,How to collect a parcel from a pick-up point,0.7814,How to collect a parcel from a pick-up point W...
2,3,no,54,How to share the pick-up code with others,0.7687,How to share the pick-up code with others You ...
3,4,no,53,When you receive a pick-up code,0.7656,When you receive a pick-up code You will recei...
4,5,no,68,The pick-up code does not work. What should I do?,0.6942,The pick-up code does not work. What should I ...
5,6,no,64,How to find a pick-up point or parcel locker c...,0.6825,How to find a pick-up point or parcel locker c...
6,7,no,66,I want to change the pick-up point or parcel l...,0.6425,I want to change the pick-up point or parcel l...
7,8,no,63,Why can I not find a pick-up point or a parcel...,0.6041,Why can I not find a pick-up point or a parcel...
8,9,no,51,How to check the status of an HopShop Delivery...,0.5895,How to check the status of an HopShop Delivery...
9,10,no,57,How much time you have to collect a parcel,0.5441,How much time you have to collect a parcel The...

,rank,hit,section_id,title,score,preview
0,1,yes,54,How to share the pick-up code with others,1.0000,How to share the pick-up code with others You ...
1,2,no,53,When you receive a pick-up code,0.6140,When you receive a pick-up code You will recei...
2,3,no,68,The pick-up code does not work. What should I do?,0.5457,The pick-up code does not work. What should I ...
3,4,no,56,How to collect a parcel from a parcel locker,0.4979,How to collect a parcel from a parcel locker Y...
4,5,no,47,The HopShop Delivery program — information for...,0.4397,The HopShop Delivery program — information for...
5,6,no,48,What you gain with HopShop Delivery,0.4216,What you gain with HopShop Delivery Convenient...
6,7,no,64,How to find a pick-up point or parcel locker c...,0.4063,How to find a pick-up point or parcel locker c...
7,8,no,55,How to collect a parcel from a pick-up point,0.4046,How to collect a parcel from a pick-up point W...
8,9,no,50,How to order a parcel with HopShop Delivery,0.4043,How to order a parcel with HopShop Delivery Wh...
9,10,no,51,How to check the status of an HopShop Delivery...,0.3988,How to check the status of an HopShop Delivery...

,rank,hit,section_id,title,score,preview
0,1,yes,86,A debit card,1.0000,A debit card You will receive a refund to your...
1,2,no,87,A credit card,0.7250,A credit card You will get your refund to the ...
2,3,no,88,Refund and card block,0.6625,Refund and card block If your card has been bl...
3,4,no,89,Bank transfer,0.6558,Bank transfer You will get the refund to the b...
4,5,no,90,BLIK,0.5630,BLIK You will get the refund to your bank acco...
5,6,no,91,Wire transfer,0.5287,Wire transfer You will get the refund within 3...
6,7,no,92,A gift card,0.4722,A gift card If you return an order for which y...
7,8,no,77,I have been waiting a long time for my order d...,0.4531,I have been waiting a long time for my order d...
8,9,no,93,What to do if the seller does not issue a refund,0.4449,What to do if the seller does not issue a refu...
9,10,no,83,How much refund you can get from the seller,0.4270,How much refund you can get from the seller Th...

,rank,hit,section_id,title,score,preview
0,1,no,41,How can I track a parcel?,0.8920,How can I track a parcel? You can track your p...
1,2,yes,51,How to check the status of an HopShop Delivery...,0.7862,How to check the status of an HopShop Delivery...
2,3,no,42,Where to check the parcel tracking number and ...,0.6867,Where to check the parcel tracking number and ...
3,4,no,50,How to order a parcel with HopShop Delivery,0.6421,How to order a parcel with HopShop Delivery Wh...
4,5,no,58,How to return an HopShop Delivery parcel,0.5664,How to return an HopShop Delivery parcel You c...
5,6,no,77,I have been waiting a long time for my order d...,0.5617,I have been waiting a long time for my order d...
6,7,no,53,When you receive a pick-up code,0.5611,When you receive a pick-up code You will recei...
7,8,no,47,The HopShop Delivery program — information for...,0.5376,The HopShop Delivery program — information for...
8,9,no,56,How to collect a parcel from a parcel locker,0.5333,How to collect a parcel from a parcel locker Y...
9,10,no,59,How to file a complaint about an HopShop Deliv...,0.5329,How to file a complaint about an HopShop Deliv...

,rank,hit,section_id,title,score,preview
0,1,yes,36,Delivery options on HopShop,1.0000,Delivery options on HopShop When buying on Hop...
1,2,no,47,The HopShop Delivery program — information for...,0.8145,The HopShop Delivery program — information for...
2,3,no,40,I am buying many products — which delivery met...,0.7201,I am buying many products — which delivery met...
3,4,no,58,How to return an HopShop Delivery parcel,0.6684,How to return an HopShop Delivery parcel You c...
4,5,no,50,How to order a parcel with HopShop Delivery,0.6682,How to order a parcel with HopShop Delivery Wh...
5,6,no,49,How much HopShop Delivery is,0.6609,How much HopShop Delivery is Delivery within H...
6,7,no,51,How to check the status of an HopShop Delivery...,0.6559,How to check the status of an HopShop Delivery...
7,8,no,26,How to choose a delivery option,0.6473,How to choose a delivery option If you buy at ...
8,9,no,15,How to buy a product on HopShop,0.6025,How to buy a product on HopShop 1. Find the pr...
9,10,no,41,How can I track a parcel?,0.6021,How can I track a parcel? You can track your p...

,rank,hit,section_id,title,score,preview
0,1,no,9,When you can withdraw from the agreement,1.0000,When you can withdraw from the agreement You c...
1,2,yes,10,How to withdraw from the agreement,0.9241,How to withdraw from the agreement To withdraw...
2,3,no,11,When you can terminate the agreement,0.6075,When you can terminate the agreement You can t...
3,4,no,12,How to terminate the agreement,0.5165,How to terminate the agreement To terminate th...
4,5,no,7,Can I have more than one HopShop account,0.5012,"Can I have more than one HopShop account Yes, ..."
5,6,no,8,How to close your HopShop account,0.4159,How to close your HopShop account You can end ...
6,7,no,77,I have been waiting a long time for my order d...,0.3908,I have been waiting a long time for my order d...
7,8,no,77,I have been waiting a long time for my order d...,0.3828,are and how they work If you have not received...
8,9,no,76,Discussion time frames,0.3539,Discussion time frames 1 hour after the purcha...
9,10,no,80,Check the Discussion time frame,0.3399,Check the Discussion time frame If 2 years (73...

,rank,hit,section_id,title,score,preview
0,1,no,18,How to make recurring purchases,0.8380,How to make recurring purchases If you buy a p...
1,2,yes,14,How to buy on HopShop,0.8145,"How to buy on HopShop In this article, you wil..."
2,3,no,39,How to provide shipping details?,0.6041,How to provide shipping details? If you have a...
3,4,no,15,How to buy a product on HopShop,0.6023,How to buy a product on HopShop 1. Find the pr...
4,5,no,32,HopShop gift cards,0.5922,HopShop gift cards If you are not sure what to...
5,6,no,50,How to order a parcel with HopShop Delivery,0.5808,How to order a parcel with HopShop Delivery Wh...
6,7,no,15,How to buy a product on HopShop,0.5749,to buy the same product or all products from a...
7,8,no,7,Can I have more than one HopShop account,0.5560,"Can I have more than one HopShop account Yes, ..."
8,9,no,48,What you gain with HopShop Delivery,0.5498,What you gain with HopShop Delivery Convenient...
9,10,no,1,How to register on HopShop,0.5128,How to register on HopShop If you want to be a...

,rank,hit,section_id,title,score,preview
0,1,no,24,How to pay for orders made from multiple sellers,1.0000,How to pay for orders made from multiple selle...
1,2,yes,30,How to split the payment,0.7276,How to split the payment In the Purchase Histo...
2,3,no,28,How to pay with one payment for orders from an...,0.5539,How to pay with one payment for orders from an...
3,4,no,40,I am buying many products — which delivery met...,0.5375,I am buying many products — which delivery met...
4,5,no,26,How to choose a delivery option,0.4761,How to choose a delivery option If you buy at ...
5,6,no,29,Payment methods,0.4364,Payment methods You cannot link payment with i...
6,7,no,41,How can I track a parcel?,0.4209,How can I track a parcel? You can track your p...
7,8,no,70,Can I open a Discussion for a canceled order,0.3449,Can I open a Discussion for a canceled order Y...
8,9,no,67,I want to change the delivery day. What should...,0.3360,I want to change the delivery day. What should...
9,10,no,35,My payment has not gone through. How to retry ...,0.3316,My payment has not gone through. How to retry ...

,rank,hit,section_id,title,score,preview
0,1,yes,95,Deadline for processing a complaint,1.0000,Deadline for processing a complaint When the s...
1,2,no,77,I have been waiting a long time for my order d...,0.7281,I have been waiting a long time for my order d...
2,3,no,77,I have been waiting a long time for my order d...,0.6953,are and how they work If you have not received...
3,4,no,75,If the issue still has not been resolved or th...,0.5880,If the issue still has not been resolved or th...
4,5,no,93,What to do if the seller does not issue a refund,0.5692,What to do if the seller does not issue a refu...
5,6,no,60,For what reasons you can file a complaint abou...,0.5326,For what reasons you can file a complaint abou...
6,7,no,59,How to file a complaint about an HopShop Deliv...,0.5041,How to file a complaint about an HopShop Deliv...
7,8,no,76,Discussion time frames,0.4322,Discussion time frames 1 hour after the purcha...
8,9,no,82,When the seller will issue a refund,0.4123,When the seller will issue a refund The seller...
9,10,no,78,Cancelling an order,0.3883,Cancelling an order You can cancel an order in...

,rank,hit,section_id,title,score,preview
0,1,yes,4,Signing in with a password and email address,1.0000,Signing in with a password and email address I...
1,2,no,2,How to register with an email,0.5941,How to register with an email Open the registr...
2,3,no,3,How to register with Google or Facebook account,0.4754,How to register with Google or Facebook accoun...
3,4,no,41,How can I track a parcel?,0.3986,How can I track a parcel? You can track your p...
4,5,no,35,My payment has not gone through. How to retry ...,0.3635,My payment has not gone through. How to retry ...
5,6,no,77,I have been waiting a long time for my order d...,0.3615,I have been waiting a long time for my order d...
6,7,no,77,I have been waiting a long time for my order d...,0.3615,are and how they work If you have not received...
7,8,no,66,I want to change the pick-up point or parcel l...,0.3473,I want to change the pick-up point or parcel l...
8,9,no,6,GDPR — how you can download your personal data...,0.3466,GDPR — how you can download your personal data...
9,10,no,1,How to register on HopShop,0.3386,How to register on HopShop If you want to be a...

,rank,hit,section_id,title,score,preview
0,1,yes,19,How to contact the seller,1.0000,How to contact the seller You can contact the ...
1,2,no,21,The seller's contact information,0.6546,The seller's contact information After complet...
2,3,no,20,Ask a question the seller,0.6418,Ask a question the seller If you want to ask t...
3,4,no,93,What to do if the seller does not issue a refund,0.5576,What to do if the seller does not issue a refu...
4,5,no,32,HopShop gift cards,0.5268,HopShop gift cards If you are not sure what to...
5,6,no,36,Delivery options on HopShop,0.5139,Delivery options on HopShop When buying on Hop...
6,7,no,22,The Message Center,0.4998,The Message Center If you do not want to exit ...
7,8,no,14,How to buy on HopShop,0.4927,"How to buy on HopShop In this article, you wil..."
8,9,no,58,How to return an HopShop Delivery parcel,0.4829,How to return an HopShop Delivery parcel You c...
9,10,no,48,What you gain with HopShop Delivery,0.4560,What you gain with HopShop Delivery Convenient...

,rank,hit,section_id,title,score,preview
0,1,yes,46,Where you can see the estimated delivery time,1.0000,Where you can see the estimated delivery time ...
1,2,no,43,Estimated delivery time,0.7597,Estimated delivery time For every offer on Hop...
2,3,no,37,What is the delivery time?,0.6872,What is the delivery time? The estimated deliv...
3,4,no,45,The estimated delivery time may differ from th...,0.6729,The estimated delivery time may differ from th...
4,5,no,44,How we calculate the estimated delivery time,0.6422,How we calculate the estimated delivery time A...
5,6,no,77,I have been waiting a long time for my order d...,0.4920,I have been waiting a long time for my order d...
6,7,no,67,I want to change the delivery day. What should...,0.4560,I want to change the delivery day. What should...
7,8,no,42,Where to check the parcel tracking number and ...,0.4390,Where to check the parcel tracking number and ...
8,9,no,38,How much does delivery cost?,0.4134,How much does delivery cost? The cost of deliv...
9,10,no,41,How can I track a parcel?,0.4123,How can I track a parcel? You can track your p...

,rank,hit,section_id,title,score,preview
0,1,yes,40,I am buying many products — which delivery met...,1.0000,I am buying many products — which delivery met...
1,2,no,24,How to pay for orders made from multiple sellers,0.9453,How to pay for orders made from multiple selle...
2,3,no,26,How to choose a delivery option,0.6523,How to choose a delivery option If you buy at ...
3,4,no,41,How can I track a parcel?,0.5202,How can I track a parcel? You can track your p...
4,5,no,39,How to provide shipping details?,0.4883,How to provide shipping details? If you have a...
5,6,no,38,How much does delivery cost?,0.4729,How much does delivery cost? The cost of deliv...
6,7,no,28,How to pay with one payment for orders from an...,0.4363,How to pay with one payment for orders from an...
7,8,no,83,How much refund you can get from the seller,0.4180,How much refund you can get from the seller Th...
8,9,no,67,I want to change the delivery day. What should...,0.4138,I want to change the delivery day. What should...
9,10,no,73,Purchases from private individuals or transact...,0.3790,Purchases from private individuals or transact...

,rank,hit,section_id,title,score,preview
0,1,yes,1,How to register on HopShop,0.9975,How to register on HopShop If you want to be a...
1,2,no,3,How to register with Google or Facebook account,0.9543,How to register with Google or Facebook accoun...
2,3,no,2,How to register with an email,0.8930,How to register with an email Open the registr...
3,4,no,5,How to register with your phone number,0.8492,How to register with your phone number Open th...
4,5,no,7,Can I have more than one HopShop account,0.7138,"Can I have more than one HopShop account Yes, ..."
5,6,no,8,How to close your HopShop account,0.6572,How to close your HopShop account You can end ...
6,7,no,5,How to register with your phone number,0.6095,"your account within 3 business days, and retur..."
7,8,no,14,How to buy on HopShop,0.5446,"How to buy on HopShop In this article, you wil..."
8,9,no,6,GDPR — how you can download your personal data...,0.5339,GDPR — how you can download your personal data...
9,10,no,48,What you gain with HopShop Delivery,0.5222,What you gain with HopShop Delivery Convenient...

,rank,hit,section_id,title,score,preview
0,1,yes,63,Why can I not find a pick-up point or a parcel...,1.0000,Why can I not find a pick-up point or a parcel...
1,2,no,64,How to find a pick-up point or parcel locker c...,0.7744,How to find a pick-up point or parcel locker c...
2,3,no,66,I want to change the pick-up point or parcel l...,0.5695,I want to change the pick-up point or parcel l...
3,4,no,55,How to collect a parcel from a pick-up point,0.5283,How to collect a parcel from a pick-up point W...
4,5,no,68,The pick-up code does not work. What should I do?,0.5125,The pick-up code does not work. What should I ...
5,6,no,53,When you receive a pick-up code,0.4622,When you receive a pick-up code You will recei...
6,7,no,47,The HopShop Delivery program — information for...,0.4097,The HopShop Delivery program — information for...
7,8,no,54,How to share the pick-up code with others,0.3984,How to share the pick-up code with others You ...
8,9,no,48,What you gain with HopShop Delivery,0.3723,What you gain with HopShop Delivery Convenient...
9,10,no,46,Where you can see the estimated delivery time,0.3711,Where you can see the estimated delivery time ...

,rank,hit,section_id,title,score,preview
0,1,yes,34,Other reasons why your payment may be pending,1.0000,Other reasons why your payment may be pending ...
1,2,no,33,Why your payment is pending or canceled,0.7162,Why your payment is pending or canceled Your p...
2,3,no,91,Wire transfer,0.6454,Wire transfer You will get the refund within 3...
3,4,no,35,My payment has not gone through. How to retry ...,0.5281,My payment has not gone through. How to retry ...
4,5,no,77,I have been waiting a long time for my order d...,0.4557,I have been waiting a long time for my order d...
5,6,no,89,Bank transfer,0.4268,Bank transfer You will get the refund to the b...
6,7,no,29,Payment methods,0.3634,Payment methods You cannot link payment with i...
7,8,no,28,How to pay with one payment for orders from an...,0.3547,How to pay with one payment for orders from an...
8,9,no,71,How to open a Discussion for a canceled order,0.3215,How to open a Discussion for a canceled order ...
9,10,no,77,I have been waiting a long time for my order d...,0.2990,are and how they work If you have not received...

,rank,hit,section_id,title,score,preview
0,1,yes,94,I have received a defective product. What shou...,1.0000,I have received a defective product. What shou...
1,2,no,69,The parcel is damaged. What should I do?,0.4271,The parcel is damaged. What should I do? If yo...
2,3,no,67,I want to change the delivery day. What should...,0.3963,I want to change the delivery day. What should...
3,4,no,74,What you should do if you do not receive your ...,0.3633,What you should do if you do not receive your ...
4,5,no,68,The pick-up code does not work. What should I do?,0.3548,The pick-up code does not work. What should I ...
5,6,no,66,I want to change the pick-up point or parcel l...,0.3403,I want to change the pick-up point or parcel l...
6,7,no,96,Sending a product back to the seller,0.3277,Sending a product back to the seller If you se...
7,8,no,77,I have been waiting a long time for my order d...,0.2998,I have been waiting a long time for my order d...
8,9,no,93,What to do if the seller does not issue a refund,0.2500,What to do if the seller does not issue a refu...
9,10,no,40,I am buying many products — which delivery met...,0.2367,I am buying many products — which delivery met...

,rank,hit,section_id,title,score,preview
0,1,yes,87,A credit card,1.0000,A credit card You will get your refund to the ...
1,2,no,86,A debit card,0.7655,A debit card You will receive a refund to your...
2,3,no,88,Refund and card block,0.5083,Refund and card block If your card has been bl...
3,4,no,93,What to do if the seller does not issue a refund,0.4566,What to do if the seller does not issue a refu...
4,5,no,83,How much refund you can get from the seller,0.4282,How much refund you can get from the seller Th...
5,6,no,92,A gift card,0.4092,A gift card If you return an order for which y...
6,7,no,90,BLIK,0.4073,BLIK You will get the refund to your bank acco...
7,8,no,91,Wire transfer,0.3941,Wire transfer You will get the refund within 3...
8,9,no,89,Bank transfer,0.3904,Bank transfer You will get the refund to the b...
9,10,no,77,I have been waiting a long time for my order d...,0.3851,I have been waiting a long time for my order d...

,rank,hit,section_id,title,score,preview
0,1,yes,60,For what reasons you can file a complaint abou...,1.0000,For what reasons you can file a complaint abou...
1,2,no,59,How to file a complaint about an HopShop Deliv...,0.7459,How to file a complaint about an HopShop Deliv...
2,3,no,95,Deadline for processing a complaint,0.4860,Deadline for processing a complaint When the s...
3,4,no,69,The parcel is damaged. What should I do?,0.4742,The parcel is damaged. What should I do? If yo...
4,5,no,74,What you should do if you do not receive your ...,0.4511,What you should do if you do not receive your ...
5,6,no,67,I want to change the delivery day. What should...,0.4241,I want to change the delivery day. What should...
6,7,no,77,I have been waiting a long time for my order d...,0.3920,I have been waiting a long time for my order d...
7,8,no,97,Consumer sales (when a consumer buys from an e...,0.3729,Consumer sales (when a consumer buys from an e...
8,9,no,77,I have been waiting a long time for my order d...,0.3608,are and how they work If you have not received...
9,10,no,48,What you gain with HopShop Delivery,0.3503,What you gain with HopShop Delivery Convenient...

,rank,hit,section_id,title,score,preview
0,1,yes,8,How to close your HopShop account,1.0000,How to close your HopShop account You can end ...
1,2,no,13,What you should do before the notice period ends,0.6405,What you should do before the notice period en...
2,3,no,7,Can I have more than one HopShop account,0.5859,"Can I have more than one HopShop account Yes, ..."
3,4,no,1,How to register on HopShop,0.5175,How to register on HopShop If you want to be a...
4,5,no,12,How to terminate the agreement,0.5134,How to terminate the agreement To terminate th...
5,6,no,3,How to register with Google or Facebook account,0.4926,How to register with Google or Facebook accoun...
6,7,no,6,GDPR — how you can download your personal data...,0.4898,GDPR — how you can download your personal data...
7,8,no,39,How to provide shipping details?,0.4837,How to provide shipping details? If you have a...
8,9,no,10,How to withdraw from the agreement,0.4737,How to withdraw from the agreement To withdraw...
9,10,no,2,How to register with an email,0.4683,How to register with an email Open the registr...

,rank,hit,section_id,title,score,preview
0,1,yes,96,Sending a product back to the seller,1.0000,Sending a product back to the seller If you se...
1,2,no,94,I have received a defective product. What shou...,0.4946,I have received a defective product. What shou...
2,3,no,60,For what reasons you can file a complaint abou...,0.4019,For what reasons you can file a complaint abou...
3,4,no,69,The parcel is damaged. What should I do?,0.3824,The parcel is damaged. What should I do? If yo...
4,5,no,59,How to file a complaint about an HopShop Deliv...,0.3751,How to file a complaint about an HopShop Deliv...
5,6,no,95,Deadline for processing a complaint,0.3733,Deadline for processing a complaint When the s...
6,7,no,97,Consumer sales (when a consumer buys from an e...,0.3601,Consumer sales (when a consumer buys from an e...
7,8,no,77,I have been waiting a long time for my order d...,0.2660,I have been waiting a long time for my order d...
8,9,no,82,When the seller will issue a refund,0.2636,When the seller will issue a refund The seller...
9,10,no,73,Purchases from private individuals or transact...,0.2488,Purchases from private individuals or transact...

,rank,hit,section_id,title,score,preview
0,1,yes,67,I want to change the delivery day. What should...,0.9899,I want to change the delivery day. What should...
1,2,no,77,I have been waiting a long time for my order d...,0.7970,I have been waiting a long time for my order d...
2,3,no,66,I want to change the pick-up point or parcel l...,0.7309,I want to change the pick-up point or parcel l...
3,4,no,78,Cancelling an order,0.6018,Cancelling an order You can cancel an order in...
4,5,no,77,I have been waiting a long time for my order d...,0.5755,are and how they work If you have not received...
5,6,no,41,How can I track a parcel?,0.5567,How can I track a parcel? You can track your p...
6,7,no,40,I am buying many products — which delivery met...,0.5507,I am buying many products — which delivery met...
7,8,no,70,Can I open a Discussion for a canceled order,0.5157,Can I open a Discussion for a canceled order Y...
8,9,no,46,Where you can see the estimated delivery time,0.4783,Where you can see the estimated delivery time ...
9,10,no,50,How to order a parcel with HopShop Delivery,0.4595,How to order a parcel with HopShop Delivery Wh...

,rank,hit,section_id,title,score,preview
0,1,no,67,I want to change the delivery day. What should...,0.9392,I want to change the delivery day. What should...
1,2,yes,77,I have been waiting a long time for my order d...,0.9175,I have been waiting a long time for my order d...
2,3,no,74,What you should do if you do not receive your ...,0.8346,What you should do if you do not receive your ...
3,4,yes,77,I have been waiting a long time for my order d...,0.7475,are and how they work If you have not received...
4,5,no,66,I want to change the pick-up point or parcel l...,0.7433,I want to change the pick-up point or parcel l...
5,6,no,68,The pick-up code does not work. What should I do?,0.6664,The pick-up code does not work. What should I ...
6,7,no,94,I have received a defective product. What shou...,0.6544,I have received a defective product. What shou...
7,8,no,40,I am buying many products — which delivery met...,0.6230,I am buying many products — which delivery met...
8,9,no,69,The parcel is damaged. What should I do?,0.6217,The parcel is damaged. What should I do? If yo...
9,10,no,70,Can I open a Discussion for a canceled order,0.5797,Can I open a Discussion for a canceled order Y...

      precision  recall    mrr   ndcg  context_relevance
mean      0.105     1.0  0.891  0.919               0.96

,question,relevant_docs,retrieved_docs,precision,recall,mrr,ndcg,context_relevance
0,Will I get a full refund including shipping if...,[83],"[83, 77, 93, 82, 70, 94, 40, 41, 86]",0.111111,1.0,1.000000,1.000000,0.50
1,Can I use multiple delivery addresses for one ...,[25],"[25, 7, 40, 24, 26, 47, 48, 28, 77, 67]",0.100000,1.0,1.000000,1.000000,0.50
2,Why does my payment status show as canceled or...,[33],"[33, 34, 35, 29, 71, 42, 51, 32, 30, 77]",0.100000,1.0,1.000000,1.000000,1.00
3,How can I find the seller's email and phone nu...,[21],"[21, 41, 67, 66, 77, 20, 42, 68, 84]",0.111111,1.0,1.000000,1.000000,1.00
4,What should I do if my parcel was damaged when...,[69],"[69, 66, 68, 94, 67, 77, 60, 63, 41, 74]",0.100000,1.0,1.000000,1.000000,1.00
5,How do I sign up using my Google or Facebook a...,[3],"[3, 1, 7, 2, 4, 68, 5, 54, 10, 64]",0.100000,1.0,1.000000,1.000000,1.00
6,How can I find my parcel's tracking number and...,[42],"[42, 51, 41, 77, 50, 59, 58, 64, 47, 49]",0.100000,1.0,1.000000,1.000000,1.00
7,How will I receive my refund from the seller?,[85],"[83, 85, 82, 84, 93, 77, 81, 74, 86]",0.111111,1.0,0.500000,0.630930,1.00
8,How long does it take to get a refund for a wi...,[91],"[91, 89, 93, 77, 34, 83, 86, 87, 90]",0.111111,1.0,1.000000,1.000000,1.00
9,How is the estimated delivery time calculated ...,[43],"[43, 44, 45, 46, 50, 37, 49, 47, 36, 48]",0.100000,1.0,1.000000,1.000000,1.00
10,What happens to my gift card if I return an or...,[92],"[92, 32, 77, 86, 70, 94, 68, 67, 87]",0.111111,1.0,1.000000,1.000000,1.00
11,How can I reorder a single product from my pas...,[16],"[16, 15, 17, 18, 35, 14, 77, 41, 79]",0.111111,1.0,1.000000,1.000000,1.00
12,How will I be notified when my refund is proce...,[84],"[84, 85, 82, 77, 83, 88, 35, 90, 87]",0.111111,1.0,1.000000,1.000000,1.00
13,How can I open a Discussion if I canceled an o...,[71],"[71, 70, 81, 77, 33, 76, 93, 35, 75]",0.111111,1.0,1.000000,1.000000,1.00
14,Why might my actual delivery time be different...,[45],"[45, 46, 43, 44, 37, 77, 63, 34, 67]",0.111111,1.0,1.000000,1.000000,1.00
15,Who is responsible if an item is damaged durin...,[72],"[72, 97, 73, 69, 40, 60, 83, 36, 77]",0.111111,1.0,1.000000,1.000000,1.00
16,What should I do if my pick-up code isn’t work...,[68],"[68, 66, 53, 63, 64, 69, 56, 65, 55, 54]",0.100000,1.0,1.000000,1.000000,1.00
17,What happens if I frequently cancel or don't p...,[79],"[79, 35, 77, 12, 13, 7, 32, 29, 14]",0.111111,1.0,1.000000,1.000000,1.00
18,What do I need to do to pick up my parcel from...,[55],"[55, 66, 64, 68, 53, 63, 69, 56, 54, 57]",0.100000,1.0,1.000000,1.000000,1.00
19,How long does it take to get a BLIK refund and...,[90],"[90, 89, 86, 87, 77, 83, 46, 91, 88, 93]",0.100000,1.0,1.000000,1.000000,1.00
20,How do I pay for my order using PayPal and how...,[31],"[31, 30, 77, 68, 24, 35, 28, 40, 41]",0.111111,1.0,1.000000,1.000000,1.00
21,How can I change my parcel locker or pick-up p...,[66],"[66, 64, 63, 68, 67, 55, 65, 56, 53, 77]",0.100000,1.0,1.000000,1.000000,1.00
22,What are the options for returning a HopShop D...,[58],"[36, 58, 47, 48, 50, 61, 56, 51, 59, 49]",0.100000,1.0,0.500000,0.630930,1.00
23,How long will my parcel be held at the pick-up...,[57],"[64, 55, 57, 66, 63, 53, 65, 68, 54, 77]",0.100000,1.0,0.333333,0.500000,0.75
24,What should I do if I'm unsure about my parcel...,[52],"[66, 67, 69, 68, 52, 94, 77, 41, 74, 42]",0.100000,1.0,0.200000,0.386853,1.00
25,What happens if the parcel locker has no avail...,[65],"[65, 66, 64, 69, 56, 63, 68, 35, 77, 61]",0.100000,1.0,1.000000,1.000000,1.00
26,Can I open a Discussion for a purchase made mo...,[80],"[70, 80, 71, 81, 76, 7, 75, 77, 79]",0.111111,1.0,0.500000,0.630930,1.00
27,How can I collect my parcel from a parcel lock...,[56],"[56, 55, 54, 53, 68, 64, 66, 63, 51, 57]",0.100000,1.0,1.000000,1.000000,1.00
28,How can I share my HopShop Delivery pick-up co...,[54],"[54, 53, 68, 56, 47, 48, 64, 55, 50, 51]",0.100000,1.0,1.000000,1.000000,1.00
29,How long does it take to get a refund to my ba...,[86],"[86, 87, 88, 89, 90, 91, 92, 77, 93, 83]",0.100000,1.0,1.000000,1.000000,1.00
30,How can I track my HopShop Delivery parcel and...,[51],"[41, 51, 42, 50, 58, 77, 53, 47, 56, 59]",0.100000,1.0,0.500000,0.630930,1.00
31,How can I find out which delivery options are ...,[36],"[36, 47, 40, 58, 50, 49, 51, 26, 15, 41]",0.100000,1.0,1.000000,1.000000,1.00
32,Can I withdraw from the agreement if my accoun...,[10],"[9, 10, 11, 12, 7, 8, 77, 76, 80]",0.111111,1.0,0.500000,0.630930,1.00
33,How can I make a purchase or set up recurring ...,[14],"[18, 14, 39, 15, 32, 50, 7, 48, 1]",0.111111,1.0,0.500000,0.630930,1.00
34,Can I split payment for multiple orders from d...,[30],"[24, 30, 28, 40, 26, 29, 41, 70, 67, 35]",0.100000,1.0,0.500000,0.630930,0.75
35,How long does a seller have to respond to my c...,[95],"[95, 77, 75, 93, 60, 59, 76, 82, 78]",0.111111,1.0,1.000000,1.000000,1.00
36,How can I enable sign-in with my email and pas...,[4],"[4, 2, 3, 41, 35, 77, 66, 6, 1]",0.111111,1.0,1.000000,1.000000,1.00
37,What are the ways to contact a seller on HopShop?,[19],"[19, 21, 20, 93, 32, 36, 22, 14, 58, 48]",0.100000,1.0,1.000000,1.000000,1.00
38,Where can I find the estimated delivery time f...,[46],"[46, 43, 37, 45, 44, 77, 67, 42, 38, 41]",0.100000,1.0,1.000000,1.000000,1.00
39,Can I combine shipping costs when buying multi...,[40],"[40, 24, 26, 41, 39, 38, 28, 83, 67, 73]",0.100000,1.0,1.000000,1.000000,1.00
40,What are the ways to register for a HopShop ac...,[1],"[1, 3, 2, 5, 7, 8, 14, 6, 48]",0.111111,1.0,1.000000,1.000000,1.00
41,Why isn't my usual pick-up point showing on th...,[63],"[63, 64, 66, 55, 68, 53, 47, 54, 48, 46]",0.100000,1.0,1.000000,1.000000,0.75
42,Why is my payment still pending after I paid b...,[34],"[34, 33, 91, 35, 77, 89, 29, 28, 71]",0.111111,1.0,1.000000,1.000000,1.00
43,What should I do if the product I received is ...,[94],"[94, 69, 67, 74, 68, 66, 96, 77, 93, 40]",0.100000,1.0,1.000000,1.000000,1.00
44,How long does it take to get a refund on my cr...,[87],"[87, 86, 88, 93, 83, 92, 90, 91, 89, 77]",0.100000,1.0,1.000000,1.000000,1.00
45,What situations allow me to file a complaint a...,[60],"[60, 59, 95, 69, 74, 67, 77, 97, 48]",0.111111,1.0,1.000000,1.000000,1.00
46,How do I close my HopShop account?,[8],"[8, 13, 7, 1, 12, 3, 6, 39, 10, 2]",0.100000,1.0,1.000000,1.000000,1.00
47,Do I have to use the original packaging or inc...,[96],"[96, 94, 60, 69, 59, 95, 97, 77, 82, 73]",0.100000,1.0,1.000000,1.000000,1.00
48,How can I change the delivery date before my o...,[67],"[67, 77, 66, 78, 41, 40, 70, 46, 50]",0.111111,1.0,1.000000,1.000000,1.00
49,What should I do if my order delivery is delay...,[77],"[67, 77, 74, 66, 68, 94, 40, 69, 70]",0.111111,1.0,0.500000,0.630930,0.75